### PR TITLE
`BarrageSession` Subscription/Snapshot Methods now Return `Future<Table>`

### LINKED ISSUE #4675: Barrage snapshot can return 0 rows to the client
**Description**
When trying to complete a Barrage snapshot,  you can get a table with 0 rows in it instead of the actual data.

**Steps to reproduce**
In one Community session create a table
```groovy
import static io.deephaven.engine.util.TableTools.*;
t = newTable(intCol("Sentinel", 10, 20, 30), stringCol("S2", "40", "50", "or more"))
```

In another worker try to fetch a snapshot
```groovy
import io.grpc.netty.NettyChannelBuilder
import io.deephaven.proto.DeephavenChannelImpl
import io.deephaven.client.impl.BarrageSession
import io.deephaven.client.impl.SessionImpl
import io.deephaven.client.impl.SessionImplConfig
import java.util.concurrent.Executors
import org.apache.arrow.memory.RootAllocator
import io.deephaven.qst.table.TicketTable
import io.deephaven.server.uri.BarrageTableResolver

managedChannel = NettyChannelBuilder.forTarget("dh://REMOTE_HOST").build()
dhChannel = new DeephavenChannelImpl(managedChannel)
session = SessionImpl.create(SessionImplConfig.builder()
    .executor(Executors.newScheduledThreadPool(4))
    .channel(dhChannel)
    .build())
barrage = BarrageSession.of(session, new RootAllocator(), managedChannel)

sub = barrage.snapshot(TicketTable.of("s/t"), BarrageTableResolver.SNAP_OPTIONS)
table = sub.entireTable()
```

**Expected results**

You get an identical table to t

**Actual results**

You get a blank table.

**Versions**
 - Deephaven: 0.29.0

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fix #4675 

This includes breaking changes to the barrage java-client API. The snapshot/subscription methods now return `Future<Table>` instead of `BarrageTable` and users are no longer required to `blockUntilCompletion` as this is handled by `Future#get`.

Subscribed tables can now be canceled only through `Liveness` destruction such as using an explicit `LivenessScope` or invoking `ReferenceCounted#forceReferenceCountToZero()`.

### CODE REVIEW

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 1]
```diff
@@ -41,6 +42,30 @@
...
+ * It is not an error to create derived tables from the {@code BarrageTable} prior to the subscription being complete,
+ * as all changes are propagated to downstream tables.
+ * <p>
+ * For Snapshots (static tables):
+ * <p>
+ * Users may call {@code snapshotEntireTable}, or {@code snapshotPartialTable}, to initiate the gRPC call to the server.
+ * These methods return the eventually populated {@code BarrageTable} to the user. The user must either set
+ * {@code blockUntilComplete} to {@code true} during initiation or call {@code blockUntilComplete} to ensure that the
+ * {@code BarrageTable} is fully populated before using it. Noting that snapshots are static tables that do not
+ * propagate changes on any update graph.
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:67]:
```suggestion
 * This class is an intermediary helper class that uses a {@code DoExchange} to populate a {@link BarrageTable} using
 * subscription data from a remote server, propagating updates if the request is a subscription.
 * <p>
 * For Subscriptions (refreshing result tables):
 * <p>
 * Users may call {@link #entireTable} or {@link #partialTable} to initiate the gRPC call to the server. These methods
 * return the eventually populated {@code BarrageTable} to the user.
 * <p>
 * If the user wants to ensure that the table is completely populated with an initial state of the remote table prior to
 * using the result they must either set {@code blockUntilComplete} to {@code true} or call
 * {@link #blockUntilComplete()} to ensure that the {@code BarrageTable} is respecting the requested subscription.
 * <p>
 * It is not an error to create derived tables from the {@code BarrageTable} prior to the subscription being complete,
 * as all changes are propagated to downstream tables.
 * <p>
 * For Snapshots (static result tables):
 * <p>
 * Users may call {@link #snapshotEntireTable} or {@link #snapshotPartialTable} to initiate the gRPC call to the server.
 * These methods return the eventually populated {@code BarrageTable} to the user. The user must either set
 * {@code blockUntilComplete} to {@code true} during initiation or call {@link #blockUntilComplete()} to ensure that the
 * {@code BarrageTable} is fully populated before using it. Noting that snapshots are static tables that do not
 * propagate changes on any update graph.
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 2]
```diff
@@ -37,6 +37,7 @@
 import java.nio.ByteBuffer;
 import java.util.BitSet;
 import java.util.concurrent.ScheduledExecutorService;
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:39]: We have unused imports.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 3]
```diff
@@ -154,17 +156,18 @@ public void onError(final Throwable t) {
...
-            handleDisconnect();
+
+            // this error will always be propagated to our CheckForCompletion#onError callback
+            resultTable.handleBarrageError(t);
         }
 
         @Override
         public void onCompleted() {
-            handleDisconnect();
+            // this will always be propagated to our CheckForCompletion#onClose callback
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:169]: We don't need to record that we're not connected here?

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 4]
```diff
@@ -274,41 +277,37 @@ protected void destroy() {
...
+     * This method will only be invoked once using the CAS of {@code connected} from 1 to 0 as a guard.
+     */
+    private synchronized void signalCompletion(@Nullable final Throwable t) {
         completed = true;
-        signalCompletion();
-        cleanup();
-    }
 
-    private synchronized void signalCompletion() {
+        if (t != null) {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:290]: Same kind of race condition as in subscribe.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java [hunk 5]
```diff
@@ -242,8 +233,8 @@ public BitSet getServerColumns() {
 
     @Override
     public void handleBarrageMessage(final BarrageMessage update) {
-        if (unsubscribed) {
-            beginLog(LogLevel.INFO).append(": Discarding update for unsubscribed table!").endl();
+        if (pendingError != null) {
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java:236]:
```suggestion
        if (pendingError != null || isFailed()) {
```

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java [hunk 6]
```diff
@@ -337,34 +329,19 @@ protected boolean isSubscribedColumn(int i) {
     }
 
     private synchronized void realRefresh() {
+        if (isFailed()) {
+            return;
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java:333]: We may want to discard pending updates here.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java [hunk 7]
```diff
@@ -271,6 +259,13 @@ public void handleBarrageError(Throwable t) {
         enqueueError(t);
     }
 
+    private synchronized void tryToDeliverErrorToCallback(final Throwable err) {
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java:262]: I think we want to synchronize `updateServerViewport`, too. Or at least the part that deals with the callback.

File: java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SnapshotExampleBase.java
Comment (rcaudy) [inline java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SnapshotExampleBase.java:1]: Multiple failures due to the AutoCloseable change.
Maybe we want to bring back `close()` as `cancel()`?
Or maybe we want to change usages to use a `LivenessScope`, which seems better and more idomatic?

**Review by rcaudy — DISMISSED** [review]

**Comment by rcaudy** [comment]
Approved, but needs thorough testing before we merge.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java [hunk 8]
```diff
@@ -38,6 +38,13 @@ BarrageSnapshot snapshot(TableSpec tableSpec, BarrageSnapshotOptions options)
         BarrageSnapshot snapshot(TableHandle tableHandle, BarrageSnapshotOptions options);
     }
 
+    /**
+     * This call will return false until all rows for the result table are available or the snapshot failed.
+     *
+     * @return true when all rows for the result table are available or the snapshot failed, false otherwise
+     */
+    boolean isCompleted();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java:46]: Maybe we should return an enum here? Success or failure? Or maybe we should just be returning a `Future` from `partialTable` and `entireTable` anyway. That would avoid letting the user get a reference before it's safe to do so.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 9]
```diff
@@ -68,7 +68,9 @@ public class BarrageSnapshotImpl extends ReferenceCountedLivenessNode implements
     private volatile int connected = 1;
     private static final AtomicIntegerFieldUpdater<BarrageSnapshotImpl> CONNECTED_UPDATER =
             AtomicIntegerFieldUpdater.newUpdater(BarrageSnapshotImpl.class, "connected");
-
+    private volatile int completed = 0;
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:71]: No need to bother changing this, since you're planning to converge these impls in the next issue, but it would be better if the parallel variables between snapshot and sub were declared in the same order, etc.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 10]
```diff
@@ -256,77 +320,63 @@ public BarrageTable blockUntilComplete() throws InterruptedException {
...
 
-    @Override
-    public BarrageTable snapshotPartialTable(RowSet viewport, BitSet columns, boolean reverseViewport,
-            boolean blockUntilComplete) throws InterruptedException {
-        isSnapshot = true;
-        return partialTable(viewport, columns, reverseViewport, blockUntilComplete);
+        // if we are building a snapshot via a growing viewport subscription, then cancel our subscription
+        if (isSnapshot) {
+            tryRecordDisconnect();
+            GrpcUtil.safelyCancel(observer, "Barrage snapshot is complete", null);
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:349]:
```suggestion
            if (tryRecordDisconnect()) {
                GrpcUtil.safelyCancel(observer, "Barrage snapshot is complete", null);
            }
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java [hunk 11]
```diff
@@ -38,28 +38,12 @@ BarrageSnapshot snapshot(TableSpec tableSpec, BarrageSnapshotOptions options)
...
-
-    /**
-     * Request a full snapshot of the data and populate a {@link Table} with the data that is received.
-     *
-     * @param blockUntilComplete Whether to block execution until all rows for the subscribed table are available
-     *
-     * @return the {@code Table}
-     */
-    Table entireTable(boolean blockUntilComplete) throws InterruptedException;
+    Future<Table> entireTable() throws InterruptedException;
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java:46]: We don't throw an `InterruptedException` anymore. We have a `Future` for that. Applies to all these interfaces.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java [hunk 12]
```diff
@@ -38,28 +38,12 @@ BarrageSnapshot snapshot(TableSpec tableSpec, BarrageSnapshotOptions options)
...
-     * This call will return false until all rows for the result table are available or the snapshot failed.
-     *
-     * @return true when all rows for the result table are available or the snapshot failed, false otherwise
-     */
-    boolean isCompleted();
-
     /**
      * Request a full snapshot of the data and populate a {@link Table} with the data that is received.
      *
      * @return the {@code Table}
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java:44]: This is not the right return documentation. Applies to all, again/

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 13]
```diff
@@ -328,34 +236,19 @@ private boolean tryRecordDisconnect() {
...
     }
 
-    private void trySignalCompletion() {
-        trySignalCompletion(null);
-    }
-
-    private void trySignalCompletion(@Nullable final Throwable t) {
-        if (!COMPLETED_UPDATER.compareAndSet(BarrageSubscriptionImpl.this, 0, 1)) {
-            return;
+    private boolean onFutureCancel(boolean cancelResult) {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:239]: It seems to me like it would be better to get rid of the argument and only call this if the argument would have been `true`. That way it matches `onFutureComplete()`, and we only have one pattern.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 14]
```diff
@@ -127,66 +141,74 @@ public void onNext(final BarrageMessage barrageMessage) {
...
+                throw new UncheckedDeephavenException("Barrage subscription objects cannot be reused");
             }
             subscribed = true;
         }
 
+        if (isSnapshot) {
+            future = new CompletableFutureAdapter();
+        } else {
+            future = new UpdateGraphAwareFutureAdapter(resultTable.getUpdateGraph());
+        }
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:210]: I'm concerned we have lurking NPEs since we delay this initialization. :-(

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 15]
```diff
@@ -318,14 +232,15 @@ protected void destroy() {
...
+    private void cancel() {
         if (!tryRecordDisconnect()) {
             return;
         }
 
-        resultTable.handleBarrageError(new RequestCancelledException("Barrage subscription cancelled by client"));
-        GrpcUtil.safelyCancel(observer, "Barrage snapshot is cancelled", exceptionWhileCompleting);
+        final RequestCancelledException requestCancelled =
+                new RequestCancelledException("Barrage subscription cancelled by client");
+        resultTable.handleBarrageError(requestCancelled);
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:242]: We don't need this handleBarrageError on a future cancel, right? Nothing can get the Table in that case. And we don't really need it on a destroy, because the table had better also be dead at that point; we just need to complete the future exceptionally, if it's not already complete.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 16]
```diff
@@ -78,7 +87,7 @@ public BarrageSnapshotImpl(
         final BarrageUtil.ConvertedArrowSchema schema = BarrageUtil.convertArrowSchema(tableHandle.response());
         final TableDefinition tableDefinition = schema.tableDef;
         resultTable = BarrageTable.make(executorService, tableDefinition, schema.attributes, new CheckForCompletion());
-        resultTable.addParentReference(this);
+        future = new CompletableFuture<>();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:90]: Don't you need the `onFutureCancel` callback?

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 17]
```diff
@@ -203,130 +225,51 @@ public BarrageTable partialTable(RowSet viewport, BitSet columns, boolean revers
...
-        cleanup();
-    }
 
-    @Override
-    public synchronized void close() {
-        if (!connected) {
-            return;
-        }
-        GrpcUtil.safelyComplete(observer);
+        resultTable.handleBarrageError(new RequestCancelledException("Barrage subscription cancelled by client"));
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:266]: We don't need this handleBarrageError on a future cancel, right? Nothing can get the Table in that case. And we don't really need it on a destroy, because the table had better also be dead at that point; we just need to complete the future exceptionally, if it's not already complete.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 18]
```diff
@@ -289,26 +218,11 @@ private boolean tryRecordDisconnect() {
...
-        trySignalCompletion(null);
-    }
-
-    private void trySignalCompletion(@Nullable final Throwable t) {
-        if (!COMPLETED_UPDATER.compareAndSet(BarrageSnapshotImpl.this, 0, 1)) {
-            return;
-        }
-        if (t != null) {
-            exceptionWhileCompleting = t;
+    private void tryCompleteFuture(@Nullable final Throwable t) {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:221]: Unused. Delete me.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java (hunk 14 above)
Comment (nbauernfeind) [reply java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:210]: The future is read in the vp-change callback which cannot be invoked until after the `observer.onNext` (which happens below). This looks safe to me. Note that the future is volatile due to the var's need to cross thread boundaries.

We cannot create this much earlier as we do not know whether the user wants a snapshot or a subscription until right here (after checking that the object is not-yet-used and still connected).

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java (hunk 15 above)
Comment (nbauernfeind) [reply java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:242]: In the snapshot case, you are right this table is not published anywhere and should be inaccessible. We do still want to do this in the subscription impl though, right? If the rpc has queued up some messages but the UG has not run the source yet, then we are able to drop those messages on the floor and do not need to rely on GC.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java (hunk 17 above)
Comment (nbauernfeind) [reply java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:266]: I think this one we want if `!isSnapshot`. Maybe we want to `resultTable.forceReferenceCountToZero()` instead?

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java [hunk 19]
```diff
@@ -41,9 +41,11 @@ BarrageSnapshot snapshot(TableSpec tableSpec, BarrageSnapshotOptions options)
     /**
      * Request a full snapshot of the data and populate a {@link Table} with the data that is received.
      *
-     * @return the {@code Table}
+     * @return a {@link Future
+     *         <Table>
+     *         } that will be populated with the snapshot
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java:46]: * @return a {@link Future} that will be populated with the result {@link Table}

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java [hunk 20]
```diff
@@ -40,68 +40,78 @@ BarrageSubscription subscribe(TableSpec tableSpec, BarrageSubscriptionOptions op
 
     /**
      * Request a full subscription of the data and populate a {@link Table} with the incrementally updating data that is
-     * received. This call will block until all rows for the subscribed table are available.
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java]: You could add that the *future* will block...

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 21]
```diff
@@ -263,8 +254,13 @@ private void cancel() {
             return;
         }
 
-        resultTable.handleBarrageError(new RequestCancelledException("Barrage subscription cancelled by client"));
-        GrpcUtil.safelyCancel(observer, "Barrage subscription is cancelled", null);
+        final RequestCancelledException cancelledException =
+                new RequestCancelledException("Barrage subscription cancelled by client");
+        if (!isSnapshot) {
+            // Stop our result table from processing any more data.
+            resultTable.forceReferenceCountToZero();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:261]: We said that `BarrageTable.destroy` should call `cleanup()`, and that the assertion from cleanup should move to `realRefresh`.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 22]
```diff
@@ -263,8 +254,13 @@ private void cancel() {
             return;
         }
 
-        resultTable.handleBarrageError(new RequestCancelledException("Barrage subscription cancelled by client"));
-        GrpcUtil.safelyCancel(observer, "Barrage subscription is cancelled", null);
+        final RequestCancelledException cancelledException =
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:257]: We're missing a future.completeExceptionally in the destroy case. But the future might be null. How dystopian.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 23]
```diff
@@ -263,8 +254,13 @@ private void cancel() {
...
+                new RequestCancelledException("Barrage subscription cancelled by client");
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:258]: Maybe we want to have a string argument to distinguish between "no longer live" and "cancelled by client" ?

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 24]
```diff
@@ -237,10 +229,8 @@ private void cancel() {
             return;
         }
 
-        final RequestCancelledException requestCancelled =
-                new RequestCancelledException("Barrage subscription cancelled by client");
-        resultTable.handleBarrageError(requestCancelled);
-        GrpcUtil.safelyCancel(observer, "Barrage snapshot is cancelled", requestCancelled);
+        GrpcUtil.safelyCancel(observer, "Barrage snapshot is cancelled",
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:232]: Same thing about a string arg.

File: engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java [hunk 25]
```diff
@@ -0,0 +1,164 @@
...
+        return getInternal(timeout, unit);
+    }
+
+    private T getInternal(long timeout, @Nullable TimeUnit unit)
+            throws InterruptedException, ExecutionException, TimeoutException {
+        // test lock conditions
+        if (updateGraph.sharedLock().isHeldByCurrentThread()) {
+            throw new UnsupportedOperationException(
+                    "Cannot Future#get while holding the " + updateGraph + " shared lock");
+        }
```
Comment (rcaudy) [inline engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java:88]: Put this in a method and call it first thing in both `get` overloads. We want to be consistent in our error delivery.
```suggestion
        if (updateGraph.sharedLock().isHeldByCurrentThread()) {
            throw new UnsupportedOperationException(
                    "Cannot Future.get(...) while holding the " + updateGraph + " shared lock");
        }
```

File: engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java [hunk 26]
```diff
@@ -0,0 +1,164 @@
...
+        if (resultSupplier != null) {
+            return resultSupplier.get();
+        }
+        if (timeout <= 0) {
+            throw new TimeoutException();
+        }
+        return getInternal(timeout, unit);
+    }
+
+    private T getInternal(long timeout, @Nullable TimeUnit unit)
```
Comment (rcaudy) [inline engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java:82]:
```suggestion
    private T getInternal(final long timeout, @Nullable final TimeUnit unit)
```

File: engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java [hunk 27]
```diff
@@ -0,0 +1,164 @@
...
+    public boolean completeExceptionally(Throwable ex) {
+        if (ex == null)
+            throw new NullPointerException();
+        return trySignalCompletion(() -> {
+            throw new ExecutionException(ex);
+        });
+    }
+
+    private boolean trySignalCompletion(@NotNull final ThrowingSupplier<T, ExecutionException> result) {
+        if (!RESULT_UPDATER.compareAndSet(UpdateGraphAwareCompletableFuture.this, null, result)) {
```
Comment (rcaudy) [inline engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java:151]:
```suggestion
        if (!RESULT_UPDATER.compareAndSet(this, null, result)) {
```

File: engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java [hunk 28]
```diff
@@ -0,0 +1,164 @@
...
+                    "Cannot Future#get while holding the " + updateGraph + " shared lock");
+        }
+
+        final boolean holdingUpdateGraphLock = updateGraph.exclusiveLock().isHeldByCurrentThread();
+        if (updateGraphCondition == null && holdingUpdateGraphLock) {
+            try (final SafeCloseable ignored = lock.lockCloseable()) {
+                if (updateGraphCondition == null) {
+                    updateGraphCondition = updateGraph.exclusiveLock().newCondition();
+                }
+            }
```
Comment (rcaudy) [inline engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java:96]:
```suggestion
        if (holdingUpdateGraphLock) {
            if (updateGraphCondition == null) {
                updateGraphCondition = updateGraph.exclusiveLock().newCondition();
            }
```

File: engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java [hunk 29]
```diff
@@ -0,0 +1,164 @@
...
+        if (!RESULT_UPDATER.compareAndSet(UpdateGraphAwareCompletableFuture.this, null, result)) {
+            return false;
+        }
+
+        final Condition localCondition = updateGraphCondition;
+        try (final SafeCloseable ignored = lock.lockCloseable()) {
+            if (localCondition != null) {
+                updateGraph.requestSignal(localCondition);
+            }
+        }
```
Comment (rcaudy) [inline engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java:160]:
```suggestion
        final Condition localUpdateGraphCondition = updateGraphCondition;
        if (localUpdateGraphCondition != null) {
            updateGraph.requestSignal(localUpdateGraphCondition);
        }
        final Condition localLockCondition = lockCondition;
        if (localLockCondition != null) {
            lock.doLocked(localLockCondition::signalAll);
        }
```

File: engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java [hunk 30]
```diff
@@ -140,23 +138,26 @@ public boolean complete(T value) {
     }
 
     public boolean completeExceptionally(Throwable ex) {
-        if (ex == null)
+        if (ex == null) {
```
Comment (rcaudy) [inline engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java:141]: You can use `Objects.requireNonNull` for this. No need to make the change if there's nothing else to change.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 31]
```diff
@@ -246,21 +249,23 @@ private void onFutureComplete() {
     @Override
     protected void destroy() {
         super.destroy();
-        cancel();
+        cancel("no longer live");
+        if (future != null) {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:253]: I'd use a local here, but it's OK; we never re-assign `future`.

**Review by rcaudy — APPROVED** [review]
Two cosmetic complaints. No need to make further changes if tests pass.

**Review by rcaudy — APPROVED** [review]
