### PR TITLE
Fix dependency bug in Kafka ingest, and some debugging cleanup for JobScheduler.TaskInvoker

### LINKED ISSUE #4064: Unexpected error in satisfaction check/probe
```
2023-06-22T16:16:01.187Z | aph-updateExecutor-1 | ERROR | rumentedTableListenerBase | Uncaught exception for entry= by(NORMAL:[Partition{column=ColumnName(__CONSTITUENT__), includeGroupByColumns=true}]), a
dded.size()=1, modified.size()=0, removed.size()=1, shifted.size()=0, modifiedColumnSet={}:
java.lang.IllegalStateException: Missing value in probe
        at io.deephaven.engine.table.impl.by.typed.incopenagg.gen.IncrementalAggOpenHasherLong.probe(IncrementalAggOpenHasherLong.java:122)
        at io.deephaven.engine.table.impl.by.OperatorAggregationStateManagerOpenAddressedAlternateBase.probeTable(OperatorAggregationStateManagerOpenAddressedAlternateBase.java:148)
        at io.deephaven.engine.table.impl.by.IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.remove(IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.java:174)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemovesForChunk(ChunkedOperatorAggregationHelper.java:653)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemoves(ChunkedOperatorAggregationHelper.java:647)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.computeDownstreamIndicesAndCopyKeys(ChunkedOperatorAggregationHelper.java:520)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onUpdate(ChunkedOperatorAggregationHelper.java:259)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:297)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:275)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.193Z | aph-updateExecutor-1 | ERROR | .AsyncClientErrorNotifier | Error in table update: java.lang.IllegalStateException: Missing value in probe
        at io.deephaven.engine.table.impl.by.typed.incopenagg.gen.IncrementalAggOpenHasherLong.probe(IncrementalAggOpenHasherLong.java:122)
        at io.deephaven.engine.table.impl.by.OperatorAggregationStateManagerOpenAddressedAlternateBase.probeTable(OperatorAggregationStateManagerOpenAddressedAlternateBase.java:148)
        at io.deephaven.engine.table.impl.by.IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.remove(IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.java:174)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemovesForChunk(ChunkedOperatorAggregationHelper.java:653)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemoves(ChunkedOperatorAggregationHelper.java:647)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.computeDownstreamIndicesAndCopyKeys(ChunkedOperatorAggregationHelper.java:520)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onUpdate(ChunkedOperatorAggregationHelper.java:259)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:297)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:275)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.245Z | aph-updateExecutor-4 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-4: Exception while executing PeriodicUpdateGraph notification: Merged Notification 2
86297628 PartitionedTable.merge(): io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted oldRecordedStep < step, instead oldRecordedStep == 620, step == 620.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.util.StepUpdater.forceUpdateRecordedStep(StepUpdater.java:65)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:343)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.253Z | aph-updateExecutor-2 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-2: Exception while executing PeriodicUpdateGraph notification: Merged Notification 1
313397605 PartitionedTable.merge(): io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted oldRecordedStep < step, instead oldRecordedStep == 620, step == 620.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.util.StepUpdater.forceUpdateRecordedStep(StepUpdater.java:65)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:343)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.254Z | aph-updateExecutor-1 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-1: Exception while executing PeriodicUpdateGraph notification: Merged Notification 5
63567161 PartitionedTable.merge(): io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted oldRecordedStep < step, instead oldRecordedStep == 620, step == 620.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.util.StepUpdater.forceUpdateRecordedStep(StepUpdater.java:65)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:343)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #4064

### CODE REVIEW

**Comment by rcaudy** [comment]
Nightlies running at https://github.com/rcaudy/deephaven-core/actions/runs/5407060540

File: extensions/source-support/src/test/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionTest.java [hunk 1]
```diff
@@ -159,6 +162,22 @@ public void run() {
                 }
             });
         }
+
```
Comment (cpwright) [inline extensions/source-support/src/test/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionTest.java:165]: Comment on line 157 is cut off.

File: extensions/source-support/src/test/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionTest.java [hunk 2]
```diff
@@ -159,6 +162,22 @@ public void run() {
...
+        @Override
+        public LogOutput append(LogOutput logOutput) {
+            return logOutput.append("DependentRegistrar[")
+                    .append(LogOutput.APPENDABLE_ARRAY_FORMATTER, dependencies).append(']');
+        }
+
+        @Override
+        public boolean satisfied(final long step) {
+            return updateGraph.satisfied(step);
```
Comment (cpwright) [inline extensions/source-support/src/test/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionTest.java:174]: I don't understand this.

My basic concern with it is: (1) we’re using the updateGraph to say we are satisfied or not.  We enqueue a notification in run() [and satisfied could occur any time after the run].  That notification may or may not be able to execute, based on those N dependencies.

But if you have the DependentRegistrar as a parent, it would have fired and have enqueued a notification that will fire sometime in the future, depending on those dependencies.  But you would never ask about them, only about the satisfaction of the Dependent registrar.

In the simple blink table case, I think I get it.  Because the update graph is only satisfied after the blink table calls it’s run() method, which will have created the notifications for the things localTable depends on.  In the dependent case, I’m just not certain why this is correct.

**Review by cpwright — APPROVED** [review]
