### PR TITLE
When Sorting with a Static Symbol Table use a RowKey or RowPosition ColumnSource

### LINKED ISSUE #5094: PartitionTableProxy's `sort` throws no `ExecutionContext` exceptions
This reproduces:
```groovy
import io.deephaven.parquet.table.ParquetTools
import io.deephaven.parquet.table.ParquetInstructions

instructions = ParquetInstructions.builder().useDictionary("I", true).build()

t = emptyTable(100000).update("I = `` + (ii % 100)", "K = ii")
ParquetTools.writeTable(t, new java.io.File("/tmp/test/A=a/data.parquet"), instructions)

t = ParquetTools.readTable("/tmp/test").partitionBy("A").proxy().sort("I").target().merge()
```

Throws an exception:
```
Error running script: io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: i
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:214)
	at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:115)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:63)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1461)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$31(QueryTable.java:1443)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3438)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1442)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1420)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:104)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at io.deephaven.engine.table.impl.SortHelpers.doSymbolTableMapping(SortHelpers.java:359)
	at io.deephaven.engine.table.impl.SortHelpers.getSortedKeys(SortHelpers.java:251)
	at io.deephaven.engine.table.impl.SortHelpers.getSortedKeys(SortHelpers.java:227)
	at io.deephaven.engine.table.impl.SortOperation.initialize(SortOperation.java:215)
	at io.deephaven.engine.table.impl.QueryTable.lambda$getResultNoMemo$71(QueryTable.java:3530)
	at io.deephaven.engine.table.impl.BaseTable.initializeWithSnapshot(BaseTable.java:1293)
	at io.deephaven.engine.table.impl.QueryTable.lambda$getResultNoMemo$72(QueryTable.java:3529)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.getResultNoMemo(QueryTable.java:3519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$getResult$70(QueryTable.java:3513)
	at io.deephaven.engine.table.impl.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3473)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3442)
	at io.deephaven.engine.table.impl.QueryTable.getResult(QueryTable.java:3512)
	at io.deephaven.engine.table.impl.QueryTable.sort(QueryTable.java:2536)
	at io.deephaven.engine.table.impl.QueryTable.sort(QueryTable.java:104)
	at io.deephaven.engine.table.impl.partitioned.PartitionedTableProxyImpl.lambda$sort$24(PartitionedTableProxyImpl.java:459)
	at io.deephaven.engine.table.impl.partitioned.PartitionedTableImpl.lambda$assertResultsStatic$8(PartitionedTableImpl.java:428)
	at io.deephaven.engine.table.impl.partitioned.TableTransformationColumn$OutputFormula.transformAndFill(TableTransformationColumn.java:153)
	at io.deephaven.engine.table.impl.partitioned.TableTransformationColumn$OutputFormula.fillChunk(TableTransformationColumn.java:132)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:412)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doParallelApplyUpdate$3(SelectColumnLayer.java:280)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doParallelApplyUpdate(SelectColumnLayer.java:279)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$prepareParallelUpdate$0(SelectColumnLayer.java:246)
	at io.deephaven.engine.table.impl.util.JobScheduler.lambda$iterateParallel$1(JobScheduler.java:353)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:255)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
	at io.deephaven.engine.table.impl.util.OperationInitializerJobScheduler.lambda$submit$0(OperationInitializerJobScheduler.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.table.impl.OperationInitializationThreadPool$1.lambda$newThread$0(OperationInitializationThreadPool.java:53)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.deephaven.util.ExecutionContextRegistrationException: No ExecutionContext registered, or current ExecutionContext has no QueryScope
	at io.deephaven.util.ExecutionContextRegistrationException.onFailedComponentAccess(ExecutionContextRegistrationException.java:26)
	at io.deephaven.engine.context.PoisonedQueryScope.fail(PoisonedQueryScope.java:22)
	at io.deephaven.engine.context.PoisonedQueryScope.getParamNames(PoisonedQueryScope.java:27)
	at io.deephaven.engine.table.impl.select.codegen.FormulaAnalyzer.getCompiledFormula(FormulaAnalyzer.java:99)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:194)
	... 49 more
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #5094.

This change removes the need for `sort` to use the `QueryCompiler` on the code path that would sort using a static symbol table.

This also disables use of the symbol table during blink table updates.

Nightlies:https://github.com/nbauernfeind/deephaven-core/actions/runs/7939920770/

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SortHelpers.java [hunk 1]
```diff
@@ -330,7 +334,7 @@ private static SparseSymbolMapping createMapping(LongChunk originalSymbol, IntCh
                 final long symTabId = originalSymbol.get(ii);
                 final int region = (int) (symTabId >> (32 + minTrailing));
                 final int id = (int) symTabId;
-                final int mappedId = mappedIndex.get(ii);
+                final int mappedId = LongSizedDataStructure.intSize("SortHelpers#createMapping", mappedIndex.get(ii));
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SortHelpers.java:337]:
```suggestion
                final int mappedId = Math.toIntExact(mappedIndex.get(ii));
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/RowKeysColumnSource.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+    @Override
+    public long getLong(long rowKey) {
+        return rowSet.get(rowKey);
+    }
+
+    @Override
+    public long getPrevLong(long rowKey) {
+        return rowSet.getPrev(rowKey);
+    }
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/RowKeysColumnSource.java:28]:
```suggestion
    public long getLong(long rowKey) {
        return rowSet.find(rowKey);
    }

    @Override
    public long getPrevLong(long rowKey) {
        return rowSet.findPrev(rowKey);
    }
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/RowKeysColumnSource.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+        final MutableLong position = new MutableLong();
+        final RowSequence.Iterator rsit = rowSet.getRowSequenceIterator();
+        rowSequence.forAllRowKeys(rowKey -> {
+            long numToAdvance = rowKey - position.longValue();
+            if (numToAdvance > 0) {
+                rsit.getNextRowSequenceWithLength(numToAdvance);
+                position.add(numToAdvance);
+            }
+            longChunk.add(rsit.peekNextKey());
+        });
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/RowKeysColumnSource.java:45]: We can replace this with `rowSet.invert(rowSequence.asRowSet())` and fill the destination chunk from the result, with appropriate closing. (I don't remember if `asRowSet()` needs to be closed.)
Or we can do this with a single `find`, a row sequence iterator, and position distances.
Or this way:
```
        final MutableLong position = new MutableLong(0);
        try (final RowSequence.Iterator rowSetIterator = rowSet.getRowSequenceIterator()) {
            rowSequence.forAllRowKeys(rowKey -> {
                position.add(rowSetIterator.advanceAndGetPositionDistance(rowKey));
                longChunk.add(position.longValue());
            });
        }
```

Comment (nbauernfeind) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/RowKeysColumnSource.java]: I did some contextual testing (rather than explicit for any kind of input row set and filled row sequence). The testing favors the `invert` approach with a single-range optimization before dropping to rowsequence's fill chunk.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java [hunk 4]
```diff
@@ -242,7 +242,11 @@ private static QueryTable aggregation(
         final QueryTable result = new QueryTable(resultRowSet, resultColumnSourceMap);
         ac.propagateInitialStateToOperators(result, outputPosition.intValue());
 
-        if (input.isRefreshing()) {
+        if (!input.isRefreshing()) {
+            if (resultRowSet.isFlat()) {
+                result.setFlat();
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java:247]: We can probably always set the result of no-key agg to flat. And the result of ticking agg, if input is add-only, append-only, blink, or if preserve-empty is true.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowKeyColumnSource.java [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+
+    @Override
+    public void fillPrevChunk(
+            @NotNull final FillContext context,
+            @NotNull final WritableChunk<? super Values> destination,
+            @NotNull final RowSequence rowSequence) {
+        doFillChunk(destination, rowSequence);
+    }
+
+    public static void doFillChunk(
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowKeyColumnSource.java:49]:
```suggestion
    static void doFillChunk(
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowKeyColumnSource.java [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+        final WritableLongChunk<? super Values> longChunk = destination.asWritableLongChunk();
+        if (rowSequence.isContiguous()) {
+            final int size = rowSequence.intSize();
+            longChunk.setSize(size);
+            final long firstRowKey = rowSequence.firstRowKey();
+            for (int ii = 0; ii < size; ++ii) {
+                longChunk.set(ii, firstRowKey + ii);
+            }
+        } else {
+            rowSequence.fillRowKeyChunk(longChunk);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowKeyColumnSource.java:61]: I'm wondering if I was wrong to suggest the complexity and we should just use this.

Comment (nbauernfeind) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowKeyColumnSource.java:61]: As discussed, the contiguous optimization seemed to be ~8% improvement in a small scenario with ~100k symbols. The performance measurement was not localized to the CS implementation, so it seems significant enough to keep. Noting that I did add a check to see if I should fill by row key ranges and that dropped back down to never having the contiguous optimization. It's possible it's all a wash, but this impl consistently came out on top.

**Review by rcaudy — APPROVED** [review]
