### PR TITLE
KafkaStreamPublisher: Fix ArrayIndexOutOfBoundsException

### LINKED ISSUE #4516: Kafka Stream Publisher  may throw `ArrayIndexOutOfBoundsException`
Using `KafkaTools.consumeToTable` (with a little help of setting `StreamPublisherBase.CHUNK_SIZE` to `32`; but happens naturally by altering Kafka's `max.poll.records`) we can achieve an `ArrayIndexOutOfBoundsException`.

Occasionally, upon entering `consumeRecords` it is possible for 1) `this.chunks` to be non-null (so we continue to use the existing chunks), and 2) `remaining` (calculated via `chunks[0].capacity() - chunks[0].size();`) is `0`.

As we consume records we pre-decrement the remaining from 0 to -1, which causes the AIOBE.
```java
            for (ConsumerRecord<?, ?> record : records) {
                if (--remaining == 0) {
```

The total failure looks similar to this:
```
ph-updateExecutor-11 | .AsyncClientErrorNotifier | Error in table update: Multiple errors encountered while ingesting stream: 
Cause 0: java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 32
Cause 1: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 2: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 3: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 4: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 5: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 6: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 7: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 8: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 9: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 10: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 11: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 12: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 13: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 14: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 15: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 16: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 17: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 18: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32
Cause 19: java.lang.IllegalStateException: Publisher chunks have size mismatch: 33, 32, 32, 32, 32, 32, 32, 32, 32, 32

	at io.deephaven.util.MultiException.maybeWrapInMultiException(MultiException.java:55)
	at io.deephaven.stream.StreamToBlinkTableAdapter.deliverFailures(StreamToBlinkTableAdapter.java:330)
	at io.deephaven.stream.StreamToBlinkTableAdapter.run(StreamToBlinkTableAdapter.java:308)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$UpdateSourceRefreshNotification.run(PeriodicUpdateGraph.java:1879)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 32
	at io.deephaven.chunk.WritableIntChunk.add(WritableIntChunk.java:79)
	at io.deephaven.kafka.ingest.KafkaStreamPublisher.consumeRecords(KafkaStreamPublisher.java:248)
	at io.deephaven.kafka.KafkaTools$SimpleKafkaRecordConsumer.consume(KafkaTools.java:1636)
	at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:383)
	at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:301)
	... 1 more
Cause 1:
java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 32
	at io.deephaven.chunk.WritableIntChunk.add(WritableIntChunk.java:79)
	at io.deephaven.kafka.ingest.KafkaStreamPublisher.consumeRecords(KafkaStreamPublisher.java:248)
	at io.deephaven.kafka.KafkaTools$SimpleKafkaRecordConsumer.consume(KafkaTools.java:1636)
	at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:383)
	at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:301)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #4516

Since we append to these chunks off of the update-graph, we only flush when we need to acquire a new set of chunks. Note that `StreamPublisherBase#flush` does not check to see if the chunk has `.size() > 0` but `IntChunkColumnSource.addChunk` does ensure that you are not adding empty chunks. (Noting that flush() is what happens first during an update graph cycle for the blink table adapter.)

We attempt to be clever to only allocate a new chunk if we are going to write a row to it. To do this, we pre-decrement a counter `remaining` and if the chunk is full we flush. Note this check `if (--remaining == 0) {`  is an off-by-one as we have not yet written the row we are counting. That isn't a big deal though; that just means we never actually fill the chunks. The `AIOBE` actually comes from recalculating the new `remaining` whenever we flush -- we are not accounting for the row that is about to be written.

This causes us to leave the method with `remaining == 1` but the chunks are already full.

### CODE REVIEW

File: extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaStreamPublisher.java [hunk 1]
```diff
@@ -203,7 +203,8 @@ public synchronized long consumeRecords(@NotNull final List<? extends ConsumerRe
                     : null;
 
             for (ConsumerRecord<?, ?> record : records) {
-                if (--remaining == 0) {
+                // Note we only flush if we are about to overflow the chunks.
+                if (--remaining < 0) {
```
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaStreamPublisher.java:207]: My preferred version looks like:
`remaining == 0`
Removed `-1` from the re-initialization of remaining after making new sink chunks
`--remaining` at the end of the for loop

File: extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaStreamPublisher.java [hunk 2]
```diff
@@ -217,8 +218,9 @@ public synchronized long consumeRecords(@NotNull final List<? extends ConsumerRe
                     chunks = getChunksToFill();
                     checkChunkSizes(chunks);
 
-                    remaining = chunks[0].capacity() - chunks[0].size();
-                    Assert.gtZero(remaining, "remaining");
+                    // Note that remaining should account for the row we are about to write.
+                    remaining = chunks[0].capacity() - chunks[0].size() - 1;
+                    Assert.geqZero(remaining, "remaining");
```
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaStreamPublisher.java:223]:
```suggestion
                    remaining = chunks[0].capacity() - chunks[0].size();
                    Assert.gtZero(remaining, "remaining");
```

**Review by rcaudy — APPROVED** [review]
