### PR TITLE
Propagate Barrage propagation errors to the client table widget

### LINKED ISSUE #896: Failed barrage subscriptions result in hung UI
I am calling ParquetTools.readTable('/data/file.parquet') from the web UI for a file that I know we don't support (data nested > 1 levels).  The method throws an exception, which is expected.  The Web UI seems to be left in a bad state tho; the table window has that "spinning DH logo" that is there while you load, that never goes away.  Clicking the "cancel" button just seems to re-trigger the same exception (judging by the log).  The bad user experience potentially here is that the table window never goes away, which is what I would expect to happen if I click "cancel".

See attached image:
Deephaven - Google Chrome_025

The exception:
```
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1116)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:977)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:578)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:1524)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:926)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.access$1400(BarrageMessageProducer.java:89)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:790)
grpc-api_1    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grpc-api_1    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    | caused by:
grpc-api_1    | java.lang.UnsupportedOperationException: Nested optional levels not supported
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.materializeWithNulls(ColumnPageReaderImpl.java:679)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.materialize(ColumnPageReaderImpl.java:344)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.readPageV1(ColumnPageReaderImpl.java:334)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.readDataPage(ColumnPageReaderImpl.java:201)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.materialize(ColumnPageReaderImpl.java:75)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.topage.ToPage.getResult(ToPage.java:52)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.topage.ToPage.toPage(ToPage.java:77)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.ColumnChunkPageStore.toPage(ColumnChunkPageStore.java:158)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPage(VariablePageSizeColumnChunkPageStore.java:111)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:150)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:17)
grpc-api_1    |         at io.deephaven.db.v2.sources.chunk.page.PageStore.fillChunk(PageStore.java:67)
grpc-api_1    |         at io.deephaven.db.v2.sources.regioned.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:50)
grpc-api_1    |         at io.deephaven.db.v2.sources.regioned.DeferredColumnRegionBase.fillChunk(DeferredColumnRegionBase.java:71)
grpc-api_1    |         at io.deephaven.db.v2.sources.chunk.page.PageStore.fillChunk(PageStore.java:71)
grpc-api_1    |         at io.deephaven.db.v2.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:31)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.getSnapshotDataAsChunk(ConstructSnapshot.java:1365)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1285)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:575)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1045)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:977)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:578)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:1524)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:926)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.access$1400(BarrageMessageProducer.java:89)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:790)
grpc-api_1    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grpc-api_1    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    |
```

The code that triggers:

```
from deephaven.ParquetTools import *
t = readTable('/data/nulls_v1_NULLS_SNAPPY.parquet')
```

The file `nulls_v1_NULLS_SNAPPY.parquet` can be obtained from the deephaven-core-test-data repository, here:
https://github.com/deephaven/deephaven-core-test-data/blob/main/parquetFiles/nulls_v1_NULLS_SNAPPY.parquet

One last note:  Judging from the log, every time I press "cancel" the exception is re-triggered, which makes it seem like the readTable operation is retrying.  If this is true this is a potentially very worrisome/bad user experience: re-doing something that a user is trying to cancel when it failed sounds like something that can get very bad very quickly, with the right "destructive" code.

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #896

### CODE REVIEW

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java [hunk 1]
```diff
@@ -839,9 +841,21 @@ public void run() {
                         updateSubscriptionsSnapshotAndPropagate();
                     }
                 } catch (final Exception exception) {
-                    // TODO: global error notification core/#55
-                    log.error().append(logPrefix).append("Could not handle barrage update propagation: ")
-                            .append(exception).endl();
+                    synchronized (BarrageMessageProducer.class) {
```
Comment (devinrsmith) [inline grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java:844]: Do you mean to sync on BarrageMessageProducer.this?

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java [hunk 2]
```diff
@@ -839,9 +842,17 @@ public void run() {
                         updateSubscriptionsSnapshotAndPropagate();
                     }
                 } catch (final Exception exception) {
-                    // TODO: global error notification core/#55
-                    log.error().append(logPrefix).append("Could not handle barrage update propagation: ")
-                            .append(exception).endl();
+                    synchronized (BarrageMessageProducer.this) {
+                        final StatusRuntimeException apiError = GrpcUtil.securelyWrapError(log, exception);
+                        log.error().append(logPrefix).append("Could not handle barrage update propagation: ")
```
Comment (niloc132) [inline grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java:847]: this will be a duplicate log, right? securelyWrapError will also emit it?

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java [hunk 3]
```diff
@@ -839,9 +842,17 @@ public void run() {
...
+                                .append(exception).endl();
+
+                        Streams.concat(activeSubscriptions.stream(), pendingSubscriptions.stream()).distinct()
+                                .forEach(sub -> GrpcUtil.safelyExecute(() -> sub.listener.onError(apiError)));
```
Comment (niloc132) [inline grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java:851]: probably should use the locked variant so you lock on the sub.listener instance to send the error?

File: web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java [hunk 4]
```diff
@@ -1213,6 +1215,11 @@ private void startAndMaybeFlush(boolean isSnapshot, RecordBatch header, ByteBuff
                 });
                 stream.onStatus(err -> {
                     checkStatus(err);
+                    if (!err.isOk()) {
+                        state.forActiveSubscriptions((table, subscription) -> {
```
Comment (niloc132) [inline web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java:1219]: TODO this too, as this is also probably wrong

File: web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java [hunk 5]
```diff
@@ -303,10 +303,11 @@ private void connectToWorker(Supplier<Promise<ConnectToken>> authTokenPromiseSup
                 });
     }
 
-    public void checkStatus(ResponseStreamWrapper.Status status) {
+    public boolean checkStatus(ResponseStreamWrapper.Status status) {
```
Comment (niloc132) [inline web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java:306]: you didn't end up using this return value, right?

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java [hunk 6]
```diff
@@ -5,6 +5,8 @@
 package io.deephaven.grpc_api.barrage;
 
 import com.google.common.annotations.VisibleForTesting;
+import com.google.common.collect.Streams;
+import com.google.rpc.Code;
```
Comment (niloc132) [inline grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageMessageProducer.java:9]: unused?

**Review by niloc132 — DISMISSED** [review]

**Review by niloc132 — APPROVED** [review]
