### PR TITLE
Fix TableViewportSubscription race condition

### LINKED ISSUE #3251: Using the Web GUI's "Select Distinct" function results in an error.
If you use "Select Distinct Values" in the Web GUI, it results in the table no longer displaying properly.

Create a table, and use the Web GUI to "Select Distinct Values". For instance, this table:

```python
from deephaven import read_csv

seattle_weather = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/GSOD/csv/seattle.csv")
```

The error message in the table is `Error: java.lang.AssertionError: realized table is closed, expected status DONE, instead is ACTIVE`.

**Expected results**

**Actual results**

**Additional details and attachments**

**Versions**

 - Engine Version: latest
 - Web UI Version: latest
 - Java Version: 11
 - Barrage Version: Unsure
 - OS: OS X Monterey
 - Browser: Chrome
 - Docker: 20.10.13

### PR DESCRIPTION
**Pull request by mofojed**
- Race condition was causing UI error with selectDistinct
- TableViewportSubscription could initialize after it had already been closed
- Check the status to see if we're already DONE before initializing
- Fixes #3251

Race condition occurs when `subscription.close()` is called before the subscription has copied the original table. You can reproduce this in a JS API page in the developer console by doing a `setInterval`, e.g.:
```
setInterval(() => {
    var subscription = table.setViewport(0, 10)
    subscription.close()
    console.log('table size', table.size)
}, 50)
```

### CODE REVIEW

File: web/client-api/src/main/java/io/deephaven/web/client/api/subscription/scratch [hunk 1]
```diff
@@ -0,0 +1,13 @@
+Trigger Select Distinct
```
Comment (devinrsmith) [inline web/client-api/src/main/java/io/deephaven/web/client/api/subscription/scratch:1]: Extraneous file, yeah? If it's useful for reviewer to see, might post as comment.

**Review by devinrsmith — COMMENTED** [review]
I think @niloc132 should review this.

File: web/client-api/src/main/java/io/deephaven/web/client/api/subscription/scratch (hunk 1 above)
Comment (mofojed) [reply web/client-api/src/main/java/io/deephaven/web/client/api/subscription/scratch]: Whoops, yea I did not mean to include that. The race condition can be identified a little more clearly than mentioned in the doc, I'll update the description.

File: web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java [hunk 2]
```diff
@@ -109,9 +109,13 @@ public TableViewportSubscription(double firstRow, double lastRow, Column[] colum
         this.original = existingTable;
         this.originalState = original.state();
         copy = existingTable.copy(false).then(table -> new Promise<>((resolve, reject) -> {
-
             // Wait until the state is running to copy it
             originalState.onRunning(newState -> {
+                if (this.status == Status.DONE) {
+                    JsLog.debug("TableViewportSubscription closed before originalState.onRunning completed, ignoring");
+                    table.close();
```
Comment (niloc132) [inline web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java:116]: i dont think you need to call this - in the case where this.status == DONE (assigned in internalClose(), we have already closed this.table?

Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java:116]: Then instead of closing here, we should reject the promise.

Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java:116]: Nope, this doesn't work after all, table.close() probably makes the most sense.

**Review by niloc132 — APPROVED** [review]
