### PR TITLE
Corrected AsOfJoin `rehashInternalFull()` to update hashSlots correctly

### LINKED ISSUE #3080: IllegalStateException in AJ update processing
Community user reported a failure in update propagation for an as-of join, with the following stack trace:
```
EFAULT.refreshThread | i.d.e.t.i.MergedListener  | 620087432 aj([[option_symbol, tdate2], tdate2], [[open_interest]]) Merged Listener: Uncaught exception for entry= PerformanceEntry{, id=173, evaluationNumber=128, operationNumber=1, description='aj([[option_symbol, tdate2], tdate2], [[open_interest]])', callerLine='PyLib.java:-2', intervalUsageNanos=1367200, intervalCpuNanos=1365800, intervalUserCpuNanos=0, intervalInvocationCount=1, intervalAdded=2, intervalRemoved=0, intervalModified=0, intervalShifted=0, intervalAllocatedBytes=-9223372036854775808, intervalPoolAllocatedBytes=-9223372036854775808, maxTotalMemory=49056579584, minFreeMemory=22606806136, collections=0, collectionTimeNanos=0, startCpuNanos=0, startUserCpuNanos=0, startTimeNanos=0, startAllocatedBytes=0, startPoolAllocatedBytes=0}: java.lang.IllegalStateException: Bad state: 17, slot=18341, slotIndex=1
        at io.deephaven.engine.table.impl.asofjoin.BucketedChunkedAjMergedListener.process(BucketedChunkedAjMergedListener.java:669)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:258)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1292)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1453)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1171)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1116)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1730)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1720)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1707)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1561)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:278)
```

This is on version `0.17.0`.

### PR DESCRIPTION
**Pull request by lbooker42**
Was able to reproduce the IllegalStateException in AJ update processing referred to in #3080 and found that the full rehashing function was not migrating cookies.  When processing large initial input tables, after a rehash the cookies remained pointing to the original (now invalid) hash slots and initial matches were not being made.  The recorded state of the hash slot in these neglected matches was 0x11 (17) as recorded in the initial issue.

Have written a reproducing test case and added to `QueryTableAjTest`

NOTE: `testAjBothIncrementalOverflow()` did not catch this error because it verifies static vs. incremental AJ and both would have failed in identical ways.

When merged will close #3080

### CODE REVIEW

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 1]
```diff
@@ -558,6 +558,20 @@ public static AsOfMatchRule of(ReverseAsOfJoinRule rule) {
...
+     * original table are returned intact, together with all the columns from rightTable.
+     *
+     * @param rightTable The right side table on the join.
+     * @param columnsToMatch A comma separated list of match conditions ("leftColumn=rightColumn" or
+     *        "columnFoundInBoth")
+     * @param columnsToAdd A comma separated list with the columns from the left side that need to be added to the right
+     *        side as a result of the match.
+     * @return a new table joined according to the specification in columnsToMatch and columnsToAdd
+     */
+    Table aj(Table rightTable, Collection<String> columnsToMatch, Collection<String> columnsToAdd);
```
Comment (lbooker42) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:573]: Was surprised that this did not exist for Java/Groovy, needed for reproduction of bug

**Review by lbooker42 — COMMENTED** [review]
`rehashInternalFull()` doesn't allow passing additional parameters, so to migrate the hash cookies properly I needed to add the member variable `hashSlots`. Once that existed, passing `hashSlots` as a parameter is simply confusing and I removed it from the function signatures.

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java (hunk 1 above)
Comment (rcaudy) [reply engine/api/src/main/java/io/deephaven/engine/table/Table.java:573]: You don't need to add this. You can get where you need to with:
```
io.deephaven.api.TableOperations#aj(TABLE, java.util.Collection<? extends io.deephaven.api.JoinMatch>, java.util.Collection<? extends io.deephaven.api.JoinAddition>, io.deephaven.api.AsOfJoinRule)
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java [hunk 2]
```diff
@@ -397,6 +397,18 @@ default Table aj(Table rightTable, Collection<String> columnsToMatch) {
                 AsOfMatchRule.of(result.rule));
     }
 
+    @Override
+    @FinalDefault
+    default Table aj(Table rightTable, Collection<String> columnsToMatch, Collection<String> columnsToAdd) {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java:402]: Unneeded, as noted in `Table`.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherFloat.java [hunk 3]
```diff
@@ -308,6 +307,7 @@ protected void rehashInternalFull(final int oldSize) {
                     destState[destinationTableLocation] = originalStateArray[sourceBucket];
                     destLeftSource[destinationTableLocation] = oldLeftSource[sourceBucket];
                     destRightSource[destinationTableLocation] = oldRightSource[sourceBucket];
+                    hashSlots.set(oldModifiedCookie[sourceBucket], destinationTableLocation);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherFloat.java:310]: So, your instincts were right, it was in `rehashInternalFull`! =)

File: engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/RightIncrementalAsOfJoinStateManagerTypedBase.java [hunk 4]
```diff
@@ -262,15 +266,19 @@ protected void buildTable(
             final ColumnSource<?>[] buildSources,
             final IntegerArraySource hashSlots,
             final TypedHasherUtil.BuildHandler buildHandler) {
+
+        // store this for access by the hashing methods
+        this.hashSlots = hashSlots;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/RightIncrementalAsOfJoinStateManagerTypedBase.java:271]: I think you should re-set this to `null` on leaving `buildTable`. Firstly, this way we don't keep the state manager's `slots` around until the first update. Secondly, I think it might help us identify bugs in maintenance of this field.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/RightIncrementalAsOfJoinStateManagerTypedBase.java [hunk 5]
```diff
@@ -440,8 +436,11 @@ private int accumulateIndices(RowSet rowSet, ColumnSource<?>[] sources, IntegerA
             return 0;
         }
 
+        // store this for access by the hashing methods
+        this.hashSlots = slots;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/RightIncrementalAsOfJoinStateManagerTypedBase.java:440]: Same comment as in `buildTable`, although I only have a bug-discovery and symmetry argument here, as I think `accumulateIndices` may only be used from listeners.
