### PR TITLE
Fix writing empty tables; fix missing beginning magic number. Fixes #855

### LINKED ISSUE #855: Writing an empty table with no dictionary columns still fails in parquet.
This test fails:

```
    @Test
    public void emptyTrivialTable() {
        final Table t = TableTools.emptyTable(0).select("A = i");
        assertEquals(int.class, t.getDefinition().getColumn("A").getDataType());
        final File dest = new File(rootFile, "ParquetTest_emptyTrivialTable.parquet");
        ParquetTools.writeTable(t, dest);
        final Table fromDisk = ParquetTools.readTable(dest);
        TstUtils.assertTableEquals(t, fromDisk);
        assertEquals(t.getDefinition(), fromDisk.getDefinition());
    }
```

### PR DESCRIPTION
**Pull request by jcferretti**
Turns out what we were missing was the initial magic number (ref: https://github.com/apache/parquet-format#file-format)

With that, all the hacks for things like "dictionaries mysteriously don't work at offset zero" can go away (_facepalm_, _despair_).

Before this change, our "zero rows" writes would show up in the output of parquet-cli like:

```
cfs@erke 23:14:09 ~/github/parquet-mr
$ /l/parquet-cli/1.12.1/bin/parquet-cli pages ~/dh/oss3/io.deephaven.db.v2.parquet.ParquetTableReadWriteTest_root/ParquetTest_emptyFlatParquet_test.parquet
Unknown error
java.lang.RuntimeException: Illegal row group of 0 rows
        at org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:902)
        at org.apache.parquet.cli.commands.ShowPagesCommand.run(ShowPagesCommand.java:98)
        at org.apache.parquet.cli.Main.run(Main.java:155)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.parquet.cli.Main.main(Main.java:185)
```

Interestingly, parquet-cli meta will show the illegal row group of zero rows without complaining on that file:

```
cfs@erke 23:11:20 ~/github/parquet-mr
$ /l/parquet-cli/1.12.1/bin/parquet-cli meta ~/dh/oss3/io.deephaven.db.v2.parquet.ParquetTableReadWriteTest_root/ParquetTest_emptyFlatParquet_test.parquet
  
File path:  /a0/h/cfs/dh/oss3/io.deephaven.db.v2.parquet.ParquetTableReadWriteTest_root/ParquetTest_emptyFlatParquet_test.parquet
Created by: parquet-mr version 1.12.0 (build db75a6815f2ba1d1ee89d1a90aeb296f1f3a8f20)
Properties:
  dh_codec_data_type:someSerializable: io.deephaven.db.v2.parquet.ParquetTableWriter$SomeSillyTest
       dh_codec_name:someSerializable: io.deephaven.util.codec.SerializableCodec
Schema:
message root {
  optional binary someStringColumn (STRING);
  optional binary nonNullString (STRING);
  optional binary nonNullPolyString (STRING);
  optional int32 someIntColumn (INTEGER(32,true));
  optional int64 someLongColumn;
  optional double someDoubleColumn;
  optional float someFloatColumn;
  optional boolean someBoolColumn;
  optional int32 someShortColumn (INTEGER(16,true));
  optional int32 someByteColumn (INTEGER(8,true));
  optional int32 someCharColumn (INTEGER(16,false));
  optional int64 someTime (TIMESTAMP(NANOS,true));
  optional binary someKey (STRING);
  optional binary nullKey (STRING);
  optional binary someSerializable;
} 
  

Row group 0:  count: 0  Infinity TB records  start: -1  total: 95 B
--------------------------------------------------------------------------------
                   type      encodings count     avg size   nulls   min / max
someStringColumn   BINARY    S RR_     0         Infinity TB 0
nonNullString      BINARY    S RR_     0         Infinity TB 0
nonNullPolyString  BINARY    S RR_     0         Infinity TB 0
someIntColumn      INT32     S RR      0         NaN B      0
someLongColumn     INT64     S RR      0         NaN B      0
someDoubleColumn   DOUBLE    S RR      0         NaN B      0
someFloatColumn    FLOAT     S RR      0         NaN B      0
someBoolColumn     BOOLEAN   S RR      0         NaN B      0
someShortColumn    INT32     S RR      0         NaN B      0
someByteColumn     INT32     S RR      0         NaN B      0
someCharColumn     INT32     S RR      0         NaN B      0
someTime           INT64     S RR      0         NaN B      0
someKey            BINARY    S RR_     0         Infinity TB 0
nullKey            BINARY    S RR_     0         Infinity TB 0
someSerializable   BINARY    S RR      0         NaN B      0

```

What we get now in the output of meta is just the Schema, and no rowgroup information (because there isn't any).

### CODE REVIEW

File: DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java [hunk 1]
```diff
@@ -442,10 +445,6 @@ public Integer get() {
                     }
                 }
             }
-            if (keyCount.intValue() == 0) {
```
Comment (rcaudy) [inline DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java:445]: Just to check my understanding, if we had an empty dictionary we were writing a dummy one with a single empty string?

File: Parquet/src/main/java/io/deephaven/parquet/ColumnWriterImpl.java [hunk 2]
```diff
@@ -95,27 +101,22 @@ private void initWriter() {
...
-    public void addDictionaryPage(Object dictionaryValues, int valuesCount) throws IOException {
+    public void addDictionaryPage(final Object dictionaryValues, final int valuesCount) throws IOException {
         if (pageCount > 0) {
             throw new RuntimeException("Attempting to add dictionary past the first page");
         }
         BulkWriter dictionaryWriter = getWriter(column.getPrimitiveType());
         //noinspection unchecked
         dictionaryWriter.writeBulk(dictionaryValues, valuesCount);
         dictionaryOffset = writeChannel.position();
-        if (dictionaryOffset == 0) {//Ugly hack to deal with parquet readers that assume dictionary is not there if the offset is 0
```
Comment (rcaudy) [inline Parquet/src/main/java/io/deephaven/parquet/ColumnWriterImpl.java:106]: I assume parquet-tools and/or drill don't mind this change?

File: Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java [hunk 3]
```diff
@@ -68,19 +73,19 @@ public RowGroupWriter addRowGroup(long size) {
     }
 
     public void close() throws IOException {
+        final OutputStream os = Channels.newOutputStream(writeChannel);
+        os.write(ParquetFileReader.MAGIC);
```
Comment (rcaudy) [inline Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java:77]: We must have been doing this somewhere else... right? How did anything read us at all?

File: Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java [hunk 4]
```diff
@@ -68,19 +73,19 @@ public RowGroupWriter addRowGroup(long size) {
...
         serializeOffsetIndexes(offsetIndexes, blocks, writeChannel);
```
Comment (rcaudy) [inline Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java:78]: Pass `os` into this method, too. It makes new ones, in a loop, and that's gross.

File: Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java [hunk 5]
```diff
@@ -68,19 +73,19 @@ public RowGroupWriter addRowGroup(long size) {
...
         ParquetMetadata footer = new ParquetMetadata(new FileMetaData(type, extraMetaData, Version.FULL_VERSION), blocks);
-        serializeFooter(footer, writeChannel);
+        serializeFooter(footer, os);
         writeChannel.close();
```
Comment (rcaudy) [inline Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java:81]: Switch to a `try-finally` and close `os` instead of `writeChannel`. See JavaDoc for `Channels.newOutputStream`.

File: DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java (hunk 1 above)
Comment (jcferretti) [reply DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java:445]: Yeah.

File: Parquet/src/main/java/io/deephaven/parquet/ColumnWriterImpl.java (hunk 2 above)
Comment (jcferretti) [reply Parquet/src/main/java/io/deephaven/parquet/ColumnWriterImpl.java:106]: Parquet tool doesn't, trying drill would be... complicated.  I could try pyarrow.

File: Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java (hunk 3 above)
Comment (jcferretti) [reply Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java:77]: Parquet is read backwards.  You seek to the end of the file and find the metadata: at the end, magic number, right before the end, the size of the metadata, which tells you how far back to seek to read said metadata.   The metadata itself has offsets in the file for the different section.   So you read all backwards, were the file itself is telling you things are.   So I think "almost" nothing would notice the /initial/ magic number.

File: Parquet/src/main/java/io/deephaven/parquet/ColumnWriterImpl.java (hunk 2 above)
Comment (jcferretti) [reply Parquet/src/main/java/io/deephaven/parquet/ColumnWriterImpl.java:106]: Just tried pyarrow, it worked:

```
cfs@erke 09:44:22 ~/py
$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import pyarrow.parquet as pq
>>> t = pq.read_table('/a0/h/cfs/dh/oss3/io.deephaven.db.v2.parquet.ParquetTableReadWriteTest_root/ParquetTest_emptyFlatParquet_test.parquet')
>>> t.to_pandas()
Empty DataFrame
Columns: [someStringColumn, nonNullString, nonNullPolyString, someIntColumn, someLongColumn, someDoubleColumn, someFloatColumn, someBoolColumn, someShortColumn, someByteColumn, someCharColumn, someTime, someKey, nullKey, someSerializable]
Index: []

```

**Review by rcaudy — APPROVED** [review]
