### PR TITLE
Eliminate Double Error Notifications in jsapi and Error Log

### LINKED ISSUE #5015: Double error notification
While working on some new kafka StreamPublishing code, I've been able to demonstrate a double error notification behavior - first, a detailed message is shown in the UI:

first-error

followed shortly there-after flashing into:

second-error

This was a bit jarring from web UX, but also strange as usually error details are obscured.

On the server side, we see the following stack traces:

```
2024-01-08T22:38:14.359Z | ph-updateExecutor-17 | ERROR | .AsyncClientErrorNotifier | Error in table update: org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange(Fetcher.java:1408)
        at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1360)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.pollAndAccept(KafkaPublisherDriver.java:128)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.runOnce(KafkaPublisherDriver.java:107)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.run(KafkaPublisherDriver.java:93)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-01-08T22:38:14.781Z | heduler-Concurrent-4 | ERROR | i.d.s.s.SessionService    | Internal Error '35a05ec6-08f0-4ae3-a1ee-e60a18303ab0' org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange(Fetcher.java:1408)
        at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1360)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.pollAndAccept(KafkaPublisherDriver.java:128)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.runOnce(KafkaPublisherDriver.java:107)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.run(KafkaPublisherDriver.java:93)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #5015.

This fixes:
1) the double error notification experience via the jsapi
2) ExportedTableUpdateMessage's error message is now obfuscated
3) de-dupes identical errors by reusing the first-known UUID associated with the exception or a cause

### CODE REVIEW

File: server/src/main/java/io/deephaven/server/session/SessionService.java [hunk 1]
```diff
@@ -70,10 +85,47 @@ public StatusRuntimeException transform(final Throwable err) {
...
             } else if (err instanceof InterruptedException) {
-                return GrpcUtil.securelyWrapError(log, err, Code.UNAVAILABLE);
+                return securelyWrapError(log, err, Code.UNAVAILABLE);
             } else {
-                return GrpcUtil.securelyWrapError(log, err);
+                return securelyWrapError(log, err, Code.INVALID_ARGUMENT);
+            }
+        }
+
+        public synchronized StatusRuntimeException securelyWrapError(
```
Comment (niloc132) [inline server/src/main/java/io/deephaven/server/session/SessionService.java:94]: Why public - do we expect subclasses of this inner type?

File: server/src/main/java/io/deephaven/server/session/SessionService.java [hunk 2]
```diff
@@ -70,10 +85,43 @@ public StatusRuntimeException transform(final Throwable err) {
...
+                if (errorId == null) {
+                    errorId = UuidCreator.getRandomBased();
+                }
+
+                curr = err;
+                do {
+                    if (curr.getStackTrace().length != 0) {
+                        // Stackless exceptions are not very useful, so we only add to the cache if the stack exists.
+                        idCache.put(curr, errorId);
+                    }
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/session/SessionService.java:117]: Is this `if` condition meaningful with identity keys? (I can't see how that would be the case.) I think we can safely dump the check and cache unconditionally.

File: server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java [hunk 3]
```diff
@@ -174,7 +187,7 @@ private synchronized void onNewTableExport(final Ticket ticket, final int export
                 sendUpdateMessage(ticket, -1, Exceptions.statusRuntimeException(Code.FAILED_PRECONDITION,
                         "Exported Table Already Failed"));
             } else {
-                sendUpdateMessage(ticket, -1, GrpcUtil.securelyWrapError(log, err, Code.FAILED_PRECONDITION));
+                sendUpdateMessage(ticket, -1, errorTransformer.transform(err));
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java:190]: We lost the status code here. Seems bad.

File: web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java [hunk 4]
```diff
@@ -301,6 +304,8 @@ public void setResolution(ResolutionState resolution, String failMsg) {
             // after a failure, we should discard onRunning (and this state entirely)
             onRunning = null;
             onReleased = null;
+
+            forActiveTables(t -> t.failureHandled(failMsg));
```
Comment (rcaudy) [inline web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java:308]: For one of the two changed sites in `WorkerConnection`, this has (effectively) changed from:
```
                        state.forActiveSubscriptions((table, subscription) -> {
                            table.failureHandled(failMsg);
                        });
```
Is that material?

File: server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java (hunk 3 above)
Comment (nbauernfeind) [reply server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java:190]: Colin says that ILLEGAL_ARGUMENT is a slight preference for him anyway. Technically these errors aren't the RPC stream themselves, but being embedded in the ETUM stream. I'd prefer that grpc status code is not part of the transform API anyway.

We're going to leave this one as is.

File: web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java (hunk 4 above)
Comment (nbauernfeind) [reply web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java:308]: Colin and I discussed. Even though there are some scenarios where the server-side table is still alive after the subscription fails, that the majority of the time it would be best for the client to try to recreate the result table. If the table wasn't alive (at least for our more expensive operations) then memoization will save face, otherwise creating a new table would have been required after a subsequent resubscribe fails.

This is a more conservative approach to the failure scenario, but not exorbitantly so.

File: server/src/main/java/io/deephaven/server/session/SessionService.java (hunk 2 above)
Comment (nbauernfeind) [reply server/src/main/java/io/deephaven/server/session/SessionService.java:117]: Apparently when the jvm starts to throw stackless exceptions, it throws singletons.

```java
    @Test
    public void testThing() {
        int cnt = 0;
        long ttl = 0;
        int[] arr = new int[0];
        Exception[] es = new Exception[10];
        while (true) {
            if (++ttl == 1000000L) break;
            try {
                arr[0] += cnt;
            } catch (ArrayIndexOutOfBoundsException npe) {
                if (npe.getStackTrace().length == 0) {
                    es[cnt++] = npe;
                    if (cnt == es.length) {
                        break;
                    }
                }
            }
        }

        System.out.println("Total Loops: " + ttl);
        for (int i = 1; i < cnt; ++i) {
            System.out.println("es[" + i + "] == es[0] is " + (es[i] == es[0]));
        }
    }
```

Output:
```
Total Loops: 99336
es[1] == es[0] is true
es[2] == es[0] is true
es[3] == es[0] is true
es[4] == es[0] is true
es[5] == es[0] is true
es[6] == es[0] is true
es[7] == es[0] is true
es[8] == es[0] is true
es[9] == es[0] is true
```

File: server/src/main/java/io/deephaven/server/session/SessionService.java [hunk 5]
```diff
@@ -85,38 +85,41 @@ public StatusRuntimeException transform(final Throwable err) {
...
-                needToAdd |= errorId == null;
-            } while (errorId == null && ++currDepth < MAX_STACK_TRACE_CAUSAL_DEPTH && (curr = curr.getCause()) != null);
+            final boolean shouldLog;
+
+            synchronized (idCache) {
+                errorId = idCache.getIfPresent(err);
+                shouldLog = errorId == null;
+
+                int currDepth = 0;
+                for (Throwable causeToCheck = err.getCause(); errorId == null
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/session/SessionService.java:103]: Spotless has done terrible things to these two for loops. It might be worth `// @formatter:off` and `// @formatter:on`.

File: server/src/main/java/io/deephaven/server/session/SessionService.java [hunk 6]
```diff
@@ -57,7 +57,7 @@ public interface ErrorTransformer {
 
     @Singleton
     public static class ObfuscatingErrorTransformer implements ErrorTransformer {
-        private static final int MAX_STACK_TRACE_CAUSAL_DEPTH = 25;
+        static final int MAX_STACK_TRACE_CAUSAL_DEPTH = 25;
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/session/SessionService.java:60]:
```suggestion
        @VisibleForTesting
        static final int MAX_STACK_TRACE_CAUSAL_DEPTH = 25;
```

**Review by rcaudy — DISMISSED** [review]

**Review by rcaudy — APPROVED** [review]
