### PR TITLE
Session State Impl Review

### LINKED ISSUE #35: SessionState - unit tests
SessionState is relatively complicated due to all of the ways that the user can interact with exports.

Exports:
- have dependencies
- may be defined out of order (cannot guarantee ordering in grpc)
- may have clean-up tasks when released
- can throw exceptions in error handlers
- can throw exceptions in the exporting callable
- users can cancel/release at any time

Unit tests have been deferred in favor of getting a proof of concept going, but these tests are extremely important.

### PR DESCRIPTION
**Pull request by nbauernfeind**
Here are unit tests for some intended use-cases of session state.

Fixes #35.

### CODE REVIEW

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 1]
```diff
@@ -372,8 +423,8 @@ public static boolean isExportStateFinal(final ExportNotification.State state) {
         // used to manage liveness of dependencies (to prevent a dependency from being released before it is used)
         private List<ExportObject<?>> parents = Collections.emptyList();
 
-        // used to detect when this object is ready for export
-        volatile int dependentCount = -1;
+        // used to detect when this object is ready for export (is visible for atomic int field updater)
+        protected volatile int dependentCount = -1;
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:427]: What happens if you keep the field private? Feels kind of yucky to make the field visible, since it's a public class. You could always make it a `static` class with an explicit reference to the enclosing `SessionState`.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 2]
```diff
@@ -372,8 +423,8 @@ public static boolean isExportStateFinal(final ExportNotification.State state) {
         // used to manage liveness of dependencies (to prevent a dependency from being released before it is used)
         private List<ExportObject<?>> parents = Collections.emptyList();
 
-        // used to detect when this object is ready for export
-        volatile int dependentCount = -1;
+        // used to detect when this object is ready for export (is visible for atomic int field updater)
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:426]: Because GitHub sucks, I can't comment on code you didn't change. But `next` and `prev` should come out. Or maybe something got lost... we had a whole plan in place to get rid of the linked list running through the exported objects.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 3]
```diff
@@ -447,9 +503,12 @@ public T get() {
             if (isExpired()) {
                 throw GrpcUtil.statusRuntimeException(Code.UNAUTHENTICATED, "session has expired");
             }
-            if (state != ExportState.EXPORTED) {
-                throw new IllegalStateException("Dependent export '" + exportId + "' is " + state.name() + " and not " + ExportState.EXPORTED.name() + ".");
+
+            // Note: an export may be released while still being a dependency of queued work; so let's make sure we're still valid
+            if (result == null) {
+                throw new IllegalStateException("Dependent export '" + exportId + "' is " + state.name() + " and not exported.");
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:509]: I've lost context: how do we know this is a "dependent" export? And can you delete the trailing '.'?

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 4]
```diff
@@ -536,17 +595,25 @@ private synchronized void setState(final ExportState state) {
...
-            if (parent != null && isExportStateFinal(parent.state)) {
+            if (parent != null && isExportStateTerminal(parent.state)) {
                 synchronized (this) {
                     errorId = parent.errorId;
+                    ExportState terminalState = ExportState.DEPENDENCY_FAILED;
+
                     if (errorId == null) {
                         final String errorDetails;
                         switch (parent.state) {
                             case RELEASED:
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:612]: Should we treat a parent that has been released as `DEPENDENCY_FAILED` for the dependent, or something else?

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 5]
```diff
@@ -686,7 +756,7 @@ private void setResult(final T result) {
 
             this.result = result;
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:757]: Do we still want to assign result if we won't manage it?

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionService.java [hunk 6]
```diff
@@ -148,6 +153,7 @@ public void closeSession(final SessionState session) {
             return;
         }
         unmanage(session);
+        session.onExpired();
```
[the remark this answers is not in the document]
Comment (nbauernfeind) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionService.java:156]: Unmanaging a second time is an error -- so the slower gRPC request to close the session will receive an error. Doesn't really seem so bad to me; but synchronizing either on the SessionService or on the SessionState would prevent the error. The behavior of the non-race is to silently call the close a success.

Maybe the proper work around is to tryUnmanage instead ignoring the error? We won't ever have a non-singleton ref-count of session states on the session service.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 7]
```diff
@@ -277,7 +328,7 @@ public void onExpired() {
      */
     @Override
     protected void destroy() {
-        expiration = null;
+        onExpired();
```
[the remark this answers is not in the document]
Comment (nbauernfeind) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:324]: Note that onExpired is idempotent -- but its purpose is to clear all outstanding state and to prevent additional outstanding state from being created. It doesn't matter if this session "disappears" because it times out (client fails to rotate session cookie) or via the closeSession rpc. In both cases we should prevent additional state from existing and we should close all outstanding streams at the moment of closure/expiration.

So I think this is not just OK, but adds value. Alternatively, we could have onExpired call destroy() and have the clean up logic inside of destroy(); maybe this is more the pattern you would want to see?

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 1 above)
Comment (nbauernfeind) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:418]: The issue is giving proper access to DEPENDENT_COUNT_UPDATER. The UPDATER is static and on the outer class. This is an inner class that captures the outer class closure. I can make it package-private instead of protected. Making it private however gives this error:

```
grpc-api_1    | java.lang.IllegalAccessException: Class io.deephaven.grpc_api.session.SessionState can not access a member of class io.deephaven.grpc_api.session.SessionState$ExportObject with modifiers "private volatile"
```

I can't move the field UPDATER into the inner class because you can't have a static member inside of a non-static inner class.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 3 above)
Comment (nbauernfeind) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:498]: It's a dependency because you're trying to resolve it? If you didn't want it, you shouldn't call get?

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 4 above)
Comment (nbauernfeind) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:602]: That's a reasonable question. I am thinking of this as a user error - like hey dummy, you released these before you gave me a chance to depend on them. (As well as the cascading cancel -- this failed because a parent (or grandparent) was cancelled.) I'm happy to change to whatever you like. We could just as well do DEPENDENCY_ALREADY_RELEASED to go along with the new ever-accumulating Index of export id's -- this wasn't a reasonable option prior to the index.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 5 above)
Comment (nbauernfeind) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:747]: Yes. Unless I misunderstand the question. Not every exported type is required to be a liveness referent. So, setting the result is how we communicate (like a future) the result of the operation. The liveness referent is there to quickly mark the object graph as dead when the session expires or is closed. Non liveness referent exports won't get any form of notification when the session expires. If you truly have an export that doesn't have a result you will tend to be a "non-export" which technically exports a null value (after invoking the desired void() method).

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 8]
```diff
@@ -813,17 +803,29 @@ private synchronized ExportNotification makeExportNotification() {
...
+            throw GrpcUtil.statusRuntimeException(Code.UNAUTHENTICATED, "session has expired");
         }
-        listener.initialize();
+        listener.initialize(versionId);
     }
 
     public void removeExportListener(final StreamObserver<ExportNotification> observer) {
-        exportListeners.stream().filter(l -> l.listener == observer).findFirst().ifPresent(this::tryUnmanage);
+        final Optional<ExportListener> listener = exportListeners.stream().filter(l -> l.listener == observer).findFirst();
+        if (listener.isPresent()) {
```
[the remark this answers is not in the document]
Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:775]:
```
    public void removeExportListener(final StreamObserver<ExportNotification> observer) {
        exportListeners.stream().filter(l -> l.listener == observer).findFirst().ifPresent(el -> {
            el.dropReference();
            exportListeners.remove(el);
        });
    }
```

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 9]
```diff
@@ -733,23 +744,38 @@ private synchronized ExportNotification makeExportNotification() {
...
         }
     }
 
     public void addExportListener(final StreamObserver<ExportNotification> observer) {
+        if (isExpired()) {
+            throw GrpcUtil.statusRuntimeException(Code.UNAUTHENTICATED, "session has expired");
+        }
+
         final ExportListener listener = new ExportListener(observer);
         manage(listener);
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:761]: I think it makes more sense for `SessionState` to not be a `LivenessArtifact` and use `retainReference` and `dropReference` rather than `manage`/`unmanage`.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:339]: I think having `destroy` (that is, being a `LivenessArtifact` muddies the water a bit. Best to just let `onExpired` do the work.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 1 above)
Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:387]: Can you try the "make it static" approach and see what happens?

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 4 above)
Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:571]: Let's see what we can do for the user experience of the hapless user who releases their parent dependencies too early, or cancels them, etc.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java (hunk 5 above)
Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:697]: We discussed verbally. Question stands.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 10]
```diff
@@ -1170,15 +1120,7 @@ public long getLongKey(final ExportObject<?> exportObject) {
...
-                final ExportObject<?> retval = new ExportObject<>(key, nextInternalExportSequence++);
-                if (tail == null) {
-                    head = tail = retval;
-                } else {
-                    retval.prev = tail;
-                    tail.next = retval;
-                    tail = retval;
-                }
-                return retval;
+                return new ExportObject<>(key);
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:1073]: By the way you no longer need to synchronize on `exportMap`.

File: grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java [hunk 11]
```diff
@@ -188,19 +164,20 @@ private synchronized void sendUpdateMessage(final Ticket ticket, final long size
...
             update.setUpdateFailureMessage(GrpcUtil.securelyWrapError(log, error).getMessage());
         }
 
-        nextMessage.addUpdates(update);
+        try {
+            responseObserver.onNext(update.build());
+        } catch (final RuntimeException err) {
+            log.error().append(logPrefix).append("failed to notify listener of state change: ").append(err).endl();
+            session.unmanageNonExport(this);
+            destroy();
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java:179]: I think you are using liveness when you don't want to. Also, your ListenerImpl need not override destroy.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 12]
```diff
@@ -110,15 +107,15 @@
     private static final AtomicIntegerFieldUpdater<SessionState> EXPORT_LISTENER_VERSION_UPDATER =
             AtomicIntegerFieldUpdater.newUpdater(SessionState.class, "exportListenerVersion");
 
-    // accumulate the set of used export id's; it is ideal if the api client uses few continuous ranges
-    private final Index usedExportIds = Index.CURRENT_FACTORY.getEmptyIndex();
+    // Usually, export life cycles are managed explicitly with the life cycle of the session state. However, we need
+    // to be able to close non-exports that are not in the map but are otherwise satisfying outstanding gRPC requests.
+    private final LivenessScope nonExportsToClose = new LivenessScope();
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:112]: We don't want to do this. Instead, a SimpleReferenceManager of WeakSimpleReferences to Closeables.

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java [hunk 13]
```diff
@@ -124,7 +124,7 @@ public SubscriptionObserver(final SessionState session, final StreamObserver<Inp
             this.myPrefix = "SubscriptionObserver{" + Integer.toHexString(System.identityHashCode(this)) + "}: ";
             this.session = session;
             this.listener = listenerAdapter.adapt(responseObserver);
-            session.manage(this); // attach the liveness of this subscription to the session
+            this.session.attachLivenessReferent(this);
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java:127]: This object should be a `SingletonLivenessManager` instead of a `LivenessArtifact`.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 14]
```diff
@@ -694,14 +688,26 @@ private void setResult(final T result) {
...
-                if (!isExportStateTerminal(state) && !isExpired()) {
-                    if (this.result instanceof LivenessReferent) {
-                        tryManage((LivenessReferent) result);
+            // result is cleared on destroy; so don't set if it won't be called
+            if (!tryRetainReference()) {
+                return;
+            }
+
+            try {
+                this.result = result;
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:697]: I still don't think you should do this if you're terminal.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 15]
```diff
@@ -905,7 +902,8 @@ protected synchronized void destroy() {
             this.exportId = exportId;
 
             if (exportId == NON_EXPORT_ID) {
-                this.export = new ExportObject<>(NON_EXPORT_ID);
+                this.export = new ExportObject<>(SessionState.this, NON_EXPORT_ID);
+                nonExportsToClose.manage(this.export);
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:906]: Goes away.

File: grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java [hunk 16]
```diff
@@ -210,11 +199,8 @@ public void onFailureInternal(final Throwable error, final UpdatePerformanceTrac
         }
 
         @Override
-        public synchronized void destroy() {
-            if (destroyed) {
-                return;
-            }
-            destroyed = true;
+        public void destroy() {
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java:202]: Method should come out, but you already did it.

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java [hunk 17]
```diff
@@ -248,23 +251,23 @@ private synchronized void queueRequest(final SubscriptionRequest subscriptionReq
...
         @Override
         public void onCompleted() {
             log.error().append(myPrefix).append("client stream closed subscription").endl();
-            destroy(); // destroy may not be called via unmanageNonExport if this subscription is also exported
+            close();
         }
 
         @Override
-        protected synchronized void destroy() {
+        public void close() {
```
[the remark this answers is not in the document]
Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java:264]: Also, save export object and cancel in close(). Clear pointer when assigning bmp, otherwise.

[the remark this answers is not in the document]
Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java:264]: Lastly, we should remove our closable from session state.

File: grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java [hunk 18]
```diff
@@ -242,6 +244,7 @@ protected void destroy() {
 
             safelyExecute(() -> logBuffer.unsubscribe(this));
             safelyExecuteLocked(responseObserver, responseObserver::onCompleted);
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java:246]: Check these methods, they shouldn't catch `Error` in general.

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 19]
```diff
@@ -289,12 +292,24 @@ public AuthContext getAuthContext() {
...
-     * Attach a non-export to the liveness scope bound to the session.
+     * Attach an on-close callback bound to the life of the session.
      *
-     * @param referent the object to manage
+     * @param onClose the callback to invoke at end-of-life
      */
-    public void attachLivenessReferent(final LivenessReferent referent) {
-        nonExportsToClose.manage(referent);
+    public synchronized void addOnCloseCallback(final Closeable onClose) {
+        if (isExpired()) {
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:300]: By the way, `isExpired` has a bug. Change it to something like:
```
    public boolean isExpired() {
        final SessionService.TokenExpiration localExpiration = expiration;
        return localExpiration == null || localExpiration.deadline.compareTo(scheduler.currentTime()) <= 0;
    }
```

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 20]
```diff
@@ -289,12 +292,24 @@ public AuthContext getAuthContext() {
...
     /**
-     * Attach a non-export to the liveness scope bound to the session.
+     * Attach an on-close callback bound to the life of the session.
      *
-     * @param referent the object to manage
+     * @param onClose the callback to invoke at end-of-life
      */
-    public void attachLivenessReferent(final LivenessReferent referent) {
-        nonExportsToClose.manage(referent);
+    public synchronized void addOnCloseCallback(final Closeable onClose) {
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:299]: This method should be synchronized on `onCloseCallbacks`, not on `this`.
At that point, I would just switch to synchronizing the remove and clear, too, and changing the reference manager to "not concurrent".

Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:299]: I would use this pattern for exportListeners, too, and back off to an `ArrayList` for those.

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java [hunk 21]
```diff
@@ -203,11 +206,15 @@ private synchronized void queueRequest(final SubscriptionRequest subscriptionReq
             }
 
             log.info().append(myPrefix).append("awaiting parent table").endl();
-            exportBuilder
+            subscriptionExport = exportBuilder
                     .require(parent)
                     .onError(listener::onError)
                     .submit(() -> {
                         synchronized (SubscriptionObserver.this) {
+                            if (isClosed) {
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java:214]: `subscriptionExport = null`

File: grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java [hunk 22]
```diff
@@ -251,24 +258,40 @@ private synchronized void queueRequest(final SubscriptionRequest subscriptionReq
...
+                    return;
+                }
+
+                isClosed = true;
             }
 
-            bmp.removeSubscription(listener);
+            if (subscriptionExport != null) {
+                subscriptionExport.cancel();
+            }
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java:282]: `subscriptionExport = null` ?

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 23]
```diff
@@ -105,14 +104,14 @@
...
-    private final ConcurrentLinkedQueue<ExportListener> exportListeners = new ConcurrentLinkedQueue<>();
+    private final List<ExportListener> exportListeners = new ArrayList<>();
     private volatile int exportListenerVersion = 0;
     private static final AtomicIntegerFieldUpdater<SessionState> EXPORT_LISTENER_VERSION_UPDATER =
             AtomicIntegerFieldUpdater.newUpdater(SessionState.class, "exportListenerVersion");
 
     // Usually, export life cycles are managed explicitly with the life cycle of the session state. However, we need
     // to be able to close non-exports that are not in the map but are otherwise satisfying outstanding gRPC requests.
-    private final SimpleReferenceManager<Closeable, WeakSimpleReference<Closeable>> onCloseCallbacks = new SimpleReferenceManager<>(WeakSimpleReference::new, true);
+    private final SimpleReferenceManager<Closeable, WeakSimpleReference<Closeable>> onCloseCallbacks = new SimpleReferenceManager<>(WeakSimpleReference::new);
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:114]: `concurrent` defaults to true..

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 24]
```diff
@@ -784,24 +789,47 @@ private synchronized ExportNotification makeExportNotification() {
...
+                throw GrpcUtil.statusRuntimeException(Code.UNAUTHENTICATED, "session has expired");
+            }
 
-        // we must check one last time that the session has not already expired; will otherwise be cleaned up on expiration
-        if (isExpired()) {
-            removeExportListener(observer);
-            throw GrpcUtil.statusRuntimeException(Code.UNAUTHENTICATED, "session has expired");
+            listener = new ExportListener(observer);
+            exportListeners.add(listener);
+            versionId = EXPORT_LISTENER_VERSION_UPDATER.incrementAndGet(this);
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:801]: No CAS needed

File: grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java [hunk 25]
```diff
@@ -784,24 +789,47 @@ private synchronized ExportNotification makeExportNotification() {
...
+            }
+
+            if (off == exportListeners.size()) {
+                // not found
+                return null;
+            }
+
+            final int finalOff = exportListeners.size() - 1;
+            exportListeners.set(off, exportListeners.get(finalOff));
+            exportListeners.remove(finalOff).onRemove();
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:829]: Calling `onRemove` on the wrong item.

Comment (rcaudy) [reply grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java:829]: Probably partially go back to old impl, I recommend COWArrayList.

**Review by rcaudy — APPROVED** [review]

**Review by rcaudy — APPROVED** [review]
