### PR TITLE
Arrays of tables/tablemaps should be sized correctly

### LINKED ISSUE #1951: Calling close on a figure object throws an error
Likely related to #1787 according to Colin.

**Description**

Closing a figure object from the server w/ the JS API method triggers an exception. Closing tables does not appear to trigger the same exception.

**Steps to reproduce**
Use dev mode web UI. The prod mode latest published doesn't seem to trigger the error.

Run this Python code or any plotting code
```python
from deephaven import Plot
from deephaven.TableTools import newTable, intCol

source = newTable(
    intCol("Keys", 3, 2, 2, 1, 1, 1)
)

result = Plot.catHistPlot("Keys Count", source, "Keys")\
    .chartTitle("Count Of Each Key")\
    .show()
```

Close the chart panel.

**Expected results**

No error in console

**Actual results**

<details><summary>Stack trace</summary>

```
dh-core.js:10087 Uncaught TypeError: Cannot read properties of undefined (reading 'workerConnection')
    at Object.$close_0 (dh-core.js:10087:38)
    at JsFigure$16methodref$close$Type.accept_48 [as accept] (dh-core.js:22966:9)
    at Object.$consume (dh-core.js:35823:12)
    at Spliterators$ArraySpliterator.consume (dh-core.js:35833:6)
    at Object.$forEachRemaining_10 (dh-core.js:35786:17)
    at Spliterators$ArraySpliterator.forEachRemaining_25 [as forEachRemaining] (dh-core.js:35837:6)
    at Object.$forEach_6 (dh-core.js:37816:27)
    at JsFigure.close_8 [as close] (dh-core.js:22835:33)
    at FigureChartModel.close (FigureChartModel.js:62:1)
    at ChartPanel.jsx:183:1
    at Promise.wrappedPromise.cancel (PromiseUtils.ts:45:1)
    at Pending.cancel (Pending.ts:60:1)
    at ChartPanel.componentWillUnmount (ChartPanel.jsx:169:1)
    at callComponentWillUnmountWithTimer (react-dom.development.js:19580:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at safelyCallComponentWillUnmount (react-dom.development.js:19587:1)
    at commitUnmount (react-dom.development.js:20109:1)
    at unmountHostComponents (react-dom.development.js:20464:1)
    at commitDeletion (react-dom.development.js:20500:1)
    at commitMutationEffects (react-dom.development.js:22782:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at commitRootImpl (react-dom.development.js:22509:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at commitRoot (react-dom.development.js:22381:1)
    at finishSyncRender (react-dom.development.js:21807:1)
    at performSyncWorkOnRoot (react-dom.development.js:21793:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21188:1)
    at updateContainer (react-dom.development.js:24373:1)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:24774:1)
    at react-dom.development.js:24884:1
    at unbatchedUpdates (react-dom.development.js:21903:1)
    at Object.unmountComponentAtNode (react-dom.development.js:24883:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.utils.ReactComponentHandler._destroy (goldenlayout.js:6237:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.container.ItemContainer.emit (goldenlayout.js:265:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.items.Component._$destroy (goldenlayout.js:4586:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.items.Stack.removeChild (goldenlayout.js:3979:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.items.Stack.removeChild (goldenlayout.js:5414:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.items.Component.close (goldenlayout.js:4555:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.container.ItemContainer.close (goldenlayout.js:1850:1)
    at push.../golden-layout/dist/goldenlayout.js.lm.controls.Tab._onCloseClick (goldenlayout.js:3767:1)
    at HTMLDivElement.dispatch (jquery.js:5429:1)
    at HTMLDivElement.elemData.handle (jquery.js:5233:1)
```

</details>

**Versions**
 - Deephaven: 0.9.0

### PR DESCRIPTION
**Pull request by niloc132**
Without this, the JS Figure will not close correctly, though other
operations are not affected by this.

Fixes #1951

### CODE REVIEW

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java [hunk 1]
```diff
@@ -657,7 +656,7 @@ public Promise fetch(JsFigure figure, FetchObjectResponse response) {
                     JsTable table = new JsTable(connection, cts);
                     // never attempt a reconnect, since we might have a different figure schema entirely
                     table.addEventListener(JsTable.EVENT_DISCONNECT, ignore -> table.close());
-                    tables[p1] = table;
+                    tables[tables.length] = table;
```
Comment (mofojed) [inline web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java:659]: Ah the beauty of JS

Couldn't we just do the same with the promises as well?

**Review by mofojed — APPROVED** [review]

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java (hunk 1 above)
Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java:659]: Could, but no need, since we know it will be sized to the full width.

I could make this more "correct in java" and count how many are tables... but it is js, so I didn't (but for a reviewer who asks for it, i will).

**Review by mattrunyon — APPROVED** [review]
Confirmed there is no more exception in the web UI
