### PR TITLE
Wrap Jetty's Resource type to force an invalid last-modified header

### LINKED ISSUE #3011: Caching issue when updating Web UI
**Description**

There seems to still be an issue with caching the Web UI index.html. Even though I've updated the web version, it is returning the same ETag, loading the old version from memory. The Web UI then fails to load because the JS files no longer exist.

**Steps to reproduce**
1. Run `./gradlew server-jetty-app:run`
2. Open http://localhost:10000/ide/ and let the UI load
3. Stop the server
4. Update `WEB_VERSION` in `web/client-ui/Dockerfile` to a new version
5. Run `./gradlew server-jetty-app:run`
6. Open http://localhost:10000/ide/ and let the UI load

**Expected results**
6. New UI should load

**Actual results**
6. UI fails to load because of a caching issue. See screenshots.

**Additional details and attachments**

Before updating Web packages. ETag for `/ide/` is `W/"dw/nfoEwv/cdw/nNJbAiXY"`:
First load:
image
After refresh:
image

After updating Web Packages (on my [branch web-v0.20.0](https://github.com/mofojed/deephaven-core/tree/web-v0.20.0)):
First load, ETag still has the same value:
image
This causes the js pages not to load, as the hash for the js files is incorrect:
image

After a hard refresh, it loads properly, but still the same ETag `W/"dw/nfoEwv/cdw/nNJbAiXY"`:
image

That ETag is different than the ETags for other files.
 

**Versions**
 - Deephaven: SHA `41e4b2f5790dabd0dceaa1663a043013ab4fac48`
 - OS: Ubuntu
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by niloc132**
Jetty always returns the last-modified date of the file, but Gradle unsets the "true" last modified date in favor of ensuring that build files cache only based on their contents. Disabling this feature is possible, but still may present as buggy in Jetty, such as if a 1.0 release occurred, then 2.0, then a 1.1 hotfix - if an installation of 1.1 were later replaced with 2.0, the 1.1 files would be "newer" so would be considered up to date.

This patch removes the last-modified value by only returning -1 when requested. We could go further and return an etag that actually maps to the release version or the contents of the file, but that is left for future work.

Fixes #3011

### CODE REVIEW

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+import java.nio.channels.ReadableByteChannel;
+
+/**
+ * Simple wrapper around the Jetty Resource type, to grant us control over caching features. The current implementation
+ * only removes the last-modified value, but a future version could provide a "real" weak/strong etag.
+ */
+public class ControlledCacheResource extends Resource {
+    private final Resource wrapped;
+
+    public ControlledCacheResource(Resource wrapped) {
```
Comment (mofojed) [inline server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java:19]: Seems like there's a lot of methods we're not overriding, such as `.toURL`, `.getURL`, `.setAssociate`, etc. Are we sure these are the only functions that need to be overridden? How did you decide what to override?

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+    public boolean isDirectory() {
+        return wrapped.isDirectory();
+    }
+
+    @Override
+    public long lastModified() {
+        // Always return -1, so that we don't get the build system timestamp. In theory we could return the app startup
+        // time as well, so that clients that connect don't need to revalidate quite as often, but this could have other
+        // side effects such as in load balancing with a short-lived old build against a seconds-older new build.
+        return -1;
```
Comment (mofojed) [inline server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java:48]: This will still be an issue with clients that have already stored the `Last-modified` header. Still get an issue with the client passing `If-Modified-Since: Fri, 01 Feb 1980 05:00:00 GMT`, I'm guessing somewhere Jetty is still checking against what the reported lastModified date is (even if it's not in a header?) and I'm still getting a 304: 

image

Everybody upgrading from v0.17 will still hit this issue and they'll be broken until they do a hard refresh.

**Review by mofojed — CHANGES_REQUESTED** [review]

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+
+    @Override
+    public String[] list() {
+        return wrapped.list();
+    }
+
+    @Override
+    public Resource addPath(String path) throws IOException, MalformedURLException {
+        // Re-wrap any instance that might be returned
+        return new ControlledCacheResource(wrapped.addPath(path));
```
Comment (devinrsmith) [inline server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java:99]: Might make sense to check if `wrapped instanceof ControlledCacheResource` so we can reduce re-wrapping a bunch of times? Not sure if issue in practice, but something like:

```java
cacheResource.addPath("1").addPath("2").addPath("3")...
```

File: server/jetty/src/main/java/io/deephaven/server/jetty/DropIfModifiedSinceHeader.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+         * @param request the {@link HttpServletRequest} to be wrapped.
+         * @throws IllegalArgumentException if the request is null
+         */
+        public HeaderRemovingHttpServletRequestWrapper(HttpServletRequest request, String headerToRemove) {
+            super(request);
+            this.headerToRemove = headerToRemove;
+        }
+
+        @Override
+        public String getHeader(String name) {
```
Comment (devinrsmith) [inline server/jetty/src/main/java/io/deephaven/server/jetty/DropIfModifiedSinceHeader.java:48]: I think `getDateHeader` (and `getIntHeader`) should be overridden as well, yeah?

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java (hunk 3 above)
Comment (devinrsmith) [reply server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java:99]: Probably makes sense to test alongside the JS plugin PR which creates zip resources.

File: server/jetty/src/main/java/io/deephaven/server/jetty/DropIfModifiedSinceHeader.java (hunk 4 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/DropIfModifiedSinceHeader.java:48]: Ah probably, though from testing it doesn't seem to matter.

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java (hunk 3 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java:99]: I can add that check, but each addPath will only wrap the next layer, right?
 * `cacheResource` is singly wrapped
 * `resource.addPath("1")` returns a singly wrapped instance, `resource1`
 * `resource1.addPath("2")` returns a singly wrapped instance, etc
 
Unless the initially created ControlledCacheResource is multiply wrapped to begin with, _or_ the wrapped resource itself somehow contains already-wrapped resources (for example a ResourceCollection full of already wrapped resources, and then wrap the ResourceCollection again), I can't see a way for this to happen? What am I missing?

Mitigation of the theoretical issue will be replacing the public ctor with a static wrap() method that does the check, and delegate to that when wrapping a sub-resource.

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java (hunk 1 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java]: I only overrode the abstract methods, and only modified the one that was specific to last-modified. The rest of the methods are implemented by the superclass Resource to rely on the abstract methods. 

 * setAssociate is kind of a special case - it isnt clear to me how it is used, and has explicit docs that it isn't actually used...
 * isSame already delegates to equals (allowing for a subclass to override isSame separately), but we already override equals
 * getResource delegates to addPath, which we override
 * isAlias calls getAlias, and getAlias has a sane default of null for resources that dont alias anything. It looks like this is meant for soft links, absolute path vs canonical path, but we're only dealing with paths inside of jars, so it shouldnt ever matter.
 * getListHTML generates HTML and has a default impl that we don't want to own
 * copyTo arguably does need us to implement it differently to work properly, but at the same time, we don't really support this - internally it is used for unpacking web archives to read them off of the disk
 * getAllResources delegates to list() and addPath(), both of which we implement, no other implementation overrides this default impl
 * 

That said, toURL is static, so doesnt need to be overridden, and getURL _is_ overridden in this class (since it is abstract).

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java (hunk 2 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java:55]: This should be fixed now, thanks for bringing it up.

File: server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java (hunk 1 above)
Comment (mofojed) [reply server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java]: Nit-pick - `getURI()` is overridden, not `getURL()`... but looks like `getURL` is deprecated anyway so I think that's okay.

**Review by mofojed — APPROVED** [review]

**Review by devinrsmith — APPROVED** [review]
LGTM - tested w/ the js plugins PR, successfully removed my ability to get 304s out w/ `If-Modified-Since`.
