### PR TITLE
If the server/proxy doesn't provide an error string, make one up

### LINKED ISSUE #3498: `coreClient.login` rejects with a "" error on failed auth
When trying to log in anonymously with anon auth disabled, `coreClient.login` rejects with an empty string error and doesn't trigger the `HACK_CONNECTION_FAILURE` event.

Expected:
Either reject with a proper error or trigger the `HACK_CONNECTION_FAILURE` with failure details.

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #3498

### CODE REVIEW

File: web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java [hunk 1]
```diff
@@ -456,7 +456,11 @@ private Promise<Void> authUpdate() {
                     // token is no longer valid, signal deauth for re-login
                     // TODO deephaven-core#2564 fire an event for the UI to re-auth
                     checkStatus(status);
-                    reject.onInvoke(status.getDetails());
+                    if (status.getDetails() == null || status.getDetails().isEmpty()) {
+                        reject.onInvoke(status.getDetails());
```
Comment (vbabich) [inline web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java:460]: Should this be the opposite? Reject with `status.getDetails()` if it's not null or empty.

Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java:460]: Yes, it definitely should. I must have somehow not rebuilt when I un-reverted this...

Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java]: Fixed, tested by running the IDE with PSK enabled on the latest server, to confirm I didn't get the 16 error code, but the proper message `Authentication details invalid`.

**Review by vbabich — APPROVED** [review]
