### PR TITLE
Prevent parquet from closing zstd streams on finalization

### LINKED ISSUE #2569: Parquet ZSTD file is not decompressed properly
**Description**

Split off from #2495 (and not solved by the two fixes in the PR that solved that ticket), originally introduced by #2397.

At least one sample zstd-compressed parquet file isn't loading properly. This worked in the 0.13 release, but is no longer working after compression was refactored to solve some native issues

**Steps to reproduce**
Download the r/place dataset from https://deephaven.io/wp-content/2022_place_deephaven.parquet
Try to load it as a table, in python this is roughly:
```
from deephaven.parquet import read
t = read("/path/to/2022_place_deephaven.parquet")
```

**Expected results**

Table loads, can be scrolled, made into a plot.

**Actual results**
```
io.deephaven.base.verify.RequirementFailure: Requirement failed: required isOpen == true, instead isOpen == false.                                                     
        at io.deephaven.base.verify.Require.fail(Require.java:107)                                                                                                     
        at io.deephaven.base.verify.Require.eqTrue(Require.java:1834)                                                                                                  
        at io.deephaven.base.verify.Require.eqTrue(Require.java:1839)                                                                                                  
        at io.deephaven.parquet.base.util.CachedChannelProvider$CachedChannel.size(CachedChannelProvider.java:174)                                                     
        at sun.nio.ch.ChannelInputStream.available(ChannelInputStream.java:114)                                                                                        
        at java.io.BufferedInputStream.available(BufferedInputStream.java:416)                                                                                         
        at com.github.luben.zstd.ZstdInputStreamNoFinalizer.readInternal(ZstdInputStreamNoFinalizer.java:147)                                                   
        at com.github.luben.zstd.ZstdInputStreamNoFinalizer.read(ZstdInputStreamNoFinalizer.java:123)                                                           
        at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:87)                                                                                  
        at org.apache.parquet.hadoop.codec.ZstdDecompressorStream.read(ZstdDecompressorStream.java:43)                                                          
        at java.io.DataInputStream.readFully(DataInputStream.java:200)                                                                                          
        at java.io.DataInputStream.readFully(DataInputStream.java:170)                                                                                          
        at org.apache.parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:286)                                                                
        at org.apache.parquet.bytes.BytesInput.copy(BytesInput.java:202)                                                                                        
        at io.deephaven.parquet.compress.DeephavenCodecFactory$CodecWrappingCompressor.decompress(DeephavenCodecFactory.java:108)                               
        at io.deephaven.parquet.base.ColumnPageReaderImpl.readDataPage(ColumnPageReaderImpl.java:221)                                                           
        at io.deephaven.parquet.base.ColumnPageReaderImpl.materialize(ColumnPageReaderImpl.java:90)                                                  
        at io.deephaven.parquet.table.pagestore.topage.ToPage.getResult(ToPage.java:58)                                                              
        at io.deephaven.parquet.table.pagestore.topage.ToPage.toPage(ToPage.java:85)                                                                            
        at io.deephaven.parquet.table.pagestore.ColumnChunkPageStore.toPage(ColumnChunkPageStore.java:91)                                                       
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPage(VariablePageSizeColumnChunkPageStore.java:122)                     
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:161)           
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:20)            
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:75)                                                                                      
        at io.deephaven.parquet.table.region.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:50)                                                 
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:79)                                                                                      
        at io.deephaven.engine.table.impl.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:51)                     
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.getSnapshotDataAsChunkList(ConstructSnapshot.java:1462)                       
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1344)                                
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:594)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1087)                
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1019)                
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:599)                        
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2143)                                                            
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1317)                                
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:994)
```

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #2569

### CODE REVIEW

**Review by devinrsmith — APPROVED** [review]

File: extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/codec/ZstdCodec.java [hunk 1]
```diff
@@ -3,11 +3,48 @@
...
+
 /**
- * Provides an alternative codec name of "ZSTD" instead of the superclass's "ZSTANDARD".
+ * Provides an alternative codec name of "ZSTD" instead of the superclass's "ZSTANDARD". These streams are also modified
+ * to use the "no finalizer" variant of the underlying streams, so that GC picking up the streams doesn't close the
+ * underlying file.
  */
 public class ZstdCodec extends ZstandardCodec {
+    @Override
+    public CompressionInputStream createInputStream(InputStream stream) throws IOException {
```
Comment (rcaudy) [inline extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/codec/ZstdCodec.java:26]: I think all of these changes belong in a differently-licensed module. Probably `ParquetHadoop`.

**Review by rcaudy — CHANGES_REQUESTED** [review]

File: extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/codec/ZstdCodec.java (hunk 1 above)
Comment (devinrsmith) [reply extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/codec/ZstdCodec.java]: Or we can make this module apache as well? (If it makes more sense to put into ParquetHadoop b/c they are intimately related, then I agree that might be best.)

File: ParquetHadoop/src/main/java/io/deephaven/parquet/compress/codec/zstd/ZstdDecompressorStream.java [hunk 2]
```diff
@@ -7,6 +25,10 @@
 import java.io.IOException;
 import java.io.InputStream;
 
+/**
+ * Modified version of {@link org.apache.parquet.hadoop.codec.ZstdDecompressorStream} but with the no-finalizer
+ * version of the output stream to avoid closing the underlying stream when GC runs.
```
Comment (rcaudy) [inline ParquetHadoop/src/main/java/io/deephaven/parquet/compress/codec/zstd/ZstdDecompressorStream.java:30]:
```suggestion
 * version of the input stream to avoid closing the underlying stream when GC runs.
```

File: extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/codec/ZstdCodec.java (hunk 1 above)
Comment (niloc132) [reply extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/codec/ZstdCodec.java]: I moved the code for the moment anyway, but if we end up adding much more in this compression stuff I think it could be nice to open that up, offer as a different option than the upstream CompressionCodecFactory(s).

**Review by rcaudy — APPROVED** [review]
