### PR TITLE
Make autocomplete stop spamming logs with junk

### LINKED ISSUE #843: Autocomplete should not spam the logs with trash
If the user is typing some code that autocomplete doesn't understand, it should NOT spam stacktraces to the logs.

### PR DESCRIPTION
**Pull request by JamesXNelson**
Resolves #843

### CODE REVIEW

File: open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java [hunk 1]
```diff
@@ -218,7 +218,15 @@ private void fixRanges(
             if (LspTools.greaterThan(result.getStart(), requested)) {
                 // The result starts after the user's cursor.
                 // adjust the text edit back, stopping at the cursor.
-                throw new UnsupportedOperationException("No extendStart support yet");
+                if (log.isTraceEnabled()) {
+                    log.trace()
+                            .append("No extendStart support yet; result:")
```
Comment (rcaudy) [inline open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java:223]: Do you want a trailing space here after the `:`?

File: open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java [hunk 2]
```diff
@@ -520,8 +528,22 @@ private void annotationComplete(Collection<CompletionItem.Builder> results, Chun
...
+            Node parent = node;
+            while(parent.jjtGetParent() != null && ! (parent.jjtGetParent() instanceof ChunkerDocument)) {
+                parent = parent.jjtGetParent();
+            }
+            log.trace()
+                    .append("Node type ")
+                    .append(node.getClass().getCanonicalName())
+                    .append(" not yet supported: ")
+                    .append(node.toSource())
+                    .append("\nParent source:")
```
Comment (rcaudy) [inline open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java:542]: blah blah, `nl()` and trailing space?

**Review by rcaudy — APPROVED** [review]

**Review by rcaudy — APPROVED** [review]
