### PR TITLE
fix: JS charts should handle shifts, read subscription data by key

### LINKED ISSUE #2435: JS ChartData type doesn't handle shifts correctly
Not the prettiest query, but it seems to get the job done.

Create the following ticking table, and then use chart builder to create a bar chart with TimeBin on x-axis and Count on y-axis, w/ sync'd state. Add a quick-filter on M is equal to 8. The chart will likely tick correctly for a little bit, but then some it will likely stop ticking and will show incorrect data.

```groovy
t = timeTable("00:00:00.001")
  .updateView("TimeBin=lowerBin(Timestamp, 1000000000)", "I=i", "K=i%3+i%5+i%7+i%11", "M=K%3+K%5+K%7+K%11")
  .sort("M")
  .countBy("Count", "TimeBin", "M")
  .sort("M")
```

image

A similar demonstration has been achieved w/ pie chart.

### LINKED ISSUE #6074: Ticking charts in JS API are broken
**Description**

After the JS refactor, at least some ticking tables produce errors when displayed in charts.

This is a regression caused by #5890.

**Steps to reproduce**
1. Create a ticking table with inserts as well as appends, e.g.
    ```python
    from deephaven import time_table
    t = time_table("PT0.01s").update(["I=i", "J=I % 7841", "K = I % 7853", "L = J * K", "M = Math.sin(L)"]).sort("M")
    ```
2. Using the chart builder, create a chart from this table
**Expected results**

A chart should appear that gets new rows added to it

**Actual results**

The chart does not have updates, and there are errors in the browser console, such as 
```
User callback ( 
function lambda() ) of type  updated  failed:  
Object { stackTrace: (39) […], detailMessage: "Index: 66, Size: 66", backingJsObject: Error, suppressedExceptions: [] }
```

### PR DESCRIPTION
**Pull request by niloc132**
Only viewport subscriptions should read data (and formatting) by
position. Also fixes an error where -1 was not returned when an invalid
position was checked in a RangeSet.

Fixes #6074
Fixes #2435

### CODE REVIEW

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java [hunk 1]
```diff
@@ -29,118 +28,51 @@
...
             }
         }
 
-        if (JsSettings.isDevMode()) {
-            assert tableData.getRows().length == indexes.length;
-            assert cachedData.values().stream().flatMap(m -> m.values().stream())
-                    .allMatch(arr -> arr.length == indexes.length);
-            assert cachedData.values().stream().flatMap(m -> m.values().stream()).allMatch(arr -> arr
-                    .reduce((Object val, Any p1, int p2) -> ((Integer) val) + 1, 0) == indexes.length);
+        // then adds
```
Comment (nbauernfeind) [inline web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java:59]: isn't this where you should apply shifts?

**Review by nbauernfeind — APPROVED** [review]

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java (hunk 1 above)
Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java:59]: (discussed on videocall) This implementation doesn't care about shifts - the rowSet provided by the subscription is already correctly shifted, we just need to splice the values into the (flat) array so that downstream charting can ingest those arrays directly.
