### PR TITLE
Fix racy TestKeyedArrayBackedMutableTable behavior, improve LTM unit test messaging, eliminate deprecated LTM methods

### LINKED ISSUE #575: LTM exclusive lock is still held
I think this issue was supposed to be fixed, or at least made better, by #571, but looks like it's still happening on occasion:

```
Check failure on line 36 in TestKeyedArrayBackedMutableTable
@github-actions github-actions / long-check-ci test report
TestKeyedArrayBackedMutableTable.testAppendOnly
java.lang.IllegalStateException: LTM reset for unit tests reported errors:
	LTM exclusive lock is still held
```

https://github.com/deephaven/deephaven-core/runs/2555676565?check_suite_focus=true

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #575.

### CODE REVIEW

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java [hunk 1]
```diff
@@ -278,10 +267,24 @@ private void waitForCompletion() throws InterruptedException, ExecutionException
...
     }
 
-    private void handleDelayedRefresh(BaseArrayBackedMutableTable kabut) {
-        new Thread(() -> {
-            SleepUtil.sleep(200);
-            LiveTableMonitor.DEFAULT.runWithinUnitTestCycle(kabut::refresh);
-        }).start();
+    private void handleDelayedRefresh(final BaseArrayBackedMutableTable table, final FunctionalInterfaces.ThrowingRunnable<IOException> action) throws Exception {
+        final Thread refreshThread;
+        final Semaphore gate = new Semaphore(0);
```
Comment (devinrsmith) [inline DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:272]: I think CountDownLatch is more appropriate construct to user here.

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java [hunk 2]
```diff
@@ -278,10 +267,24 @@ private void waitForCompletion() throws InterruptedException, ExecutionException
...
+            refreshThread.start();
+            action.run();
+
+        } finally {
+            table.setOnPendingChange(null);
+        }
+        try {
+            refreshThread.join();
+        } catch (InterruptedException ignored) {
+        }
```
Comment (devinrsmith) [inline DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:288]: Does it make sense to just not catch this exception and let junit handle it?

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java [hunk 3]
```diff
@@ -278,10 +267,24 @@ private void waitForCompletion() throws InterruptedException, ExecutionException
...
+        try {
+            refreshThread = new Thread(() -> {
+                gate.acquireUninterruptibly();
+                LiveTableMonitor.DEFAULT.runWithinUnitTestCycle(table::refresh);
+            });
+            refreshThread.start();
+            action.run();
+
+        } finally {
+            table.setOnPendingChange(null);
```
Comment (devinrsmith) [inline DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:283]: It seems like there may be another race here? We need to make sure that the LTM cycle has actually picked up our action - ie, I'm assuming that `action.run()`, invoking `mutableInputTable.add` is completed off thread? In which case, it's possible that we re-null-out setOnPendingChange before a cycle starts.

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java [hunk 4]
```diff
@@ -278,10 +267,24 @@ private void waitForCompletion() throws InterruptedException, ExecutionException
...
+        final Thread refreshThread;
+        final Semaphore gate = new Semaphore(0);
+        table.setOnPendingChange(gate::release);
+        try {
+            refreshThread = new Thread(() -> {
+                gate.acquireUninterruptibly();
+                LiveTableMonitor.DEFAULT.runWithinUnitTestCycle(table::refresh);
+            });
+            refreshThread.start();
+            action.run();
```
Comment (devinrsmith) [inline DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:280]: Maybe we can get rid of the gate, and just have `setOnPendingChange(refreshThread::start)`?

Or, can the action itself be invoking the LTM code:

```
table.setOnPendingChange(() -> LiveTableMonitor.DEFAULT.runWithinUnitTestCycle(table::refresh))
```
?

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java (hunk 1 above)
Comment (rcaudy) [reply DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:272]: It's functionally equivalent, but sure, it's a better name. I had considered it, but didn't use it just because it's slightly more obscure. I'll change it.

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java (hunk 2 above)
Comment (rcaudy) [reply DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:288]: Sure. Less code.

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java (hunk 3 above)
Comment (rcaudy) [reply DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:283]: No. Action.run() runs onPendingChange on the current thread.

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java (hunk 4 above)
Comment (rcaudy) [reply DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java:280]: No, that defeats the intentionally-concurrent design of the unit test.

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java (hunk 2 above)
Comment (rcaudy) [reply DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java]: I ended up wrapping and re-throwing, to add more documentation to the exception message. But it's not ignored anymore.

File: DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java (hunk 1 above)
Comment (rcaudy) [reply DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java]: This is done. While doing it, I noticed a way to improve the concurrency of the test, so that's a nice side effect.

**Review by devinrsmith — APPROVED** [review]
I'm happy enough that this seems better than the sleep, and we think it will fix the issue. Were you ever actually able to reproduce the issue locally?

More broadly speaking, the concurrent nature of of the engine and our testing of it likely deserves improvements in the future. I know we were considering injecting the LTM to get rid of the global one, and that would probably be the proper time to revamp our unit testing.

Let @niloc132 chime in before merging.

**Review by niloc132 — APPROVED** [review]
