### PR TITLE
fix: Credentials Resolution Bug in S3 Reads

### LINKED ISSUE #6435: S3 parquet provider very slow without specified credentials
In an environment with no S3 credentials defined, run the following command

```python
from deephaven import parquet
from deephaven.experimental import s3

poi = parquet.read(
    path="s3://fsq-os-places-us-east-1/release/dt=2024-11-19/places/parquet/places-00000.snappy.parquet",
    special_instructions=s3.S3Instructions(
        # @devinrsmith had a theory that it was timeout, but that doesn't seem to make a difference
        connection_timeout="PT20s",
        read_timeout="PT20s"
    ),
)
```
By itself that command takes about 10-20s locally. If credentials are defined (either using the standard aws config file in the user's home folder, or just adding `credentials=s3.Credentials.anonymous()` to the `@S3Instructions` params), that time is 5-10s.

After the command completes, the web UI will show the table, subscribing to it with a viewport. Ostensibly that should only load about a page of each column, and should be able to load fairly quickly. Instead, that takes 200-300s locally. With credentials provided, that is 2-5s.

---

In several `ForkJoinPool.commonPool-worker-N`  threads, calls to `java.util.concurrent.locks.ReentrantLock.tryLock()` were the biggest "consumer" of time, preventing these threads from proceeding. From a thread that spent 226 seconds in PageStore.fillChunk:
screenshot934

Example stack trace in that lock (not the same thread, but close):
```
"ForkJoinPool.commonPool-worker-130" #647 [2238196] daemon prio=5 os_prio=0 cpu=107.56ms elapsed=936.99s tid=0x00007b2b3c046e80 nid=2238196 waiting on condition  [0x00007b2d95bf8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.5/Native Method)
        - parking to wait for  <0x000000060c00ed90> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@21.0.5/LockSupport.java:269)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.5/AbstractQueuedSynchronizer.java:756)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(java.base@21.0.5/AbstractQueuedSynchronizer.java:1038)
        at java.util.concurrent.locks.ReentrantLock$Sync.tryLockNanos(java.base@21.0.5/ReentrantLock.java:168)
        at java.util.concurrent.locks.ReentrantLock.tryLock(java.base@21.0.5/ReentrantLock.java:479)
        at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:194)
        at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
        at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.resolveCredentials(InstanceProfileCredentialsProvider.java:149)
        at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
        at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60)
        at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:109)
        at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
        at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:128)
        at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
        at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60)
        at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:109)
        at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
        at software.amazon.awssdk.services.s3.auth.scheme.internal.S3AuthSchemeInterceptor.lambda$trySelectAuthScheme$3(S3AuthSchemeInterceptor.java:152)
        at software.amazon.awssdk.services.s3.auth.scheme.internal.S3AuthSchemeInterceptor$$Lambda/0x00007b2e347768c0.get(Unknown Source)
        at software.amazon.awssdk.core.internal.util.MetricUtils.reportDuration(MetricUtils.java:77)
        at software.amazon.awssdk.services.s3.auth.scheme.internal.S3AuthSchemeInterceptor.trySelectAuthScheme(S3AuthSchemeInterceptor.java:152)
        at software.amazon.awssdk.services.s3.auth.scheme.internal.S3AuthSchemeInterceptor.selectAuthScheme(S3AuthSchemeInterceptor.java:83)
        at software.amazon.awssdk.services.s3.auth.scheme.internal.S3AuthSchemeInterceptor.beforeExecution(S3AuthSchemeInterceptor.java:63)
        at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$beforeExecution$1(ExecutionInterceptorChain.java:59)
        at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain$$Lambda/0x00007b2e34769590.accept(Unknown Source)
        at java.util.ArrayList.forEach(java.base@21.0.5/ArrayList.java:1596)
        at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.beforeExecution(ExecutionInterceptorChain.java:59)
        at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.runInitialInterceptors(AwsExecutionContextBuilder.java:239)
        at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:130)
        at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsAsyncClientHandler.java:63)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.lambda$execute$3(BaseAsyncClientHandler.java:116)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler$$Lambda/0x00007b2e347d2a80.get(Unknown Source)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.measureApiCallSuccess(BaseAsyncClientHandler.java:294)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:89)
        at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:56)
        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.getObject(DefaultS3AsyncClient.java:5681)
        at software.amazon.awssdk.services.s3.DelegatingS3AsyncClient.lambda$getObject$43(DelegatingS3AsyncClient.java:4233)
        at software.amazon.awssdk.services.s3.DelegatingS3AsyncClient$$Lambda/0x00007b2e347d0ad8.apply(Unknown Source)
        at software.amazon.awssdk.services.s3.internal.crossregion.S3CrossRegionAsyncClient.invokeOperation(S3CrossRegionAsyncClient.java:61)
        at software.amazon.awssdk.services.s3.DelegatingS3AsyncClient.getObject(DelegatingS3AsyncClient.java:4233)
        at io.deephaven.extensions.s3.S3Request.sendImpl(S3Request.java:163)
        - locked <0x000000063344ab88> (a io.deephaven.extensions.s3.S3Request)
        at io.deephaven.extensions.s3.S3Request$Acquired.send(S3Request.java:193)
        at io.deephaven.extensions.s3.S3ChannelContext.getOrCreateRequest(S3ChannelContext.java:161)
        at io.deephaven.extensions.s3.S3ChannelContext.fill(S3ChannelContext.java:121)
        at io.deephaven.extensions.s3.S3SeekableByteChannel.read(S3SeekableByteChannel.java:88)
        at io.deephaven.util.channel.CachedChannelProvider$CachedChannel.read(CachedChannelProvider.java:207)
        at io.deephaven.util.channel.ReadableByteChannelNoClose.read(ReadableByteChannelNoClose.java:28)
        at sun.nio.ch.ChannelInputStream.read(java.base@21.0.5/ChannelInputStream.java:74)
        at sun.nio.ch.ChannelInputStream.read(java.base@21.0.5/ChannelInputStream.java:103)
        - locked <0x0000000634633e10> (a sun.nio.ch.ChannelInputStream)
        at com.google.common.io.CountingInputStream.read(CountingInputStream.java:64)
        at java.io.FilterInputStream.read(java.base@21.0.5/FilterInputStream.java:119)
        at shaded.parquet.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:170)
        at shaded.parquet.org.apache.thrift.transport.TTransport.readAll(TTransport.java:100)
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:632)
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:532)
        at org.apache.parquet.format.InterningProtocol.readFieldBegin(InterningProtocol.java:188)
        at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1003)
        at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:995)
        at org.apache.parquet.format.PageHeader.read(PageHeader.java:870)
        at org.apache.parquet.format.Util.read(Util.java:390)
        at org.apache.parquet.format.Util.readPageHeader(Util.java:133)
        at org.apache.parquet.format.Util.readPageHeader(Util.java:128)
        at io.deephaven.parquet.base.ColumnChunkReaderImpl.readPageHeader(ColumnChunkReaderImpl.java:316)
        at io.deephaven.parquet.base.ColumnChunkReaderImpl$ColumnPageDirectAccessorImpl.getPageReader(ColumnChunkReaderImpl.java:351)
        at io.deephaven.parquet.table.pagestore.OffsetIndexBasedColumnChunkPageStore.getPageImpl(OffsetIndexBasedColumnChunkPageStore.java:154)
        at io.deephaven.parquet.table.pagestore.OffsetIndexBasedColumnChunkPageStore.getPage(OffsetIndexBasedColumnChunkPageStore.java:142)
        - locked <0x0000000634633d50> (a io.deephaven.parquet.table.pagestore.OffsetIndexBasedColumnChunkPageStore$PageState)
        at io.deephaven.parquet.table.pagestore.OffsetIndexBasedColumnChunkPageStore.getPageContainingImpl(OffsetIndexBasedColumnChunkPageStore.java:195)
        at io.deephaven.parquet.table.pagestore.OffsetIndexBasedColumnChunkPageStore.getPageContaining(OffsetIndexBasedColumnChunkPageStore.java:169)
        at io.deephaven.parquet.table.pagestore.OffsetIndexBasedColumnChunkPageStore.getPageContaining(OffsetIndexBasedColumnChunkPageStore.java:30)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:81)
        at io.deephaven.parquet.table.region.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:57)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:85)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:85)
        at io.deephaven.engine.table.impl.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:56)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.snapshotColumnsSerial(ConstructSnapshot.java:1523)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.lambda$snapshotColumnsParallel$4(ConstructSnapshot.java:1420)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot$$Lambda/0x00007b2e34994000.run(Unknown Source)
        at io.deephaven.engine.table.impl.util.JobScheduler.lambda$iterateParallel$1(JobScheduler.java:356)
        at io.deephaven.engine.table.impl.util.JobScheduler$$Lambda/0x00007b2e34994848.run(Unknown Source)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:258)
        - locked <0x00000006346292b8> (a io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:164)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$$Lambda/0x00007b2e34994ea8.run(Unknown Source)
        at io.deephaven.engine.table.impl.util.OperationInitializerJobScheduler.lambda$submit$0(OperationInitializerJobScheduler.java:40)
        at io.deephaven.engine.table.impl.util.OperationInitializerJobScheduler$$Lambda/0x00007b2e349952e0.run(Unknown Source)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
        at io.deephaven.engine.context.ExecutionContext$$Lambda/0x00007b2e34156ad0.get(Unknown Source)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
        at io.deephaven.engine.table.impl.ForkJoinPoolOperationInitializer$1.lambda$submit$0(ForkJoinPoolOperationInitializer.java:35)
        at io.deephaven.engine.table.impl.ForkJoinPoolOperationInitializer$1$$Lambda/0x00007b2e349954f8.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(java.base@21.0.5/ForkJoinTask.java:1403)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@21.0.5/ForkJoinTask.java:387)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@21.0.5/ForkJoinPool.java:1312)
        at java.util.concurrent.ForkJoinPool.scan(java.base@21.0.5/ForkJoinPool.java:1843)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@21.0.5/ForkJoinPool.java:1808)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@21.0.5/ForkJoinWorkerThread.java:188)

   Locked ownable synchronizers:
        - None

```

### PR DESCRIPTION
**Pull request by malhotrashivam**
Closes #6435 

**Context:**
S3 reads require AWS credentials, typically provided via a credentials provider. If no provider is explicitly set, the system defaults to resolving credentials from number of sources like environment variables, credentials files, etc.

**Issue:**
When no credentials provider was set by user, credentials were unnecessarily being resolved on every read instead of reusing resolved credentials. This caused delays in table snapshot processing for S3.

### CODE REVIEW

**Comment by malhotrashivam** [comment]
Confirmed with @niloc132 this fixes the original reported issue.

**Review by devinrsmith — APPROVED** [review]
Looks great, glad it's an easy fix.

File: extensions/s3/src/main/java/io/deephaven/extensions/s3/ResolvingCredentials.java [hunk 1]
```diff
@@ -26,20 +26,18 @@
...
                 || instructions.credentialsFilePath().isPresent()) {
             return ProfileCredentials.INSTANCE.awsV2CredentialsProvider(instructions);
         }
-        return PROVIDER_CHAIN;
+        return AwsCredentialsProviderChain.builder()
+                .credentialsProviders(
+                        DefaultCredentialsProvider.create(),
+                        AnonymousCredentialsProvider.create())
+                .reuseLastProviderEnabled(true)
+                .build();
```
Comment (niloc132) [inline extensions/s3/src/main/java/io/deephaven/extensions/s3/ResolvingCredentials.java:41]: Does this mean that if I make two calls to s3, one with creds, then one without, the second call will end up reusing the creds from the previous call?

If so, I'm not sure that's what we want.

**Review by niloc132 — APPROVED** [review]
