### PR TITLE
gRPC websocket streams should close sanely

### LINKED ISSUE #1745: Jetty uncaught exception via jsapi/input_table.html
Part of #1744

When adding to an input table via http://localhost:10000/jsapi/input_table.html, server-jetty has an uncaught exception, and prints a stacktrace out to STDERR:

```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@616ad585
io.deephaven.engine.liveness.LivenessStateException: BarrageTable-248611212 could not be released as it was no longer live
        at io.deephaven.engine.liveness.ReferenceCountedLivenessNode.dropReference(ReferenceCountedLivenessNode.java:64)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.onCancel(ArrowFlightUtil.java:196)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:279)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:362)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:350)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:913)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:920)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:887)
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:332)
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:276)
        at io.grpc.servlet.web.websocket.WebsocketStreamImpl.transportReportStatus(WebsocketStreamImpl.java:127)
        at io.grpc.servlet.web.websocket.WebSocketServerStream.onError(WebSocketServerStream.java:130)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onError(JakartaWebSocketFrameHandler.java:312)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$closeConnection$2(WebSocketCoreSession.java:280)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1460)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1479)
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.closeConnection(WebSocketCoreSession.java:280)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:251)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:485)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:343)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

The input table *does* get updated correctly.

I've tried, but can't reproduce this via the java client - so might be jsapi specific in some respects.

Also, this exception does not *seem* to occur (or is swallowed?) when running server-netty.

As a follow up to this ticket, or as part of this ticket, we may want to see what sort of logging hooks we can get into jetty to pipe uncaught exceptions through our logger.

### PR DESCRIPTION
**Pull request by niloc132**
Websocket-based gRPC-web streams were not correctly notifying gRPC internals when the stream was finished, this patch removes a poor attempt at that and correctly ends the stream.

This diff also adds java.util.logging support, forwarding it to slf4j, and sending slf4j's log level configuration back into java.util.logging.

Finally, this patch simplifies directly running main()s in the server project, so that they share configuration with the actual declare application.

Fixes #1745

### CODE REVIEW

File: server/src/main/java/io/deephaven/server/runner/Main.java [hunk 1]
```diff
@@ -62,6 +63,10 @@ public static Configuration init(String[] args, Class<?> mainClass) throws IOExc
 
         final Configuration config = Configuration.getInstance();
 
+        // After logging and config are working, redirect any future JUL logging to SLF4J
```
Comment (niloc132) [inline server/src/main/java/io/deephaven/server/runner/Main.java:66]: It seems like there should be a saner place to put this, but we don't have a centralized place to set up logging for all processes, so I started just with the two server mains. The initialize method in the log factory provider doesn't work, as that won't be called in this case until after the error in this bug has happened.

I'm not totally convinced we should have a single place for this, since the various client CLI mains seem to prefer to send to logback, so we wouldn't want to necessarily do the same log setup that exists in this class anyway?

Open to feedback and advice.

File: grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebsocketStreamImpl.java [hunk 2]
```diff
@@ -253,6 +249,9 @@ public void writeTrailers(Metadata trailers, boolean headersSent, Status status)
             } catch (IOException e) {
                 throw Status.fromThrowable(e).asRuntimeException();
             }
+            transportState().runOnTransportThread(() -> {
```
Comment (niloc132) [inline grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebsocketStreamImpl.java:252]: It is very likely that more calls need to be wrapped in this, I'm going to continue to work on this - this is the main reason I have this marked as draft.

File: server/jetty/build.gradle [hunk 3]
```diff
@@ -69,3 +69,7 @@ applicationDefaultJvmArgs = [
 ] + extraJvmArgs
 
 apply plugin: 'io.deephaven.java-open-nio'
+
+tasks.withType(JavaExec) {
+    jvmArgs applicationDefaultJvmArgs
+}
```
Comment (devinrsmith) [inline server/jetty/build.gradle:75]: As formulated, this likely overwrites what we've set in java-open-nio.

I *think* `jvmArgs += applicationDefaultJvmArgs` would be better?

Comment (niloc132) [reply server/jetty/build.gradle:75]: I'll confirm this when i'm back, but applicationDefaultJvmArgs was already itself picking up that addopens, so I don't think it should need further processing?

```
> Task :server-jetty:JettyMain.main()
Caching disabled for task ':server-jetty:JettyMain.main()' because:
  Build cache is disabled
Task ':server-jetty:JettyMain.main()' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command '/usr/lib/jvm/java-11-openjdk/bin/java''. Working directory: /home/colin/workspace/illumon/core.new Command: /usr/lib/jvm/java-11-openjdk/bin/java --add-opens java.base/java.nio=ALL-UNNAMED -server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XshowSettings:vm -XX:InitialRAMPercentage=25.0 -XX:MinRAMPercentage=70.0 -XX:MaxRAMPercentage=80.0 -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser...
```

ACtually it looks like there is some other interaction going on here, like the :run itself is a JavaExec with defaults that come from applicationDefaultJvmArgs _appended_ to the task's own args, so they get doubled:
```
> Task :server-jetty:run
Caching disabled for task ':server-jetty:run' because:
  Build cache is disabled
Task ':server-jetty:run' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command '/usr/lib/jvm/java-11-openjdk/bin/java''. Working directory: /home/colin/workspace/illumon/core.new/server/jetty Command: /usr/lib/jvm/java-11-openjdk/bin/java -Ddeephaven.console.type=groovy -server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XshowSettings:vm -XX:InitialRAMPercentage=25.0 -XX:MinRAMPercentage=70.0 -XX:MaxRAMPercentage=80.0 --add-opens java.base/java.nio=ALL-UNNAMED -server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XshowSettings:vm -XX:InitialRAMPercentage=25.0 -XX:MinRAMPercentage=70.0 -XX:MaxRAMPercentage=80.0 -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser...
```

File: grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebsocketStreamImpl.java (hunk 2 above)
Comment (niloc132) [reply grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebsocketStreamImpl.java:252]: Confirmed that this is necessary, but no other writes need to be wrapped in the way I was thinking. There is another flow control detail that is not correct, but flow control doesn't yet do anything for this or grpc-servlet.

File: server/jetty/build.gradle (hunk 3 above)
Comment (niloc132) [reply server/jetty/build.gradle:75]: Some notes on this:

 * the `jvmArgs(...)` method strictly appends. To replace, use setJvmArgs(...), which clears the _extra_ jvm args and then reassigns, or setAllJvmArgs(...) which clears other properties as well. See org.gradle.process.internal.JvmOptions
 * It also parses the incoming flags, and passes some off to other fields/methods, like assertionsEnabled, systemProperty(), etc.
 * This means that interacting with "jvmArgs" in a JavaExec closure behaves differently based on using it like a method or a field. I don't love groovy. However, it does mean that this code is the correct way to assign these missing properties _for IJ run configs_, if I had written `jvmArgs = applicationDefaultJvmArgs`, it would have done as you described, mostly.
 * Repeating this for clarity: Note that the setJvmArgs method does _not_ unassign Xmx or system props, but you can at least re-assign them. Doesn't apply here, but it could bite one day.

Okay, knowing that, we want to set three options for three things:
 1. script for dists
 2. JavaExec for the `:run` task
 3. other arbitrary JavaExecs

A `tasks.withType(JavaExec)` lets us set 2 and 3. A `applicationDefaultJvmArgs` sets 1 and 2. `tasks.withType(CreateStartScripts)` only sets 1. So applying tasks.withType for both JavaExec and CreateStartScripts seems like the simplest option, and omit applicationDefaultJvmArgs.

Comment (niloc132) [reply server/jetty/build.gradle:75]: Tested with running each of these three ways, and invoking `jps -v | grep JettyMain` to check for missing/dup args.

File: server/src/main/java/io/deephaven/server/runner/Main.java (hunk 1 above)
Comment (devinrsmith) [reply server/src/main/java/io/deephaven/server/runner/Main.java:66]: I'm happy to be explicit here for now, generalize later if necessary.

File: server/jetty/build.gradle (hunk 3 above)
Comment (devinrsmith) [reply server/jetty/build.gradle]: Good to know, thanks for the investigation.

**Review by devinrsmith — APPROVED** [review]
