### PR TITLE
fix: Added support to read iceberg tables partitioned by date

### LINKED ISSUE #6419: Failure in reading Iceberg tables partitiond by date
On reading an iceberg table partitioned by date, the core app fails with the following error:

```
Caused by: io.deephaven.engine.table.impl.locations.TableDataException: Partitioning column event_date has type java.lang.Integer but expected java.time.LocalDate
	at io.deephaven.iceberg.layout.IcebergKeyValuePartitionedLayout.keyFromDataFile(IcebergKeyValuePartitionedLayout.java:96)
	at io.deephaven.iceberg.layout.IcebergBaseLayout.findKeys(IcebergBaseLayout.java:197)
```
Basically, the partitioning value is being read as an integer from the `PartitionData` associated with the `DataFile` instead of being casted to the right type.

As part of this issue, we should fix it. I have linked the steps to reproduce this error in the comment.

### PR DESCRIPTION
**Pull request by malhotrashivam**
Closes #6419

### CODE REVIEW

File: extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java [hunk 1]
```diff
@@ -89,11 +90,18 @@ IcebergTableLocationKey keyFromDataFile(
...
-            final Object colValue = partitionData.get(colData.index);
-            if (colValue != null && !colData.type.isAssignableFrom(colValue.getClass())) {
-                throw new TableDataException("Partitioning column " + colName
-                        + " has type " + colValue.getClass().getName()
-                        + " but expected " + colData.type.getName());
+            final Object colValue;
+            final Object valueFromPartitionData = partitionData.get(colData.index);
+            if (valueFromPartitionData != null) {
+                colValue = IdentityPartitionConverters.convertConstant(
+                        partitionData.getType(colData.index), valueFromPartitionData);
```
Comment (devinrsmith) [inline extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java:97]: Is this okay to universally apply? Should we only do it when the partition spec specifies `identity`? https://iceberg.apache.org/spec/#partition-transforms

Comment (malhotrashivam) [reply extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java:105]: Added a check to ensure identity transform. We would need to test properly for non-identity transform.

**Review by devinrsmith — APPROVED** [review]
