### PR TITLE
Address dependency and liveness issues in KafkaTools.StreamPartitionedTable

### LINKED ISSUE #4952: ZeroKeyUpdateByManager NPE
This happened after I switched a workload from release 0.28.0 to 0.31.0, so it might not be 0.31.0 specific.

```
Server shutdown: Uncaught exception in thread PeriodicUpdateGraph.DEFAULT.refreshThread

java.lang.NullPointerException: Cannot read field "result" because "this.zeroKeyUpdateBy" is null
io.deephaven.engine.table.impl.updateby.ZeroKeyUpdateByManager.upstreamSatisfied(ZeroKeyUpdateByManager.java:138)
io.deephaven.engine.table.impl.updateby.UpdateBy$UpdateByListener.canExecute(UpdateBy.java:1092)
io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.canExecute(InstrumentedTableListenerBase.java:311)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.flushNormalNotificationsAndCompleteCycle(BaseUpdateGraph.java:564)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.flushNotificationsAndCompleteCycle(BaseUpdateGraph.java:518)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.lambda$doRefresh$5(BaseUpdateGraph.java:915)
io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.doRefresh(BaseUpdateGraph.java:900)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.refreshAllTables(BaseUpdateGraph.java:887)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshAllTables(PeriodicUpdateGraph.java:1090)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.refreshTablesAndFlushNotifications(BaseUpdateGraph.java:779)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshTablesAndFlushNotifications(PeriodicUpdateGraph.java:1014)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.lambda$new$0(PeriodicUpdateGraph.java:139)
java.base/java.lang.Thread.run(Thread.java:1583)
```

Not sure if the after shutdown is relevant or not:
```
After shutdown initiated: Unexpected iteration job error
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 14, updateGraph.clock().currentStep() == 14.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.BaseTable.notifyListenersOnError(BaseTable.java:838)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailureInternalWithDependent(InstrumentedTableListenerBase.java:181)
        at io.deephaven.engine.table.impl.BaseTable$ListenerImpl.onFailureInternal(BaseTable.java:979)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailure(InstrumentedTableListenerBase.java:172)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onError(SelectAndViewAnalyzer.java:637)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:195)
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportTaskCompleteAndResumeIteration(JobScheduler.java:288)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
        at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
        at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        Suppressed: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted logicalClock.currentState() == LogicalClock.State.Updating, instead logicalClock.currentState() == Idle, LogicalClock.State.Updating == Updating.
                at io.deephaven.base.verify.Assert.fail(Assert.java:100)
                at io.deephaven.base.verify.Assert.eq(Assert.java:1380)
2023-12-15T07:07:20.421Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Done invoking FIRST shutdown tasks
                at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.addNotification(BaseUpdateGraph.java:398)
                at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.addNotification(PeriodicUpdateGraph.java:403)
                at io.deephaven.engine.table.impl.BaseTable.lambda$notifyListeners$8(BaseTable.java:735)
                at io.deephaven.util.datastructures.SimpleReferenceManager.forEach(SimpleReferenceManager.java:136)
                at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:734)
2023-12-15T07:07:20.421Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke MIDDLE shutdown tasks
                at io.deephaven.engine.table.impl.SelectOrUpdateListener.completionRoutine(SelectOrUpdateListener.java:126)
                at io.deephaven.engine.table.impl.SelectOrUpdateListener$1.onAllRequiredColumnsCompleted(SelectOrUpdateListener.java:98)
                at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:627)
                at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$prepareParallelUpdate$1(SelectColumnLayer.java:252)
                at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:192)
                ... 12 more
```

Not sure if related at all to https://github.com/deephaven/deephaven-core/issues/4391

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #4952 

* Address dependency satisfaction issue for KafkaTools.StreamPartitionedTable when used with append-only or ring constituents
* Address liveness and reachability issues for the UpdateSourceCombiner and reachability issues for StreamPartitionedQueryTable

### CODE REVIEW

**Review by nbauernfeind — DISMISSED** [review]

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java [hunk 1]
```diff
@@ -1529,6 +1551,10 @@ private static Table makeResultTable() {
                     ArrayBackedColumnSource.getMemoryColumnSource(int.class, null));
             resultSources.put(CONSTITUENT_COLUMN_NAME,
                     ArrayBackedColumnSource.getMemoryColumnSource(Table.class, null));
+            /*
+             * This is subtle, but this QueryTable is an inner class of StreamPartitionedTable, and so it will have a
+             * hard-ref to this, which will keep this reachable for the UpdateSourceCombiner.
+             */
```
Comment (devinrsmith) [inline extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java:1557]: While the motivations to keep hard-ref are true, this does not in fact keep a hard-ref as it is written.

Comment (rcaudy) [reply extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]: Yeah, I was dumb. Fixed in the next commit.

**Review by nbauernfeind — APPROVED** [review]
