### PR TITLE
Raise the gRPC max payload limit to 100mb

### LINKED ISSUE #1816: Large DoPut calls fail on the server
Steps to reproduce, upload using the web UI (or python, java, etc) some large table, at least larger than 5mb over the wire.

```
server_1      | Jan 11, 2022 4:09:51 PM io.grpc.netty.NettyServerStream$TransportState deframeFailed
server_1      | WARNING: Exception processing message
server_1      | io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 6490343
server_1      |         at io.grpc.Status.asRuntimeException(Status.java:526)
server_1      |         at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:391)
server_1      |         at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:271)
server_1      |         at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:177)
server_1      |         at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
server_1      |         at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:255)
server_1      |         at io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:226)
server_1      |         at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:508)
server_1      |         at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:106)
server_1      |         at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:840)
server_1      |         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
server_1      |         at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
server_1      |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
server_1      |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
server_1      |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
server_1      |         at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
server_1      |         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
server_1      |         at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
server_1      |         at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
server_1      |         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
server_1      |         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
server_1      |         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
server_1      |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
server_1      |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
server_1      |         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
server_1      |         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
server_1      |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
server_1      |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
server_1      |         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
server_1      |         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
server_1      |         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
server_1      |         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
server_1      |         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
server_1      |         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
server_1      |         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
server_1      |         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
server_1      |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
server_1      |         at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #1816

### CODE REVIEW

File: server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java [hunk 1]
```diff
@@ -55,23 +55,6 @@
 })
 public class DeephavenApiServerModule {
 
-    @Provides
-    @Singleton
-    static Server buildServer(
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java:60]: Was this unused?

**Review by rcaudy — DISMISSED** [review]

**Review by rcaudy — APPROVED** [review]
