### PR TITLE
Arrow Encoding for LocalDate and LocalTime

### LINKED ISSUE #4823: Python arrow.to_arrow() doesn't handle java.time.LocalDate/LocalTime data correctly.
```
import pyarrow as pa
import pyarrow.parquet as pap
import pandas as pd

from deephaven import empty_table
from deephaven.arrow import to_arrow
from deephaven.parquet import write


dh_table = empty_table(10000).update(formulas=[
    "someDateColumn = i % 10 == 0 ? null : java.time.LocalDate.ofEpochDay(i)",
    "nullDateColumn = (java.time.LocalDate)null",
    "someTimeColumn = i % 10 == 0 ? null : java.time.LocalTime.of(i%24, i%60, (i+10)%60)",
    "nullTimeColumn = (java.time.LocalTime)null"
])

pa_table = to_arrow(dh_table)
print(pa_table)

write(dh_table, "data_from_dh.parquet", compression_codec_name="SNAPPY")
pa_table1 = pap.read_table("data_from_dh.parquet")
print("")
print(pa_table1)
```
```
pyarrow.Table
someDateColumn: fixed_size_binary[6]
nullDateColumn: fixed_size_binary[6]
someTimeColumn: fixed_size_binary[7]
nullTimeColumn: fixed_size_binary[7]
----
someDateColumn: [<Invalid array: Buffer #1 too small in array of type fixed_size_binary[6] and length 10000: expected at least 60000 byte(s), got 40008>]
nullDateColumn: [<Invalid array: Buffer #1 too small in array of type fixed_size_binary[6] and length 10000: expected at least 60000 byte(s), got 1256>]
someTimeColumn: [<Invalid array: Buffer #1 too small in array of type fixed_size_binary[7] and length 10000: expected at least 70000 byte(s), got 0>]
nullTimeColumn: [<Invalid array: Buffer #1 too small in array of type fixed_size_binary[7] and length 10000: expected at least 70000 byte(s), got 40008>]

pyarrow.Table
someDateColumn: date32[day]
nullDateColumn: date32[day]
someTimeColumn: time64[ns]
nullTimeColumn: time64[ns]
----
someDateColumn: [[null,1970-01-02,1970-01-03,1970-01-04,1970-01-05,...,1997-05-14,1997-05-15,1997-05-16,1997-05-17,1997-05-18]]
nullDateColumn: [[null,null,null,null,null,...,null,null,null,null,null]]
someTimeColumn: [[null,01:01:11.000000000,02:02:12.000000000,03:03:13.000000000,04:04:14.000000000,...,11:35:45.000000000,12:36:46.000000000,13:37:47.000000000,14:38:48.000000000,15:39:49.000000000]]
nullTimeColumn: [[null,null,null,null,null,...,null,null,null,null,null]]

```

### LINKED ISSUE #5265: `LocalDate` and `LocalTime` are not Serialized Properly over Arrow
Run in an Enterprise environment, but this reproducer is only using Core components.

Deephaven Version: 0.30.4

x = """
import jpy
from deephaven import dtypes
from deephaven import new_table
from deephaven.column import InputColumn
from deephaven.column import string_col

DateTimeFormatter = jpy.get_type("java.time.format.DateTimeFormatter")
LocalDate = jpy.get_type("java.time.LocalDate")

cols = []
ecd = LocalDate.parse("2023-03-19", DateTimeFormatter.ofPattern("yyyy-MM-dd"))
cols.append(InputColumn("localDateCol", dtypes.LocalDate, input_data=[ecd]))
cols.append(string_col('stringCol', ['someString']))

tbl = new_table(cols)
"""

worker.run_script(x)
tbl = worker.open_table('tbl')

print(tbl)

# the below line should not segfault ...
z = tbl.to_arrow().to_pandas()

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #4823.
Fixes #5265.

### CODE REVIEW

**Review by niloc132 — APPROVED** [review]

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java [hunk 1]
```diff
@@ -173,6 +191,38 @@ static WritableChunk<Values> extractChunkFromInputStream(
...
+            final WritableObjectChunk<T, Values> chunk;
+            if (outChunk != null) {
+                chunk = outChunk.asWritableObjectChunk();
+            } else {
+                final int numRows = Math.max(totalRows, inner.size());
+                chunk = WritableObjectChunk.makeWritableChunk(numRows);
+                chunk.setSize(numRows);
+            }
+
+            for (int ii = 0; ii < inner.size(); ++ii) {
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java:217]: Should we assert that `outOffset == 0` if `outChunk == null`? Or make the allocating version delegate to the other? May be impossible due to the iteration design.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java [hunk 2]
```diff
@@ -173,6 +191,38 @@ static WritableChunk<Values> extractChunkFromInputStream(
...
+                char value = inner.get(ii);
+                chunk.set(outOffset + ii, value == NULL_CHAR ? null : transform.apply(value));
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java:219]: If you change the other call to move null-handling responsibility into the transform, we should do the same here.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java [hunk 3]
```diff
@@ -4,9 +4,11 @@
 package io.deephaven.extensions.barrage.chunk;
 
 import com.google.common.base.Charsets;
+import io.deephaven.chunk.LongChunk;
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:7]: Unused imports.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java [hunk 4]
```diff
@@ -144,6 +148,26 @@ static <T> ChunkInputStreamGenerator makeInputStreamGenerator(
                 if (type == Short.class) {
                     return ShortChunkInputStreamGenerator.convertBoxed(chunk.asObjectChunk(), rowOffset);
                 }
+                if (type == LocalDate.class) {
+                    return IntChunkInputStreamGenerator.<LocalDate>convertWithTransform(chunk.asObjectChunk(),
+                            rowOffset, date -> {
+                                final long epochDay = date.toEpochDay();
+                                if (epochDay < 0 || epochDay > Integer.MAX_VALUE) {
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:155]: Why don't we like negative dates?
Maybe we should support everything in `[QueryConstants.MIN_INT, Integer.MAX_VALUE]`?
Check conversions for `LocalDate.MIN` and `LocalDate.MAX`. If we can't fit this in an `int` as days, but can fit it into a `long`as millis, we should choose the other representation maybe.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java [hunk 5]
```diff
@@ -657,10 +654,10 @@ private static ArrowType arrowTypeFor(Class<?> type) {
                     return Types.MinorType.LIST.getType();
                 }
                 if (type == LocalDate.class) {
-                    return LOCAL_DATE_TYPE;
+                    return Types.MinorType.DATEDAY.getType();
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java:657]: Do we want to support the other format? I'm OK with picking one for this PR, but we should support receiving both in the future.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java [hunk 6]
```diff
@@ -149,18 +150,28 @@ static <T> ChunkInputStreamGenerator makeInputStreamGenerator(
                     return ShortChunkInputStreamGenerator.convertBoxed(chunk.asObjectChunk(), rowOffset);
                 }
                 if (type == LocalDate.class) {
-                    return IntChunkInputStreamGenerator.<LocalDate>convertWithTransform(chunk.asObjectChunk(),
+                    final long msPerDay = 24 * 60 * 60 * 1000L;
+                    final long minDate = QueryConstants.MIN_LONG / msPerDay;
+                    final long maxDate = QueryConstants.MAX_LONG / msPerDay;
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:155]: Shouldn't these be static constants?

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java [hunk 7]
```diff
@@ -323,15 +335,16 @@ static WritableChunk<Values> extractChunkFromInputStream(
                             fieldNodeIter, bufferInfoIter, is, outChunk, outOffset, totalRows);
                 }
                 if (type == LocalDate.class) {
-                    return IntChunkInputStreamGenerator.extractChunkFromInputStreamWithTransform(
-                            Integer.BYTES, options,
-                            LocalDate::ofEpochDay,
+                    final long msPerDay = 24 * 60 * 60 * 1000L;
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:338]: Same question.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java (hunk 5 above)
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java:657]: Since we've switched formats, should we be be using `DATEMILLI`?
On the other hand, `DateMilliVector` seems to map to `LocalDateTime`, not `LocalDate`. Have we made a mistake?

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java [hunk 8]
```diff
@@ -657,10 +654,10 @@ private static ArrowType arrowTypeFor(Class<?> type) {
...
                 }
                 if (type == LocalTime.class) {
-                    return LOCAL_TIME_TYPE;
+                    return Types.MinorType.TIMENANO.getType();
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java:660]: `TimeNanoVector` maps to `Long`, not `LocalTime`. Are we sure it's local, and not implicitly UTC?

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java [hunk 9]
```diff
@@ -144,6 +149,36 @@ static <T> ChunkInputStreamGenerator makeInputStreamGenerator(
...
+                                if (epochDay < minDate || epochDay > maxDate) {
+                                    throw new IllegalArgumentException("Date out of range: " + date + " (" + epochDay
+                                            + " not in [" + minDate + ", " + maxDate + "])");
+                                }
+                                return epochDay * msPerDay;
+                            });
+                }
+                if (type == LocalTime.class) {
+                    return LongChunkInputStreamGenerator.<LocalTime>convertWithTransform(chunk.asObjectChunk(),
+                            rowOffset, date -> {
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:171]: `date`->`time`?

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java [hunk 10]
```diff
@@ -144,6 +149,36 @@ static <T> ChunkInputStreamGenerator makeInputStreamGenerator(
...
+                if (type == LocalDate.class) {
+                    final long msPerDay = 24 * 60 * 60 * 1000L;
+                    final long minDate = QueryConstants.MIN_LONG / msPerDay;
+                    final long maxDate = QueryConstants.MAX_LONG / msPerDay;
+                    return LongChunkInputStreamGenerator.<LocalDate>convertWithTransform(chunk.asObjectChunk(),
+                            rowOffset, date -> {
+                                if (date == null) {
+                                    return QueryConstants.NULL_LONG;
+                                }
+                                final long epochDay = date.toEpochDay();
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:161]: https://arrow.apache.org/docs/python/generated/pyarrow.date64.html#pyarrow.date64 seems to suggest that this needs to be millis form the epoch, meaning we are doing the math too simply.

**Review by jmao-denver — COMMENTED** [review]
Missing the changes in arrow.py

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java (hunk 8 above)
Comment (nbauernfeind) [reply extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java:660]:
```
enum TimeUnit: short { SECOND, MILLISECOND, MICROSECOND, NANOSECOND }

/// Time is either a 32-bit or 64-bit signed integer type representing an
/// elapsed time since midnight, stored in either of four units: seconds,
/// milliseconds, microseconds or nanoseconds.
///
/// The integer `bitWidth` depends on the `unit` and must be one of the following:
/// * SECOND and MILLISECOND: 32 bits
/// * MICROSECOND and NANOSECOND: 64 bits
///
/// The allowed values are between 0 (inclusive) and 86400 (=24*60*60) seconds
/// (exclusive), adjusted for the time unit (for example, up to 86400000
/// exclusive for the MILLISECOND unit).
/// This definition doesn't allow for leap seconds. Time values from
/// measurements with leap seconds will need to be corrected when ingesting
/// into Arrow (for example by replacing the value 86400 with 86399).
table Time {
  unit: TimeUnit = MILLISECOND;
  bitWidth: int = 32;
}
```

It looks correct.
```java
    TIMENANO(new Time(TimeUnit.NANOSECOND, 64)) {
```

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java (hunk 10 above)
Comment (nbauernfeind) [reply extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:161]: This is the documentation source that matters which clearly indicates that leap seconds are ignored:
```
enum DateUnit: short {
  DAY,
  MILLISECOND
}

/// Date is either a 32-bit or 64-bit signed integer type representing an
/// elapsed time since UNIX epoch (1970-01-01), stored in either of two units:
///
/// * Milliseconds (64 bits) indicating UNIX time elapsed since the epoch (no
///   leap seconds), where the values are evenly divisible by 86400000
/// * Days (32 bits) since the UNIX epoch
table Date {
  unit: DateUnit = MILLISECOND;
}
```

**Review by rcaudy — APPROVED** [review]

File: py/server/tests/test_arrow.py [hunk 11]
```diff
@@ -106,13 +106,21 @@ def test_arrow_types_unsigned_integers(self):
     def test_arrow_types_time(self):
         pa_types = [
             pa.time64('ns'),
-            pa.date32(),
-            pa.timestamp('ns', tz='MST'),
```
Comment (jmao-denver) [inline py/server/tests/test_arrow.py:111]: It looks like that we don't support pa.timestamp(ns) with a tz, what about just no tz or tz=utc? If we flatly don't support pa.timestamp, maybe we should remove the 'java.time.Instant' mapping?

Comment (nbauernfeind) [reply py/server/tests/test_arrow.py:111]: Actually the test might be passing now. I suspect the test isn't looking at the time zones. I do think that the data is correct; the timezone is just like a display that applies to all elements. Instant's aren't in a particular time zone in general. Locally I only get lfs and postgres failures; so... we'll find out soon.

**Review by rcaudy — APPROVED** [review]
