### PR TITLE
Our UsePreviousValues implementations generally need to care about satisfaction, rather than just last notification step

### LINKED ISSUE #3980: Clock issues in PartitionedTable transform and downstream aggregations
**Description**

I have been working on a self windowing partitioned table, with the help of multiple team members from deephaven this is now working as expected! However when applying transforms and/or subsequent aggregations to the merged output table, an assertion error is being triggered:

```bash
EFAULT.refreshThread | .AsyncClientErrorNotifier | Error in table update: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Previous values requested or inconsistent while blocking run processing: beforeClockValue=106, previousValuesRequested=true is never executed.
        at io.deephaven.base.verify.Assert.fail(Assert.java:87)
        at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:222)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1216)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1061)
        at io.deephaven.engine.table.impl.BaseTable.initializeWithSnapshot(BaseTable.java:1250)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:116)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:75)
        at io.deephaven.engine.table.impl.QueryTable.lambda$aggNoMemo$15(QueryTable.java:752)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
        at io.deephaven.engine.table.impl.QueryTable.aggNoMemo(QueryTable.java:751)
        at io.deephaven.engine.table.impl.QueryTable.lambda$aggBy$14(QueryTable.java:726)
        at io.deephaven.engine.table.impl.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3495)
        at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3464)
        at io.deephaven.engine.table.impl.QueryTable.aggBy(QueryTable.java:726)
        at io.deephaven.engine.table.impl.QueryTable.aggBy(QueryTable.java:109)
        at io.deephaven.api.TableOperationsDefaults.aggBy(TableOperationsDefaults.java:337)
        at io.deephaven.api.TableOperationsDefaults.aggBy(TableOperationsDefaults.java:324)
        at io.deephaven.api.TableOperationsDefaults.countBy(TableOperationsDefaults.java:412)
        at io.deephaven.api.TableOperationsDefaults.countBy(TableOperationsDefaults.java:406)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:191)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at io.deephaven.dynamic.Script_6.transformfn(Script_6.groovy:61)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1048)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1142)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:112)
        at com.sun.proxy.$Proxy29.apply(null:-1)
        at io.deephaven.engine.table.impl.partitioned.TableTransformationColumn$OutputFormula.transformAndFill(TableTransformationColumn.java:154)
        at io.deephaven.engine.table.impl.partitioned.TableTransformationColumn$OutputFormula.fillChunk(TableTransformationColumn.java:133)
        at io.deephaven.engine.table.impl.select.Formula.getChunk(Formula.java:161)
        at io.deephaven.engine.table.impl.sources.ViewColumnSource.getChunk(ViewColumnSource.java:204)
        at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:448)
        at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doSerialApplyUpdate$2(SelectColumnLayer.java:264)
        at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
        at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:263)
        at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:212)
        at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.submit(ImmediateJobScheduler.java:23)
        at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:210)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:589)
        at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:76)
        at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
        at io.deephaven.engine.table.impl.SelectOrUpdateListener.onUpdate(SelectOrUpdateListener.java:93)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:291)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:269)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1238)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$QueueNotificationProcessor.doWork(PeriodicUpdateGraph.java:1414)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.flushNormalNotificationsAndCompleteCycle(PeriodicUpdateGraph.java:1117)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.flushNotificationsAndCompleteCycle(PeriodicUpdateGraph.java:1061)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.lambda$doRefresh$11(PeriodicUpdateGraph.java:1697)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.doRefresh(PeriodicUpdateGraph.java:1685)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshAllTables(PeriodicUpdateGraph.java:1672)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshTablesAndFlushNotifications(PeriodicUpdateGraph.java:1526)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.lambda$new$3(PeriodicUpdateGraph.java:293)
        at java.lang.Thread.run(Thread.java:829)

```

**Steps to reproduce**
1. Compile the attached Java class.
2. Run the attached groovy script in the IDE.
3. Generate traffic on the configured kafka topic.

**Expected results**

Aggregations work as expected and apply proper aggregation without throwing an exception in both transforms and subsequent calls to aggregate the merged result.

**Actual results**

Eventually the above exception is seen.

**Additional details and attachments**

This is the java class in text format: [Windowed.txt](https://github.com/deephaven/deephaven-core/files/11728004/Windowed.txt)
This is the groovy script that I am using for testing: [example.txt](https://github.com/deephaven/deephaven-core/files/11728019/example.txt)

I am currently using redpanda with a topic getting ~150k msgs/s. The content of the messages doesn't seem to matter, also this happens on a static table with a backlog of messages or with a topic with an active producer.

**Versions**
 - Deephaven: 0.25.0
 - OS: OSX
 - Browser: Brave
 - Docker: N/A

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #3980

### CODE REVIEW

**Comment by rcaudy** [comment]
Nightlies running at https://github.com/rcaudy/deephaven-core/actions/runs/5263071146

File: engine/table/src/main/java/io/deephaven/engine/table/impl/ConstituentDependency.java [hunk 1]
```diff
@@ -83,6 +92,7 @@ public LogOutput append(@NotNull final LogOutput logOutput) {
 
     @Override
     public boolean satisfied(final long step) {
+        StepUpdater.checkForOlderStep(step, lastSatisfiedStep);
```
Comment (cpwright) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/ConstituentDependency.java:95]: Also backwards?

**Review by cpwright — APPROVED** [review]
