### PR TITLE
Fix issue with shift propagation from Table.reverse() on blink tables

### LINKED ISSUE #3858: Stream table reverse assertion failure
```groovy
import io.deephaven.engine.table.impl.TimeTable
x1 = TimeTable.newBuilder().streamTable(true).period(1000).build()
x2 = x1.reverse()
```

fails shortly after execution with:

```
2023-05-22T20:23:00.626Z | EFAULT.refreshThread | ERROR | rumentedTableListenerBase | Uncaught exception for entry= reverse(), added.size()=999673, modified.size()=0, removed.size()=1, shifted.size()=0, modifiedColumnSet={EMPTY}:
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted update.shifted.empty().
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.assertion(Assert.java:116)
        at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:637)
        at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:225)
        at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:104)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:283)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:261)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1285)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1461)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1164)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1109)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$11(UpdateGraphProcessor.java:1744)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1732)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1719)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1573)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$new$3(UpdateGraphProcessor.java:270)
        at java.lang.Thread.run(Thread.java:833)

2023-05-22T20:23:00.629Z | EFAULT.refreshThread | ERROR | .AsyncClientErrorNotifier | Error in table update: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted update.shifted.empty().
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.assertion(Assert.java:116)
        at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:637)
        at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:225)
        at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:104)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:283)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:261)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1285)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1461)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1164)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1109)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$11(UpdateGraphProcessor.java:1744)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1732)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1719)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1573)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$new$3(UpdateGraphProcessor.java:270)
        at java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #3858

### CODE REVIEW

**Comment by rcaudy** [comment]
Tested with unit test and the provided reproducer.

**Review by devinrsmith — APPROVED** [review]
I've verified this fixes the issue. I can't say I understand the nuances involved in `ReverseOperation#onUpdate`. I'm assuming the `else` branch is still technically "correct" for empty resultRowSets in the non-blink case; but this will be an improvement for non-blink cases regardless?

**Comment by rcaudy** [comment]
> I've verified this fixes the issue. I can't say I understand the nuances involved in `ReverseOperation#onUpdate`. I'm assuming the `else` branch is still technically "correct" for empty resultRowSets in the non-blink case; but this will be an improvement for non-blink cases regardless?

Correct. There's no reason to communicate any shifts at all for rows that don't exist (in post-shift space) in the result table. In this case, we can assess that by looking at the result row set once all upstream removes have been removed. Not communicating unnecessary shifts simplifies the downstream update, and potentially saves a lot of work for downstream listeners.

**Comment by devinrsmith** [comment]
> communicating unnecessary shifts

Should we explicitly disallow unnecessary shifts? Or, have helpers that catch them and simplify them away for all cases?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/ReverseOperation.java [hunk 1]
```diff
@@ -149,44 +151,49 @@ private void onUpdate(final TableUpdate upstream) {
...
-                } else {
-                    // Note: begin/end flip responsibilities in the transformation
-                    nextShiftDelta = -upstream.shifted().getShiftDelta(idx - 1);
-                    final long minStart = Math.max(-nextShiftDelta - newShift, 0);
-                    nextShiftStart = Math.max(minStart, transform(upstream.shifted().getEndRange(idx - 1)));
-                    nextShiftEnd = transform(upstream.shifted().getBeginRange(idx - 1));
-                    if (nextShiftEnd < nextShiftStart) {
-                        continue;
+            // Only compute downstream shifts if there are retained rows to shift
+            if (resultRowSet.isEmpty()) {
```
Comment (nbauernfeind) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/ReverseOperation.java:155]: You could also skip this if the prev rowset is empty (since shifts affect rows that exist in both key spaces)
