### PR TITLE
Fix integer overflow in SortedRanges.invertOnNew.  Fixes #666.

### LINKED ISSUE #666: Integer overflow in SortedRanges.invertOnNew
Charles reported the following test case for TestIncrementalReleaseFilter fails:

```
    public void testBigTable() {
        final Table sourcePart = TableTools.emptyTable(1_000_000_000L);
        final List<Table> sourceParts = IntStream.range(0, 20).mapToObj(x -> sourcePart).collect(Collectors.toList());
        final Table source = TableTools.merge(sourceParts);
        TableTools.show(source);

        final IncrementalReleaseFilter incrementalReleaseFilter = new IncrementalReleaseFilter(2, 10_000_000);
        final Table filtered = source.where(incrementalReleaseFilter);
        final Table flattened = filtered.flatten();

        assertEquals(2, filtered.size());

        int cycles = 0;
        while (filtered.size() < source.size()) {
            LiveTableMonitor.DEFAULT.runWithinUnitTestCycle(incrementalReleaseFilter::refresh);
            cycles++;
        }
        assertTableEquals(source, filtered);
        assertTableEquals(flattened, filtered);
        System.out.println("Cycles: " + cycles);
    }
```

The root case is the `int pos` local variable in SortedRanges.invertOnNew overflowing.

### PR DESCRIPTION
**Pull request by jcferretti**

### CODE REVIEW

**Review by rcaudy — APPROVED** [review]

File: DB/src/main/java/io/deephaven/db/v2/utils/sortedranges/SortedRanges.java [hunk 1]
```diff
@@ -2191,7 +2191,7 @@ static boolean removeLegacy(final MutableObject<SortedRanges> sarOut, final Inde
     public final TreeIndexImpl invertRangeOnNew(final long start, final long end, final long maxPosition) {
         final long packedStart = pack(start);
         int i = 0;
-        int pos = 0;
+        long pos = 0;
```
Comment (rcaudy) [inline DB/src/main/java/io/deephaven/db/v2/utils/sortedranges/SortedRanges.java:2194]: Does this one need a unit test, too?

**Review by rcaudy — APPROVED** [review]
