### PR TITLE
Fix for failure in Head_By and AggAllBy after Format_Column

### LINKED ISSUE #4501: Calling Head_By After Format_Column Fails with Exception
Chaining operations after _format_columns_ works for some operations but not _head_by_.  We need to decide if we are going to support chaining on _format_columns_ or only allow it on a leaf table.  If not allowed, errors should be explicit.  If allowed, column formatting should be carried along through subsequent tables. (Easier said than done.)

Run the following code snippet (Tested in Deephaven 0.28.0+)
````
from deephaven import new_table
from deephaven.column import string_col, double_col

result = new_table([
    double_col("Doubles", [3.1, 5.45, -1.0]),
    string_col("Strings", ["Creating", "New", "Tables"])
])

result = result.format_columns(["Doubles=Decimal(`##0.00%`)"]).head_by(1)
````
You will get an exception like the following:
````
Type: <class 'deephaven.dherror.DHError'>
Value: table head_by operation failed. : RuntimeError: io.deephaven.engine.table.impl.NoSuchColumnException: Unknown column names [Doubles__TABLE_NUMBER_FORMAT], available column names are [Doubles,Strings]
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 1487, in head_by
    return Table(j_table=self.j_table.headBy(num_rows, *by))
RuntimeError: io.deephaven.engine.table.impl.NoSuchColumnException: Unknown column names [Doubles__TABLE_NUMBER_FORMAT], available column names are [Doubles,Strings]
````
If you use head_by(1, ['Strings']) or head_by(1, ['Doubles','Strings']), you get essentially the same error

### PR DESCRIPTION
**Pull request by malhotrashivam**
Closes #4501

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java [hunk 1]
```diff
@@ -835,31 +834,37 @@ private Table headOrTailBy(long nRows, boolean head, String... groupByColumns) {
             String colName = colNames.get(i);
             if (!groupByColsSet.contains(colName)) {
                 final Class<?> dataType = getDefinition().getColumn(colName).getDataType();
-                casting[j] = colName + " = " + getCastFormula(dataType) + colName;
+                casting[j] = String.format("%s = %s%s", colName, getCastFormula(dataType), colName);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java:837]: Formats are nice, but they are definitely much more expensive than concatenation. This loop isn't so tight, though, so I suppose it's up to you if you want to keep this change or revert it.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java [hunk 2]
```diff
@@ -835,31 +834,37 @@ private Table headOrTailBy(long nRows, boolean head, String... groupByColumns) {
...
                     updates[j++] =
                             // Get the first nRows rows:
                             // colName = isNull(colName) ? null
                             // : colName.size() > nRows ? colName.subVector(0, nRows)
                             // : colName
-                            colName + '=' + "isNull(" + colName + ") ? null" +
-                                    ':' + colName + ".size() > " + nRows + " ? " + colName + ".subVector(0, " + nRows
-                                    + ')' +
-                                    ':' + colName;
+                            String.format(
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java:844]: Wow, this is much more readable.

**Review by rcaudy — COMMENTED** [review]
I think this is good, but I want @devinrsmith to give me an opinion on the two file moves to QST, and whether he has an alternate module he prefers.

File: qst/src/main/java/io/deephaven/qst/table/AggregateAllTable.java [hunk 3]
```diff
@@ -35,7 +35,7 @@ public static Builder builder() {
     public static Optional<Aggregation> singleAggregation(
             AggSpec spec, Collection<? extends ColumnName> groupByColumns,
             Collection<? extends ColumnName> tableColumns) {
-        Set<ColumnName> exclusions = AggregateAllExclusions.of(spec, groupByColumns);
+        Set<ColumnName> exclusions = AggregateAllExclusions.of(spec, groupByColumns, tableColumns);
```
Comment (devinrsmith) [inline qst/src/main/java/io/deephaven/qst/table/AggregateAllTable.java:38]: I don't think we should move ColumnFormatting into qst; I'm thinking this should be the responsibility of the calling layer (engine). What about expanding this function to take in an additional parameter `Collection<? extends ColumnName> specialExclusions`?

**Review by devinrsmith — CHANGES_REQUESTED** [review]

File: qst/src/main/java/io/deephaven/qst/table/AggregateAllTable.java (hunk 3 above)
Comment (rcaudy) [reply qst/src/main/java/io/deephaven/qst/table/AggregateAllTable.java:38]: Then we won't get it right if we try to call `singleAggregation` from the QST layer.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java (hunk 1 above)
Comment (malhotrashivam) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java]: How do we usually decide between the two: performance vs readability?
Is that why we always keep string.format in exceptions because performance is not a concern there?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java [hunk 4]
```diff
@@ -732,24 +731,46 @@ public Table aggAllBy(AggSpec spec, ColumnName... groupByColumns) {
...
+    /**
+     * Computes the single-aggregation from the agg-all implied by the {@code spec} and {@code groupByColumns} by
+     * removing the {@code groupByColumns} and any extra columns implied by the {@code spec}.
+     *
+     * @param spec the spec
+     * @param groupByColumns the group by columns
+     * @param tableColumns the table columns
+     * @return the aggregation, if non-empty
+     */
+    static Optional<Aggregation> singleAggregation(
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java:760]:
```suggestion
    @VisibleForTesting
    static Optional<Aggregation> singleAggregation(
```

**Review by rcaudy — APPROVED** [review]

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java (hunk 4 above)
Comment (malhotrashivam) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java:760]: Will add this in my next PR to avoid another review cycle.
