### PR TITLE
Move subscribeToLogs sending off-thread

### LINKED ISSUE #3270: Groovy parser error kills web UI
```
2023-01-06T00:05:22.908Z | orinmemory://model/1 |  WARN | i.d.l.parse.PendingParse  | Parser for inmemory://model/1: Encountered parse exception io.deephaven.lang.generated.TokenMgrException: Lexical error at line 1, column 2.  Encountered: "\u00a0" (160), after : ""                                                                                                   
        at io.deephaven.lang.generated.ChunkerTokenManager.getNextToken(ChunkerTokenManager.java:2377)                                                                                                                                                                                                                                                                        
        at io.deephaven.lang.generated.Chunker.jj_ntk_f(Chunker.java:4370)                                                                                                                                                                                                                                                                                                    
        at io.deephaven.lang.generated.Chunker.Expression(Chunker.java:2794)                                                                                                                                                                                                                                                                                                  
        at io.deephaven.lang.generated.Chunker.Values(Chunker.java:1659)                                                                                                                                                                                                                                                                                                      
        at io.deephaven.lang.generated.Chunker.Statement(Chunker.java:302)                 
        at io.deephaven.lang.generated.Chunker.EatStatements(Chunker.java:221)             
        at io.deephaven.lang.generated.Chunker.Document(Chunker.java:158)                  
        at io.deephaven.lang.parse.PendingParse$ParseJob.parse(PendingParse.java:72)       
        at io.deephaven.lang.parse.PendingParse.parse(PendingParse.java:162)               
        at java.lang.Thread.run(Thread.java:829)                                           
 while parsing xﾠ=ﾠbaseTable.snapshotWhen(triggerTable)
```

This error seems to kill the websocket connection, and then causes an issues w/ gRPC websocket mulitplex:

```
2023-01-06T00:05:22.918Z | qtp1485485458-51     | ERROR | i.d.e.b.util.GrpcUtil     | Unanticipated gRPC Error: io.grpc.StatusRuntimeException: UNKNOWN                                                                                                                                                                                                                           
        at io.grpc.Status.asRuntimeException(Status.java:530)                                                                                                                                                                                                                                                                                                                     
        at io.grpc.servlet.web.websocket.MultiplexedWebsocketStreamImpl$Sink.writeMetadataToStream(MultiplexedWebsocketStreamImpl.java:79)                                                                                                                                                                                                                                        
        at io.grpc.servlet.web.websocket.MultiplexedWebsocketStreamImpl$Sink.writeTrailers(MultiplexedWebsocketStreamImpl.java:128)                                                                                                                                                                                                                                               
        at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:133)                                                                                                                                                                                                                                                                                             
        at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:228)                                                                                                                                                                                                                                                                                                 
        at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:212)                                                                                                                                                                                                                                                                                                         
        at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)                                                                                                                                                                                                                                                                                         
        at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)                                                                                                                                                                                                                                                                                                       
        at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)                                                                                                                                                                                                                                                                            
        at io.deephaven.server.session.SessionServiceGrpcImpl$InterceptedCall.close(SessionServiceGrpcImpl.java:257)                                                                                                                                                                                                                                                              
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)                                                                                                                                                                                                                                                                                
        at io.deephaven.extensions.barrage.util.GrpcUtil.safelyExecuteLocked(GrpcUtil.java:154)                                                                                                                                                                                                                                                                                   
        at io.deephaven.server.session.SessionCloseableObserver.close(SessionCloseableObserver.java:39)                                                                                                                                                                                                                                                                           
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:279)                                                                                                                                                                                                                                                         
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)                                                                                                                                                                                                                                                                      
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)                                                                                                                                                                                                                                                                                    
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)                                                                                                                                                                                                                                                 
        at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)                                                                                                                                                                                                                                                                                           
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:378)                                                                                                                                                                                                                                                                       
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:365)                                                                                                                                                                                                                                                                               
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:923)                                                                                                                                                                                                                                                      
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)                                                                                                                                                                                                                                                                                                          
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)                                                                                                                                                                                                                                                          
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:930)                                                                                                                                                                                                                                                            
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:888)                                                                                                                                                                                                                                                                    
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:339)                                                                                                                                                                                                                                                                      
        at io.grpc.internal.AbstractServerStream$TransportState.access$100(AbstractServerStream.java:184)                                                                                                                                                                                                                                                                         
        at io.grpc.internal.AbstractServerStream$TransportState$1.run(AbstractServerStream.java:289)                                                                                                                                                                                                                                                                              
        at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:241)                                                                                                                                                                                                                                                                     
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.deframerClosed(AbstractWebsocketStreamImpl.java:25)                                                                                                                                                                                                                                  
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)                                                                                                                                                                                                                                                                                                       
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:198)                                                                                                                                                                                                                                                                                  
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:293)                                                                                                                                                                                                                                                              
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.transportReportStatus(AbstractWebsocketStreamImpl.java:103)                                                                                                                                                                                                                                                  
        at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onError(MultiplexedWebSocketServerStream.java:224)                                                                                                                                                                                                                                                      
        at io.grpc.servlet.web.websocket.GrpcWebsocket.onError(GrpcWebsocket.java:48)                                                                                                                                                                                                                                                                                             
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onError(JakartaWebSocketFrameHandler.java:312)                                                                                                                                                                                                                                                 
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$closeConnection$2(WebSocketCoreSession.java:284)                                                                                                                                                                                                                                                 
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1465)                                                                                                                                                                                                                                                                                       
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1484)                                                                                                                                                                                                                                                                                       
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)                                                                                                                                                                                                                                                              
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.closeConnection(WebSocketCoreSession.java:284)                                                                 
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:254)                                                                           
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:482)                                                                      
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)                                                                        
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)                                                                                   
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)                
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)                                                                                       
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)                                                                  
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)                                                              
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)                                                               
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)                                                             
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)                                                                      
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)                                                                                              
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)                                                                                         
        at java.lang.Thread.run(Thread.java:829)                                 
        caused by:                                                                                  
java.io.IOException: java.nio.channels.ClosedChannelException                               
        at org.eclipse.jetty.util.FutureCallback.block(FutureCallback.java:163)             
        at org.eclipse.jetty.util.FutureCallback.block(FutureCallback.java:139)             
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketBasicRemote.sendBinary(JakartaWebSocketBasicRemote.java:66)                                                        
        at io.grpc.servlet.web.websocket.MultiplexedWebsocketStreamImpl$Sink.writeMetadataToStream(MultiplexedWebsocketStreamImpl.java:77)                                               
        at io.grpc.servlet.web.websocket.MultiplexedWebsocketStreamImpl$Sink.writeTrailers(MultiplexedWebsocketStreamImpl.java:128)                                                      
        at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:133)       
        at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:228)           
        at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:212)                   
        at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)                                                                                                
        at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)                 
        at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)                                                                                   
        at io.deephaven.server.session.SessionServiceGrpcImpl$InterceptedCall.close(SessionServiceGrpcImpl.java:257)                                                                     
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)                                                                                       
        at io.deephaven.extensions.barrage.util.GrpcUtil.safelyExecuteLocked(GrpcUtil.java:154)                                                                                          
        at io.deephaven.server.session.SessionCloseableObserver.close(SessionCloseableObserver.java:39)                                                                                  
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:279)                                                                
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)                                                                             
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)                                                                                           
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)                                                        
        at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)     
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:378)                                                                              
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:365)                                                                                      
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:923)                                                             
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)                    
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)                                                                 
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:930)                                                                   
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:888)                                                                           
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:339)                                                                             
        at io.grpc.internal.AbstractServerStream$TransportState.access$100(AbstractServerStream.java:184)                                                                                
        at io.grpc.internal.AbstractServerStream$TransportState$1.run(AbstractServerStream.java:289)                                                                                     
        at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:241)                                                                            
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.deframerClosed(AbstractWebsocketStreamImpl.java:25)                                         
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)                 
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:198)                                                                                         
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:293)                                                                     
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.transportReportStatus(AbstractWebsocketStreamImpl.java:103)                                                         
        at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onError(MultiplexedWebSocketServerStream.java:224)                                                             
        at io.grpc.servlet.web.websocket.GrpcWebsocket.onError(GrpcWebsocket.java:48)       
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onError(JakartaWebSocketFrameHandler.java:312)                                                        
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$closeConnection$2(WebSocketCoreSession.java:284)                                                        
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1465)                                                                                              
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1484)                                                                                              
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)                                                                     
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.closeConnection(WebSocketCoreSession.java:284)                                                                 
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:254)                                                                           
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:482)                                                                      
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)                                                                        
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)                                                                                   
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)                
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)                                                                                       
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)                                                                  
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)                                                              
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)                                                               
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)                                                             
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)                                                                      
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)                                                                                              
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)                                                                                         
        at java.lang.Thread.run(Thread.java:829)                                            
caused by:                                                                                  
java.nio.channels.ClosedChannelException: null                                              
        at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onOutgoingFrame(WebSocketSessionState.java:184)                                                               
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.sendFrame(WebSocketCoreSession.java:514)                                                                       
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketRemoteEndpoint.sendFrame(JakartaWebSocketRemoteEndpoint.java:140)                                                  
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketBasicRemote.sendBinary(JakartaWebSocketBasicRemote.java:65)                                                        
        at io.grpc.servlet.web.websocket.MultiplexedWebsocketStreamImpl$Sink.writeMetadataToStream(MultiplexedWebsocketStreamImpl.java:77)                                               
        at io.grpc.servlet.web.websocket.MultiplexedWebsocketStreamImpl$Sink.writeTrailers(MultiplexedWebsocketStreamImpl.java:128)                                                      
        at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:133)       
        at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:228)           
        at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:212)                   
        at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)                                                                                                
        at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)                 
        at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)                                                                                   
        at io.deephaven.server.session.SessionServiceGrpcImpl$InterceptedCall.close(SessionServiceGrpcImpl.java:257)                                                                     
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)                                                                                       
        at io.deephaven.extensions.barrage.util.GrpcUtil.safelyExecuteLocked(GrpcUtil.java:154)                                                                                          
        at io.deephaven.server.session.SessionCloseableObserver.close(SessionCloseableObserver.java:39)                                                                                  
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:279)                                                                
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)                                                                             
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)                                                                                           
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)                                                        
        at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)                                                                                                  
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:378)                                                                              
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:365)                                                                                      
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:923)                                                             
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)                    
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)                                                                 
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:930)                                                                   
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:888)                                                                           
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:339)                                                                             
        at io.grpc.internal.AbstractServerStream$TransportState.access$100(AbstractServerStream.java:184)                                                                                
        at io.grpc.internal.AbstractServerStream$TransportState$1.run(AbstractServerStream.java:289)                                                                                     
        at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:241)                                                                            
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.deframerClosed(AbstractWebsocketStreamImpl.java:25)                                         
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)                 
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:198)                                                                                         
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:293)                                                                     
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.transportReportStatus(AbstractWebsocketStreamImpl.java:103)                                                         
        at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onError(MultiplexedWebSocketServerStream.java:224)                                                             
        at io.grpc.servlet.web.websocket.GrpcWebsocket.onError(GrpcWebsocket.java:48)       
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onError(JakartaWebSocketFrameHandler.java:312)                                                        
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$closeConnection$2(WebSocketCoreSession.java:284)                                                        
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1465)                                                                                              
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1484)                                                                                              
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)                                                                     
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.closeConnection(WebSocketCoreSession.java:284)                                                                 
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:254)                                                                           
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:482)                                                                      
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)                                                                        
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)                                                                                   
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)                
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)                                                                                       
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)                                                                  
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)                                                              
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)                                                               
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)                                                             
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)                                                                      
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)                                                                                              
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)                                                                                         
        at java.lang.Thread.run(Thread.java:829)                                            
```

### PR DESCRIPTION
**Pull request by devinrsmith**
Fixes #3270

### CODE REVIEW

**Comment by devinrsmith** [comment]
I've exercised a lot of "heavy real world" testing with this new logic (essentially, logging out 10 million values in a tight server loop, and having a variety of clients connected). Both through the web UI console client, the JS api console client, and a different java clients (that could have different behaviors; ie, sleeping, batching, etc). I added some metric instrumentation, and can confirm that all branches have been heavily exercised, and I haven't observed any race conditions.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java [hunk 1]
```diff
@@ -303,57 +316,145 @@ public void onCompleted() {
...
+                GrpcUtil.safelyOnNext(client, payload);
+            }
+            // we don't know if the queue is empty
+            return false;
+        }
+
+        // ------------------------------------------------------------------------------------------------------------
+
+        private void onReady() {
+            scheduler.runImmediately(this);
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:423]: I think this should be a no-op if `guard.get() == true`.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java [hunk 2]
```diff
@@ -303,57 +316,145 @@ public void onCompleted() {
...
+                }
+                if (!client.isReady()) {
+                    // When !client.isReady(), onReady() is going to be called and will handle the reschedule.
+                    // Note: it's important that client.isReady() is checked _outside_ of the guard block (otherwise,
+                    // the onReady() call could execute and schedule before the current thread exits the guard block,
+                    // and we'd fail to successfully reschedule).
+                    return;
+                }
+                if (queueIsKnownEmpty) {
+                    scheduler.runAfterDelay(SUBSCRIBE_TO_LOGS_SEND_MILLIS, this);
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:400]: This makes me wonder if we should have a repeat scheduling option in the scheduler.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java [hunk 3]
```diff
@@ -303,57 +316,145 @@ public void onCompleted() {
...
+            while (!done && client.isReady()) {
+                LogSubscriptionData payload = dequeue();
+                if (payload == null) {
+                    // we know the queue is empty
+                    return true;
                 }
-            } catch (Throwable ignored) {
-                // we are ignoring exceptions here deliberately, and just shutting down
-                close();
+                GrpcUtil.safelyOnNext(client, payload);
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:414]: Can this block even if ready? I'm imagining a scenario where `isReady` returns `true`, but it can only accommodate  a small payload. I suspect the gRPC implementation buffers in messages, though.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java [hunk 4]
```diff
@@ -303,57 +316,145 @@ public void onCompleted() {
...
+        // or ArrayBlockingQueue; this would have different semantics though since they are queues, and not ring
+        // buffers (we may not care about semantics for overloaded cases - if you are missing logging data, it may not
+        // matter _what_ logging data you are missing).
+        //
+        // https://github.com/devinrsmith/JAtomicRingBuffer, or similar SPSC ring buffers, may be relevant if we need a
+        // ring buffer with higher concurrent performance.
+
+        private void enqueue(LogSubscriptionData payload) {
+            synchronized (buffer) {
+                buffer.addOverwrite(payload);
```
[the remark this answers is not in the document]
Comment (devinrsmith) [reply server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:451]: I do like the semantics of closing a slow client; keeps things cleaner IMO.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java (hunk 1 above)
Comment (devinrsmith) [reply server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:423]: I _think_ you are right, but it's a _very_ rare case. In some testing I did, it only saved us from executing 

```
>>> 13/3583491
3.6277473558605283e-06
```

times.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java (hunk 2 above)
Comment (devinrsmith) [reply server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:439]: I've tried to plumb it, but ran into limitations about how we shim the scheduler. Added a note.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java (hunk 3 above)
Comment (devinrsmith) [reply server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java]: I think technically, yes, but unlikely; I'm not 100% confident. There are multiple layers of abstraction, and I think it gets down into framing code.

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java [hunk 5]
```diff
@@ -303,58 +316,155 @@ public void onCompleted() {
...
+                boolean bufferIsKnownEmpty;
+                try {
+                    bufferIsKnownEmpty = false;
+                    while (true) {
+                        if (done) {
+                            return;
+                        }
+                        if (tooSlow) {
+                            // The client can't keep up (and/or, an unreasonable amount of data is being logged).
+                            GrpcUtil.safelyError(client, Code.RESOURCE_EXHAUSTED, "Too slow");
```
Comment (devinrsmith) [inline server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:397]: Is there a better Code to use?

File: IO/src/main/java/io/deephaven/io/logger/LogBuffer.java [hunk 6]
```diff
@@ -8,14 +8,15 @@
 
 import java.util.ArrayList;
 import java.util.List;
```
Comment (rcaudy) [inline IO/src/main/java/io/deephaven/io/logger/LogBuffer.java:10]: Unused
```suggestion
```

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java [hunk 7]
```diff
@@ -137,6 +137,7 @@ public void startConsole(StartConsoleRequest request, StreamObserver<StartConsol
     @Override
     public void subscribeToLogs(LogSubscriptionRequest request, StreamObserver<LogSubscriptionData> responseObserver) {
         GrpcUtil.rpcWrapper(log, responseObserver, () -> {
+            sessionService.getCurrentSession();
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:140]: Not a particular criticism of your change, but given that we often use this to assert authentication, maybe we should rename it?

**Review by rcaudy — APPROVED** [review]

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java (hunk 7 above)
Comment (devinrsmith) [reply server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:140]: I think we might want to have an additional method with a more appropriate name, yes.
