### PR TITLE
ReplayTable: Only Fail Table (not the server) on Error

### LINKED ISSUE #5016: Replaying inappropriate data crashes server
**Description**

Replaying a table that violates the conditions of a replayable table crashes the server.

**Steps to reproduce**
Run this code (you need the example data):
```
from deephaven import read_csv

crypto = read_csv("/data/examples/CryptoCurrencyHistory/CSV/CryptoTrades_20210922.csv")

from deephaven.replay import TableReplayer

replayer = TableReplayer("2021-09-22T16:00:11.78Z", "2021-09-22T20:11:34.60Z")
replayed_crypto = replayer.add_table(crypto, "Timestamp")
replayer.start()
```

**Expected results**

I expect an error in the IDE log that tells me I've done something wrong.

**Actual results**

Here is the error upon crash:
Screenshot 2024-01-08 at 8 07 35 PM

And the Docker logs:
```
examples-deephaven-1  | crypto = read_csv("/data/examples/CryptoCurrencyHistory/CSV/CryptoTrades_20210922.csv")
examples-deephaven-1  | 
examples-deephaven-1  | from deephaven.replay import TableReplayer
examples-deephaven-1  | 
examples-deephaven-1  | replayer = TableReplayer("2021-09-22T16:00:11.78Z", "2021-09-22T20:11:34.60Z")
examples-deephaven-1  | replayed_crypto = replayer.add_table(crypto, "Timestamp")
examples-deephaven-1  | replayer.start()
examples-deephaven-1  | 2024-01-09T02:07:16.584Z | aph-updateExecutor-2 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-2: Exception while executing UpdateGraph notification: UpdateSourceRefreshNotification{1802521732, for UpdateSource{443362842}}: java.lang.RuntimeException: The historical table contains a null or decreasing time that cannot be replayed.
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceIterators(ReplayTable.java:66)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceToCurrentTime(ReplayTable.java:84)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.run(ReplayTable.java:94)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph$UpdateSourceRefreshNotification.run(BaseUpdateGraph.java:955)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)
examples-deephaven-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
examples-deephaven-1  | 
examples-deephaven-1  | Initiating shutdown due to: Exception while processing UpdateGraph notification
examples-deephaven-1  | java.lang.RuntimeException: The historical table contains a null or decreasing time that cannot be replayed.
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceIterators(ReplayTable.java:66)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceToCurrentTime(ReplayTable.java:84)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.run(ReplayTable.java:94)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph$UpdateSourceRefreshNotification.run(BaseUpdateGraph.java:955)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)
examples-deephaven-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
examples-deephaven-1  | 2024-01-09T02:07:16.594Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Initiating shutdown processing
examples-deephaven-1  | 2024-01-09T02:07:16.595Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke FIRST shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.598Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Done invoking FIRST shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.598Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke MIDDLE shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.599Z | Thread-0             |  INFO | portedTableUpdateListener | ExportedTableUpdateListener(10b1bbd1) is complete
examples-deephaven-1  | 2024-01-09T02:07:16.602Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Done invoking MIDDLE shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.602Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke LAST shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.622Z | qtp935520971-63      |  INFO | i.d.s.s.SessionService    | No AuthenticationRequestHandler registered for type Bearer
examples-deephaven-1  | 2024-01-09T02:07:16.622Z | qtp935520971-63      |  INFO | i.d.s.s.SessionService    | No AuthenticationRequestHandler registered for type Bearer
examples-deephaven-1  | 2024-01-09T02:07:16.622Z | qtp935520971-63      |  INFO | i.d.s.s.SessionService    | No AuthenticationRequestHandler registered for type Bearer
examples-deephaven-1  | 2024-01-09T02:07:16.642Z | Thread-26            |  INFO | o.e.jetty.server.Server   | Stopped Server@3c28e5b6{STOPPING}[11.0.17,sto=5000]
examples-deephaven-1  | 2024-01-09T02:07:16.642Z | Thread-26            |  INFO | o.e.jetty.server.Server   | Shutdown Server@3c28e5b6{STOPPING}[11.0.17,sto=5000]
examples-deephaven-1  | 2024-01-09T02:07:16.644Z | Thread-26            |  INFO | o.e.j.s.AbstractConnector | Stopped ServerConnector@26d820eb{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:10000}
examples-deephaven-1 exited with code 1
```

**Additional details and attachments**

I'm working with the image [here](https://raw.githubusercontent.com/deephaven/deephaven-core/main/containers/python-examples/base/docker-compose.yml).

**Versions**
 - Deephaven: 0.31.0
 - OS: MacOS 13.2.1
 - Browser: Safari
 - Docker: 4.19.0

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #5016.

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/replay/Replayer.java [hunk 1]
```diff
@@ -190,8 +190,8 @@ public Table replay(Table dataSource, String timeColumn) {
         if (dataSource.isRefreshing()) {
             dataSource = dataSource.snapshot();
         }
-        final ReplayTable result =
-                new ReplayTable(dataSource.getRowSet(), dataSource.getColumnSourceMap(), timeColumn, this);
+        final ReplayTable result = new ReplayTable(
+                dataSource.getRowSet(), dataSource.getColumnSourceMap(), timeColumn, this, updateGraph);
         currentTables.add(result);
         if (deltaNanos < Long.MAX_VALUE) {
             updateGraph.addSource(result);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/replay/Replayer.java:197]: I don't love the pattern wherein the replayer removes itself from the update graph, but is added externally. Maybe we should add a "start()" method to ReplayTable?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayTable.java [hunk 2]
```diff
@@ -91,12 +94,19 @@ public void run() {
...
+                getRowSet().writableCast().insert(added);
+                notifyListeners(added, RowSetFactory.empty(), RowSetFactory.empty());
+            } else {
+                added.close();
+            }
+        } catch (final Exception err) {
+            updateSourceRegistrar.removeSource(this);
+
+            // propagate the error to our listeners
+            notifyListenersOnError(err, null);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayTable.java:109]: Why don't we have a UPL node? Maybe we should be using an `io.deephaven.engine.table.impl.InstrumentedUpdateSource`.

Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayTable.java:109]: This is less paranoid than what I have been pushing for lately. What if the exception you caught came from notifyListeners? See the pattern around `io.deephaven.engine.table.impl.util.FunctionGeneratedTableFactory.DelayedErrorNotifier`. The data indexing branch will make this more generic.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java [hunk 3]
```diff
@@ -209,46 +209,39 @@ private WritableRowSet refreshLocationSizes() {
         }
     }
 
-    private class LocationChangePoller extends InstrumentedUpdateSource {
+    private class LocationChangePoller extends InstrumentedTableUpdateSource {
         private final TableLocationSubscriptionBuffer locationBuffer;
 
         private LocationChangePoller(@NotNull final TableLocationSubscriptionBuffer locationBuffer) {
-            super(updateGraph, description + ".rowSetUpdateSource");
+            super(SourceTable.this, description + ".rowSetUpdateSource");
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java:216]: Be sure to pass our actual registrar.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/TimeTable.java [hunk 4]
```diff
@@ -158,10 +158,10 @@ public void run() {
         refresh(true);
     }
 
-    private class SourceRefresher extends InstrumentedUpdateSource {
+    private class SourceRefresher extends InstrumentedTableUpdateSource {
 
         public SourceRefresher() {
-            super(updateGraph, name);
+            super(TimeTable.this, name);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/TimeTable.java:164]: Be sure to pass the registrar.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/replay/Replayer.java [hunk 5]
```diff
@@ -60,8 +62,9 @@ public Replayer(Instant startTime, Instant endTime) {
     @Override
     public void start() {
         deltaNanos = DateTimeUtils.millisToNanos(System.currentTimeMillis()) - DateTimeUtils.epochNanos(startTime);
-        for (Runnable currentTable : currentTables) {
-            updateGraph.addSource(currentTable);
+        updateGraph.addSource(sourceRefresher);
+        for (ReplayTableBase currentTable : currentTables) {
+            currentTable.start();
         }
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/replay/Replayer.java:68]: It might be worth a forward-looking comment that points out that the ReplayTables are allowed to run in parallel with the Replayer, and that maybe we might want an UpdateSourceCombiner in the future.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateSource.java [hunk 6]
```diff
@@ -16,19 +17,26 @@ public abstract class InstrumentedTableUpdateSource extends InstrumentedUpdateSo
     @ReferentialIntegrity
     private Runnable delayedErrorReference;
 
-    public InstrumentedTableUpdateSource(final BaseTable<?> table, final String description) {
-        super(table.getUpdateGraph(), description);
+    public InstrumentedTableUpdateSource(
+            final UpdateSourceRegistrar updateSourceRegistrar,
+            final BaseTable<?> table,
+            final String description) {
+        super(updateSourceRegistrar, description);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateSource.java:24]: Assert that the USR and BT have the same update graph.
