### PR TITLE
Force PartitionAwareSourceTable to coalesce whenever a partition filter is applied via where

### LINKED ISSUE #5482: MatchFilter exception from UI on Uncoalesced Table
**Description**

When you filter by Date, the table no longer coalesces; and if you operate in the UI filtering and sorting your table, you can get the following:

```heduler-Concurrent-1 | i.d.s.s.SessionState      | Internal Error 'de18b7ea-2e17-4b8b-8323-e1d29dbc05e5' java.lang.IllegalStateException: Inputs already initialized, use copy() instead of re-using a WhereFilter
	at io.deephaven.engine.table.impl.select.MatchFilter.beginOperation(MatchFilter.java:220)
	at io.deephaven.engine.table.impl.select.ComposedFilter.lambda$beginOperation$0(ComposedFilter.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.deephaven.engine.table.impl.select.ComposedFilter.beginOperation(ComposedFilter.java:84)
	at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$23(QueryTable.java:1271)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$28(QueryTable.java:1271)
	at io.deephaven.engine.table.impl.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3674)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3643)
	at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$29(QueryTable.java:1269)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.whereInternal(QueryTable.java:1223)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:1162)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:100)
	at io.deephaven.engine.table.impl.DeferredViewTable.doCoalesce(DeferredViewTable.java:243)
	at io.deephaven.engine.table.impl.UncoalescedTable.coalesce(UncoalescedTable.java:78)
	at io.deephaven.engine.table.impl.UncoalescedTable.sort(UncoalescedTable.java:415)
	at io.deephaven.engine.table.impl.UncoalescedTable.sort(UncoalescedTable.java:43)
	at io.deephaven.server.table.ops.SortTableGrpcImpl.create(SortTableGrpcImpl.java:104)
	at io.deephaven.server.table.ops.SortTableGrpcImpl.create(SortTableGrpcImpl.java:26)
	at io.deephaven.server.table.ops.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:757)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:995)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Versions**
 - Deephaven: 0.34.1 (as part of Core+)

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #5482

### CODE REVIEW

**Review by nbauernfeind — DISMISSED** [review]

File: engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java [hunk 1]
```diff
@@ -89,51 +87,49 @@ public Table where(Filter filter) {
...
 
         Table localResult = tableAndRemainingFilters.table;
-        if (localResult instanceof DeferredViewTable) {
-            localResult = ((DeferredViewTable) localResult)
-                    .getResultTableWithWhere(tableAndRemainingFilters.remainingFilters);
-        } else {
-            localResult =
-                    localResult.where(Filter.and(WhereFilter.copyFrom(tableAndRemainingFilters.remainingFilters)));
+        if (tableAndRemainingFilters.remainingFilters.length != 0) {
+            localResult = localResult.where(Filter.and(tableAndRemainingFilters.remainingFilters));
```
Comment (cpwright) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java:116]: does Filter.and do something useful here?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java [hunk 2]
```diff
@@ -89,51 +87,49 @@ public Table where(Filter filter) {
...
         if (whereFilters.length == 0) {
+            // The result is effectively the same as if we called doCoalesce()
             copyAttributes((BaseTable<?>) localResult, CopyAttributeOperation.Coalesce);
             setCoalesced(localResult);
         }
         return localResult;
     }
 
     private Table applyDeferredViews(Table result) {
-        if (result instanceof DeferredViewTable) {
```
Comment (cpwright) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java:134]: Do we have good coverage for dropping this and composing it?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java (hunk 1 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java:116]: Yes. The API is written to accept one filter, instead of `List`.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java (hunk 2 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java:134]: This was compensating for the super-weirdness in the `TableReference` implementations. I'm convinced it's doing the same things.

**Review by cpwright — APPROVED** [review]

**Review by cpwright — APPROVED** [review]
