### PR TITLE
Don't remove subscriptions while iterating them

### LINKED ISSUE #2070: propagateUpdates CME
```
java.util.ConcurrentModificationException: null
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
        at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl.propagateUpdates(ApplicationServiceGrpcImpl.java:212)
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl$FieldUpdatePropagationJob.run(ApplicationServiceGrpcImpl.java:298)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #2070

### CODE REVIEW

**Review by nbauernfeind — DISMISSED** [review]

File: server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java [hunk 1]
```diff
@@ -209,7 +210,8 @@ private synchronized void propagateUpdates() {
         updatedFields.clear();
         final FieldsChangeUpdate update = builder.build();
 
-        subscriptions.forEach(sub -> sub.send(update));
+        List<Subscription> subscriptionsToCancel = subscriptions.stream().filter(sub -> sub.send(update)).collect(Collectors.toList());
```
Comment (devinrsmith) [inline server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java:213]: filter predicates *should* be stateless ...

**Review by devinrsmith — CHANGES_REQUESTED** [review]

File: server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java (hunk 1 above)
Comment (niloc132) [reply server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java]: Yeah - removeIf is so much clearer, thanks for the kick to just do it right.

I almost went with removeIf right away after seeing your comment, then assume that it would be equally "inappropriate" to do so, even though, like Stream.filter with a collect on the end, I know it will traverse every item. Instead I went with 
```
        for (Iterator<Subscription> iterator = subscriptions.iterator(); iterator.hasNext(); ) {
            Subscription subscription = iterator.next();
            if (!subscription.send(update)) {
                iterator.remove();
            }
        }
```
And IJ gave me a "why don't you just use Collection.removeIf" popup. Fixed.

File: server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java [hunk 2]
```diff
@@ -209,7 +210,7 @@ private synchronized void propagateUpdates() {
         updatedFields.clear();
         final FieldsChangeUpdate update = builder.build();
 
-        subscriptions.forEach(sub -> sub.send(update));
+        subscriptions.removeIf(subscription -> !subscription.send(update));
```
Comment (devinrsmith) [inline server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java:213]: Do we need any of the side-effects that onClose previously provided? (We aren't calling onClose now.)

* `session.removeOnCloseCallback(subscription)`
* `subscription.notifyObserverAborted()`

Comment (niloc132) [reply server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java:213]: No you're right, though the broken behavior won't be visible externally

 * the leaked callback will just leak until the session cleans it up, which isnt ideal
 * the observer notification doesnt matter, since the observer is already by definition failed

I really dont care for this close-is-remove-but-not-cancel pattern we have used here and elsewhere. I am also not sure that what we seem to have here makes sense at all (why does a close() call necessarily mean sending the aborted message, but doesnt do the cleanup from the session?), but I think that cleanup is outside the scope for this set of changes.

File: server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java [hunk 3]
```diff
@@ -363,12 +367,17 @@ public void close() {
             remove(this);
         }
 
-        // must be sync wrt parent
+        /**
+         * Sends an update to the subscribed client. Returns true if successful - if false, the client is no longer
+         * listening and this subscription should be canceled after iteration.
```
Comment (devinrsmith) [inline server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java:372]: Looking at callers of `send` - do we also need to do an onCancel call in `listFields`?

Comment (niloc132) [reply server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java:372]: Probably, though a) it is a weak ref anyway, and b) the subscription won't be in the list so doesnt need to be removed. I'll make the change in this patch, though it probably should be incorporated into a bigger change that generally cleans up these patterns, rather than fixing each piecemeal as we've been doing.

**Review by devinrsmith — APPROVED** [review]
