### PR TITLE
fix: JS API should use GetConfigurationConstants for auth calls

### LINKED ISSUE #5955: JSAPI duplicates authentication header in Open/Next handshake requests
**Description**

When the browser issues an OpenHandshake followed by a NextHandshake for  flight authentication it sends identical authentication headers.  This causes Core+ to reject the Next and fail to establish connections properly.

**Additional details and attachments**

Screenshot 2024-08-19 at 12 42 32 PM
Screenshot 2024-08-19 at 12 42 23 PM

**Versions**
 - Deephaven: 0.36.0
 - OS: MacOS
 - Browser: Chrome Version 126.0.6478.127 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by niloc132**
In addition to more closely following what other Deephaven clients do, this prevents an issue where Open/Next pairs of gRPC calls (to emulate a bidirectional call) can race each other to redeem a one-time use auth token.

Fixes #5955

### CODE REVIEW

**Comment by niloc132** [comment]
Confirmed by @abaranec to resolve the issue. Should be backported to 0.36.1.

File: web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java [hunk 1]
```diff
@@ -479,54 +481,56 @@ private Promise<Void> authUpdate() {
...
                     scheduledAuthUpdate = DomGlobal.setTimeout(ignore -> {
                         authUpdate();
                     }, sessionTimeoutMs / 2);
 
-                    resolve.onInvoke((Void) null);
-                } else {
-                    if (status.getCode() == Code.Unauthenticated) {
+                    result.getMessage().getConfigValuesMap().forEach((item, key) -> {
+                        if (key.equals("http.session.durationMs")) {
+                            sessionTimeoutMs = Double.parseDouble(item.getStringValue());
```
Comment (nbauernfeind) [inline web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java:510]: We probably need to move setting the `sessionTimeoutMs` prior to using it in the `setTimeout` a few lines above?

**Review by nbauernfeind — APPROVED** [review]
