### PR TITLE
A few cleanups and bug fixes

### LINKED ISSUE #4383: Class Initialization Monitor Deadlock
Apparently we can get into a situation where we fail to class load from the UpdateGraph notification processing thread.

I'm not sure how to reproduce yet.

```
    java.lang.Thread.State: RUNNABLE
         at io.deephaven.engine.rowset.impl.RspBitmapBuilderSequential.appendRange(RspBitmapBuilderSequential.java:77)
         - waiting on the Class initialization monitor for io.deephaven.engine.rowset.impl.RefCountedCow
         at io.deephaven.engine.rowset.impl.singlerange.SingleRange.ixInvertOnNew(SingleRange.java:772)
         at io.deephaven.engine.rowset.impl.WritableRowSetImpl.invert(WritableRowSetImpl.java:260)
         at io.deephaven.engine.rowset.RowSet.invert(RowSet.java:93)
         at io.deephaven.engine.table.impl.FlattenOperation.onUpdate(FlattenOperation.java:97)
         at io.deephaven.engine.table.impl.FlattenOperation$1.onUpdate(FlattenOperation.java:58)
         at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
         at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification$$Lambda$3031/0x000000080170ef18.run(Unknown Source)
         at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:334)
         at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:316)
         at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
         at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
         at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
         at
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor$$Lambda$2148/0x00000008013c97d8.run(Unknown Source)
         at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
         at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory$$Lambda$2150/0x00000008013ca2e0.run(Unknown Source)
         at java.lang.Thread.run(java.base@15.0.2/Thread.java:832)
```

[stacktrace_20230827.txt](https://github.com/deephaven/deephaven-core/files/12456742/stacktrace_20230827.txt)

### PR DESCRIPTION
**Pull request by rcaudy**
* Add more details to the failure message seen in `TestFormulaArrayEvaluation.testViewIncrementalRandomizedPerformanceTest`
* Some simplification and cleanups for `SelectColumn` implementations
* Install the correct (default) `UpdateGraph` in the `ExecutionContext` when initializing `UpdatePerformanceTracker.InternalState`. Don't install an unnecessary one during flush.
* Re-address `RefCountedCow`/`RspArray` static initialization deadlock due to debug flag, by making `RefCountedCow`'s debug flag independent. Introduce private debug flag for `SingleRange`, rather than sharing `RspArray`'s.

Fixes #4383

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java [hunk 1]
```diff
@@ -68,7 +68,9 @@ static Collection<SelectColumn> copyFrom(Collection<SelectColumn> selectColumns)
      * @param table the table to initialize internals from
      * @return a list containing all columns from 'table' that the result depends on
      */
-    List<String> initInputs(Table table);
+    default List<String> initInputs(Table table) {
```
Comment (nbauernfeind) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java:71]: `@FinalDefault`?

**Review by nbauernfeind — DISMISSED** [review]

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java (hunk 1 above)
Comment (cpwright) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java:71]: Or mabye just delete it?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java [hunk 2]
```diff
@@ -70,14 +70,9 @@ public SelectColumn copy() {
...
 
-    @Override
-    public final List<String> initInputs(@NotNull final Table table) {
-        return initInputs(table.getRowSet(), table.getColumnSourceMap());
-    }
-
     @Override
     public final Class<?> getReturnedType() {
-        return Table.class;
+        return long.class;
```
Comment (cpwright) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java:75]: Why should this class exist in addition to io.deephaven.engine.table.impl.sources.LongSingleValueSource#LongSingleValueSource?

**Review by cpwright — DISMISSED** [review]

File: engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java (hunk 2 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java:75]: Two reasons I can come up with:
1. It is simpler and tighter, since it's immutable and has no previous tracking.
2. It can be used in a select/view/update/updateView with other `SelectColumn` instances. This is more powerful, and also way more accessible than having to build a custom copy operation that adds columns.

File: engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/singlerange/SingleRange.java [hunk 3]
```diff
@@ -22,6 +22,10 @@
 import java.util.function.LongConsumer;
 
 public abstract class SingleRange implements OrderedLongSet {
+
+    private static final boolean debug =
```
[the remark this answers is not in the document]
Comment (rcaudy) [reply engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/singlerange/SingleRange.java:26]: I think the finer-grained debugging has value. We already had multiple debug flags, suggesting a need for fine-grained debugging in past cases. I would somewhat rather keep these separate, since you can easily combine multiple flags but you can't easily split them again.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java (hunk 1 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java:71]: Deleting it and inlining the uses would be OK, I guess.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java (hunk 2 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java:75]: We agreed to a small change here.

**Review by cpwright — APPROVED** [review]
