### PR TITLE
fix!: DH-20783: Update sort operations to put NULL first, NaN last

### LINKED ISSUE #5820: DoubleSegmentedSortedMultiset infinite loop
Potential infinite loop. Easy to reproduce, although the reproducer is not minimized yet.

```python
from deephaven.column import double_col, int_col
from deephaven.agg import (
    sorted_first,
    sorted_last,
    count_distinct,
    distinct,
    min_,
    max_,
)

x = new_table(
    [double_col("X", [-0.0, 0.0, float("nan"), float("inf"), float("-inf"), None])]
).update_view(["XStr=Double.toString(X)"])

x_aggs = merge([x] * 700).agg_by(
    [
        sorted_first("X", ["SortedFirst=X"]),
        sorted_last("X", ["SortedLast=X"]),
        count_distinct(["CountDistinct=X"]),
        count_distinct(["CountDistinctWithNulls=X"], count_nulls=True),
        distinct(["Distinct=X"]),
        distinct(["DistinctWithNulls=X"], include_nulls=True),
        min_(["Min=X"]),
        max_(["Max=X"]),
    ]
)
```

results in spinning computation. Resulting stacktrace:

```
"DeephavenApiServer-Scheduler-Serial-1" #131 [367] daemon prio=5 os_prio=0 cpu=49186.83ms elapsed=1993.30s tid=0x00007fca4c185ce0 nid=367 runnable  [0x00007fcd02bfb000]                                             
   java.lang.Thread.State: RUNNABLE                                                                                                                                                                                  
        at io.deephaven.engine.table.impl.ssms.DoubleSegmentedSortedMultiset.upperBound(DoubleSegmentedSortedMultiset.java:781)                                                                                      
        at io.deephaven.engine.table.impl.ssms.DoubleSegmentedSortedMultiset.insertExistingIntoLeaf(DoubleSegmentedSortedMultiset.java:95)                                                                           
        at io.deephaven.engine.table.impl.ssms.DoubleSegmentedSortedMultiset.insertExisting(DoubleSegmentedSortedMultiset.java:398)                                                                                  
        at io.deephaven.engine.table.impl.ssms.DoubleSegmentedSortedMultiset.insert(DoubleSegmentedSortedMultiset.java:439)                                                                                          
        at io.deephaven.engine.table.impl.ssms.DoubleSegmentedSortedMultiset.insert(DoubleSegmentedSortedMultiset.java:77)                                                                                           
        at io.deephaven.engine.table.impl.by.ssmcountdistinct.count.DoubleChunkedCountDistinctOperator.addChunk(DoubleChunkedCountDistinctOperator.java:212)                                                         
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.processColumnNoKey(ChunkedOperatorAggregationHelper.java:2506)                                                                         
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.doNoKeyUpdate(ChunkedOperatorAggregationHelper.java:2396)                                                                              
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.doNoKeyAddition(ChunkedOperatorAggregationHelper.java:2233)                                                                            
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.noKeyAggregation(ChunkedOperatorAggregationHelper.java:2053)                                                                           
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:156)                                                                                 
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.lambda$aggregation$2(ChunkedOperatorAggregationHelper.java:134)                                                                        
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$$Lambda/0x00007fccac8cefc0.call(Unknown Source)                                                                                        
        at io.deephaven.engine.table.impl.BaseTable.initializeWithSnapshot(BaseTable.java:1293)                                                                                                                      
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.lambda$aggregation$3(ChunkedOperatorAggregationHelper.java:131)                                                                        
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$$Lambda/0x00007fccac8ce720.get(Unknown Source)                                                                                         
        at io.deephaven.engine.liveness.LivenessScopeStack.computeEnclosed(LivenessScopeStack.java:179)                                                                                                              
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:119)                                                                                 
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:74)                                                                                  
        at io.deephaven.engine.table.impl.QueryTable.lambda$aggNoMemo$18(QueryTable.java:845)                                                                                                                        
        at io.deephaven.engine.table.impl.QueryTable$$Lambda/0x00007fccac8cd5e8.get(Unknown Source)                                                                                                                  
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)                                                                                                
        at io.deephaven.engine.table.impl.QueryTable.aggNoMemo(QueryTable.java:844)                                                                                                                                  
        at io.deephaven.engine.table.impl.QueryTable.lambda$aggBy$17(QueryTable.java:820)                                                                                                                            
        at io.deephaven.engine.table.impl.QueryTable$$Lambda/0x00007fccac8c7be0.get(Unknown Source)                                                                                                                  
        at io.deephaven.engine.table.impl.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3674)                                                                                                               
        - locked <0x00000000e0fa96c8> (a io.deephaven.engine.table.impl.QueryTable$MemoizedResult)                                                                                                                   
        at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3643)                                                                                                                             
        at io.deephaven.engine.table.impl.QueryTable.aggBy(QueryTable.java:820)                                                                                                                                      
        at io.deephaven.engine.table.impl.QueryTable.aggBy(QueryTable.java:100)                                                                                                                                      
        at io.deephaven.api.TableOperationsDefaults.aggBy(TableOperationsDefaults.java:312)                                                                                                                          
```

### LINKED ISSUE #5824: WritableDoubleChunk sort does not sort NULL_DOUBLE first
As noted in #5820, `WritableDoubleChunk#sort` uses `Arrays#sort(double[], ...)` which does not sort NULL_DOUBLEs first; `-Infinity` is sorted earlier.

### PR DESCRIPTION
**Pull request by lbooker42**
This PR updates sort operations throughout the Deephaven codebase to ensure consistent ordering where NULL values come first and NaN values come last, addressing ticket [DH-20783](https://deephaven.atlassian.net/browse/DH-20783). This represents a breaking change to the existing sort behavior.

- Updates chunk sorting implementations to use custom sorting logic instead of Java's default primitive sorting
- Adds comprehensive tests to verify the new NULL-first, NaN-last ordering behavior
- Fixes equality comparison functions in segmented sorted multisets to prevent infinite loops

Closes #5820. Closes #5824

Sorting changes in this PR affect:

- Table sort / sortDescending
- Chunk sort
- Sorted aggregations
   - AggSortedFirst
   - AggSortedLast 

[DH-20783]: https://deephaven.atlassian.net/browse/DH-20783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java [hunk 1]
```diff
@@ -1341,7 +1341,7 @@ private static boolean geq(double lhs, double rhs) {
 
     private static boolean eq(double lhs, double rhs) {
         // region equality function
-        return lhs == rhs;
+        return doComparison(lhs, rhs) == 0;
```
Comment (lbooker42) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java]: This change is the primary correction for https://github.com/deephaven/deephaven-core/issues/5820

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 2]
```diff
@@ -0,0 +1,275 @@
...
+
+final class WritableChunkUtils {
+
+    private static final int NULL_FLOAT_BITS = Float.floatToIntBits(NULL_FLOAT);
+    private static final int MIN_FINITE_FLOAT_BITS = Float.floatToIntBits(QueryConstants.MIN_FINITE_FLOAT);
+
+    private static final long NULL_DOUBLE_BITS = Double.doubleToLongBits(NULL_DOUBLE);
+    private static final long MIN_FINITE_DOUBLE_BITS = Double.doubleToLongBits(QueryConstants.MIN_FINITE_DOUBLE);
+
+    @SuppressWarnings("unused")
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java]: Here and below. I'd rather not have an always-throws method in the codebase. I'm not sure why it needs to be here, but I'd like to enumerate my feelings.

1. If it doesn't need to be here, but you want to signal to other developers that you didn't forget the "boolean" case, then I think a comment might be more appropriate.
2. If it needs to be there to satisfy some codegen or dynamic linking case, can you please add a comment here and below that explains why these are marked unused and always throw?

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 3]
```diff
@@ -0,0 +1,275 @@
...
+    }
+
+    @SuppressWarnings("unused")
+    public static void sortUnsafe(boolean[] data, int fromIndexInclusive, int toIndexExclusive) {
+        throw new UnsupportedOperationException();
+    }
+
+    public static void sortUnsafe(char[] data, int fromIndexInclusive, int toIndexExclusive) {
+        Arrays.sort(data, fromIndexInclusive, toIndexExclusive);
+    }
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java]: The code in this class is very dependent on the specific values of Deephaven constants. For example, it expects `NULL_CHAR` to sort to the end of the array and it expects `NULL_FLOAT` to sort close to the beginning. In some alternate universe, if someone tried to change these constants to something else, it could silently break this code.

I think I would suggest making these expectations explicit by having a class constructor that asserts or otherwise throws exceptions if the constants do not match the implicit assumptions. Something like

~~~
    // These assertions reflect sorting assumptions made by this code. If these assertions
    // change, this code will need to be carefully audited.
    static {
        assert(NULL_CHAR == Character.MAX_VALUE);
        assert(NULL_FLOAT == -Float.MAX_VALUE);
        assert(Float.NEGATIVE_INFINITY < NULL_FLOAT);
    }
~~~

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 4]
```diff
@@ -0,0 +1,275 @@
...
+
+    public static void sort(char[] data, int fromIndexInclusive, int toIndexExclusive) {
+        sortUnsafe(data, fromIndexInclusive, toIndexExclusive);
+        // We need to "fix-up" the nulls (Character.MAX_VALUE) from end of subset to beginning of subset.
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java]: Suggested rewording:

```
sortUnsafe() places Deephaven NULL_CHAR (Character.MAX_VALUE) at the end of the slice. This code moves them to the
beginning of the slice.
```

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 5]
```diff
@@ -0,0 +1,275 @@
...
+        // [ (...,) data_1, ..., data_m, NULL_CHAR_1, ..., NULL_CHAR_n (,...) ]
+        // ->
+        // [ (...,) NULL_CHAR_1, ..., NULL_CHAR_n, data_1, ..., data_m (,...) ]
+        if (toIndexExclusive - fromIndexInclusive <= 1) {
+            // size 0 or 1, already sorted
+            return;
+        }
+        if (data[fromIndexInclusive] == NULL_CHAR) {
+            // all are NULL_CHAR, already sorted
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java:26]: Suggest
```
// All are NULL_CHAR, therefore already sorted
```

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 6]
```diff
@@ -0,0 +1,275 @@
...
+            return;
+        }
+        if (data[toIndexExclusive - 1] != NULL_CHAR) {
+            // none are NULL_CHAR, already sorted
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java:30]:
```
// None are NULL_CHAR, therefore already sorted
```

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 7]
```diff
@@ -0,0 +1,275 @@
...
+            return;
+        }
+        // We know first position is not NULL_CHAR; we don't want to exclude the last position, b/c it may be the
+        // only NULL_CHAR.
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java]:
```
// We know:
// 1. The first position is not NULL_CHAR (so we can start at fromIndexInclusive + 1)
// 2. There is at least one NULL_CHAR in the slice (so there exists an exact match and the return value of
// binarySearchFirst is nonnegative)
```

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 8]
```diff
@@ -0,0 +1,275 @@
...
+        final int firstNullIx = binarySearchFirst(data, fromIndexInclusive + 1, toIndexExclusive, NULL_CHAR);
+        final int nullCount = toIndexExclusive - firstNullIx;
+        System.arraycopy(data, fromIndexInclusive, data, fromIndexInclusive + nullCount,
+                toIndexExclusive - fromIndexInclusive - nullCount);
+        Arrays.fill(data, fromIndexInclusive, fromIndexInclusive + nullCount, NULL_CHAR);
+    }
+
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java:41]: Do these `sortUnsafe`s need to be public? If they are public I think they need to have some kind of Javadoc indicating what is "unsafe" about them. I'm torn because I don't really think that Javadoc should make any promises, because we are really doing implementation-defined behavior here. But then again, if we're doing implementation defined behavior, why is it public? Anyway, something like

```
/**
 *  This method is "unsafe" in the Deephaven context because it does not honor the Deephaven canonical
 *  ordering of NULL_BYTE.
 */
```

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 9]
```diff
@@ -0,0 +1,275 @@
...
+                high = mid;
+            } else {
+                return mid;
+            }
+        }
+        return -(low + 1);
+    }
+
+    private static int binarySearchFirst(float[] a, int fromIndexInclusive, int toIndexExclusive, float key,
+            int keyBits) {
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java]: I don't think the `keyBits` argument needs to exist. I think it might be better to calculate it here as

```
final int keyBits = Float.floatToIntBits(key);
```

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 10]
```diff
@@ -0,0 +1,275 @@
...
+        int high = toIndexExclusive - 1;
+        while (low <= high) {
+            final int mid = (low + high) >>> 1;
+            final float midVal = a[mid];
+            if (midVal < key) {
+                low = mid + 1;
+            } else if (midVal > key) {
+                high = mid - 1;
+            } else {
+                final int midBits = Float.floatToIntBits(midVal);
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java]: I spent way too much time inside this `else` clause convincing myself it was correct. Then I noticed that Java's `Arrays.binarySearch` has the same logic and I can't argue with that. However I think I would still reorder it and heavily comment it so the next person can have more confidence in it. This is my draft:

```
                // If we get here, !(midVal < key) && !(midVal > key). We are in one of six cases:
                // 1. Both midVal and key are NaN. Therefore they are considered equal, and midBits == keyBits
                // 2. Neither midVal nor key are NaN but their bitwise representation is the same. Therefore
                //    they are considered equal and midBits == keyBits.
                // 3. midVal is not NaN and key is NaN. Therefore mid is less than key, and midBits < keyBits
                // 4. midVal is NaN and key is not NaN. Therefore mid is greater than key, and midBits > keyBits
                // 5. midVal is -0.0 and key is +0.0. Therefore mid is less than key, and midBits < keyBits
                // 6. midVal is +0.0 and key is -0.0. Therefore mid is greater than key, and midBits > keyBits
                if (midBits == keyBits) {
                    // Cases 1 and 2: They are actually equal, so either return or keep searching for the first instance.
                    if (low != mid) {
                        // This is where we differ from Arrays.binarySearch;
                        // we continue searching downwards to find the first instance.
                        high = mid;
                    } else {
                        return mid;
                    }
                } else if (midBits < keyBits) {
                    // cases 3 and 5.
                    low = mid + 1;
                } else {
                    // cases 4 and 6.
                    high = mid - 1;
                }
```

**Review by kosak — COMMENTED** [review]
I've only looked at one file so far, but I thought I would share my comments about WritableChunkUtils.java so you can take a look.

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunk.java [hunk 11]
```diff
@@ -92,16 +92,14 @@ default int capacity() {
     int internalCapacity(long password);
 
     /**
-     * Sort this chunk in-place using Java's primitive defined ordering.
-     * <p>
-     * Of note is that nulls or NaNs are not sorted according to Deephaven ordering rules.
+     * Sort this chunk in-place using Deephaven defined ordering where {@code null} is lt all other values and
+     * Double.NaN / Float.NaN are gt all other values.
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunk.java]: 1. De-hyphenate: in place
2. Hyphenate: Deephaven-defined
3. where {@code null} (for reference types) or QueryConstants.NULL_XXX (for value types)
4. lt -> less than
5. gt -> greater than

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunk.java [hunk 12]
```diff
@@ -92,16 +92,14 @@ default int capacity() {
...
      */
     void sort();
 
     /**
-     * Sort this chunk in-place using Java's primitive defined ordering.
-     * <p>
-     * Of note is that nulls or NaNs are not sorted according to Deephaven ordering rules.
+     * Sort this chunk in-place using Deephaven defined ordering where {@code null} is lt all other values and
+     * Double.NaN / Float.NaN are gt all other values.
```
Comment (kosak) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunk.java]: Same as above

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 13]
```diff
@@ -0,0 +1,267 @@
...
+        Arrays.sort(data, fromIndexInclusive, toIndexExclusive);
+    }
+
+    // These assertions reflect sorting assumptions made by this code. If these assertions
+    // change, this code will need to be carefully audited.
+    static {
+        assert(NULL_CHAR == Character.MAX_VALUE);
+        assert(NULL_FLOAT == -Float.MAX_VALUE);
+        assert(Float.NEGATIVE_INFINITY < NULL_FLOAT);
+    }
```
Comment (devinrsmith) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java]: Better to capture these as runnable unit tests IMO.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java (hunk 1 above)
Comment (devinrsmith) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java]: This would be better as `DoubleComparisons.eq(lhs, rhs)`, yeah?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/FloatSegmentedSortedMultiset.java [hunk 14]
```diff
@@ -1341,7 +1341,7 @@ private static boolean geq(float lhs, float rhs) {
 
     private static boolean eq(float lhs, float rhs) {
         // region equality function
-        return lhs == rhs;
+        return doComparison(lhs, rhs) == 0;
```
Comment (devinrsmith) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/FloatSegmentedSortedMultiset.java]: This would be better as `FloatComparison.eq(lhs, rhs)`, yeah?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java (hunk 1 above)
Comment (devinrsmith) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java]: Also - I think all of the `gt`, `lt`, etc, would be better replaced by the specific method in `DoubleComparisons`.

File: replication/static/src/main/java/io/deephaven/replicators/TupleCodeGenerator.java [hunk 15]
```diff
@@ -67,14 +67,14 @@ public class TupleCodeGenerator {
...
+           LONG(   "Long",    long.class, LHS + " == " + RHS                                ,      "Long.hashCode(" + VAL + ")", "LongComparisons.compare("   + LHS + ", " + RHS + ")", OUT + ".writeLong("   + VAL + ')', IN + ".readLong()"  , "io.deephaven.util.compare.LongComparisons"                       ),
+          FLOAT(  "Float",   float.class, "FloatComparisons.eq(" + LHS + ", " + RHS + ")"   ,     "Float.hashCode(" + VAL + ")", "FloatComparisons.compare("  + LHS + ", " + RHS + ")", OUT + ".writeFloat("  + VAL + ')', IN + ".readFloat()" , "io.deephaven.util.compare.FloatComparisons"                      ),
+         DOUBLE( "Double",  double.class, "DoubleComparisons.eq(" + LHS + ", " + RHS + ")"  ,    "Double.hashCode(" + VAL + ")", "DoubleComparisons.compare(" + LHS + ", " + RHS + ")", OUT + ".writeDouble(" + VAL + ')', IN + ".readDouble()", "io.deephaven.util.compare.DoubleComparisons"                     ),
```
Comment (devinrsmith) [inline replication/static/src/main/java/io/deephaven/replicators/TupleCodeGenerator.java]: I think this also brings up the point that the hashcode is incorrect too; it should be using FloatComparisons.hashCode / DoubleComparisons.hashCode. You can demonstrate the inconsistent eq / hashcode behavior w/ a tuple that contains 0.0 and another that contains -0.0.

Comment (devinrsmith) [reply replication/static/src/main/java/io/deephaven/replicators/TupleCodeGenerator.java]: Honestly, I think it would be better if all this generated code delegated to the `XComparisons` code even though for a lot of the primitives it's just a shim... it gives us clear semantics, and allows us to consider better pluggable logic for this stuff in the future. That said, I'm "ok" just fixing the floating point stuff for scope.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java (hunk 1 above)
Comment (lbooker42) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java]: Good point, I assume this indirection was intended to make replication simpler. But we have comparison classes for each datatype so I'll be more explicit.

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 16]
```diff
@@ -0,0 +1,212 @@
...
+package io.deephaven.chunk;
+
+import java.util.Arrays;
+import java.util.Comparator;
+
+import static io.deephaven.util.QueryConstants.NULL_CHAR;
+import static io.deephaven.util.QueryConstants.NULL_DOUBLE;
+import static io.deephaven.util.QueryConstants.NULL_FLOAT;
+
+final class WritableChunkUtils {
```
Comment (cpwright) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java:13]: Do we have test complete test coverage for this primitive?

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java [hunk 17]
```diff
@@ -0,0 +1,212 @@
...
+        return begin;
+    }
+
+    /**
+     * @return the smallest i in [begin, end) where a[i] > key, or end if no such element
+     */
+    private static int upperBound(double[] a, int begin, int end, double key) {
+        while (begin < end) {
+            final int mid = (begin + end) >>> 1;
+            if (Double.compare(a[mid], key) <= 0) {
```
Comment (cpwright) [inline engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java:208]: Seems like we would have -0 and 0 problems here.

File: engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java [hunk 18]
```diff
@@ -4063,6 +4064,25 @@ public void testArrayKeys() {
...
+
+        final ExecutionContext executionContext = ExecutionContext.makeExecutionContext(true);
+        ThreadPoolExecutor executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(1);
+        executor.submit(() -> {
+            try (final SafeCloseable ignored = executionContext.open()) {
+                // This might trigger an infinite loop in DoubleSegmentedSortedMultiSet
+                return merged.aggBy(AggCountDistinct(true, "CountDistinctWithNulls=X"));
+            }
+        }).get(10, TimeUnit.SECONDS);
+    }
```
Comment (cpwright) [inline engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java:4091]: there should be some expectation as to a correct result, not just hanging

File: engine/table/src/test/java/io/deephaven/engine/table/impl/by/TestSortedFirstOrLastByFactory.java [hunk 19]
```diff
@@ -54,11 +51,14 @@ public void testSortedFirstOrLastBy() {
...
+
+        final String[] colNames = new String[] {"Sym", "intCol", "doubleCol", "Indices"};
+
         final QueryTable queryTable = getTable(size, random, columnInfo = initColumnInfos(
                 colNames,
-                new SetGenerator<>("a", "b", "c", "d"),
+                new SetGenerator<>("a", "b", "c", "d", "e", "f"),
                 new IntGenerator(10, 100, 0.1),
-                new SetGenerator<>(10.1, 20.1, 30.1),
+                new SetGenerator<>(10.1, 20.1, 30.1, NULL_DOUBLE, Double.NaN),
```
Comment (cpwright) [inline engine/table/src/test/java/io/deephaven/engine/table/impl/by/TestSortedFirstOrLastByFactory.java:61]: I think we should be worried that we are going to end up with too many things poisoned given that 20% of rows will be NaN.

Perhaps add some tests that remove the NaN or have a separate column that excludes the NaN.

File: replication/static/src/main/java/io/deephaven/replicators/TupleCodeGenerator.java [hunk 20]
```diff
@@ -67,14 +67,14 @@ public class TupleCodeGenerator {
...
-           CHAR(   "Char",    char.class, LHS + " == " + RHS                              , "Character.hashCode(" + VAL + ")", "CharComparisons.compare("   + LHS + ", " + RHS + ")", OUT + ".writeChar("   + VAL + ')', IN + ".readChar()"  , "io.deephaven.util.compare.CharComparisons"                       ),
-         OBJECT( "Object",  Object.class, "ObjectComparisons.eq(" + LHS + ", " + RHS + ")",   "Objects.hashCode(" + VAL + ")", "ObjectComparisons.compare(" + LHS + ", " + RHS + ")", OUT + ".writeObject(" + VAL + ')', IN + ".readObject()", "io.deephaven.util.compare.ObjectComparisons", "java.util.Objects"),
+           BYTE(   "Byte",    byte.class,   "ByteComparisons.eq(" + LHS + ", " + RHS + ")",   "ByteComparisons.hashCode(" + VAL + ")", "ByteComparisons.compare("   + LHS + ", " + RHS + ")", OUT + ".writeByte("   + VAL + ')', IN + ".readByte()"  , "io.deephaven.util.compare.ByteComparisons"                       ),
```
Comment (cpwright) [inline replication/static/src/main/java/io/deephaven/replicators/TupleCodeGenerator.java]: The arguments are probably not necessary anymore given that you're using XComparisons universally. (Lightly held opinion).

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java (hunk 16 above)
Comment (lbooker42) [reply engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java:13]: Updated tests, reaching 100% lines and functions tested.

File: engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java (hunk 17 above)
Comment (lbooker42) [reply engine/chunk/src/main/java/io/deephaven/chunk/WritableChunkUtils.java:208]: Updated docs to clarify this search is valid when `a` is a result of `Arrays.sort()` (which matches `Double.compare()` semantics))

File: engine/table/src/test/java/io/deephaven/engine/table/impl/by/TestSortedFirstOrLastByFactory.java (hunk 19 above)
Comment (lbooker42) [reply engine/table/src/test/java/io/deephaven/engine/table/impl/by/TestSortedFirstOrLastByFactory.java:61]: SortedFirst/LastBy doesn't have poisoning effects with NaN. NaN is treated like a normal (but highest) value when sorted.

File: replication/static/src/main/java/io/deephaven/replicators/TupleCodeGenerator.java (hunk 20 above)
Comment (lbooker42) [reply replication/static/src/main/java/io/deephaven/replicators/TupleCodeGenerator.java]: I simplified this considerably.
