### PR TITLE
Give table update listeners short version of propagation error

### LINKED ISSUE #1068: Exported Table Update Listener should not log Table Failures
When a table fails to update, the LTM logs:
```
EFAULT.refreshThread | .d.v.InstrumentedListener | Uncaught exception for entry= Update([X, Y]), added.size()=1, modified.size()=0, removed.size()=0, shifted.size()=0, modifiedColumnSet={EMPTY}:
```

But so does the ExportedTableUpdateListener; and that's unnecessary:
```
EFAULT.refreshThread | portedTableUpdateListener | Internal Error '82eec0c0-3744-4b49-ba97-3978c1d0adea' io.deephaven.db.v2.select.FormulaEvaluationException: In formula: Y = X.substring(0)
```

Testable Query:
```groovy
class XX {
  int cnt = 0
  String run() {
    if (++cnt == 10) throw new RuntimeException() 
    return "" + cnt
  }
}
x = new XX();
t = timeTable("00:00:01").update("I = x.run()")
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #1068

### CODE REVIEW

File: grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java [hunk 1]
```diff
@@ -163,7 +163,7 @@ private synchronized void sendUpdateMessage(final Ticket ticket, final long size
                 .setExportId(ticket).setSize(size);
 
         if (error != null) {
-            update.setUpdateFailureMessage(GrpcUtil.securelyWrapError(log, error).getMessage());
```
Comment (rcaudy) [inline grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java:166]: We don't want to include the exception's message, here?

**Review by rcaudy — APPROVED** [review]

**Review by rcaudy — APPROVED** [review]

**Review by devinrsmith — APPROVED** [review]

**Review by rcaudy — APPROVED** [review]
