### PR TITLE
Small ring chunk source cleanup

### LINKED ISSUE #5498: Ring table nested array mis-match
During development of #5497, I ran into a case where the server was unable to ring the resulting blink table.

Screenshot from 2024-05-16 13-31-00

Here, we see the issue is that the `src[1]` is of type `Object[]` and fails to copy into the `data` destination (where the elements are of type `double[][]`). Only `src[1]` is uncopyable; `src[0]` works b/c it's null, and `src[2]` works because it's the correct nested primitive type.

```
2024-05-16T20:31:09.801Z | aph-updateExecutor-3 | ERROR | .AsyncClientErrorNotifier | Error in table update: java.lang.ArrayStoreException: [Ljava.lang.Object;
        at io.deephaven.chunk.WritableObjectChunk.copyFromTypedArray(WritableObjectChunk.java:165)
        at io.deephaven.chunk.WritableObjectChunk.copyFromTypedChunk(WritableObjectChunk.java:145)
        at io.deephaven.chunk.WritableObjectChunk.copyFromChunk(WritableObjectChunk.java:141)
        at io.deephaven.engine.table.impl.sources.chunkcolumnsource.ObjectChunkColumnSource.lambda$fillChunk$0(ObjectChunkColumnSource.java:123)
        at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeyRanges$1(RowSequence.java:182)
        at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKeyRange(SingleRangeMixin.java:25)
        at io.deephaven.engine.rowset.RowSequence.forAllRowKeyRanges(RowSequence.java:181)
        at io.deephaven.engine.table.impl.sources.chunkcolumnsource.ObjectChunkColumnSource.fillChunk(ObjectChunkColumnSource.java:111)
        at io.deephaven.engine.table.impl.sources.SwitchColumnSource.fillChunk(SwitchColumnSource.java:128)
        at io.deephaven.engine.table.impl.sources.ring.AbstractRingChunkSource.fillRingFromMiddle(AbstractRingChunkSource.java:243)
        at io.deephaven.engine.table.impl.sources.ring.AbstractRingChunkSource.append(AbstractRingChunkSource.java:216)
        at io.deephaven.engine.table.impl.sources.ring.AbstractRingChunkSource.appendBounded(AbstractRingChunkSource.java:175)
        at io.deephaven.engine.table.impl.sources.ring.RingColumnSource.appendBounded(RingColumnSource.java:128)
        at io.deephaven.engine.table.impl.sources.ring.AddsToRingsListener.append(AddsToRingsListener.java:165)
        at io.deephaven.engine.table.impl.sources.ring.AddsToRingsListener.onUpdate(AddsToRingsListener.java:157)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:334)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:316)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:711)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:836)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### PR DESCRIPTION
**Pull request by devinrsmith**
This was originally explored as a fix for #5498; ultimately, it was an upstream data issue that was solved in #5503. Along the way though, it was noted that ring chunk sources were 1) using reflection in places they didn't need to, and 2) using specifically typed arrays for generic types as opposed to other object chunks which use `Object[]` at the top layer. In the latest iteration of this, the construction reflection was removed (there is a new getLength check); but I'm apt to keep the more specifically typed arrays unless we know they are causing other issues. At a minimum, the specifically typed arrays helped us notice and fix #5503.

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AbstractRingChunkSource.java [hunk 1]
```diff
@@ -73,7 +73,13 @@ public AbstractRingChunkSource(@NotNull Class<T> type, int capacity) {
         }
         this.capacity = capacity;
         // noinspection unchecked
-        ring = (ARRAY) Array.newInstance(type, capacity);
+        ring = type.isArray()
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AbstractRingChunkSource.java:76]: I think the wider issue here is that this code is using reflection to determine the array type instead of using inheritance (and using `Object[]` to hold non-primitive values).

**Comment by devinrsmith** [comment]
I guess this use of the type system, while (ab)using `Object[0]`, may be more generously described as being able to cast to super types for "free" (for read only use cases), and more specific types for "free" (for writing use cases), although those have there own risks as well.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AbstractRingChunkSource.java (hunk 1 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AbstractRingChunkSource.java:76]: Are you certain you shouldn't be using `Object[]` in more cases?

Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AbstractRingChunkSource.java:76]: Never mind, we figured out that we were dealing with weird upstream data.

File: engine/chunk/src/main/java/io/deephaven/chunk/Chunk.java [hunk 2]
```diff
@@ -17,7 +17,7 @@ public interface Chunk<ATTR extends Any> {
     /**
      * The threshold at which we should use System.arrayCopy rather than our own copy
      */
-    int SYSTEM_ARRAYCOPY_THRESHOLD = 16;
+    int SYSTEM_ARRAYCOPY_THRESHOLD = 0;
```
Comment (rcaudy) [inline engine/chunk/src/main/java/io/deephaven/chunk/Chunk.java]: Why?

**Review by rcaudy — APPROVED** [review]
