### PR TITLE
autocomplete: fix recurision resolving variables that reference each other

### LINKED ISSUE #2528: `ChunkerCompleter.resolveScopeType` line 1030 infinite recursion
`ChunkerCompleter.resolveScopeType` appears to go into infinite recursion.

image

Triggering code is:

```python
from deephaven import time_table

t = time_table("00:00:01").update(["X=i", "Y=i%2"])

p = t.partition_by("Y")

print(p.constituent_changes_permitted)
print(p.constituent_column)
print(p.constituent_table_columns)
print(p.key_columns)

ct = p.constituent_tables


p0 = p.get_constituent([0])

m = p.merge()

px = p.filter(***)
py = p.sort(***)

f = p.filter(***)
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #2528.

### CODE REVIEW

File: open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java [hunk 1]
```diff
@@ -1026,8 +1033,8 @@ private Optional<Class<?>> resolveScopeType(
             // This is pretty hacky, but our only use case here is looking for table loads, so...
             if (assignment.getValue() instanceof IsScope) {
                 final List<IsScope> subscope = ((IsScope) assignment.getValue()).asScopeList();
-                if (!subscope.equals(scope)) {
-                    result = resolveScopeType(request, subscope);
+                if (!alreadyVisited.contains(subscope)) {
```
Comment (JamesXNelson) [inline open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java:1036]: could probably just do `if (alreadyVisited.add(subscope))`, but not really important.

**Review by JamesXNelson — APPROVED** [review]

**Review by JamesXNelson — APPROVED** [review]
