### PR TITLE
Fix thread safety for gRPC websocket transports 

### LINKED ISSUE #4406: MessageDeframer NullPointerException
Found in the [Web UI e2e tests](https://github.com/deephaven/web-client-ui/issues/1466) while running rollup tests. Intermittently occurred causing a brief disconnect, which would cause e2e tests to blip and fail. The cause/NullPointerException details were found by adding extra logging, as there isn't [logging in this particular case](https://github.com/deephaven/deephaven-core/blob/84199c76c835ee0f1b1032c8f4c8b17ab4d15732/grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebsocketStreamImpl.java#L113) to prevent an infinite loop with the logger stream.

```
2023-08-29 14:54:16 2023-08-29T18:54:16.013Z | qtp880533231-33      |  WARN | plexedWebsocketStreamImpl | MJB MultiplexedWebsocketStreamImpl cancel: Status{code=UNKNOWN, description=null, cause=java.lang.NullPointerException: Cannot invoke "io.grpc.internal.CompositeReadableBuffer.readableBytes()" because "this.unprocessed" is null
2023-08-29 14:54:16     at io.grpc.internal.MessageDeframer.readRequiredBytes(MessageDeframer.java:346)
2023-08-29 14:54:16     at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:269)
2023-08-29 14:54:16     at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:178)
2023-08-29 14:54:16     at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
2023-08-29 14:54:16     at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:262)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.inboundDataReceived(AbstractWebsocketStreamImpl.java:25)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.inboundDataReceived(AbstractWebsocketStreamImpl.java:99)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onMessage(MultiplexedWebSocketServerStream.java:219)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.AbstractWebSocketServerStream.lambda$onOpen$0(AbstractWebSocketServerStream.java:115)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.invoke(AbstractDecodedMessageSink.java:61)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.onWholeMessage(DecodedBinaryMessageSink.java:60)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.accept(ByteBufferMessageSink.java:64)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:592)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onBinary(JakartaWebSocketFrameHandler.java:642)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:243)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671)
2023-08-29 14:54:16     at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
2023-08-29 14:54:16     at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1485)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
2023-08-29 14:54:16     at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
2023-08-29 14:54:16     at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:369)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
2023-08-29 14:54:16     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
2023-08-29 14:54:16     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
2023-08-29 14:54:16     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
2023-08-29 14:54:16     at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-29 14:54:16 }
```

### PR DESCRIPTION
**Pull request by niloc132**
Some gRPC operations on `ServerTransportListener` and `TransportState` are specified as only intended to be called from the "transport thread" - prior to this patch, we had incorrectly interpreted this to allow serial operations from the websocket handler in the server. This patch ensures that those operations are additionally serialized against calls from gRPC internals. Among other things, this fixes an issue where messages could be closed while being deframed.

Fixes #4406

### CODE REVIEW

File: grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletAdapter.java [hunk 1]
```diff
@@ -172,8 +172,10 @@ public void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOEx
                 getAuthority(req),
                 logId);
 
-        transportListener.streamCreated(stream, method, headers);
-        stream.transportState().runOnTransportThread(stream.transportState()::onStreamAllocated);
+        stream.transportState().runOnTransportThread(() -> {
+            transportListener.streamCreated(stream, method, headers);
```
Comment (niloc132) [inline grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletAdapter.java:176]: i'm struggling to imagine a case where this would matter to be handled like this, but this is technically more in line with what the javadocs for ServerTransportListener specify.

**Review by nbauernfeind — APPROVED** [review]
