### PR TITLE
A workaround to a JPY issue with long values, fixes #1461

### LINKED ISSUE #1461: [Python] lowerBin() computes incorrect result when used in a query
**Description**

The following python code is supposed to make a table with 2 columns, one containing a date-time and the other containing the date-time floored via the `lowerBin()` method, and print the equivalent result of `lowerBin()` to console.

```
from deephaven.DBTimeUtils import expressionToNanos, convertDateTime, lowerBin
from deephaven.TableTools import newTable, dateTimeCol

nanosBin = expressionToNanos("T15M")
dateTime = convertDateTime("2020-01-01T00:35:00 NY")

source = newTable(
    dateTimeCol("DateTimes", dateTime)
)

result = source.update("DateTimesBinned = lowerBin(DateTimes, nanosBin)")
print(lowerBin(dateTime, nanosBin))
```

However, the print statement and the table result in 2 different results

`2020-01-01T00:30:00.000000000 NY` vs `2020-01-01T00:34:59.016`

Screen Shot 2021-10-18 at 10 57 06 PM

**Steps to reproduce**

Described above

**Expected results**

The output of the print statement for `lowerBin()` should match the column computed by `lowerBin()`.

**Actual results**

The output of the print statement for `lowerBin()` appears correct, while the column computed by `lowerBin()` is not correct.

**Additional details and attachments**

This does not happen in groovy. This may be related to https://github.com/deephaven/deephaven-core/issues/1348

**Versions**
 - Deephaven: latest
 - OS: OSX
 - Browser: Chrome
 - Docker: Docker version 20.10.8, build 3967b7d

### PR DESCRIPTION
**Pull request by jmao-denver**
In JPY, PyObject.getObjectValue() seems always to select Java Integer
for a Python int object  which is not restricted by the number
of bits in Python 3

### CODE REVIEW

**Comment by jmao-denver** [comment]
Not sure if DHE suffers from the same problem

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java [hunk 1]
```diff
@@ -189,7 +189,16 @@ public static Object convert(PyObject pyObject) {
         } else if (pyObject.isCallable()) {
             return wrapCallable(pyObject);
         } else if (pyObject.isConvertible()) {
-            return pyObject.getObjectValue();
+            Object objValue = pyObject.getObjectValue();
+            // workaround a JPY issue with determining the correct Java type a Python 'int' should be
+            // mapped to (int or long) without causing an implicit overflow
+            if (objValue instanceof  Integer || objValue.getClass() == int.class) {
+                long longValue;
+                if ((longValue = pyObject.getLongValue()) > (int) objValue) {
```
Comment (devinrsmith) [inline engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:197]: I think `!=` is more appropriate?

Note: we'll still have issues w/ python "ints" that really should be BigInteger (> 64 bits)

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java [hunk 2]
```diff
@@ -189,7 +189,16 @@ public static Object convert(PyObject pyObject) {
         } else if (pyObject.isCallable()) {
             return wrapCallable(pyObject);
         } else if (pyObject.isConvertible()) {
-            return pyObject.getObjectValue();
+            Object objValue = pyObject.getObjectValue();
+            // workaround a JPY issue with determining the correct Java type a Python 'int' should be
+            // mapped to (int or long) without causing an implicit overflow
+            if (objValue instanceof  Integer || objValue.getClass() == int.class) {
```
Comment (devinrsmith) [inline engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: Do we think the second case will ever trigger? I would expect that the instanceof is sufficient.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 1 above)
Comment (jmao-denver) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:197]: != is definitely the correct way, covering both negative and positive values; and yes, we need to address the BigDecimal translation in the future.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 2 above)
Comment (jmao-denver) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: I am not 100% sure, and that's why I threw it in there just in case there are some edges cases that are not obvious to us now

**Comment by cpwright** [comment]
Should we simply look further up the chain at JPy and fix that.  I expect the problem relates to these lines in 
JType_ConvertJavaToPythonObject.

    } else if (JPy_IS_CLONG(pyArg) && (type == JPy_JObject || ((*jenv)->IsAssignableFrom(jenv, JPy_Integer_JClass, type->classRef)))) {
        return JType_CreateJavaIntegerObject(jenv, type, pyArg, objectRef);
    } else if (JPy_IS_CLONG(pyArg) && (type == JPy_JObject || ((*jenv)->IsAssignableFrom(jenv, JPy_Long_JClass, type->classRef)))) {
        return JType_CreateJavaLongObject(jenv, type, pyArg, objectRef);

**Comment by devinrsmith** [comment]
> Should we simply look further up the chain at JPy and fix that. I expect the problem relates to these lines in JType_ConvertJavaToPythonObject.
> 
> ```
> } else if (JPy_IS_CLONG(pyArg) && (type == JPy_JObject || ((*jenv)->IsAssignableFrom(jenv, JPy_Integer_JClass, type->classRef)))) {
>     return JType_CreateJavaIntegerObject(jenv, type, pyArg, objectRef);
> } else if (JPy_IS_CLONG(pyArg) && (type == JPy_JObject || ((*jenv)->IsAssignableFrom(jenv, JPy_Long_JClass, type->classRef)))) {
>     return JType_CreateJavaLongObject(jenv, type, pyArg, objectRef);
> ```

I made this same comment here https://github.com/deephaven/deephaven-core/issues/1461#issuecomment-1015624546. Ultimately, I think the implicit type conversion layer of python objects to to java objects needs to be examined, and we may want to provide the (java) caller with better hooks on how to handle the different cases.

These types of problems may also be better solved by pushing application logic further down into python instead of trying to be as general as we can w/ `PythonScope`. I've made some similar changes for FetchObject (landing soon) where script session changes are handled with .py logic instead of numerous JNI boundary crossings.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 2 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: Why don't we use `PyObject.isLong()` or `PyObject.isInt()`?

Comment (devinrsmith) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: isLong / isInt are the same (python 3), but it won't actually tell you how many bits are in the python int.

Comment (devinrsmith) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: An alternative would be to do `PyObject.isLong()`, `PyObject.getLongValue()`, and downcast back to `int` if appropriate (or, choose to have `convert` never return an int and always return a long)

**Comment by jmao-denver** [comment]
@devinrsmith @cpwright 

I think you meant JType_ConvertPythonToJavaObject (not JType_ConvertJavaToPythonObject).  

The straightforward changes I could see are:

1. to switch the order of the two blocks (or simply remove the one check assignability of Integer, which amounts to the alternative Devin mentioned about, and with that, potentially double the memory used for a column unnecessarily

2. to examine the actual value and select the appropriate Java type, which is almost the same (hacky) as the solution in this PR but with one fewer JNI/Python boundary crossing

I am not strongly inclined towards  any one of the 3 solutions, but this PR is still my favorite simply because it is higher level and less likely to break other things (?)

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java [hunk 3]
```diff
@@ -189,7 +189,16 @@ public static Object convert(PyObject pyObject) {
         } else if (pyObject.isCallable()) {
             return wrapCallable(pyObject);
         } else if (pyObject.isConvertible()) {
-            return pyObject.getObjectValue();
+            Object objValue = pyObject.getObjectValue();
+            // workaround a JPY issue with determining the correct Java type a Python 'int' should be
+            // mapped to (int or long) without causing an implicit overflow
+            if (objValue instanceof Integer || objValue.getClass() == int.class) {
```
Comment (devinrsmith) [inline engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: I'm not a fan of `.getClass()` check here, I don't think it adds anything of value.

Happy to approve without.

I think this convert logic could be pushed all down into python (and save us numerous JNI calls), potentially pending https://github.com/deephaven/deephaven-core/issues/1775. Obviously not part of this simple fix, but something we may want to do in the future. Going to add a note to the linked issue.

**Review by devinrsmith — CHANGES_REQUESTED** [review]

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 2 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java]: I like that.

Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java]: @cpwright do you like the above? Preference for always `long`, or `int` if it fits?

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 3 above)
Comment (cpwright) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: objValue.getClass() being int.class seems impossible; as you would not have a class object.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 2 above)
Comment (cpwright) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java]: I would suggest int if it fits.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 3 above)
Comment (jmao-denver) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:195]: thanks, removed!

**Review by devinrsmith — DISMISSED** [review]
I'm OK with this approach. Based on @rcaudy feedback thought, he may prefer the `pyObject.isLong()`, `pyObject.getLongValue()`, and seeing if it fits into int. It's an extra case, but it fits the pattern established here.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java [hunk 4]
```diff
@@ -189,7 +189,16 @@ public static Object convert(PyObject pyObject) {
         } else if (pyObject.isCallable()) {
             return wrapCallable(pyObject);
         } else if (pyObject.isConvertible()) {
-            return pyObject.getObjectValue();
+            Object objValue = pyObject.getObjectValue();
+            // workaround a JPY issue with determining the correct Java type a Python 'int' should be
+            // mapped to (int or long) without causing an implicit overflow
+            if (objValue instanceof Integer) {
+                long longValue;
+                if ((longValue = pyObject.getLongValue()) != (int) objValue) {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:197]: Please add a unit test for the fix.

**Review by rcaudy — DISMISSED** [review]

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java (hunk 4 above)
Comment (jmao-denver) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java:197]: done

**Review by devinrsmith — APPROVED** [review]
