### PR TITLE
Disable idle stream timeout, allow it to be configured downstream

### LINKED ISSUE #3733: URI / java barrage subscription unexpectedly closed after 30 seconds
A user reported that a URI subscription was being cancelled. This can be reproduced locally with:

server
```python
from deephaven import time_table

t60 = time_table("00:01:00")
```

client
```python
from deephaven import uri

# replace with appropriate URI
t60 = uri.resolve("dh://<server>/scope/t60")
```

After 30 seconds of inactivity, the client subscription gets closed with the error

```
13:42:48.367 ERROR c-default-executor-0 | i.BarrageSubscriptionImpl | Barrage/ClientSubscription/Table:export/1/1534798306/: Error detected in subscription: io.grpc.StatusRuntimeException: CANCELLED: client cancelled
        at io.grpc.Status.asRuntimeException(Status.java:539)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.deephaven.client.impl.BearerHandler$BearerListener.onClose(BearerHandler.java:121)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
13:42:48.368 ERROR c-default-executor-0 | i.BarrageSubscriptionImpl | Barrage/ClientSubscription/Table:export/1/1534798306/: unexpectedly closed by other host
```

This behavior does not happen via JS / web UI subscriptions, nor with faster ticking tables (for example, `time_table("00:00:01")`).

Upon further debugging, it was found that the jetty http2 idle timeout default of 30 seconds was causing this issue:

```
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:288)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.lambda$onCancel$2(SessionServiceGrpcImpl.java:362)
        at io.deephaven.server.session.SessionServiceGrpcImpl.rpcWrapper(SessionServiceGrpcImpl.java:393)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.onCancel(SessionServiceGrpcImpl.java:362)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:378)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:365)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:923)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:930)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:888)
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:339)
        at io.grpc.internal.AbstractServerStream$TransportState.access$100(AbstractServerStream.java:184)
        at io.grpc.internal.AbstractServerStream$TransportState$1.run(AbstractServerStream.java:289)
        at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:241)
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:198)
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:293)
        at io.grpc.servlet.jakarta.ServletAdapter$GrpcReadListener.lambda$onError$2(ServletAdapter.java:347)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
        at io.grpc.servlet.jakarta.ServletServerStream$ServletTransportState.runOnTransportThread(ServletServerStream.java:144)
        at io.grpc.servlet.jakarta.ServletAdapter$GrpcReadListener.onError(ServletAdapter.java:345)
        at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:403)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1448)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:596)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
        at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.handleWithContext(HttpChannelOverHTTP2.java:688)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

A̶s̶ ̶a̶ ̶t̶e̶m̶p̶o̶r̶a̶r̶y̶ ̶w̶o̶r̶k̶a̶r̶o̶u̶n̶d̶,̶ ̶t̶h̶e̶ ̶u̶s̶e̶r̶ ̶c̶a̶n̶ ̶s̶e̶t̶ ̶t̶h̶e̶ ̶c̶o̶n̶f̶i̶g̶u̶r̶a̶t̶i̶o̶n̶ ̶p̶r̶o̶p̶e̶r̶t̶y̶ ̶`̶h̶t̶t̶p̶.̶s̶e̶s̶s̶i̶o̶n̶.̶d̶u̶r̶a̶t̶i̶o̶n̶M̶s̶`̶ ̶t̶o̶ ̶3̶0̶0̶0̶0̶ ̶(̶3̶0̶ ̶s̶e̶c̶o̶n̶d̶s̶ ̶i̶n̶s̶t̶e̶a̶d̶ ̶o̶f̶ ̶d̶e̶f̶a̶u̶l̶t̶ ̶o̶f̶ ̶5̶ ̶m̶i̶n̶u̶t̶e̶s̶)̶.̶

This ^ does *NOT* work.

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #3733

### CODE REVIEW

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java [hunk 1]
```diff
@@ -128,6 +134,15 @@ public int port() {
     @Nullable
     public abstract Boolean http1();
 
+    public abstract OptionalInt http2StreamIdleTimeout();
+
+    /**
+     *
+     */
+    public int http2StreamIdleTimeoutOrDefault() {
+        return http2StreamIdleTimeout().orElse(0);
```
Comment (niloc132) [inline server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:143]: Need to fix the Javadoc here. The default is defined here, but I intend to also define it in the default .prop file:
 * Defining it here prevents downstream breakage in applications built on top of DHC, while still leaving a reasonable default, without changing any Java or properties files
 * Defining it in the .prop file allows it to be passed to a client if so configured (I don't intend to enable that by default at this time), so that in theory if a deployment sets a concrete value here, clients can be informed at what time their streams will end if they've had no traffic.

Ideally we would solve this config situation differently, but I think this is a good compromise?

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java [hunk 2]
```diff
@@ -128,6 +134,15 @@ public int port() {
     @Nullable
     public abstract Boolean http1();
 
+    public abstract OptionalInt http2StreamIdleTimeout();
```
Comment (devinrsmith) [inline server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:137]: Can we make this an `Optional<Duration>` instead? (I was going to suggest OptionalLong to match `#setStreamIdleTimeout(long)`, but think Duration is better.)

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java (hunk 1 above)
Comment (devinrsmith) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:143]: Does 0 explicitly mean "don't ever idle timeout"?

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java [hunk 3]
```diff
@@ -26,6 +27,7 @@ public abstract class JettyConfig implements ServerConfig {
     public static final int DEFAULT_PLAINTEXT_PORT = 10000;
     public static final String HTTP_WEBSOCKETS = "http.websockets";
     public static final String HTTP_HTTP1 = "http.http1";
+    public static final String HTTP_STREAM_TIMEOUT = "http2.stream.idleTimeout";
```
Comment (devinrsmith) [inline server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:30]: I think we should call this `http2.stream.idleTimeoutMillis`, or leave as-is and expect parsing to be done via `java.time.Duration#parse`

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java (hunk 2 above)
Comment (devinrsmith) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:137]: We can also have a `@Check` annotation to ensure the value makes sense (ie, I'm assuming negative timeouts should not be allowed.)

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java (hunk 3 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:30]: I think I like Duration strings rather than big ints, but I'm hesitant to change this since we are pretty uniformly millis for other configs at this time.

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java (hunk 1 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:143]: Any non-positive number is a legal value, and interpreted as "no timeout". Salient bit of Jetty:
```
        long streamIdleTimeout = getStreamIdleTimeout();
        if (streamIdleTimeout > 0)
            session.setStreamIdleTimeout(streamIdleTimeout);
            ```

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java (hunk 2 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:137]: Technically negative values are allowed.

**Comment by devinrsmith** [comment]
Afaict, this PR does not fix the issue for me. Looking at the code, it seems that `org.eclipse.jetty.http2.HTTP2Session#setStreamIdleTimeout` may essentially be a no-op w/ 0, or supplanted by other means of configuring it. (It's likely that it's an oversight from jetty embedded configurability, or we are trying to configuring jetty incorrectly.)

**Comment by devinrsmith** [comment]
Note: setting `org.eclipse.jetty.http2.HTTP2Session#setStreamIdleTimeout` to > 0 seems to work, in the sense that it changes the 30s timeout we are seeing; it's just that 0 doesn't take.

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java (hunk 1 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:143]: Thanks for clearing up that I was misreading this. I've updated the patch now to directly set our preferred timeout directly on each Http2 connection/session, rather than attempt to do it globally. I'll follow up with a bug report slash feature request to Jetty to see if this could be easier to use?

Comment (devinrsmith) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:143]: Great.

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java (hunk 2 above)
Comment (niloc132) [reply server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:137]: I'd still vote no, unless we have a consumer that takes Duration (for example, move to ServerConfig and pass to a matching method there to use it in netty... which doesnt exist, and if it did, it would be long+TimeUnit).

Otherwise we're just building up extra checks to turn a number (as is our convention in every other timeout/duration) into an object, then right back into a number again.

Following jetty (and ServerBuilder), I will change this to a long, and add a `Millis` suffix to the name.

File: server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java [hunk 4]
```diff
@@ -104,6 +106,9 @@ public static Builder buildFromConfig(Configuration config) {
         if (httpHttp1 != null) {
             builder.http1(Boolean.parseBoolean(httpHttp1));
         }
+        if (h2StreamIdleTimeout != null) {
+            builder.http2StreamIdleTimeout(Integer.parseInt(h2StreamIdleTimeout));
```
Comment (devinrsmith) [inline server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java:110]: `Long.parseLong`?

**Review by devinrsmith — CHANGES_REQUESTED** [review]

**Review by nbauernfeind — COMMENTED** [review]
No additional comments from me.

**Review by devinrsmith — APPROVED** [review]
