### PR TITLE
Correctly check Join result sizes in Go unit tests

### LINKED ISSUE #3490: Go client unit test failures in CI
We had failures reported on Sunday, March 5 and Monday, March 6's CI runs:

* https://github.com/deephaven/deephaven-core/actions/runs/4334668409/jobs/7568712072
* https://scans.gradle.com/s/ggv7pf7ctrjhe/console-log?task=:go:testGoClient
```
  === RUN   TestCrossJoin
      tablehandle_test.go:353: resultRec1 was too large
  --- FAIL: TestCrossJoin (0.06s)
```

* https://github.com/deephaven/deephaven-core/actions/runs/4340451456/jobs/7578994817
* https://scans.gradle.com/s/jns5nkasva3ho/console-log?task=:go:testGoClient
```
  === RUN   TestCrossJoinQuerySerial
      query_test.go:875: result1 was too large
  --- FAIL: TestCrossJoinQuerySerial (0.08s)
```

These seems to be somewhat random. A single failure each night, once for JDK 11, once for JDK 17.

### PR DESCRIPTION
**Pull request by chipkent**
Go unit tests use random input tables.  The checks for join results can be wrong.  Use correct Join checks to resolve the problem.

Resolves #3490

### CODE REVIEW

File: go/pkg/client/tablehandle_test.go [hunk 1]
```diff
@@ -349,13 +353,18 @@ func TestCrossJoin(t *testing.T) {
...
+
+	if resultRec1.NumRows() >= leftRec.NumRows()*rightRec.NumRows() {
+		t.Errorf("resultRec1 is the wrong size: %v >= %v", resultRec1.NumRows(), leftRec.NumRows()*rightRec.NumRows())
 		return
 	}
 
-	if resultRec2.NumRows() <= leftRec.NumRows() {
-		t.Error("resultRec2 was too small")
+	if resultRec2.NumRows() != leftRec.NumRows()*rightRec.NumRows() {
+		t.Errorf("resultRec2 is the wrong size: %v != %v", resultRec2.NumRows(), leftRec.NumRows()*rightRec.NumRows())
```
Comment (kosak) [inline go/pkg/client/tablehandle_test.go:367]: spacing around '*' operator :-)

**Review by kosak — APPROVED** [review]
Approved with spacing nits
