### PR TITLE
Fixes #807 by null checking before invalid unbox during ungroup

### LINKED ISSUE #807: Ungrouping Java arrays with nulls in different elements causes the IDE to crash
**Description**

Attempting to use `ungroup` on a table with Java arrays in the same row that have nulls in different array elements appears to cause DH to crash.

**Steps to reproduce**

The following Python code segment will cause DH to crash:

```python
from deephaven.TableTools import emptyTable
t = emptyTable(1).update("X = new Integer[]{null, 2, 3}", "Z = new Integer[]{4, 5, null}")
t_ungrouped = t.ungroup()
```

**Expected results**

The table `t` looks like this:
```
X         Z
[,2,3]. [4,5,]
```
I would expect the table `t_ungrouped` to have elements in table cells that correspond to the elements in the arrays.

**Actual results**

The following error is generated:

Could not handle barrage update propagation: io.deephaven.UncheckedDeephavenException: Failure to execute snapshot function with unchanged clock.

The stack trace is much longer.  Also, the spinning DH logo comes up and won't stop.  You also can't click "cancel" to stop it.  The only way I've found to remedy this is to reload the webpage altogether.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: OSS
 - OS: OS X Big Sur
 - Browser: Chrome
 - Docker: 20.10.6

### PR DESCRIPTION
**Pull request by nbauernfeind**
- Changed Char and Boolean impls
- Re-ran Replication
- Unit Tested

### CODE REVIEW

File: DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedBooleanArrayColumnSource.java [hunk 1]
```diff
@@ -22,7 +22,7 @@ public Boolean get(long index) {
         long segment = index>>base;
         int offset = (int) (index & ((1<<base) - 1));
         Boolean[] array = innerSource.get(segment);
-        if(offset >= array.length) {
+        if (offset >= array.length || array[offset] == null) {
```
Comment (nbauernfeind) [inline DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedBooleanArrayColumnSource.java:25]: @rcaudy should the boolean column null check the array obtained from innerSource here like in the other impls?

**Review by rcaudy — APPROVED** [review]
