### PR TITLE
BarrageSubscriptionImpl: fix race conditions in subscription logic

### LINKED ISSUE #803: BarrageSourceTable for static data; properly seal and make static
There is a quick and dirty quick-trick to convert BarrageSourceTable to a static table if it is ever "sealed".

What is a better long term solution for uploading what is otherwise static content? We do not need (or want) to enable prev tracking, etc, for these static sources (that are otherwise defined/satisfied over time or incrementally via append-only updates).

### LINKED ISSUE #3300: BarrageTable to allow off-UGP ingestion in some use cases when not published
We want this for `DoPut`, so we can deliver static data without involving the UGP or asking it to hurry up.

While we're at it, we should avoid the slightly-dirty fact that the (thankfully, not published) interim `BarrageTable` starts out refreshing, and enables previous tracking, etc.

### LINKED ISSUE #4594: BarrageSubscription NPE when empty update is received after initial subscription
**Description**

If an empty update is received on a Barrage subscription after the initial subscription has been completed, you get an NPE

**Steps to reproduce**

1. Create a DH instance with the following script code
```groovy
import io.deephaven.engine.util.SortedBy
qq = timeTable("PT1S")
qqWatch = SortedBy.sortedLastBy(qq, "Timestamp")
```

2. In another DH instance, try to subscribe to that table with barrage
```groovy
import io.grpc.netty.NettyChannelBuilder
import io.deephaven.proto.DeephavenChannelImpl
import io.deephaven.client.impl.BarrageSession
import io.deephaven.client.impl.SessionImpl
import io.deephaven.client.impl.SessionImplConfig
import java.util.concurrent.Executors
import org.apache.arrow.memory.RootAllocator
import io.deephaven.qst.table.TicketTable
import io.deephaven.server.uri.BarrageTableResolver

managedChannel = NettyChannelBuilder.forTarget("dh://REMOTE_HOST").build()
dhChannel = new DeephavenChannelImpl(managedChannel)
session = SessionImpl.create(SessionImplConfig.builder()
    .executor(Executors.newScheduledThreadPool(4))
//    .authenticationTypeAndValue(AUTH_DETAILS)
    .channel(dhChannel)
    .build())
barrage = BarrageSession.of(session, new RootAllocator(), managedChannel)

sub = barrage.subscribe(TicketTable.of("s/qqWatch"), BarrageTableResolver.SUB_OPTIONS)
table = sub.entireTable()
```

**Expected results**

You get a functional subscription

**Actual results**

You get an NPE on the first empty table update

**Versions**
 - Deephaven: 0.28.0

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #803
Fixes #3300
Fixes #4594

The rnd4 (1:56pm MT) nightlies: https://github.com/nbauernfeind/deephaven-core/actions/runs/6552157706

### CODE REVIEW

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 1]
```diff
@@ -208,28 +215,33 @@ public synchronized BarrageTable partialTable(RowSet viewport, BitSet columns, b
...
-            // Send the initial subscription:
-            observer.onNext(FlightData.newBuilder()
-                    .setAppMetadata(ByteStringAccess.wrap(makeRequestInternal(
-                            viewport, columns, reverseViewport, options, tableHandle.ticketId().bytes())))
-                    .build());
-            subscribed = true;
+        this.viewport = viewport;
+        this.reverseViewport = reverseViewport;
 
+        if (resultTable.isRefreshing()) {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:239]: We've become convinced that we no longer need this listener. The update source needs to handle this, and can do the callback directly.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 2]
```diff
@@ -307,10 +292,39 @@ public void onUpdate(final TableUpdate upstream) {
...
+
+        boolean isComplete = exceptionWhileCompleting != null;
+
+        // test to see if the viewport matches the requested
+        if (viewport == null && resultTable.getServerViewport() == null) {
+            isComplete = true;
+        } else if (viewport != null && resultTable.getServerViewport() != null
+                && reverseViewport == resultTable.getServerReverseViewport()) {
+            isComplete |= viewport.subsetOf(resultTable.getServerViewport());
+        }
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:309]:
```suggestion
        // @formatter:off
        final boolean isComplete = exceptionWhileCompleting != null
                // Full subscription is completed
                || (viewport == null && resultTable.getServerViewport() == null)
                // Viewport subscription is completed
                || (viewport != null && resultTable.getServerViewport() != null
                    && reverseViewport == resultTable.getServerReverseViewport()
                    && viewport.subsetOf(resultTable.getServerViewport()));
        // @formatter:on
```

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java [hunk 3]
```diff
@@ -217,16 +218,18 @@ public BitSet getServerColumns() {
      * @param onSealFailure pass a callback that gets invoked if the table fails to finish applying updates
      */
     public synchronized void sealTable(final Runnable onSealRunnable, final Runnable onSealFailure) {
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java:220]: Do we still need sealTable? If we're not refreshing, we don't need to use the update graph at all.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java [hunk 4]
```diff
@@ -301,8 +313,11 @@ private synchronized void realRefresh() {
         localPendingUpdates.clear();
 
         if (update != null) {
-            maybeEnablePrevTracking();
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java:304]: We moved this elsewhere. It's easier to verify correctness that way, but we're doing prev tracking for one extra (coalesced) message.

**Review by rcaudy — COMMENTED** [review]
We need some further refactoring, which may simplify matters.

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/GrpcUtil.java [hunk 5]
```diff
@@ -17,7 +17,7 @@ public class GrpcUtil {
     private static final Logger log = LoggerFactory.getLogger(GrpcUtil.class);
 
     public static StatusRuntimeException securelyWrapError(final Logger log, final Throwable err) {
-        return securelyWrapError(log, err, Code.INVALID_ARGUMENT);
+        return securelyWrapError(log, err, Code.ABORTED);
```
[the remark this answers is not in the document]
Comment (nbauernfeind) [reply extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/GrpcUtil.java:20]: Cristian, Colin, and I dug in a bit and agree that ABORTED is an acceptable alternative. Per our discussion, Ryan, it would be better to change this in isolation swapping the status type for other similar cases.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 6]
```diff
@@ -230,24 +230,17 @@ private void handleDisconnect() {
...
+    private synchronized void signalCompletion() {
         if (completedCondition != null) {
             resultTable.getUpdateGraph().requestSignal(completedCondition);
-        } else {
-            synchronized (BarrageSnapshotImpl.this) {
-                BarrageSnapshotImpl.this.notifyAll();
-            }
         }
+
+        BarrageSnapshotImpl.this.notifyAll();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:243]: Threw me off for a minute... you're synchronized on `this`, but acting like you're signaling on a different object.
```suggestion
        notifyAll();
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 7]
```diff
@@ -230,24 +230,17 @@ private void handleDisconnect() {
...
-            exceptionWhileCompleting = new Exception();
-            signalCompletion();
-        });
+        completed = true;
+        signalCompletion();
         cleanup();
     }
 
-    private void signalCompletion() {
+    private synchronized void signalCompletion() {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:238]: Something is fishy in this class. `exceptionWhileCompleting` exists, but is never assigned to non-null.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 8]
```diff
@@ -207,83 +180,37 @@ public BarrageTable partialTable(RowSet viewport, BitSet columns, boolean revers
...
+            }
+            if (subscribed) {
+                throw new UncheckedDeephavenException(
+                        "BarrageSubscription objects cannot be reused.");
+            }
+            subscribed = true;
         }
-        subscribed = true;
+
+        checkForCompletion.expectedViewport = viewport == null ? null : viewport.copy();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:197]: Maybe we want to just construct `checkForCompletion` with these here, instead of in the constructor?

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 9]
```diff
@@ -293,44 +220,56 @@ public void onUpdate(final TableUpdate upstream) {
...
-        if (completed || (resultTable.isRefreshing() && listener == null)) {
-            // we've either already completed or have already scheduled completion
+    private boolean checkIfCompleteOrThrow() {
+        if (exceptionWhileCompleting != null) {
+            throw new UncheckedDeephavenException("Error while handling subscription:", exceptionWhileCompleting);
+        }
+        return completed;
+    }
+
+    public void blockUntilComplete() throws InterruptedException {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:230]: JavaDoc me.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 10]
```diff
@@ -293,44 +220,56 @@ public void onUpdate(final TableUpdate upstream) {
...
-                observer.onCompleted();
-            } else {
-                // no longer need to listen; we're caught up
-                resultTable.removeUpdateListener(listener);
-                listener = null;
-            }
+        // test lock conditions
+        if (updateGraph.sharedLock().isHeldByCurrentThread()) {
+            throw new UnsupportedOperationException(
+                    "Cannot create subscription while holding the UpdateGraph shared lock");
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:238]:
```suggestion
                    "Cannot wait for subscription to complete while holding the UpdateGraph shared lock");
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 11]
```diff
@@ -293,44 +220,56 @@ public void onUpdate(final TableUpdate upstream) {
...
+        }
 
-            signalCompletion();
+        boolean holdingUpdateGraphLock = updateGraph.exclusiveLock().isHeldByCurrentThread();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:241]:
```suggestion
        final boolean holdingUpdateGraphLock = updateGraph.exclusiveLock().isHeldByCurrentThread();
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 12]
```diff
@@ -293,44 +220,56 @@ public void onUpdate(final TableUpdate upstream) {
...
+        if (completedCondition == null && holdingUpdateGraphLock) {
+            completedCondition = resultTable.getUpdateGraph().exclusiveLock().newCondition();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:243]: This needs to happen under the lock on `this`.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 13]
```diff
@@ -387,7 +326,7 @@ public synchronized void close() {
         cleanup();
     }
 
-    private void cleanup() {
+    private synchronized void cleanup() {
         this.connected = false;
         this.tableHandle.close();
         resultTable = null;
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:332]: I think this is dangerous and can lead to NPEs.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 14]
```diff
@@ -387,7 +326,7 @@ public synchronized void close() {
         cleanup();
     }
 
-    private void cleanup() {
+    private synchronized void cleanup() {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:329]: Not obvious to me why we need this to be synchronized, yet.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java [hunk 15]
```diff
@@ -504,4 +443,65 @@ public BarrageMessage parse(final InputStream stream) {
...
+                    || (expectedColumns != null && expectedColumns.equals(serverColumns));
+
+            final boolean isComplete = exceptionWhileCompleting != null
+                    // Full subscription is completed
+                    || (expectedViewport == null && serverViewport == null && correctColumns)
+                    // Viewport subscription is completed
+                    || (expectedViewport != null
+                        && expectedReverseViewport == resultTable.getServerReverseViewport()
+                        && expectedViewport.equals(serverViewport)
+                        && correctColumns);
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:476]:
```suggestion
            final boolean isComplete = exceptionWhileCompleting != null
                    // Full subscription is completed
                    || (correctColumns && expectedViewport == null && serverViewport == null)
                    // Viewport subscription is completed
                    || (correctColumns && expectedViewport != null
                        && expectedReverseViewport == resultTable.getServerReverseViewport()
                        && expectedViewport.equals(serverViewport));
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java (hunk 8 above)
Comment (nbauernfeind) [reply java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java:197]: The reason that I'm constructing in the constructor is because I would like to pass the "container" of callbacks to the BarrageTable.make() call. However, we don't yet know what the user will subscribe to; so we set the expected viewport once we know the actual subscription request.

Alternatively, I could add a method to BarrageTable to set the vpChangedCallback. If you have a strong preference to change to this, let me know. Otherwise, I will leave this comment alone.

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java [hunk 16]
```diff
@@ -69,6 +79,35 @@ BarrageSnapshot snapshot(TableSpec tableSpec, BarrageSnapshotOptions options)
...
 
+    /**
+     * Request a partial snapshot of the data limited by viewport or column set and populate a {@link BarrageTable} with
+     * the data that is received. Allows the viewport to be reversed.
+     *
+     * @param viewport the position-space viewport to use for the subscription
+     * @param columns the columns to include in the subscription
+     * @param reverseViewport Whether to treat {@code posRowSet} as offsets from
+     *        {@link io.deephaven.engine.table.Table#size()} rather than {@code 0}
+     * @param blockUntilComplete block execution until the subscribed table viewport is satisfied
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java:90]:
```suggestion
     * @param blockUntilComplete Whether to block execution until the subscribed table viewport is satisfied
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 17]
```diff
@@ -203,20 +206,58 @@ public synchronized BarrageTable partialTable(RowSet viewport, BitSet columns, b
...
+                    return resultTable;
+                }
+                if (completedCondition == null) {
+                    completedCondition = resultTable.getUpdateGraph().exclusiveLock().newCondition();
+                }
+            }
+        }
+
+        if (holdingUpdateGraphLock) {
+            while (!completed && exceptionWhileCompleting == null) {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:248]:
```suggestion
            while (!checkIfCompletedOrThrow()) {
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 18]
```diff
@@ -203,20 +206,58 @@ public synchronized BarrageTable partialTable(RowSet viewport, BitSet columns, b
...
+                completedCondition.await();
+            }
         } else {
-            throw new UncheckedDeephavenException("Error while handling snapshot:", exceptionWhileCompleting);
+            synchronized (this) {
+                while (!completed && exceptionWhileCompleting == null) {
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:253]:
```suggestion
                while (!checkIfCompletedOrThrow()) {
```

File: java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java [hunk 19]
```diff
@@ -203,20 +206,58 @@ public synchronized BarrageTable partialTable(RowSet viewport, BitSet columns, b
...
+                    wait(); // BarrageSnapshotImpl lock
+                }
+            }
         }
+
+        checkIfCompleteOrThrow();
```
Comment (rcaudy) [inline java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java:259]: Delete this if you take my suggestions.
```suggestion
```

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java [hunk 20]
```diff
@@ -210,36 +239,30 @@ public BitSet getServerColumns() {
...
 
         synchronized (pendingUpdatesLock) {
             pendingUpdates.add(update.clone());
         }
-        doWakeup();
+
+        if (!isRefreshing()) {
+            try {
+                realRefresh();
+            } catch (Throwable err) {
```
Comment (rcaudy) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java:256]: I think we need this logic in instrumentedRefresh(), too.

**Review by rcaudy — APPROVED** [review]
