### PR TITLE
Correct JS API handling of int64 and boolean columns

### LINKED ISSUE #3347: Hierarchical table expand row for boolean columns not working correctly
**Description**
rollup_booleans

Create a rollup table on a boolean column with the table sidebar menu for rollups in the UI.

```
from deephaven import empty_table, time_table
              
size = 100
scale = 1000

random_values_with_null_NaN = empty_table(size).update([
    "MyString=(i%11==0? null : `a`+(int)(scale*(Math.random()*2-1)))",
    "MyInt=(i%12==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyLong=(i%13==0 ? null : (long)(scale*(Math.random()*2-1)))",
    "MyFloat=(float)(i%14==0 ? null : i%10==0 ? 1.0F/0.0F: i%5==0 ? -1.0F/0.0F : (float) scale*(Math.random()*2-1))",
    "MyDouble=(double)(i%16==0 ? null : i%10==0 ? 1.0D/0.0D: i%5==0 ? -1.0D/0.0D : (double) scale*(Math.random()*2-1))",
    "MyBoolean = (i%17==0 ? null : (int)(10*Math.random())%2==0)",
    "MyChar = (i%18==0 ? null : new Character((char) (((26*Math.random())%26)+97)) )",
    "MyShort=(short)(i%19==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyByte=(Byte)(i%19==0 ? null : new Byte( Integer.toString((int)(Byte.MAX_VALUE*(Math.random()*2-1)))))",
    "MyBigDecimal=(i%21==0 ? null : new java.math.BigDecimal(scale*(Math.random()*2-1)))",
    "MyBigInteger=(i%22==0 ? null : new java.math.BigInteger(Integer.toString((int)(scale*(Math.random()*2-1)))))"
])

```

**Steps to reproduce**

Attempt to collapse/expand the `true` row.

**Expected results**

Row expands and collapses.

**Actual results**

Sometimes nothing, sometimes it expands, sometimes false expands.

**Versions**
Engine Version: 0.21.0
Web UI Version: 0.26.0
Java Version: 11.0.16
Barrage Version: 0.5.0

### PR DESCRIPTION
**Pull request by niloc132**
Boolean columns weren't updated when the server started using the validity buffer to handle nulls instead of a null value byte.

Longs were being translated to doubles incorrectly using Double.longBitsToDouble, which is incorrect when the long binary format matches a Double NaN.

Fixes #3347

### CODE REVIEW

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java [hunk 1]
```diff
@@ -425,6 +426,11 @@ private static ConvertedArrowSchema convertArrowSchema(
             if (type.getValue() == null) {
                 Class<?> defaultType = getDefaultType(getArrowType.apply(i), result, i);
                 type.setValue(defaultType);
+            } else if (type.getValue() == boolean.class) {
+                // check existing barrage clients that might be sending int8 instead of bool
+                // TODO (deephaven-core#3404) widen this check for better assurances
```
Comment (mofojed) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java:431]: Wrong ticket number:
```suggestion
                // TODO (deephaven-core#3403) widen this check for better assurances
```

**Review by mofojed — CHANGES_REQUESTED** [review]
Need to clean up the ticket number in the TODO.

Also, I'm still seeing some errors when doing the example from my ticket (random value table with groups on MyBoolean and MyChar). Sometimes rows get stuck in their state (clicking doesn't collapse/expand when it should), or collapsing and expanding at the level above doesn't reset the state for the descendants, or after doing some expanding/collapsing and then trying to collapse the top level it throws an error:
```
server_1  | 2023-02-03T14:19:11.491Z | heduler-Concurrent-2 | ERROR | icalTableViewSubscription | Internal Error '236fa67f-f40b-44b2-a10a-2dab001c795f' io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted linkedDirectives.remove(childDirective.nodeKey) == childDirective, instead linkedDirectives.remove(childDirective.nodeKey) == io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl$LinkedDirective@3582de8c, childDirective == io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl$LinkedDirective@673813bd.
server_1  |         at io.deephaven.base.verify.Assert.fail(Assert.java:99)
server_1  |         at io.deephaven.base.verify.Assert.eq(Assert.java:1379)
server_1  |         at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.lambda$removeOldChildren$7(HierarchicalTableImpl.java:1107)
server_1  |         at java.util.ArrayList.forEach(ArrayList.java:1511)
server_1  |         at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.removeOldChildren(HierarchicalTableImpl.java:1106)
server_1  |         at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.linkKeyTableNodeDirectives(HierarchicalTableImpl.java:1061)
server_1  |         at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.traverseExpansionsAndFillSnapshotChunks(HierarchicalTableImpl.java:1148)
server_1  |         at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.snapshotData(HierarchicalTableImpl.java:1134)
server_1  |         at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.snapshot(HierarchicalTableImpl.java:940)
server_1  |         at io.deephaven.engine.table.impl.hierarchical.RollupTableImpl.snapshot(RollupTableImpl.java:55)
server_1  |         at io.deephaven.server.hierarchicaltable.HierarchicalTableViewSubscription.buildAndSendSnapshot(HierarchicalTableViewSubscription.java:313)
server_1  |         at io.deephaven.server.hierarchicaltable.HierarchicalTableViewSubscription.process(HierarchicalTableViewSubscription.java:278)
server_1  |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
server_1  |         at java.util.concurrent.FutureTask.run(FutureTask.java:264)
server_1  |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
server_1  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
server_1  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
server_1  |         at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:165)
server_1  |         at java.lang.Thread.run(Thread.java:833)
server_1  | 
```
expand-all-failure

**Comment by mofojed** [comment]
Sorry, I don't have specific steps to reproduce... was just doing a bunch of operations, expanding and collapsing, expand all in rows, etc, and eventually got into a weird state:
expand-all-failure

**Review by nbauernfeind — APPROVED** [review]

**Review by mofojed — APPROVED** [review]
