### PR TITLE
make default behavior of QueryTable#snapshot take an initial snapshot

### LINKED ISSUE #824: Snapshot does not work OOTB with static tables
**Description**

The .snapshot() method does not freeze tables in time, as described in the enterprise docs [here](https://deephaven.io/enterprise/docs/onboarding/become-an-expert/use-table-snapshots/#creating-a-static-snapshot).

**Steps to reproduce**

Execute the following commands:

`from deephaven import TableTools as ttools`
`data = ttools.timeTable("00:00:10").update("X=i", "Y=new int[]{0,1,2}").tail(5).ungroup()`
`static_data = ttools.emptyTable(1).snapshot(data)`

**Expected results**

I expected `static_data` to contain exactly what `data` contained at the time of creating `static_data`, in a static table. You will get this desired result if you instead use

`static_data = ttools.emptyTable(1).snapshot(data, True)`

where this second optional parameter is not described anywhere in enterprise docs.

**Actual results**

`static_data` will be an empty table with the correct schema. No data from `data` gets copied.

**Versions**
 - Deephaven: 0.1.0
 - OS: masOS Big Sur 11.4
 - Browser: Safari 14.1.1
 - Docker: 3.3.3

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #824.

### CODE REVIEW

File: DB/src/main/java/io/deephaven/db/tables/Table.java [hunk 1]
```diff
@@ -2287,7 +2287,7 @@ default Table sort(Collection<SortColumn> columnsToSortBy) {
     Table snapshot(Table rightTable, boolean doInitialSnapshot, String... stampColumns);
 
     default Table snapshot(Table rightTable, String... stampColumns) {
```
Comment (rcaudy) [inline DB/src/main/java/io/deephaven/db/tables/Table.java:2289]: Can you clarify the JavaDoc on `TableOperations` to specify the default behavior? Also, please make sure @devinrsmith and the dev-rel folks know about this change, for QST and documentation respectively.

**Review by rcaudy — COMMENTED** [review]
See comment regarding docs and communication.

**Review by rcaudy — APPROVED** [review]
Make sure the docs team hear's about this, and understands that it is a changer relative to DHE.
