### PR TITLE
Drop Usage of `ensureGil` from PythonDeephavenSession and Copy Current Scope

### LINKED ISSUE #2324: Table named "new" doesn't display
**Description**

Table named "new" doesn't display.

**Steps to reproduce**
I ran the following commands.  I created a table named "new", then used it in a natural_join.  The join worked, but the table named "new" didn't show up.

```python
old=ag.where("isNull(extra_description)")
new=ag.where("extra_description=`opennatjoin`")
j=old.natural_join(new, "bench_name", "new_elapsed=elapsed_seconds,new_std=elapsed_seconds_std").update("PctChange=(elapsed_seconds-new_elapsed)/elapsed_seconds")
```

**Expected results**

I expected to see the table.

**Actual results**

I did not see the table.

### LINKED ISSUE #5138: Global Python Variables labled 'i', 'ii', and 'k' give an Error "no variable exists with name"
```python
i = time_table("PT1s")
ii = time_table("PT1s")
k = time_table("PT1s")
```

Yield this error:
```
io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Could not resolve 'sourceId': no variable exists with name 'k'
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.protobuf.StatusProto.toStatusRuntimeException(StatusProto.java:52)
	at io.deephaven.proto.util.Exceptions.statusRuntimeException(Exceptions.java:14)
	at io.deephaven.server.console.ScopeTicketResolver.resolve(ScopeTicketResolver.java:110)
	at io.deephaven.server.console.ScopeTicketResolver.resolve(ScopeTicketResolver.java:87)
	at io.deephaven.server.session.TicketRouter.resolve(TicketRouter.java:73)
	at io.deephaven.server.session.TicketRouter.resolve(TicketRouter.java:106)
	at io.deephaven.server.table.ops.TableServiceGrpcImpl.resolveOneShotReference(TableServiceGrpcImpl.java:719)
	at io.deephaven.server.table.ops.TableServiceGrpcImpl.lambda$oneShotOperationWrapper$8(TableServiceGrpcImpl.java:693)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4820)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4828)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.deephaven.server.table.ops.TableServiceGrpcImpl.oneShotOperationWrapper(TableServiceGrpcImpl.java:694)
	at io.deephaven.server.table.ops.TableServiceGrpcImpl.applyPreviewColumns(TableServiceGrpcImpl.java:379)
	at io.deephaven.proto.backplane.grpc.TableServiceGrpc$MethodHandlers.invoke(TableServiceGrpc.java:3791)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.lambda$onHalfClose$1(SessionServiceGrpcImpl.java:406)
	at io.deephaven.server.session.SessionServiceGrpcImpl.rpcWrapper(SessionServiceGrpcImpl.java:444)
	at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.onHalfClose(SessionServiceGrpcImpl.java:406)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.halfClosed(ServerImpl.java:868)
	at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:238)
	at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)
	at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:192)
	at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:201)
	at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:265)
	at io.grpc.servlet.jakarta.ServletAdapter$GrpcReadListener.lambda$onAllDataRead$1(ServletAdapter.java:337)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
	at io.grpc.servlet.jakarta.ServletServerStream$ServletTransportState.runOnTransportThread(ServletServerStream.java:144)
	at io.grpc.servlet.jakarta.ServletAdapter$GrpcReadListener.onAllDataRead(ServletAdapter.java:336)
	at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:411)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:587)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:461)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:450)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Probably we should filter the variables from `takeSnapshot` against the `NameValidator`.

### PR DESCRIPTION
**Pull request by nbauernfeind**
Cleans up the `toMap` interface for use in other contexts (e.g. they want all `Table` instances) and Python copies `currentScope` instead of trying to do the work under the GIL.

Also fixes #5138 by only disallowing `i`, `ii`, `k` when used as formula parameters - allowing users to name tables in their REPL these things (and observe expected UI behavior).

Also fixes #2324 which is the java-reserved-keyword version of #5138.

### CODE REVIEW

File: engine/context/src/main/java/io/deephaven/engine/context/StandaloneQueryScope.java [hunk 1]
```diff
@@ -80,12 +81,28 @@ public <T> void putParam(final String name, final T value) {
...
-        valueRetrievers.entrySet().stream()
-                .map(e -> ImmutablePair.of(e.getKey(), (Object) e.getValue().value))
-                .filter(predicate)
-                .forEach(e -> result.put(e.getKey(), e.getValue()));
+    public <T> Map<String, T> toMap(
+            @Nullable final Function<Object, T> valueMapper,
+            @NotNull final ParamFilter<T> filter) {
+        final Map<String, T> result = new HashMap<>();
+
+        synchronized (valueRetrievers) {
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/StandaloneQueryScope.java:89]: Don't need this synchronized block.

File: engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java [hunk 2]
```diff
@@ -325,38 +326,25 @@ public boolean hasParamName(String name) {
...
-                return (T) getVariable(name);
+                return getVariable(name);
             } catch (MissingVariableException e) {
                 return defaultValue;
             }
         }
 
         @Override
         public <T> void putParam(final String name, final T value) {
-            NameValidator.validateQueryParameterName(name);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java:359]: Do you need the same change in standalone? Maybe we shouldn't change that, after all, but this does let us be more consistent with script sessions.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScope.java [hunk 3]
```diff
@@ -143,7 +143,12 @@ default Collection<String> getKeysCollection() {
     /**
      * @return the Python's __main__ module namespace
      */
-    public PyDictWrapper mainGlobals();
+    PyDictWrapper mainGlobals();
+
+    /**
+     * @return the current scope or the main globals if no scope is set
+     */
+    PyDictWrapper currentScope();
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/util/PythonScope.java:151]: Why do we need this in the interface?

File: server/src/main/java/io/deephaven/server/console/ScopeTicketResolver.java [hunk 4]
```diff
@@ -71,14 +71,12 @@ public SessionState.ExportObject<Flight.FlightInfo> flightInfoFor(
...
-                visitor.accept(TicketRouter.getFlightInfo((Table) varObj, descriptorForName(varName),
-                        flightTicketForName(varName)));
-            }
-        });
+        final QueryScope queryScope = ExecutionContext.getContext().getQueryScope();
+        queryScope.toMap(wrapped -> {
+            final Object value = queryScope.unwrapObject(wrapped);
+            return value instanceof Table ? (Table) value : null;
+        }, (n, t) -> t != null).forEach((name, table) -> visitor
+                .accept(TicketRouter.getFlightInfo(table, descriptorForName(name), flightTicketForName(name))));
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/console/ScopeTicketResolver.java:79]:
```suggestion
        queryScope.toMap(queryScope::unwrapObject, (n, t) -> t instanceof Table).forEach((name, table) -> visitor
                .accept(TicketRouter.getFlightInfo((Table) table, descriptorForName(name), flightTicketForName(name))));
```

File: engine/sql/src/main/java/io/deephaven/engine/sql/Sql.java [hunk 5]
```diff
@@ -82,16 +82,11 @@ private static Scope scope(Map<String, Table> scope, Map<TicketTable, Table> out
...
-                .toMap()
-                .entrySet()
-                .stream()
-                .map(e -> Map.entry(e.getKey(), queryScope.unwrapObject(e.getValue())))
-                .filter(e -> e.getValue() instanceof Table)
-                .collect(Collectors.toMap(Entry::getKey, e -> (Table) e.getValue()));
-
-        return scope;
+        final QueryScope queryScope = ExecutionContext.getContext().getQueryScope();
+        return queryScope.toMap(wrapped -> {
```
Comment (rcaudy) [inline engine/sql/src/main/java/io/deephaven/engine/sql/Sql.java:86]: Of you change `ScopeTicketResolver`, change this, too.

File: Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java [hunk 6]
```diff
@@ -255,7 +257,10 @@ protected Changes createDiff(PythonSnapshot from, PythonSnapshot to, RuntimeExce
 
     @Override
     protected Set<String> getVariableNames(Predicate<String> allowName) {
-        return PyLib.ensureGil(() -> scope.getKeys().filter(allowName).collect(Collectors.toUnmodifiableSet()));
+        return scope.currentScope().copy().keySet().stream()
```
Comment (rcaudy) [inline Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java:260]: `PyDictWrappers` are `AutoCloseable`, and it would be better to close the copies we make of `currentScope()` and `mainGlobals`.

File: engine/table/src/main/java/io/deephaven/engine/util/PythonScope.java (hunk 3 above)
Comment (nbauernfeind) [reply engine/table/src/main/java/io/deephaven/engine/util/PythonScope.java:151]: Previously we were using `getKeysRaw` (through delegation) and `getEntriesRaw` both of which created a `Stream` around iterating items in the `currentScope`. Now we must make a copy/dictCopy prior to using the returned values. (We were assuming that we could `ensureGil` while collecting keys and/or values, but this is not the case as performing these operations involve JNI.

I will remove the superfluous methods since I don't believe there is a good way to use them safely anymore.

**Review by rcaudy — APPROVED** [review]
