### PR TITLE
Suppress Unpredictable Client-Behavior gRPC related Exceptions

### LINKED ISSUE #4172: Error Thrown From Web Machinery
This was a host using HTTP2 over SSL. 

To reproduce connect to a server and run the following in the REPL:
```groovy
Thread.sleep(10000)
```

Then hard-refresh the page (to open a new session -- I was seeing if #3041 is still an issue). When the `sleep` completes the following error hits the console:

```
Exception while executing runnable io.grpc.servlet.jakarta.ServletServerStream$Sink$$Lambda$1799/0x00000008013edb38@44de5a36java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:47)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:67)
	at io.grpc.servlet.jakarta.ServletServerStream$Sink.lambda$cancel$2(ServletServerStream.java:306)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
	at io.grpc.servlet.jakarta.ServletServerStream$ServletTransportState.runOnTransportThread(ServletServerStream.java:144)
	at io.grpc.servlet.jakarta.ServletServerStream$Sink.cancel(ServletServerStream.java:305)
	at io.grpc.servlet.jakarta.ServletServerStream$Sink.writeHeaders(ServletServerStream.java:232)
	at io.grpc.internal.AbstractServerStream.writeHeaders(AbstractServerStream.java:103)
	at io.grpc.internal.ServerCallImpl.sendHeadersInternal(ServerCallImpl.java:147)
	at io.grpc.internal.ServerCallImpl.sendHeaders(ServerCallImpl.java:104)
	at io.grpc.PartialForwardingServerCall.sendHeaders(PartialForwardingServerCall.java:38)
	at io.grpc.ForwardingServerCall.sendHeaders(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.sendHeaders(ForwardingServerCall.java:39)
	at io.deephaven.server.session.SessionServiceGrpcImpl$InterceptedCall.sendHeaders(SessionServiceGrpcImpl.java:265)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:377)
	at io.deephaven.extensions.barrage.util.GrpcUtil.lambda$safelyComplete$1(GrpcUtil.java:73)
	at io.deephaven.extensions.barrage.util.GrpcUtil.safelyExecuteLocked(GrpcUtil.java:45)
	at io.deephaven.extensions.barrage.util.GrpcUtil.safelyComplete(GrpcUtil.java:72)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:188)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1380)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:921)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

I would expect this error to be suppressed as it is nothing that a user will be able to deal with (and is otherwise confusing).

### LINKED ISSUE #4173: SessionState.ExportObject cancels should not make it to the log
Not sure exactly how to reproduce, but something is logging CANCEL status runtime exceptions when it's probably OK to not log at all.

```
io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Export in state CANCELLED
        at io.grpc.Status.asRuntimeException(Status.java:539)
        at io.grpc.protobuf.StatusProto.toStatusRuntimeException(StatusProto.java:52)
        at io.deephaven.proto.util.Exceptions.statusRuntimeException(Exceptions.java:14)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$onErrorHandler$0(SessionState.java:1323)
        at io.deephaven.server.session.SessionState$ExportObject.setState(SessionState.java:799)
        at io.deephaven.server.session.SessionState$ExportObject.cancel(SessionState.java:1038)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller$SubscriptionRequestHandler.close(ArrowFlightUtil.java:695)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller.close(ArrowFlightUtil.java:422)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller.tryClose(ArrowFlightUtil.java:433)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller.onCancel(ArrowFlightUtil.java:395)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onCancel(ServerCalls.java:195)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.lambda$onCancel$2(SessionServiceGrpcImpl.java:392)
        at io.deephaven.server.session.SessionServiceGrpcImpl.rpcWrapper(SessionServiceGrpcImpl.java:425)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.onCancel(SessionServiceGrpcImpl.java:392)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:378)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:365)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:923)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:930)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:888)
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:339)
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:283)
        at io.grpc.servlet.jakarta.ServletServerStream$Sink.lambda$cancel$1(ServletServerStream.java:301)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
        at io.grpc.servlet.jakarta.ServletServerStream$ServletTransportState.runOnTransportThread(ServletServerStream.java:144)
        at io.grpc.servlet.jakarta.ServletServerStream$Sink.cancel(ServletServerStream.java:301)
        at io.grpc.internal.AbstractServerStream.cancel(AbstractServerStream.java:148)
        at io.grpc.servlet.jakarta.ServletAdapter$GrpcReadListener.onError(ServletAdapter.java:346)
        at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:403)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:596)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
        at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208)
        at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155)
        at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:378)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.lang.Thread.run(Thread.java:832)
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #4172
Fixes #4173 

- Do not print out gRPC out-of-band cancellations (such as session expiry, or a dependent export cancellation).
- Suppress all IOExceptions when writing gRPC stream metadata. (there are races between client closing cancelled RPCs and us notifying them)
- Suppress all IOExceptions from `MultiplexedWebsocketStreamImpl#onError` propagation.
- Do not allow Exceptions to leak out when attempting to close AsynContext (which might already be completed whenever an RPC is cancelled and/or errored from different, raceful, code paths).

### CODE REVIEW

File: grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerStream.java [hunk 1]
```diff
@@ -303,8 +303,13 @@ public void cancel(Status status) {
             close(Status.CANCELLED.withCause(status.asRuntimeException()), new Metadata());
             CountDownLatch countDownLatch = new CountDownLatch(1);
             transportState.runOnTransportThread(() -> {
-                asyncCtx.complete();
-                countDownLatch.countDown();
+                try {
+                    asyncCtx.complete();
+                    countDownLatch.countDown();
```
Comment (niloc132) [inline grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerStream.java:308]: i think the countdown latch should go in finally, so that even if complete throws we still unblock the calling thread?

File: grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebSocketServerStream.java [hunk 2]
```diff
@@ -219,15 +218,16 @@ public void onMessage(ByteBuffer message) throws IOException {
...
             stream.transportReportStatus(Status.UNKNOWN);// transport failure of some kind
         }
         streams.clear();
         // onClose will be called automatically
-        if (error instanceof ClosedChannelException) {
-            // ignore this for now
-            // TODO need to understand why this is happening
+        if (error instanceof IOException) {
+            // IOExceptions frequently occur when clients close the connection
+            // Note we have seen both EofExceptions and ClosedChannelExceptions
```
Comment (niloc132) [inline grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebSocketServerStream.java:230]: check both specific cases (eof and closedchannel), rather than all io errors?

File: grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerStream.java [hunk 3]
```diff
@@ -303,8 +303,13 @@ public void cancel(Status status) {
...
+                } catch (final Exception err) {
+                    // this happens when the async context is already complete
+                    logger.info("Unexpected exception completing async context: " + err.getMessage());
```
Comment (niloc132) [inline grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerStream.java:311]: do we want to log this? i see you're not logging for io errors when writing headers/trailers below - those go out in success or failure causes, but this is explicitly the cancel() method, so we are already expecting failure, it is less surprising to see an error here?

File: grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebsocketStreamImpl.java [hunk 4]
```diff
@@ -76,7 +76,7 @@ private void writeMetadataToStream(Metadata headers, boolean closeBitSet) {
             try {
                 websocketSession.getBasicRemote().sendBinary(message);
             } catch (IOException e) {
-                throw Status.fromThrowable(e).asRuntimeException();
+                // ignore IOExceptions; they are likely due to unpredictable client behavior
```
Comment (niloc132) [inline grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebsocketStreamImpl.java:79]: I agree that this should not throw, and onError should be called automatically, so we shouldn't need to do specific handling here for that case. Can you adjust the comment to reflect that, so it is clear that this case is handled, rather than just being ignored?

**Review by niloc132 — APPROVED** [review]
