### PR TITLE
PythonDeephavenSession#getVariables should unwrap PyObjects

### LINKED ISSUE #2360: listFlights does not work against python session
It seems like listFlight against a python session does not work (empty list returned). listFields *does* work. At least since 0.11.0.

Tested with a python console session and the java client examples io.deephaven.client.examples.ListTables and io.deephaven.client.examples.SubscribeToFields.

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #2360

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/util/PythonDeephavenSession.java [hunk 1]
```diff
@@ -193,7 +194,9 @@ protected void evaluate(String command, String scriptName) {
 
     @Override
     public Map<String, Object> getVariables() {
-        return Collections.unmodifiableMap(scope.getEntriesMap());
+        final Map<String, Object> outMap = new LinkedHashMap<>();
+        scope.getEntriesMap().forEach((key, value) -> outMap.put(key, maybeUnwrap(value)));
+        return outMap;
```
Comment (devinrsmith) [inline engine/table/src/main/java/io/deephaven/engine/util/PythonDeephavenSession.java:199]: I'm wondering if `io.deephaven.engine.util.PythonScopeJpyImpl#convertValue` or `io.deephaven.engine.util.PythonScopeJpyImpl#convert` is the more appropriate place to do the unwrapping.

Comment (devinrsmith) [inline engine/table/src/main/java/io/deephaven/engine/util/PythonDeephavenSession.java:199]: I'm wondering if `io.deephaven.engine.util.PythonScopeJpyImpl#convertValue` or `io.deephaven.engine.util.PythonScopeJpyImpl#convert` is the more appropriate place to do the unwrapping.

**Review by devinrsmith — APPROVED** [review]
