### PR TITLE
JavaClient: Encode Packed Booleans Instead of Reinterpretted Bytes

### LINKED ISSUE #1373: Hook up doPut integration unit testing
During doPut work, integration unit testing wasn't hooked up. Some code was sketched out, but it seems like there is some part of the in-process setup that is not working.

```
"Test worker" #20 prio=5 os_prio=0 tid=0x00007faa1d1f4000 nid=0x1d79b waiting on condition [0x00007fa9e8b22000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000782dd52b8> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.apache.arrow.flight.AsyncPutListener.getResult(AsyncPutListener.java:46)
        at org.apache.arrow.flight.FlightClient$$Lambda$593/200171235.run(Unknown Source)
        at org.apache.arrow.flight.FlightClient$PutObserver.getResult(FlightClient.java:486)
        at io.deephaven.client.impl.FlightSession.putTicket(FlightSession.java:118)
        at io.deephaven.client.impl.FlightSession.put(FlightSession.java:98)
        at io.deephaven.client.DeephavenFlightSessionTest.doPutNewTable(DeephavenFlightSessionTest.java:67)
```

### LINKED ISSUE #3799: Java client fails to publish columns of booleans
**Description**

After #3401 the Java Flight client cannot send a `boolean` column.

**Steps to reproduce**
Running [`io.deephaven.client.examples.DoPutTable`](https://github.com/deephaven/deephaven-core/blob/2275928a7a4e1e7a7d222ac9f00ba27995b39d2e/java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoPutTable.java#L100) fails.

**Expected results**

image

**Actual results**

```
org.apache.arrow.flight.FlightRuntimeException: INVALID_ARGUMENT: Details Logged w/ID 'c1388af5-3f84-4da5-bc3c-0ae6fa0cc72a'
	at org.apache.arrow.flight.CallStatus.toRuntimeException(CallStatus.java:131)
	at org.apache.arrow.flight.grpc.StatusUtils.fromGrpcRuntimeException(StatusUtils.java:164)
	at org.apache.arrow.flight.grpc.StatusUtils.fromThrowable(StatusUtils.java:185)
	at org.apache.arrow.flight.FlightClient$SetStreamObserver.onError(FlightClient.java:445)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.apache.arrow.flight.grpc.ClientInterceptorAdapter$FlightClientCallListener.onClose(ClientInterceptorAdapter.java:117)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

And in the UI:

```
qtp214313531-59      | .s.SessionServiceGrpcImpl | Internal Error 'c1388af5-3f84-4da5-bc3c-0ae6fa0cc72a' io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted deephaven column type == arrow inferred type, instead deephaven column type == boolean, arrow inferred type == byte.
qtp214313531-59      | .s.SessionServiceGrpcImpl | Internal Error '2c75cda5-abc5-4a80-a497-cad8b594ba6a' java.lang.NullPointerException: Cannot invoke "io.deephaven.extensions.barrage.table.BarrageTable.getColumnSources()" because "this.resultTable" is null
qtp214313531-59      | .s.SessionServiceGrpcImpl | io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Result flight schema never provided
```

**Additional details and attachments**

The naive fix seems to be rather simple:
Change this line from `TINYINT` to `BIT`
https://github.com/deephaven/deephaven-core/blob/2275928a7a4e1e7a7d222ac9f00ba27995b39d2e/java-client/flight/src/main/java/io/deephaven/client/impl/FieldAdapter.java#L53

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #3799.
Fixes #1373.

### CODE REVIEW

File: java-client/flight/src/main/java/io/deephaven/client/impl/VectorHelper.java [hunk 1]
```diff
@@ -30,6 +23,14 @@ public static void fill(TinyIntVector vector, byte[] array, int offset, int len)
         vector.setValueCount(len);
     }
 
+    public static void fill(BitVector vector, byte[] array, int offset, int len) {
+        vector.allocateNew(len);
+        for (int i = 0; i < len; i++) {
+            vector.set(i, array[offset + i] != Util.NULL_BOOL ? 1 : 0, array[offset + i] == Util.TRUE_BOOL ? 1 : 0);
+        }
+        vector.setValueCount(len);
+    }
```
Comment (devinrsmith) [inline java-client/flight/src/main/java/io/deephaven/client/impl/VectorHelper.java:32]: Instead of exposing the constants, I think it might be better to present a new interface for iterating/accessing items through `BooleanArray`.

Maybe it's as simple as:

```java
public final class BooleanArray extends PrimitiveArrayBase<Boolean> {
    ...
    public Boolean value(int index) {
        ...
    }
```
?

It's also not unreasonable to think this should be generic on `io.deephaven.qst.array.Array<T>`.

**Review by devinrsmith — CHANGES_REQUESTED** [review]

File: java-client/flight/src/main/java/io/deephaven/client/impl/VectorHelper.java (hunk 1 above)
Comment (devinrsmith) [reply java-client/flight/src/main/java/io/deephaven/client/impl/VectorHelper.java:32]: We might additionally consider adding:

```java
public boolean isNull(int index) {
...
}
```

for users who want to iterate the primitive arrays without needing to go through a potentially boxing / unboxing.

**Comment by devinrsmith** [comment]
May be worthwhil to try and fix #1373, here is the commented out code updated:

```java
    // TODO (deephaven-core#1373): Hook up doPut integration unit testing
    @Test
    public void doPutStream() throws Exception {
        try (
                final TableHandle ten = flightSession.session().execute(TableSpec.empty(10).view("I=i"));
                // DoGet
                final FlightStream tenStream = flightSession.stream(ten);
                // DoPut
                final TableHandle tenAgain = flightSession.putExport(tenStream)) {
            assertThat(tenAgain.response().getSchemaHeader()).isEqualTo(ten.response().getSchemaHeader());
        }
    }

     @Test
     public void doPutNewTable() throws TableHandleException, InterruptedException {
         try (final TableHandle newTableHandle = flightSession.putExport(newTable(), bufferAllocator)) {
            // ignore
         }
     }
 ```
 
It appears the flight client is blocking on getResult; it may be a factor that this is an in-process setup?
 
 ```
 java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	  at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	  at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	  at org.apache.arrow.flight.AsyncPutListener.getResult(AsyncPutListener.java:46)
	  at org.apache.arrow.flight.FlightClient$$Lambda$788.1823014131.run(Unknown Source:-1)
	  at org.apache.arrow.flight.FlightClient$PutObserver.getResult(FlightClient.java:491)
	  at io.deephaven.client.impl.FlightClientHelper.put(FlightClientHelper.java:51)
	  at io.deephaven.client.impl.FlightClientHelper.put(FlightClientHelper.java:29)
	  at io.deephaven.client.impl.FlightSession.put(FlightSession.java:198)
	  at io.deephaven.client.impl.FlightSession.putExportManual(FlightSession.java:183)
	  at io.deephaven.client.impl.FlightSession.putExport(FlightSession.java:135)
	  at io.deephaven.client.DeephavenFlightSessionTest.doPutStream(DeephavenFlightSessionTest.java:93)
```

File: server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java [hunk 2]
```diff
@@ -79,9 +79,6 @@ interface Builder {
 
     @Before
     public void setUp() throws Exception {
-        UpdateGraphProcessor.DEFAULT.enableUnitTestMode();
-        UpdateGraphProcessor.DEFAULT.resetForUnitTests(false);
-
```
Comment (devinrsmith) [inline server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java:84]: Is this un-related cleanup?

File: java-client/flight-dagger/src/test/java/io/deephaven/client/DeephavenFlightSessionTest.java [hunk 3]
```diff
@@ -81,25 +83,25 @@ public void updateBy() throws Exception {
...
+            assertThat(tenSchema.tableDef).isEqualTo(tenAgainSchema.tableDef);
+        }
+    }
+
+    @Test
+    public void doPutNewTable() throws TableHandle.TableHandleException, InterruptedException {
+        try (final TableHandle newTableHandle = flightSession.putExport(newTable(), bufferAllocator)) {
+            // ignore
+        }
+    }
```
Comment (devinrsmith) [inline java-client/flight-dagger/src/test/java/io/deephaven/client/DeephavenFlightSessionTest.java:104]: Awesome!

**Review by devinrsmith — COMMENTED** [review]
All looks good to me. Looks like spotless in complaining. We probably want to push this through nightlies?

**Review by devinrsmith — APPROVED** [review]
