### PR TITLE
JS API should return nulls rather than undefined when reading table data

### LINKED ISSUE #5400: JSAPI returns `undefined` for a `null` value in table data
**Description**

The value retrieved from a table via the JSAPI doesn't match the value shown in the console.

**Steps to reproduce**

- On a DHE VM, run this snippet in a Core+ groovy console:
```
ts = emptyTable(1).update("X=(String)null")
println ts.getColumnSource("X").get(0)
// Prints "null"
```

- Create a Core+ Groovy PQ with the snippet above, save it as `TestPQ`
- Open `https://<vm>/irisapi/table_viewport.html`
- Run this snippet in the browser console:
```
var { default: getObject } = await import('./get_object.js')
async function getValue(queryName, tableName, colName, rowIndex) {
    var q = c.getKnownConfigs().find(q => q.name === queryName)
    var t = await getObject(c, q, tableName)
    console.log('size:', t.size)
    t.setViewport(rowIndex, rowIndex)
    var v = await t.getViewportData()
    var column = t.findColumn(colName)
    console.log('viewport, column:', v, column)
    return v.rows[0].get(column);
}
var value = await getValue('TestPQ', 'ts', 'X', 0)
console.log('value, type:', value, typeof value)
// Prints "value, type: undefined undefined"
```

**Expected results**

Value retrieved via JSAPI matches the value returned by `ts.getColumnSource("X").get(0)` in the Code Studio

**Actual results**

JSAPI returns `undefined` when the actual value in the table is `null`

**Versions**
- Core+:  0.33.3

### PR DESCRIPTION
**Pull request by niloc132**
While Java arrays are initialized to nulls, GWT normalizes undefined and null to be equivalent, so we need to explicitly assign null values when building arrays.

Adds tests to ensure this doesn't break as part of #188. 

Fixes #5400

### CODE REVIEW

File: web/client-api/src/test/java/io/deephaven/web/client/api/NullValueTestGwt.java [hunk 1]
```diff
@@ -28,12 +29,28 @@ public class NullValueTestGwt extends AbstractAsyncGwtTestCase {
                     "   \"MyString=i==0?null:``+i\",\n" +
                     "   \"MyDate=i==0?null:epochNanosToInstant(i)\",\n" +
                     "   \"MyBigInteger=i==0?null:java.math.BigInteger.valueOf(i)\",\n" +
-                    "   \"MyBigDecimal=i==0?null:java.math.BigDecimal.valueOf(i, 4)\"\n" +
+                    "   \"MyBigDecimal=i==0?null:java.math.BigDecimal.valueOf(i, 4)\",\n" +
+                    "   \"MyStringArray1=i==0?null:new String[] {`A`, `B`, `C`}\"\n" +
```
Comment (mofojed) [inline web/client-api/src/test/java/io/deephaven/web/client/api/NullValueTestGwt.java:33]: Why `MyStringArray1` instead of just `MyStringArray`? 1 dimension?

**Review by mofojed — APPROVED** [review]
Looks fine, one question about the StringArray in the unit test table.
I tested in browser console with this snippet:
```
var dh = (await import('./dh-core.js')).default
var client = new dh.CoreClient(window.location.protocol + "//" + window.location.host);
await client.login({type: 'io.deephaven.authentication.psk.PskAuthenticationHandler', token: 'iris'});
var connection = await client.getAsIdeConnection();
var ide = await connection.startSession("python");
await ide.runCode(`
from deephaven import empty_table

x = empty_table(1).update("X=(String)null")
`)


var x = await connection.getObject({ type: 'Table', name: 'x' })
x.setViewport(0, 0)
var data = await x.getViewportData()
var value = data.get(0).get(x.columns[0])
console.log('Value is', value, ', isNull?=', value === null)
```

**Review by vbabich — APPROVED** [review]

File: web/client-api/src/test/java/io/deephaven/web/client/api/NullValueTestGwt.java (hunk 1 above)
Comment (niloc132) [reply web/client-api/src/test/java/io/deephaven/web/client/api/NullValueTestGwt.java:33]: Yep, also to add another test for arrays that contain nulls, but given the preview issues, I didn't dig in there yet.
