### PR TITLE
`TableServiceAsyncTest`: Eliminate Compiler Overhead Variance; Close `QueryCompiler`'s `JavaFileManager`

### LINKED ISSUE #4798: TableServiceAsyncTest timeout unit test failure
It appears that the following test is sometimes failing:

```
2023-11-08T18:52:13.9139040Z io.deephaven.client.impl.TableServiceAsyncTest > longChainAsyncExportOnlyLast FAILED
2023-11-08T18:52:13.9142554Z     java.util.concurrent.TimeoutException at TableServiceAsyncTest.java:79
```

It suggests that there is an underlying race (potentially Batch / ETCR or related), or client implementation bug; but it's possible the timeout is too short given CI resources, TBD.

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #4798.
Follow up work #4814.

Whenever I could catch a timeout in the debugger the server was not blocked, always making progress, but spending time in compilation. I've eliminated the need to recompile formulas for each operation in the chain and added some validation that the data in the result tables are as expected.

While testing ways to reproduce and/or fix the original issue, I discovered that the `JavaFileManager` that we're creating on every compilation request opened file handles for many of the jars on my classpath. After around 50'ish queries the `QueryCompiler` broke complaining of `Too many open files`. Running a quick `lsof | cut | sort | uniq -c` showed 40+ open file handles each on many of the jars on my classpath. I've done the bare minimum in this PR, will write a follow up issue, and discuss via team-slack.

Multiplexed this PR's Check CI here: https://github.com/nbauernfeind/deephaven-core/actions/runs/6830355652
Multiplexed current main's Check CI here: https://github.com/nbauernfeind/deephaven-core/actions/runs/6830357421/
(I expect to see a failure or three in the current main and none for this PR as it's hard to tell if the issue has been fixed.)

### CODE REVIEW

File: java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java [hunk 1]
```diff
@@ -93,8 +93,11 @@ private static List<TableSpec> createLongChain(int numColumns, int numRows) {
             if (i == 0) {
                 longChain.add(TableSpec.empty(numRows).view("I_0=ii"));
             } else {
+                // create a chain using the previous table even though we don't need the data
                 final TableSpec prev = longChain.get(i - 1);
-                longChain.add(prev.updateView("I_" + i + " = 1 + I_" + (i - 1)));
+                // to avoid timeouts due to compilation variance reuse the same expression, including the destination
+                // column which shows up in the generated formula's FormulaEvaluationException
+                longChain.add(prev.updateView("I_1 = 1 + I_0"));
```
Comment (devinrsmith) [inline java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:100]: I'm not sure how this is directly related to #4798; that is _specifically_ around a timeout error. I'd assume in the case of too many open files in the compilation path there will be some _other_ error that causes TableServiceAsyncTest to fail, correct?

Comment (devinrsmith) [inline java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:100]: I think reworking as `prev.updateView("Next = Current + 1", "Current = Next")` better matches the original intentions of the query.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 2]
```diff
@@ -683,19 +683,60 @@ private void maybeCreateClass(String className, String code, String packageName,
         }
     }
 
+    private static JavaCompiler JAVA_COMPILER = null;
```
Comment (devinrsmith) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:686]: Needs to be volatile for this pattern.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 3]
```diff
@@ -683,19 +683,60 @@ private void maybeCreateClass(String className, String code, String packageName,
...
+    private static JavaCompiler getJavaCompiler() {
+        JavaCompiler localCompiler = JAVA_COMPILER;
+        if (localCompiler != null) {
+            return localCompiler;
+        }
+        synchronized (QueryCompiler.class) {
+            localCompiler = JAVA_COMPILER;
+            if (localCompiler != null) {
+                return localCompiler;
+            }
```
Comment (devinrsmith) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:697]: Bit more compact to do:

```java
JavaCompiler localCompiler;
if ((localCompiler = JAVA_COMPILER) == null) {
   sync (...) {
     if ((localCompiler = JAVA_COMPILER) == null) {
     ...
     }
}
return localCompiler;
}
```

File: java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java (hunk 1 above)
Comment (nbauernfeind) [reply java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:100]: Everytime it was timed out the server was in the middle of compiling. I did a bunch of instrumentation - there is no real issue with the test, just that the variance of compilation causes it to time out. Repeated local runs are actually harder to time out because the classes have been precompiled.

The change that you are commenting on here, is the actual fix -- run the long chain without repeatedly invoking the compiler. If you prefer, we can split this out from the singleton creation.

Comment (nbauernfeind) [reply java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:100]: The test currently does not validate the data. As far as I can tell, the purpose is to ensure that some table returns at the end of the chain.

I like the proposed change as it eliminates the need to recompile the formulas repeatedly while preserving the original implementation. Though, perhaps we should be adding an assert table equals to validate the expected data is returned.

Comment (devinrsmith) [reply java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:100]: Ah, makes sense; I never saw that high of variation likely due to the points you bring up.

Comment (devinrsmith) [reply java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:100]: Shouldn't my proposal not need repeated compilation? The strings are fixed.

Comment (nbauernfeind) [reply java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java]: > I like the proposed change [...]

I meant to reference your suggestion which is a nice improvement.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 4]
```diff
@@ -683,19 +683,51 @@ private void maybeCreateClass(String className, String code, String packageName,
...
     }
 
+    private static volatile JavaCompiler JAVA_COMPILER = null;
+
+    private static JavaCompiler getJavaCompiler() {
+        JavaCompiler localCompiler;
+        if ((localCompiler = JAVA_COMPILER) == null) {
+            synchronized (QueryCompiler.class) {
+                if ((localCompiler = JAVA_COMPILER) == null) {
+                    localCompiler = JAVA_COMPILER = ToolProvider.getSystemJavaCompiler();
```
Comment (devinrsmith) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:693]: One small improvement:

```java
JAVA_COMPILER = localCompiler = ...
```

does a volatile write, whereas the existing one does volatile write + read.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 5]
```diff
@@ -683,19 +683,51 @@ private void maybeCreateClass(String className, String code, String packageName,
...
+     * the classpath, which is <b>very</b> expensive.
+     */
+    private static volatile JavaFileManager JAVA_FILE_MANAGER = null;
+
+    private static JavaFileManager getJavaFileManager() {
+        JavaFileManager localManager;
+        if ((localManager = JAVA_FILE_MANAGER) == null) {
+            synchronized (QueryCompiler.class) {
+                if ((localManager = JAVA_FILE_MANAGER) == null) {
+                    localManager = JAVA_FILE_MANAGER = getJavaCompiler().getStandardFileManager(null, null, null);
```
Comment (devinrsmith) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:714]: Ditto.

File: java-client/session/src/main/java/io/deephaven/client/impl/Session.java [hunk 6]
```diff
@@ -22,6 +24,12 @@ public interface Session
     @Override
     void close();
 
+    /**
+     * Returns the current auth token.
+     */
+    @VisibleForTesting
+    UUID getCurrentToken();
```
Comment (devinrsmith) [inline java-client/session/src/main/java/io/deephaven/client/impl/Session.java:31]: I don't think we need this on the interface; SessionImpl is OK.

File: java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java [hunk 7]
```diff
@@ -79,22 +85,30 @@ private static TableHandle get(TableHandleFuture future)
         return future.getOrCancel(GETTIME);
     }
 
-    private static void checkSucceeded(TableHandle x) {
+    private void checkSucceeded(TableHandle x, int chainLength) {
         assertThat(x.isSuccessful()).isTrue();
+        try (final SafeCloseable ignored = getExecutionContext().open()) {
+            final Table result = getSession(session.getCurrentToken()).<Table>getExport(x.exportId().id()).get();
```
Comment (devinrsmith) [inline java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:91]: I think we should capture the server-side session in `DeephavenSessionTestBase` field; you should have access to `SessionImpl` w/ return call of `io.deephaven.client.SessionSubcomponent#newSession`

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 8]
```diff
@@ -683,27 +683,63 @@ private void maybeCreateClass(String className, String code, String packageName,
...
+        JavaCompiler localCompiler;
+        if ((localCompiler = JAVA_COMPILER) == null) {
+            synchronized (QueryCompiler.class) {
+                if ((localCompiler = JAVA_COMPILER) == null) {
+                    JAVA_COMPILER = localCompiler = ToolProvider.getSystemJavaCompiler();
+                }
+            }
+        }
+        if (localCompiler == null) {
+            throw new RuntimeException("No Java compiler provided - are you using a JRE instead of a JDK?");
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:698]:
```suggestion
            throw new UncheckedDeephavenException("No Java compiler provided - are you using a JRE instead of a JDK?");
```

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 9]
```diff
@@ -735,7 +771,7 @@ private void maybeCreateClassHelper(String fqClassName, String finalCode, String
      * @return a Pair of success, and the compiler output
      */
     private Pair<Boolean, String> tryCompile(File basePath, Collection<File> javaFiles) throws IOException {
-        final JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
+        final JavaCompiler compiler = getJavaCompiler();
         if (compiler == null) {
             throw new RuntimeException("No Java compiler provided - are you using a JRE instead of a JDK?");
         }
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:777]: This is no longer necessary.
```suggestion
```

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 10]
```diff
@@ -683,27 +683,63 @@ private void maybeCreateClass(String className, String code, String packageName,
...
+        // the java file manager is not thread safe
+        synchronized (QueryCompiler.class) {
+            result = compiler.getTask(compilerOutput,
+                    fileManager,
+                    null,
+                    compilerOptions,
+                    null,
+                    Collections.singletonList(new JavaSourceFromString(fqClassName, finalCode)))
+                    .call();
+        }
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:742]: No way can we merge this unless you can convince me that compilation was already single-threaded somewhere under the hood (which I don't believe to be the case).

File: java-client/session/src/main/java/io/deephaven/client/impl/Session.java (hunk 6 above)
Comment (rcaudy) [inline java-client/session/src/main/java/io/deephaven/client/impl/Session.java:31]: Do we want to make this less obscure?

File: java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java [hunk 11]
```diff
@@ -79,22 +85,30 @@ private static TableHandle get(TableHandleFuture future)
...
+            ExecutionContext.getContext().getQueryScope().putParam("ChainLength", chainLength);
+            final Table expected = TableTools.emptyTable(CHAIN_ROWS).update("Current = ii - 1 + ChainLength");
```
Comment (rcaudy) [inline java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java:93]: I don't understand this test.

**Review by rcaudy — CHANGES_REQUESTED** [review]

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java (hunk 10 above)
Comment (devinrsmith) [reply engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:742]: I was going to make a similar comment.

Comment (nbauernfeind) [reply engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:742]: It's definitely not synchronized under the hood - go-client tests caught this via some concurrent modification exceptions.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 12]
```diff
@@ -697,13 +697,29 @@ private void maybeCreateClassHelper(String fqClassName, String finalCode, String
 
         final StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, null, null);
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:698]: Should be `JavaFileManager`. No need to change in this PR.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 13]
```diff
@@ -697,13 +697,29 @@ private void maybeCreateClassHelper(String fqClassName, String finalCode, String
...
+        boolean exceptionThrown = false;
+        try {
+            result = compiler.getTask(compilerOutput,
+                    fileManager,
+                    null,
+                    compilerOptions,
+                    null,
+                    Collections.singletonList(new JavaSourceFromString(fqClassName, finalCode)))
+                    .call();
+        } catch (final Exception err) {
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:710]: Would you really want to suppress an `Error`? Probably better to catch `Throwable`, given what's happening here.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 14]
```diff
@@ -683,62 +683,42 @@ private void maybeCreateClass(String className, String code, String packageName,
...
-    }
-
     private void maybeCreateClassHelper(String fqClassName, String finalCode, String[] splitPackageName,
             String rootPathAsString, String tempDirAsString) {
         final StringWriter compilerOutput = new StringWriter();
 
-        final JavaCompiler compiler = getJavaCompiler();
+        final JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
+        if (compiler == null) {
+            throw new RuntimeException("No Java compiler provided - are you using a JRE instead of a JDK?");
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:692]: Still better as `UncheckedDeephavenException`.

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 15]
```diff
@@ -771,7 +751,7 @@ private void maybeCreateClassHelper(String fqClassName, String finalCode, String
      * @return a Pair of success, and the compiler output
      */
     private Pair<Boolean, String> tryCompile(File basePath, Collection<File> javaFiles) throws IOException {
-        final JavaCompiler compiler = getJavaCompiler();
+        final JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
         if (compiler == null) {
             throw new RuntimeException("No Java compiler provided - are you using a JRE instead of a JDK?");
```
Comment (rcaudy) [inline engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:756]: Here, too... UDE.

**Review by rcaudy — COMMENTED** [review]
Only the comment regarding suppressing Errors is really important/actionable.

**Review by rcaudy — APPROVED** [review]

**Review by rcaudy — APPROVED** [review]

**Review by devinrsmith — APPROVED** [review]
