### PR TITLE
Fix broken calendar unit tests over midnight.

### LINKED ISSUE #5024: Calendar unit tests can fail over midnight.
```
2024-01-10T01:20:23.8901220Z > Task :engine-table:test
2024-01-10T01:20:23.8904136Z 1 compiler directives added
2024-01-10T01:20:53.3896228Z 
2024-01-10T01:20:53.3899750Z > Task :engine-time:test
2024-01-10T01:22:25.7899338Z 1 compiler directives added
2024-01-10T01:22:26.9896107Z 
2024-01-10T01:22:26.9900424Z io.deephaven.time.calendar.TestBusinessCalendar > testFutureNonBusinessDate FAILED
2024-01-10T01:22:26.9905263Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1518
2024-01-10T01:22:27.1896130Z 
2024-01-10T01:22:27.1905079Z io.deephaven.time.calendar.TestBusinessCalendar > testFutureBusinessDate FAILED
2024-01-10T01:22:27.1910054Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1507
2024-01-10T01:22:27.2127322Z 
2024-01-10T01:22:27.2131458Z io.deephaven.time.calendar.TestBusinessCalendar > testPastBusinessDate FAILED
2024-01-10T01:22:27.2137304Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1512
2024-01-10T01:22:27.4896452Z 
2024-01-10T01:22:27.4900881Z io.deephaven.time.calendar.TestBusinessCalendar > testPastNonBusinessDate FAILED
2024-01-10T01:22:27.4907836Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1528
2024-01-10T01:22:27.7897931Z 
2024-01-10T01:22:27.7902255Z io.deephaven.time.calendar.TestBusinessCalendar > testFutureDate FAILED
2024-01-10T01:22:27.7906425Z     junit.framework.AssertionFailedError at Assert.java:57
2024-01-10T01:22:27.7908125Z 
2024-01-10T01:22:27.7909725Z io.deephaven.time.calendar.TestBusinessCalendar > testCurrentDate FAILED
2024-01-10T01:22:27.7912981Z     junit.framework.AssertionFailedError at Assert.java:57
2024-01-10T01:22:27.7914660Z 
2024-01-10T01:22:27.7916207Z io.deephaven.time.calendar.TestBusinessCalendar > testPastDate FAILED
2024-01-10T01:22:27.7919383Z     junit.framework.AssertionFailedError at Assert.java:57
2024-01-10T01:22:27.7921025Z 
2024-01-10T01:22:27.7922475Z io.deephaven.time.calendar.TestCalendar > testFutureDate FAILED
2024-01-10T01:22:27.7925827Z     junit.framework.AssertionFailedError at TestCalendar.java:166
2024-01-10T01:22:27.7927609Z 
2024-01-10T01:22:27.7929172Z io.deephaven.time.calendar.TestCalendar > testCurrentDate FAILED
2024-01-10T01:22:27.7932392Z     junit.framework.AssertionFailedError at TestCalendar.java:162
2024-01-10T01:22:27.8895891Z 
2024-01-10T01:22:27.8900138Z io.deephaven.time.calendar.TestCalendar > testPastDate FAILED
2024-01-10T01:22:27.8904027Z     junit.framework.AssertionFailedError at TestCalendar.java:172
2024-01-10T01:22:28.2900146Z 1 compiler directives added
2024-01-10T01:22:29.9905713Z 
2024-01-10T01:22:29.9909226Z 187 tests completed, 10 failed
2024-01-10T01:22:30.0899186Z 
2024-01-10T01:22:30.0903256Z > Task :engine-time:test FAILED
```

### PR DESCRIPTION
**Pull request by chipkent**
Resolves #5024.

### CODE REVIEW

File: engine/time/src/test/java/io/deephaven/time/calendar/TestBusinessCalendar.java [hunk 1]
```diff
@@ -1503,29 +1503,33 @@ public void testMinusNonBusinessDays() {
     }
 
     public void testFutureBusinessDate() {
-        assertEquals(bCalendar.plusBusinessDays(DateTimeUtils.todayLocalDate(), 3), bCalendar.futureBusinessDate(3));
-        assertEquals(bCalendar.plusBusinessDays(DateTimeUtils.todayLocalDate(), -3), bCalendar.futureBusinessDate(-3));
+        assertEquals(bCalendar.plusBusinessDays(DateTimeUtils.todayLocalDate(bCalendar.timeZone()), 3),
```
Comment (devinrsmith) [inline engine/time/src/test/java/io/deephaven/time/calendar/TestBusinessCalendar.java:1506]: Wouldn't it be better to call `bCalendar.calendarDate()`?

**Review by devinrsmith — APPROVED** [review]
