### PR TITLE
Fix JS client leaking exported references, clarify dh.Widget API

### LINKED ISSUE #4903: Widgets cause leaks, do not release all resources
**Description**

Some of the objects we use (JsTreeTable, Pandas tables, JsPartitionedTable) do not manage their tickets correctly, and leak memory.

**Steps to reproduce**
1. Restart your server from a clean slate with no applications so that export tickets can be counted a little bit easier.
2. Go to a JSAPI page (http://localhost:10000/jsapi/), and run the following code in the browser console to create a connection and then print out all the export messages (replace the token `iris` with your token):
```
// REPLACE THE TOKEN WITH YOUR PSK
var token = 'iris';
var dh = (await import('./dh-core.js')).default

var c = new dh.CoreClient(window.location.protocol + "//" + window.location.host)
await c.login({type: 'io.deephaven.authentication.psk.PskAuthenticationHandler', token})

console.log('Logged in...')

var connection = await c.getAsIdeConnection()
var ide = await connection.startSession('python')

console.log('Session started...')

// Keep track of the states for all tickets. Map from ID to state.
var allStates = new Map();

// Just track the current states for the current test run.
var currentStates = new Map();

var STATE_COLORS = {
    'EXPORTED': 'red',
    'RELEASED': 'green',
};

// Listen for SessionState messages
ide.onLogMessage(({ message }) => {
    // We only want to see messages that contain export messages
    const matches = message.match(/export \'(.+)\' is ExportState\.(.+)/);
    if (matches == null) {
        return;
    }

    const [ , exportId, state ] = matches;
    if (exportId.length > 4) {
        // Non-exports are given hex strings for their exportId: https://github.com/deephaven/deephaven-core/blob/6d1d1c96c79d7121763365ceff59f1004b3539fd/server/src/main/java/io/deephaven/server/session/SessionState.java#L590
        // We don't care about these exports
        return;
    }
    allStates.set(exportId, state);
    currentStates.set(exportId, state);
    
    const stateColor = STATE_COLORS[state] ?? 'yellow';
    console.log('[State Update] %s => %c%s', exportId, `background: ${stateColor}`, state);
});

// Add debug logging for SessionState
await ide.runCode(`
import jpy
logger = jpy.get_type('org.slf4j.LoggerFactory').getLogger('io.deephaven.server.session.SessionState')
jpy.cast(logger, jpy.get_type('ch.qos.logback.classic.Logger')).setLevel(jpy.get_type('ch.qos.logback.classic.Level').DEBUG)
`)

async function fetchWidgetExportedObjects(widget) {
    const fetchedObjects = await Promise.all(
        widget.exportedObjects.map(eo => {
            console.log('Fetching exported object', eo);
            return eo.fetch();
        })
    );

    await Promise.all(
        fetchedObjects.filter(o => o.exportedObjects != null).map(o => fetchWidgetExportedObjects(o))        
    );

    fetchedObjects.forEach(fo => { 
        console.log('Closing exported object', fo);
        fo.close() 
    });
}

// Add some helper functions that will be used below
async function fetchAndCloseVariable(varDef, fetchExportedObjects) {
    console.log('Fetching', varDef.title)
    
    const o = await connection.getObject(varDef)

    console.log('Obtained', varDef.title, o, 'closing...')

    if (fetchExportedObjects) {
        await fetchWidgetExportedObjects(o);
    }

    o.close()
    
    console.log('Closed', varDef.title)

    // We need to wait for the close to actually finish. 1s should be more than enough for these purposes, since there's no promise we can actually await on.
    await new Promise(r => setTimeout(r, 1000));
}

async function testCode(code, fetchExportedObjects = false) {
    currentStates.clear()
    var result = await ide.runCode(code);
    var updates = [...result.changes.created, ...result.changes.updated]
    try {
        await Promise.all(updates.map(update => fetchAndCloseVariable(update, fetchExportedObjects)));
    } catch (e) {
        console.error('Error while trying to run tests', e);
    }
    
    let releasedCount = 0;
    const testStates = new Map(currentStates);
    testStates.forEach((state, exportId) => {
        if (state === 'RELEASED') {
            releasedCount++;
        }
    });

    const isSuccess = releasedCount === testStates.size;
    
    console.groupCollapsed('[TEST RESULTS]: %c %s: %s/%s objects released', `background: ${isSuccess ? 'green' : 'red'}`, isSuccess ? 'PASS': 'FAIL', releasedCount, testStates.size);
    console.dir(testStates);
    console.groupEnd();
}
```
3. Run the following snippet to create a regular table, fetch it, and then close it:
```
await testCode(`
from deephaven import empty_table
t = empty_table(1)
`)
```
4. Run the following snippet to create a Pandas table, fetch it, and then close it:
```
await testCode(`
import pandas as pd
df = pd.DataFrame()
`)
```
5. Run the following snippet to create a HierarchicalTable, fetch it, then close it:
```
await testCode(`
from deephaven import empty_table
r = empty_table(1).rollup(aggs=None, by=[])
`)
```

6. Run the following snippet to create a Plotly Express widget, fetch it, and then close it:
```
await testCode(`
from deephaven import empty_table
from deephaven.plot import express as dx

w = dx.line(empty_table(100).update(["x=i", "y=i*(-i)"]), x="x", y="y")
`, true)
```
7. Run the following to create a PartitionedTable, fetch it, and then close it:
```
await testCode(`
from deephaven import empty_table
pt = empty_table(10000).update(["x=(int)Math.floor(i/100)", "y=(int)Math.floor(i/10)", "z=i"]).partition_by(["x", "y"])
`)
```
8. Figure:
```
await testCode(`
from deephaven import empty_table
from deephaven.plot.figure import Figure

p = Figure().plot_xy(series_name="Test", t=empty_table(100).update(["x=i", "y=i*(-i)"]), x="x", y="y").show()
`)
```
9. deephaven.ui widget exporting another widget:
```
await testCode(`
from deephaven import empty_table, ui
from deephaven.plot import express as dx

@ui.component
def foo():
    return dx.line(empty_table(100).update(["x=i", "y=i*(-i)"]), x="x", y="y")

f = foo()
`, true)
```

**Expected results**
3,4,5,6: All tickets allocated should be released after a close

**Actual results**
3. All tickets are released (2)
4. Export ticket 3 is never released, and there is a ticket with ID -1 exported? (though -1 is released)
5. Export ticket 4 is never released
6. Export ticket -2 is never released
7. Export tickets 6 and -3 are never released

A clear and concise description of what actually happened.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 7e596a603b9e685c09b948bf63d7b9a6a7642854

### PR DESCRIPTION
**Pull request by niloc132**
This PR is an update to https://github.com/deephaven/deephaven-core/pull/4909.

JsPartitionedTable, JsFigure, PandasTable were previously being leaked even with correct usage, ensure that those are released when client code calls close(). Additionally, partitioned tables would be re-exported unnecessarily, but only the re-export was released, leaking the original reference.

Widget and WidgetExportedObject had documentation indicating how to consume exported objects, but these rules were not enforced. The rules have changed to be more consistent and are enforced, which should avoid later confusion, and new documentation added to propose potential patterns to follow when authoring plugins.

Fixes #4903

### CODE REVIEW

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java [hunk 1]
```diff
@@ -34,15 +33,57 @@
...
+ * the user access to table manipulation/creation methods not supported by gRPC or the JS API.</li>
+ * <li>The plugin provides reference to Tables and other objects that only make sense within the context of the widget
+ * instance, so when the widget goes away, those objects should be released as well. This is also an example of
+ * {@link io.deephaven.web.client.api.JsPartitionedTable}, as the partitioned table tracks creation of new keys through
+ * an internal table instance.</li>
+ * </ul>
+ *
+ * Handling server objects in messages also has more than one potential pattern that can be used:
+ * <ul>
+ * <li>One object per message - the message clearly is about that message, no other details required.</li>
```
Comment (mofojed) [inline web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java:77]:
```suggestion
 * <li>One object per message - the message clearly is about that object, no other details required.</li>
```

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java [hunk 2]
```diff
@@ -29,13 +34,46 @@ public class JsWidgetExportedObject implements ServerObject {
...
     private final TypedTicket ticket;
 
+    private final JsLazy<Promise<?>> fetched;
+
     public JsWidgetExportedObject(WorkerConnection connection, TypedTicket ticket) {
         this.connection = connection;
         this.ticket = ticket;
+        this.fetched = JsLazy.of(() -> {
+            if (getType() == null) {
+                return Promise.reject("Exported object has no type, can't be fetched");
```
Comment (mofojed) [inline web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:44]: Is this a case that actually happens?

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java [hunk 3]
```diff
@@ -47,32 +85,47 @@ public TypedTicket typedTicket() {
...
+     */
+    @JsMethod
+    public Promise<JsWidgetExportedObject> reexport() {
+        Ticket reexportedTicket = connection.getConfig().newTicket();
+        return Callbacks.grpcUnaryPromise(c -> {
+            ExportRequest req = new ExportRequest();
+            req.setSourceId(ticket.getTicket());
+            req.setResultId(reexportedTicket);
+            connection.sessionServiceClient().exportFromTicket(req, connection.metadata(), c::apply);
+        }).then(success -> {
```
Comment (mofojed) [inline web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:102]: The downside of this is the extra round trip (not a `TicketAndPromise`), but it is a lot cleaner this way.

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java [hunk 4]
```diff
@@ -47,32 +85,47 @@ public TypedTicket typedTicket() {
...
     /**
-     * Releases the server-side resources associated with this object, regardless of whether or not other client-side
-     * objects exist that also use that object.
+     * Releases the server-side resources associated with this object, regardless of whether other client-side objects
+     * exist that also use that object. Should not be called after fetch() has been invoked.
      */
     @JsMethod
     public void close() {
-        connection.releaseTicket(ticket.getTicket());
+        if (!fetched.isAvailable()) {
```
Comment (mofojed) [inline web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:127]: Is it worth warning in the `else` case? Or a debug log?

**Review by mofojed — CHANGES_REQUESTED** [review]
Minor doc correction, couple of questions/comments.

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java (hunk 2 above)
Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:44]: it sure can - make some python object that doesnt have a plugin, and send it from the server using `stream.on_data(..., [my_obj])`. The object will be exported, the client will have a reference to it (but can't `fetch()` it), can pass that back to the server via `dh.Widget.sendMessage()`.

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java (hunk 3 above)
Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:102]: Oh right - I can make it less clean and less round trippy....

Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:102]: Hmm. I can, but then there will be zero round trips, and we would be ignoring failure (if any) from the exportFromTIcket call, and would only find out after trying to use the resulting object.

In that case, we could stop returning promise entirely.

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java (hunk 2 above)
Comment (mofojed) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:44]: Ah yea true. Client will want to close those, but not fetch those... If you do try and fetch it, it'll reject, but then you won't be able to close it. Release the ticket here instead, since they already screwed up trying to fetch something they shouldn't?

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java (hunk 3 above)
Comment (mofojed) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:102]: I'm indifferent. Could file a ticket to optimize this in the future?

File: web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java (hunk 2 above)
Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java:44]: I've locally added a guard to prevent fetching (and throw an error in that case), but close() can still be done later.

**Review by mofojed — APPROVED** [review]
