### PR TITLE
fix: DH-22265: increment Kafka column index for complex spec

### LINKED ISSUE #7884: Kafka: Chunk sizes don't match error when combining jsonSpec and simpleSpec
**Description**

I tried to consume a Kafka topic to a table with a jsonSpec extracting a single column from the key and a simpleSpec to get the value as another column.
It resulted in an error like:
Chunk sizes don't match: 500, 500, 500, 1000, 0
Debugging, it looks like 500 records are processed and the 3 automatically added Kafka columns have a matching chunk size, but my key column has 1000 and the value column 0?

If I change the key spec to a simpleSpec it works.

**Versions**
 - Deephaven: 41.0

### PR DESCRIPTION
**Pull request by devinrsmith**
This fixes a bug where the column indexing is incorrectly calculated; it only manifests when the key spec is "complex" and the value spec is "simple".

Fixes #7884

### CODE REVIEW

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java [hunk 1]
```diff
@@ -1273,9 +1287,9 @@ private static ConsumeStruct getConsumeStruct(
                     cc.setColumnIndex.setColumnIndex(publisherParametersBuilder, nextColumnIndex.getAndIncrement());
                 });
 
-        final KeyOrValueIngestData keyIngestData = keySpec.getIngestData(KeyOrValue.KEY,
+        final KeyOrValueIngestData keyIngestData = keySpec.ingestDataAndIncrement(KeyOrValue.KEY,
                 schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
-        final KeyOrValueIngestData valueIngestData = valueSpec.getIngestData(KeyOrValue.VALUE,
+        final KeyOrValueIngestData valueIngestData = valueSpec.ingestDataAndIncrement(KeyOrValue.VALUE,
                 schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
```
[the remark this answers is not in the document]
Comment (devinrsmith) [reply extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]: Testing will be in a follow-up PR.

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java [hunk 2]
```diff
@@ -336,6 +336,45 @@ protected abstract KeyOrValueIngestData getIngestData(
             protected abstract KeyOrValueProcessor getProcessor(
                     TableDefinition tableDef,
                     KeyOrValueIngestData data);
+
+            private KeyOrValueIngestData ingestDataAndIncrement(
```
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]:
```suggestion
            private KeyOrValueIngestData getIngestDataAndIncrementColumnIndex(
```

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java [hunk 3]
```diff
@@ -336,6 +336,45 @@ protected abstract KeyOrValueIngestData getIngestData(
...
+                    KeyOrValue keyOrValue,
+                    SchemaRegistryClient schemaRegistryClient,
+                    Map<String, ?> configs,
+                    MutableInt nextColumnIndexMut,
+                    List<ColumnDefinition<?>> columnDefinitionsOut) {
```
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]:
```suggestion
                    final KeyOrValue keyOrValue,
                    final SchemaRegistryClient schemaRegistryClient,
                    final Map<String, ?> configs,
                    final MutableInt nextColumnIndexMut,
                    final List<ColumnDefinition<?>> columnDefinitionsOut) {
```

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java [hunk 4]
```diff
@@ -1273,10 +1312,10 @@ private static ConsumeStruct getConsumeStruct(
...
                 });
 
-        final KeyOrValueIngestData keyIngestData = keySpec.getIngestData(KeyOrValue.KEY,
-                schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
-        final KeyOrValueIngestData valueIngestData = valueSpec.getIngestData(KeyOrValue.VALUE,
-                schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
+        final KeyOrValueIngestData keyIngestData = keySpec.ingestDataAndIncrement(
+                KeyOrValue.KEY, schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
+        final KeyOrValueIngestData valueIngestData = valueSpec.ingestDataAndIncrement(
+                KeyOrValue.VALUE, schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
```
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]:
```suggestion
        final KeyOrValueIngestData keyIngestData = keySpec.getIngestDataAndIncrementColumnIndex(
                KeyOrValue.KEY, schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
        final KeyOrValueIngestData valueIngestData = valueSpec.getIngestDataAndIncrementColumnIndex(
                KeyOrValue.VALUE, schemaRegistryClient, configs, nextColumnIndex, columnDefinitions);
```

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java [hunk 5]
```diff
@@ -336,6 +336,45 @@ protected abstract KeyOrValueIngestData getIngestData(
...
+                final int ixPre = nextColumnIndexMut.get();
+                final int sizePre = columnDefinitionsOut.size();
+                // It's unfortunate we have to do this; but the getIngestData signature and design of KeyOrValueSpec
+                // would need a breaking change to improve in these regards.
+                final KeyOrValueIngestData ingestData = getIngestData(keyOrValue, schemaRegistryClient, configs,
+                        nextColumnIndexMut, columnDefinitionsOut);
+                final int addedIx = nextColumnIndexMut.get() - ixPre;
+                final int addedColumns = columnDefinitionsOut.size() - sizePre;
+                if (ingestData == null) {
+                    // ignore case (or, possible a complex impl that chooses to return null when it's empty):
```
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]:
```suggestion
                    // ignore case (or, possibly a complex impl that chooses to return null when it's empty):
```

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java [hunk 6]
```diff
@@ -336,6 +336,45 @@ protected abstract KeyOrValueIngestData getIngestData(
...
+                    if (addedIx != 0 || addedColumns != 0) {
+                        throw new IllegalStateException(
+                                "KeyOrValueSpec getIngestData is modifying out-variables without returning ingest data");
+                    }
+                } else if (ingestData.isSimple()) {
+                    // simple case:
+                    // expecting exactly one increment and one column
+                    if (addedIx != 1 || addedColumns != 1) {
+                        throw new IllegalStateException(
+                                "Simple KeyOrValueSpec getIngestData is not adding exactly one index or one column");
```
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]:
```suggestion
                                "Simple KeyOrValueSpec getIngestData is not adding exactly one index and one column");
```

File: extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java (hunk 2 above)
Comment (rcaudy) [inline extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java]: Maybe:
```
            protected KeyOrValueIngestData getIngestData(
                    KeyOrValue keyOrValue,
                    SchemaRegistryClient schemaRegistryClient,
                    Map<String, ?> configs,
                    int nextColumnIndex,
                    List<ColumnDefinition<?>> columnDefinitionsOut) {
                return getIngestData(keyOrValue, schemaRegistryClient, configs, new MutableInt(nextColumnIndex),
                        columnDefinitionsOut);
            }

            private KeyOrValueIngestData getIngestDataAndIncrementColumnIndex(
                    final KeyOrValue keyOrValue,
                    final SchemaRegistryClient schemaRegistryClient,
                    Map<String, ?> configs,
                    MutableInt nextColumnIndexMut,
                    List<ColumnDefinition<?>> columnDefinitionsOut) {
                final int ixPre = nextColumnIndexMut.get();
                final int sizePre = columnDefinitionsOut.size();
                // It's unfortunate we have to do this; but the getIngestData signature and design of KeyOrValueSpec
                // would need a breaking change to improve in these regards.
                final KeyOrValueIngestData ingestData = getIngestData(keyOrValue, schemaRegistryClient, configs,
                        ixPre, columnDefinitionsOut);
                final int addedColumns = columnDefinitionsOut.size() - sizePre;
                if (ingestData == null) {
                    // ignore case (or, possible a complex impl that chooses to return null when it's empty):
                    // expecting no modifications
                    if (addedColumns != 0) {
                        throw new IllegalStateException(
                                "KeyOrValueSpec getIngestData is modifying out-variables without returning ingest data");
                    }
                } else {
                    nextColumnIndexMut.set(ixPre + addedColumns);
                }
                return ingestData;
            }
        }
```

**Review by rcaudy — COMMENTED** [review]
I think we're being a bit brittle.

**Review by rcaudy — DISMISSED** [review]
Approving, but I liked my simpler version that absolved the implementations of any responsibility for mutating the index quite a lot more. This version has an awful lot of validation and warning trace that only benefits anyone if the current nonsense implementation is desirable long-term.

**Review by rcaudy — APPROVED** [review]
I think the commented-out warnings are ugly, but I'm willing to compromise here.
