### PR TITLE
Better failure messages related to LFS

### LINKED ISSUE #4561: Improve error message for Git LFS related failures
As part of #4421, we moved all parquet files from the core repo to Git LFS. So now, on pulling the core repo, these files don't get fetched by default in case Git LFS is not installed on the system. This can lead to errors like the following while running tests locally:
```
    Caused by: io.deephaven.parquet.base.ParquetFileReaderException: extensions/parquet/table/build/resources/test/e1/uncompressed.parquet is not a Parquet file. expected magic number at tail [80, 65, 82, 49] but found [55, 49, 48, 10]
    at app//io.deephaven.parquet.base.ParquetFileReader.<init>(ParquetFileReader.java:62)
    at app//io.deephaven.parquet.table.ParquetTools.getParquetFileReaderChecked(ParquetTools.java:801)
    at app//io.deephaven.parquet.table.ParquetTools.getParquetFileReader(ParquetTools.java:784)
    ... 50 more
```
The fix is to run `git lfs install; git lfs pull` inside the repo.
We should make the error message more clear with the above instructions to fix it. Also, we should update the README to mention setup instructions for Git LFS.

### PR DESCRIPTION
**Pull request by malhotrashivam**
Closes #4561

### CODE REVIEW

**Review by rcaudy — DISMISSED** [review]

File: extensions/parquet/base/src/main/java/io/deephaven/parquet/base/InvalidParquetFileException.java [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package io.deephaven.parquet.base;
+
+public class InvalidParquetFileException extends ParquetFileReaderException {
```
Comment (niloc132) [inline extensions/parquet/base/src/main/java/io/deephaven/parquet/base/InvalidParquetFileException.java:3]: Javadoc? alternatively, change the test to catch any ParquetFileReaderException and just check the `message` to see if it is this kind of failure?

Comment (malhotrashivam) [reply extensions/parquet/base/src/main/java/io/deephaven/parquet/base/InvalidParquetFileException.java:6]: I feel that a different exception is less error prone than relying on the message string. So added a Javadoc for now. Hope that's okay.

**Review by niloc132 — APPROVED** [review]

**Review by chipkent — APPROVED** [review]
