### PR TITLE
Log User-Friendly Error When AutoComplete is not Available

### LINKED ISSUE #4315: Non-autocomplete py-env throws jedi Exception on startup
Follow the instructions here for non-autocomplete python setup:
https://github.com/deephaven/deephaven-core/tree/main/server/jetty-app#python-quickstart

Then start up the server:

On the console we see the following exception printed on start:
```
qtp79706679-65       | .c.ConsoleServiceGrpcImpl | Error trying to enable jedi autocompleteio.deephaven.engine.context.QueryScope$MissingVariableException: No variable for: jedi_settings
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$getVariable$0(PythonDeephavenSession.java:164)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.deephaven.integrations.python.PythonDeephavenSession.getVariable(PythonDeephavenSession.java:164)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.autoCompleteStream(ConsoleServiceGrpcImpl.java:284)
	at io.deephaven.server.util.GrpcServiceOverrideBuilder$BidiStreamMethod.invoke(GrpcServiceOverrideBuilder.java:309)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler.startCall(ServerCalls.java:235)
	at io.deephaven.server.browserstreaming.BrowserStreamInterceptor.interceptCall(BrowserStreamInterceptor.java:69)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceInterceptor.lambda$interceptCall$0(SessionServiceGrpcImpl.java:351)
	at io.deephaven.server.session.SessionServiceGrpcImpl.rpcWrapper(SessionServiceGrpcImpl.java:425)
	at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceInterceptor.interceptCall(SessionServiceGrpcImpl.java:350)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.deephaven.grpc.AbstractMtlsClientCertificateInterceptor.lambda$interceptCall$1(AbstractMtlsClientCertificateInterceptor.java:27)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.deephaven.grpc.AbstractMtlsClientCertificateInterceptor.interceptCall(AbstractMtlsClientCertificateInterceptor.java:27)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:704)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:407)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:616)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:604)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.streamCreatedInternal(ServerImpl.java:645)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.streamCreated(ServerImpl.java:466)
	at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.createStream(AbstractWebsocketStreamImpl.java:94)
	at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.processHeaders(MultiplexedWebSocketServerStream.java:253)
	at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onMessage(MultiplexedWebSocketServerStream.java:191)
	at io.grpc.servlet.web.websocket.AbstractWebSocketServerStream.lambda$onOpen$0(AbstractWebSocketServerStream.java:115)
	at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.invoke(AbstractDecodedMessageSink.java:61)
	at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.onWholeMessage(DecodedBinaryMessageSink.java:60)
	at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.accept(ByteBufferMessageSink.java:64)
	at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:592)
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onBinary(JakartaWebSocketFrameHandler.java:642)
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:243)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1485)
	at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671)
	at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
	at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480)
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413)
	at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:369)
	at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #4315

### CODE REVIEW

File: server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java [hunk 1]
```diff
@@ -283,7 +288,15 @@ public StreamObserver<AutoCompleteRequest> autoCompleteStream(
...
-                log.error().append("Error trying to enable jedi autocomplete").append(err).endl();
+                if (err instanceof QueryScope.MissingVariableException) {
+                    if (!ALREADY_WARNED_ABOUT_NO_AUTOCOMPLETE.getAndSet(true)) {
+                        log.error().append("Autocomplete package not found; disabling autocomplete.").endl();
+                        log.error().append("Add the jvm flag '-D").append(DISABLE_AUTOCOMPLETE_FLAG)
+                                .append("=true' to disable this message.").endl();
+                    }
+                } else {
+                    log.error().append("Error trying to enable jedi autocomplete").append(err).endl();
+                }
```
Comment (devinrsmith) [inline server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java:299]: I don't know if specifically checking against MissingVariableException is something we need to do - I say catch any exception and set the flag.

Additionally, I think mentioning `pip install deephaven-core[autocomplete]==<version>` as a potential fix would be helpful here.

**Review by devinrsmith — APPROVED** [review]
