### PR TITLE
Proposed fix for scope snapshot diff gaps

### LINKED ISSUE #4145: ScriptSession API to ensure snapshots/diffs of bindings are always consistent.
Original title/topic: Generalize script session "deltas", probably by letting the script session entirely control snapshots internally, rather than expose this directly, such as by returning changes when running script code. This will also deal with some potential races, making it the script session implementation's responsibility to not lose track of changes.

Split off from #2453 to be its own issue.

This was found to be broken, where assigning/nulling a binding rapidly can break the application service's internal state, by missing changes and emitting inconsistent updates:
```python
from deephaven_server import Server
s = Server()
s.start()

import time
from deephaven import empty_table, time_table

while True:
    t = time_table("PT1m")
    time.sleep(.04)
    t = None
    time.sleep(.04)
```
Usually takes 10s-1minute to fail.

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #4145

### CODE REVIEW

File: py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java [hunk 1]
```diff
@@ -115,24 +114,10 @@ public void start() throws Exception {
...
-                // We are limited in how we can track external changes, and the web IDE has made this change and
-                // already applied it.
-                // Take a fresh snapshot right away to continue polling
-                nextSnapshot = scriptSession.snapshot();
-            } else {
-                throw e;
-            }
-        }
-        ScriptSession.SnapshotScope s = nextSnapshot;
+    private void checkGlobals(ScriptSession scriptSession) {
```
Comment (niloc132) [inline py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java:117]: This should probably move into ScriptSession, and make the delay configurable?

File: engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java [hunk 2]
```diff
@@ -96,31 +98,25 @@ public ExecutionContext getExecutionContext() {
...
-            applyDiff(beforeSnapshot, afterSnapshot, null);
+    private synchronized Changes observeScopeChangesInternal(@Nullable final RuntimeException evaluationError) {
+        final S beforeSnapshot = lastSnapshot;
+        lastSnapshot = takeSnapshot();
+        try (beforeSnapshot) {
+            return applyDiff(beforeSnapshot, lastSnapshot, evaluationError);
         }
     }
 
+    protected interface Snapshot extends SafeCloseable {
```
Comment (niloc132) [inline engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java:118]: Thought (that shouldn't preclude merging): If this is protected and we're removing the generics and other members, do we need generics anymore? As it is protected and not accessible from any non-protected methods, I don't think we need to consider it at all.

Consider: initialSnapshot only runs in the constructor anyway (obligatory "don't call abstract/non-final methods in a constructor), and takeSnapshot()/applyDiff() is only called by observeScopeChangesInternal.. I haven't gone through the exercise yet, but it might be possible to get rid of most of this, pushing it down to just part of the Snapshot interface/implementation, and let the script session not care/cast about what type it has (but the subclass would work out specifics).

**Review by niloc132 — DISMISSED** [review]
Please link to https://github.com/deephaven/deephaven-core/issues/4145 for this.

Verified that the changed APIs won't affect DnD.

File: engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java (hunk 2 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java:118]: Let's defer this to a subsequent issue.

File: Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java [hunk 3]
```diff
@@ -280,24 +280,25 @@ public boolean hasVariableName(String name) {
...
-                    globals.delItem(name);
-                } catch (KeyError key) {
-                    // ignore
-                }
-            } else {
-                if (!(newValue instanceof PyObject)) {
-                    newValue = PythonObjectWrapper.wrap(newValue);
-                }
-                globals.setItem(name, newValue);
+        // Observe any external changes that are not yet recorded
```
Comment (niloc132) [inline Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java:283]: Matching change needs to happen to the groovy script session, the notifyVariableChange method is called from there (and should be deleted), since it will notify the app service of a new variable... racing the current snapshot.

**Review by jmao-denver — APPROVED** [review]
LGTM

File: server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java [hunk 4]
```diff
@@ -167,6 +171,13 @@ public DeephavenApiServer run() throws IOException, ClassNotFoundException, Time
         return this;
     }
 
+    private void checkGlobals(ScriptSession scriptSession) {
+        scriptSession.observeScopeChanges();
+        scheduler.runAfterDelay(100, () -> {
```
Comment (niloc132) [inline server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java:176]: should we parameterize this, so that in case 100ms breaks things, we can turn it down/off by configuration?

**Comment by niloc132** [comment]
My testing seems to show that this does the job. First, running the python script in the linked issue (ran three times for 5+ mins each), then these two script commands:

## Python
```python
from deephaven.execution_context import get_exec_ctx
@get_exec_ctx()
def doStuff():
    global t
    from deephaven import time_table
    t = time_table("PT1s").update("I=i")
import threading
thread = threading.Thread(target=doStuff)
```
before this, the table wouldn't show up, after the fix it correctly shows up in the table dropdown in the UI right away.

## Groovy
```groovy
ec = io.deephaven.engine.context.ExecutionContext.getContext()
Thread.start({ -> ec.open(); getBinding().setVariable("asdf", timeTable("PT1s"))  })
```
Before this fix sometimes this would cause an error, sometimes it would just not show the table in the dropdown, afterwards the table shows up in the UI right away.

**Review by niloc132 — APPROVED** [review]

**Review by jmao-denver — APPROVED** [review]
