### PR TITLE
Fix UpdateByListener.satisfied() and JobScheduler.IterationManager handling for errors in error reporting

### LINKED ISSUE #4063: Parallel task double-close error
```
2023-06-16T18:06:14.054Z | [32mEFAULT.refreshThread[0;39m | [34m INFO[0;39m | [33me.u.i.PeriodicUpdateGraph[0;39m | Update Graph Processor cycleTime=55456.845ms, safePointTime=0ms, safePointTimePct=0%, safePointSyncTime=0ms, lockWaitTime=19.015ms, yieldTime=0ms, sleepTime=0ms
Initiating shutdown due to: Unexpected iteration job error
java.lang.IllegalStateException: IterationManager-334517681's reference count has been decreased more than increased
	at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:218)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onTaskError(JobScheduler.java:173)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.accept(JobScheduler.java:279)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.run(JobScheduler.java:251)
	at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted closed == false, instead closed == true.
		at io.deephaven.base.verify.Assert.fail(Assert.java:100)
		at io.deephaven.base.verify.Assert.eqFalse(Assert.java:1022)
		at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:285)
		at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.accept(JobScheduler.java:278)
		... 9 more
```

### LINKED ISSUE #4358: update_by assertion failure
Triggered while creating kafka query.

```
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 933, updateGraph.clock().currentStep() == 933.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.BaseTable.notifyListenersOnError(BaseTable.java:806)
        at io.deephaven.engine.table.impl.updateby.UpdateBy.deliverUpdateError(UpdateBy.java:1059)
        at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.onError(UpdateBy.java:1010)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:183)
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:292)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:284)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:256)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
        at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
        at org.jpy.PyLib.callAndReturnObject(Native Method)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Code looked something like:

```python
from deephaven import dtypes
from deephaven.execution_context import get_exec_ctx
from deephaven.stream.kafka.consumer import (
    consume_to_partitioned_table,
    simple_spec,
    TableType,
    ALL_PARTITIONS_SEEK_TO_BEGINNING,
)
from deephaven.table import Table
from deephaven.updateby import cum_max


ctx = get_exec_ctx()


def max_date(t: Table) -> Table:
    with ctx:
        return (
            t.update_by([cum_max(["MaxTimestamp = KafkaTimestamp"])])
            .update_view(["Date=formatDate(MaxTimestamp, java.time.ZoneOffset.UTC)"])
            .drop_columns(["MaxTimestamp"])
        )


# todo: is there a way to do this without merge()? ie, re-partition?
my_partitioned_table = (
    consume_to_partitioned_table(
        kafka_config={
            "bootstrap.servers": "myserver:9092",
        },
        topic="my_topic",
        offsets=ALL_PARTITIONS_SEEK_TO_BEGINNING,
        key_spec=simple_spec("KafkaKey", dtypes.byte_array),
        value_spec=simple_spec("KafkaValue", dtypes.byte_array),
        table_type=TableType.append(),
    )
    .transform(max_date)
    .merge()
    .partition_by(["KafkaPartition", "Date"])
)
```

I'm not sure if other interactive snippets I executed may have caused the error.

### LINKED ISSUE #4391: ZeroKeyUpdateByManager NPE
```
2023-08-29T15:49:22.781Z | EFAULT.refreshThread |  WARN | i.d.e.u.LogicalClockImpl  | LogicalClockImpl cycle was not completed in normal operation, value=40                                                                                 
Initiating shutdown due to: Uncaught exception in thread PeriodicUpdateGraph.DEFAULT.refreshThread                                                                                                                                           
java.lang.RuntimeException: Error in Python interpreter:                                                                                                                                                                                     
Type: <class 'RuntimeError'>                                                                                                                                                                                                                 
Value: java.lang.NullPointerException: Cannot read field "result" because "this.zeroKeyUpdateBy" is null                                                                                                                                     
        at io.deephaven.engine.table.impl.updateby.ZeroKeyUpdateByManager.upstreamSatisfied(ZeroKeyUpdateByManager.java:123)                                                                                                                 
        at io.deephaven.engine.table.impl.updateby.UpdateBy$UpdateByListener.canExecute(UpdateBy.java:1117)                                                                                                                                  
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.canExecute(InstrumentedTableListenerBase.java:311)                                                                                                  
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.flushNormalNotificationsAndCompleteCycle(PeriodicUpdateGraph.java:1184)                                                                                                  
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.flushNotificationsAndCompleteCycle(PeriodicUpdateGraph.java:1145)                                                                                                        
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.lambda$doRefresh$12(PeriodicUpdateGraph.java:1839)                                                                                                                       
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)                                                                                                                                                           
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.doRefresh(PeriodicUpdateGraph.java:1827)                                                                                                                                 
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshAllTables(PeriodicUpdateGraph.java:1814)                                                                                                                          
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshTablesAndFlushNotifications(PeriodicUpdateGraph.java:1659)                                                                                                        
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.lambda$new$3(PeriodicUpdateGraph.java:330)                                                                                                                               
        at org.jpy.PyLib.callAndReturnObject(Native Method) 
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

May be the same issues as https://github.com/deephaven/deephaven-core/issues/4358, just failing in a different way.

```
After shutdown initiated: Unexpected iteration job error
java.lang.IllegalStateException: IterationManager-165022758's reference count has been decreased more than increased
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:218)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onTaskError(JobScheduler.java:175)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:283)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:256)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
        at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
        at org.jpy.PyLib.callAndReturnObject(Native Method)
        at org.jpy.PyObject.call(PyObject.java:449)
```

### PR DESCRIPTION
**Pull request by rcaudy**
Fixes #4063
Fixes #4391
Fixes #4358

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java [hunk 1]
```diff
@@ -180,13 +180,23 @@ private void onTaskError(@NotNull final Exception e) {
         protected void onReferenceCountAtZero() {
             final Exception localException = exception.get();
             if (localException != null) {
-                onError.accept(localException);
+                try {
+                    onError.accept(localException);
+                } catch (Exception e) {
+                    e.initCause(localException);
```
Comment (cpwright) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java:186]: It says this can only be called once, so if we have a throwable with a cause from accept; will this defeat the point?  Perhaps we should log "localException" and report "e".

File: engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java [hunk 2]
```diff
@@ -1116,9 +1096,30 @@ public void onFailureInternal(@NotNull final Throwable originalException, @Nulla
         public boolean canExecute(final long step) {
             return upstreamSatisfied(step);
         }
+
+        @Override
+        public boolean satisfied(final long step) {
+            if (super.satisfied(step)) {
```
Comment (cpwright) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java:1102]: If we inverted this if condition, the method would read more linearly.

File: engine/test-utils/build.gradle [hunk 3]
```diff
@@ -13,6 +13,7 @@ dependencies {
     implementation project(':engine-tuple')
     implementation project(':base-test-utils')
     implementation project(':engine-rowset-test-utils')
+    implementation project(':FishUtil')
```
Comment (cpwright) [inline engine/test-utils/build.gradle:16]: maybe in your next release change this from "Fish".

Comment (rcaudy) [reply engine/test-utils/build.gradle:16]: Yeah, we have a cleanup issue, too. I'll see what survives.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java (hunk 1 above)
Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java]: Used addSuppressed at your suggestion. Good catch!

**Review by cpwright — DISMISSED** [review]

**Review by cpwright — APPROVED** [review]
