### PR TITLE
fix: Fix PartitioningColumnDataIndex: region RowSet provenance and index RowSet tracking

### LINKED ISSUE #5916: NPE in update processing for a PartitioningColumnDataIndex when sorted by first row key
A user testing a POC integration with Deephaven `SourceTable`-level APIs reported the following stack trace, but this has not been reproduced so far:
```
ph-updateExecutor-14 | rumentedTableListenerBase | Uncaught exception for entry= sortInternal, added.size()=0, modified.size()=49, removed.size()=0, shifted.size()=0, modifiedColumnSet={dh_row_set,__FRK__}: java.lang.NullPointerException
at io.deephaven.engine.table.impl.select.FunctionalColumnLong.lambda$new$0(FunctionalColumnLong.java:52)
at io.deephaven.engine.table.impl.select.FunctionalColumnLong$1.getLong(FunctionalColumnLong.java:131)
at io.deephaven.engine.table.impl.chunkfillers.LongChunkFiller.lambda$fillByIndices$1(LongChunkFiller.java:45)
at io.deephaven.engine.rowset.RowSet.lambda$forAllRowKeys$0(RowSet.java:312)
at io.deephaven.engine.rowset.impl.sortedranges.SortedRanges.forEachLong(SortedRanges.java:433)
at io.deephaven.engine.rowset.impl.sortedranges.SortedRanges.ixForEachLong(SortedRanges.java:4615)
at io.deephaven.engine.rowset.impl.WritableRowSetImpl.forEachRowKey(WritableRowSetImpl.java:339)
at io.deephaven.engine.rowset.RowSet.forAllRowKeys(RowSet.java:311)
at io.deephaven.engine.table.impl.chunkfillers.LongChunkFiller.fillByIndices(LongChunkFiller.java:44)
at io.deephaven.engine.table.impl.select.FunctionalColumnLong$1.fillChunk(FunctionalColumnLong.java:165)
at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
at io.deephaven.engine.table.impl.SortHelpers.makeAndFillValues(SortHelpers.java:788)
at io.deephaven.engine.table.impl.SortHelpers.doChunkSortingOne(SortHelpers.java:513)
at io.deephaven.engine.table.impl.SortHelpers.getSortMappingOne(SortHelpers.java:469)
at io.deephaven.engine.table.impl.SortHelpers.getSortedKeys(SortHelpers.java:263)
at io.deephaven.engine.table.impl.SortListener.onUpdate(SortListener.java:235)
at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:334)
at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:316)
at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:711)
at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:836)
at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
at java.base/java.lang.Thread.run(Thread.java:829)
```

It appears to be the case that:
1. We had a ticking `TransformedDataIndex` (with a `sortByFirstRowKey` applied, so presumably for an aggregation).
2. The data index table contained a `null` row set at one of the modified row keys.
3. Given the circumstances, the data index is likely a `PartitioningColumnDataIndex`. Users would not have had any indexed columns, and the data set is clearly refreshing. User also unlikely to have created a `TableBackedDataIndex`.

### PR DESCRIPTION
**Pull request by rcaudy**
May fix #5916

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java [hunk 1]
```diff
@@ -295,7 +295,7 @@ private WritableRowSet update(final boolean initializing) {
                  * to close() the previous row sets for modified locations. This is not important for current
                  * implementations, since they always allocate new, flat RowSets.
                  */
```
Comment (malhotrashivam) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java:297]: This comment might need to be updated since we are no longer using getRowSet here.

Comment (rcaudy) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java:297]: This was indirectly a very good catch, thanks!

**Review by cpwright — APPROVED** [review]
