### PR TITLE
Adjust parameters for floating point tests

### LINKED ISSUE #4743: Analyze test failures from datagen fixes
Changes made to `io.deephaven.engine.testutil.generator.FloatGenerator` and `io.deephaven.engine.testutil.generator.DoubleGenerator` which correct range issues, effectively reduce the range of possible values. This ends up failing a variety of tests (this may not be a complete list since the generation of data isn't deterministic)

```

io.deephaven.engine.table.impl.QueryTableAggregationTest > testTDigestIncremental FAILED
    junit.framework.ComparisonFailure at QueryTableAggregationTest.java:2832

io.deephaven.engine.table.impl.updateby.TestRollingProduct > testStaticZeroKeyTimedRev FAILED
    junit.framework.ComparisonFailure at TestRollingProduct.java:424

io.deephaven.engine.table.impl.updateby.TestRollingSum > testBucketedGeneralTickingTimedFwdExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingSum.java:986

io.deephaven.engine.table.impl.updateby.TestRollingSum > testBucketedGeneralTickingFwdRev FAILED
    junit.framework.ComparisonFailure at TestRollingSum.java:854

io.deephaven.engine.table.impl.updateby.TestRollingSum > testBucketedGeneralTickingTimedRev FAILED
    junit.framework.ComparisonFailure at TestRollingSum.java:887

io.deephaven.engine.table.impl.updateby.TestRollingSum > testBucketedGeneralTickingFwd FAILED
    junit.framework.ComparisonFailure at TestRollingSum.java:798

io.deephaven.engine.table.impl.updateby.TestRollingSum > testBucketedGeneralTickingRev FAILED
    junit.framework.ComparisonFailure at TestRollingSum.java:742

io.deephaven.engine.table.impl.updateby.TestRollingSum > testBucketedGeneralTickingFwdExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingSum.java:826

io.deephaven.engine.table.impl.updateby.TestRollingSum > testBucketedGeneralTickingRevExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingSum.java:770

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticBucketedRevExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticZeroKeyFwdExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticBucketedFwd FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticBucketedRev FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticZeroKeyRevExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticZeroKeyFwdRevWindow FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticZeroKeyTimedFwdExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:653

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticBucketedFwdExclusive FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestRollingWAvg > testStaticGroupedBucketed FAILED
    junit.framework.ComparisonFailure at TestRollingWAvg.java:548

io.deephaven.engine.table.impl.updateby.TestUpdateByGeneral > testMixedGeneralZeroKey FAILED
    junit.framework.ComparisonFailure at TestUpdateByGeneral.java:183

io.deephaven.engine.table.impl.updateby.TestUpdateByGeneral > testMixedAppendOnlyZeroKey FAILED
    junit.framework.ComparisonFailure at TestUpdateByGeneral.java:181

io.deephaven.engine.table.impl.updateby.TestUpdateByGeneral > testMixedAppendOnlyBucketed FAILED
    junit.framework.ComparisonFailure at TestUpdateByGeneral.java:181

io.deephaven.engine.table.impl.updateby.TestUpdateByGeneral > testMixedGeneralBucketed FAILED
    junit.framework.ComparisonFailure at TestUpdateByGeneral.java:183
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Initiating shutdown processing
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Starting to invoke FIRST shutdown tasks
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Done invoking FIRST shutdown tasks
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Starting to invoke MIDDLE shutdown tasks
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Done invoking MIDDLE shutdown tasks
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Starting to invoke LAST shutdown tasks
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Done invoking LAST shutdown tasks
[Thread-14] WARN io.deephaven.util.process.ShutdownManagerImpl - Finished shutdown processing

1212 tests completed, 22 failed
```

A [commit](https://github.com/niloc132/deephaven-core/commit/6076bb711e3a8efb8029ab06904f9b3eee975fa4) has been made which reduces the range of the generated data in a few places - could just as easily increase the tolerance of the tests. Some investigation should be done to verify that these reduced ranges/tolerances are appropriate.

### PR DESCRIPTION
**Pull request by lbooker42**
Analyzed test sensitivity and changes made during the datagen updates (#4735) and verified the changes are correct and do not mask inaccuracies in the operations being tested.

Using floating point values with varying magnitudes increases floating point error, pushing it beyond the "acceptable" level of error in these tests.  Adjusting the tests to produce random values clustered within the same magnitude reduces the final error and allows these tests to pass.

Closes #4743.

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/BucketedPartitionedUpdateByManager.java [hunk 1]
```diff
@@ -121,6 +115,12 @@ class BucketedPartitionedUpdateByManager extends UpdateBy {
             transformFailureListener = new TransformFailureListener(transformedTable);
             transformedTable.addUpdateListener(transformFailureListener);
             result.addParentReference(transformFailureListener);
+
```
Comment (lbooker42) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/BucketedPartitionedUpdateByManager.java:118]: @rcaudy This moves initialization of the listener after it's dependencies are fully initialized.  Doesn't belong in this commit, but correcting a bad pattern (but not incorrect due the lock being held).

File: engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ZeroKeyUpdateByManager.java [hunk 2]
```diff
@@ -80,6 +74,12 @@ public class ZeroKeyUpdateByManager extends UpdateBy {
 
             // result will depend on zeroKeyUpdateBy
             result.addParentReference(zeroKeyUpdateBy.result);
+
```
Comment (lbooker42) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ZeroKeyUpdateByManager.java:77]: Same as previous comment.

**Review by niloc132 — APPROVED** [review]

**Review by rcaudy — APPROVED** [review]
