### PR TITLE
Fix ExactMatch Filter for Non-Convertible Types; Use RangeFilter on QueryScope Vars

### LINKED ISSUE #5526: Use `RangeConditionFilter` for query scope vars in addition to literals
This becomes a `ConditionFilter` and does not parallelize:
```
fbig2 = big.where(filters = ["trailer_ts_ns_ts > tstart", "trailer_ts_ns_ts < tend"])
```

This becomes a `RangeConditionFilter` and does parallelize:
```
fbig2 = big.where(filters = ["trailer_ts_ns_ts > '2024-05-17T19:59:27.995Z'", "trailer_ts_ns_ts < '2024-05-17T19:59:28Z'"])
```

### LINKED ISSUE #5584: Filters for equality don't work with non-primitive/string scope variables
Filters for equality (like `.where("MyCol = someObject")`) don't work for arbitrary datatypes (e.g. `java.time.LocalDate`, `java.awt.Color`).

```python
from deephaven import empty_table
from deephaven.time import to_j_local_date
import jpy
BLACK = jpy.get_type('java.awt.Color').BLACK
colors = empty_table(1000).update("Color = new java.awt.Color(i%255, i*2 % 255, i*i % 255)")
colors_filtered_works = colors.where("Color = java.awt.Color.BLACK")
colors_filtered_broken = colors.where("Color = BLACK")
```

Throws:

```
RuntimeError: java.lang.IllegalArgumentException: Unknown type java.awt.Color for MatchFilter value auto-conversion
	at io.deephaven.engine.table.impl.select.MatchFilter$ColumnTypeConvertorFactory.getConvertor(MatchFilter.java:501)
	at io.deephaven.engine.table.impl.select.MatchFilter.init(MatchFilter.java:183)
	at io.deephaven.engine.table.impl.QueryTable.initializeAndPrioritizeFilters(QueryTable.java:1175)
	at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$29(QueryTable.java:1225)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.whereInternal(QueryTable.java:1223)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:1162)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:100)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:163)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:163)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1537)
```

Same thing for LocalDate:

```python
from deephaven import empty_table
from deephaven.time import to_j_local_date
x = empty_table(1_000).update(["Date = '2024-06-07'"])
my_date = to_j_local_date("2024-06-06")
filter1 = x.where("Date=my_date")
filter2 = x.where("Date='2024-06-06'") # same exception
```

```
RuntimeError: java.lang.IllegalArgumentException: Unknown type java.time.LocalDate for MatchFilter value auto-conversion
	at io.deephaven.engine.table.impl.select.MatchFilter$ColumnTypeConvertorFactory.getConvertor(MatchFilter.java:501)
	at io.deephaven.engine.table.impl.select.MatchFilter.init(MatchFilter.java:183)
```

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #5584
Fixes #5526 

Nightlies: https://github.com/nbauernfeind/deephaven-core/actions/runs/9665514128/

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 1]
```diff
@@ -459,6 +463,54 @@ Object convertStringLiteral(String str) {
...
             }
+            if (cls == LocalDate.class) {
+                return new ColumnTypeConvertor() {
+                    @Override
+                    Object convertStringLiteral(String str) {
+                        if (str.charAt(0) != '\'' || str.charAt(str.length() - 1) != '\'') {
+                            throw new IllegalArgumentException(
+                                    "Instant literal not enclosed in single-quotes (\"" + str + "\")");
+                        }
+                        return LocalDate.parse(str.substring(1, str.length() - 1));
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:474]: I think we want to use `DateTimeUtils` for these.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/ZonedDateTimeRangeFilter.java [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+import io.deephaven.chunk.*;
+import io.deephaven.chunk.attributes.Values;
+import io.deephaven.engine.rowset.WritableRowSet;
+import io.deephaven.engine.rowset.RowSet;
+import io.deephaven.time.DateTimeUtils;
+import org.jetbrains.annotations.NotNull;
+
+import java.time.ZonedDateTime;
+
+public class ZonedDateTimeRangeFilter extends LongRangeFilter {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/ZonedDateTimeRangeFilter.java:22]: We should actually explicitly discuss if this is good. ZonedDateTime equals and comparison are not consistent with Instant or epoch nanos.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java [hunk 3]
```diff
@@ -147,10 +83,12 @@ public WhereFilter getExpression(String expression, Matcher matcher, Object... a
                 final boolean icase = matcher.group(2) != null;
                 final boolean inverted = matcher.group(3) != null;
                 final String[] values = new SplitIgnoreQuotes().split(matcher.group(4), ',');
+                final FormulaParserConfiguration parserConfiguration = (FormulaParserConfiguration) args[0];
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java:86]: I'm not sure this fallback can be expected to work ever for "in".

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java [hunk 4]
```diff
@@ -202,6 +140,59 @@ public WhereFilter getExpression(String expression, Matcher matcher, Object... a
...
+        if (isRowVariable(columnName)) {
+            log.debug().append("WhereFilterFactory creating ConditionFilter for expression: ")
+                    .append(expression).endl();
+            return ConditionFilter.createConditionFilter(expression, parserConfiguration);
+        }
+
+        boolean inverted = false;
+        switch (op) {
+            case "!=":
+                inverted = !inverted;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java:160]:
```suggestion
                inverted = true;
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java [hunk 5]
```diff
@@ -202,6 +140,59 @@ public WhereFilter getExpression(String expression, Matcher matcher, Object... a
...
+                        value);
+
+            case "<":
+            case ">":
+            case "<=":
+            case ">=":
+                try {
+                    if (mirrored) {
+                        final String dir = op.substring(0, 1);
+                        op = op.replaceFirst(dir, dir.equals("<") ? ">" : "<");
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java:179]: You could hard-code these conversions.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java [hunk 6]
```diff
@@ -202,6 +140,59 @@ public WhereFilter getExpression(String expression, Matcher matcher, Object... a
...
+                    }
+                    log.debug().append("WhereFilterFactory creating RangeConditionFilter for expression: ")
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java:181]:
```suggestion
                    log.debug().append("WhereFilterFactory creating RangeFilter for expression: ")
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java [hunk 7]
```diff
@@ -202,6 +140,59 @@ public WhereFilter getExpression(String expression, Matcher matcher, Object... a
...
+                            .append(expression).endl();
+                    return new RangeFilter(columnName, op, value, expression, parserConfiguration);
+                } catch (Exception e) {
+                    log.warn().append("WhereFilterFactory could not make RangeFilter for expression: ")
+                            .append(expression).append(" due to ").append(e)
+                            .append(" Creating ConditionFilter instead.").endl();
+                    return ConditionFilter.createConditionFilter(expression, parserConfiguration);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java:188]: I don't see how you can hit this.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java [hunk 8]
```diff
@@ -48,93 +49,28 @@ public class WhereFilterFactory {
...
-        parser.registerFactory(new AbstractExpressionFactory<>(
-                START_PTRN + "(" + ID_PTRN + ")\\s*(?:(?:={1,2})|(!=))\\s*(" + ID_PTRN + ")" + END_PTRN) {
-            @Override
-            public WhereFilter getExpression(String expression, Matcher matcher, Object... args) {
-                final String columnName = matcher.group(1);
-                final boolean inverted = matcher.group(2) != null;
-                final String paramName = matcher.group(3);
-
-                final FormulaParserConfiguration parserConfiguration = (FormulaParserConfiguration) args[0];
+                final boolean mirrored = !leftIsId;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java:66]: We're allowing literal op columName, but we're not allowing QueryScopeParam op columName. That feels incomplete, but the change might be pretty annoying. Might need more test coverage, as well.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 9]
```diff
@@ -286,10 +325,51 @@ Object convertParamValue(Object paramValue) {
...
+         * @return whether the value was an array or collection
+         */
+        final boolean convertValue(
+                @NotNull final ColumnDefinition<?> column,
+                @NotNull final String strValue,
+                @NotNull final Map<String, Object> queryScopeVariables,
+                @NotNull final Consumer<Object> valueConsumer) {
+            if (queryScopeVariables.containsKey(strValue)) {
+                Object paramValue = queryScopeVariables.get(strValue);
+                if (paramValue != null && paramValue.getClass().isArray()) {
```
[the remark this answers is not in the document]
Comment (nbauernfeind) [reply engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:345]: Filed as #5634

File: engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java [hunk 10]
```diff
@@ -5003,6 +5010,66 @@ public static Instant parseInstantQuiet(@Nullable final String s) {
...
+
+    /**
+     * Parses the string argument as a {@link LocalDateTime}.
+     * <p>
+     * Date time strings are formatted according to the ISO 8601 date time format
+     * {@code yyyy-MM-ddThh:mm:ss[.SSSSSSSSS] TZ} and others.
+     *
+     * @param s date time string
+     * @return a {@link LocalDateTime} represented by the input string, or {@code null} if the string can not be parsed
+     * @see DateTimeFormatter#ISO_INSTANT
```
Comment (rcaudy) [inline engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java:5057]:
```suggestion
```

File: engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java [hunk 11]
```diff
@@ -5003,6 +5010,66 @@ public static Instant parseInstantQuiet(@Nullable final String s) {
...
+     * Date time strings are formatted according to the ISO 8601 date time format
+     * {@code yyyy-MM-ddThh:mm:ss[.SSSSSSSSS]} and others.
+     *
+     * @param s date time string
+     * @return a {@link LocalDateTime} represented by the input string
+     * @throws DateTimeParseException if the string cannot be parsed
+     */
+    @ScriptApi
+    @NotNull
+    public static LocalDateTime parseLocalDateTime(@NotNull final String s) {
```
Comment (rcaudy) [inline engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java:5025]: Be sure to add unit tests. Can likely start by copy-paste from parseZDT test.

File: engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java [hunk 12]
```diff
@@ -5003,6 +5010,66 @@ public static Instant parseInstantQuiet(@Nullable final String s) {
...
+        } catch (Exception ex) {
+            throw new DateTimeParseException("Cannot parse local date time: " + s, ex);
+        }
+    }
+
+    /**
+     * Parses the string argument as a {@link LocalDateTime}.
+     * <p>
+     * Date time strings are formatted according to the ISO 8601 date time format
+     * {@code yyyy-MM-ddThh:mm:ss[.SSSSSSSSS] TZ} and others.
```
Comment (rcaudy) [inline engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java:5053]:
```suggestion
     * {@code yyyy-MM-ddThh:mm:ss[.SSSSSSSSS]} and others.
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 13]
```diff
@@ -88,11 +84,13 @@ public enum CaseSensitivity {
         MatchCase, IgnoreCase
     }
 
+    // TODO NATE NOCOMMIT: USE BUILDER TO CREATE MATCH FILTER??
+
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:88]: Be sure to delete. Let's defer introducing a builder.

However, I think it might be time to add JavaDoc to the constructors:
"This constructor is called by X, for Y."
Or turn them into static methods with meaningful names.

```suggestion
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 14]
```diff
@@ -46,21 +47,16 @@ static MatchFilter ofLiterals(
...
                 literals.stream().map(AsObject::of).toArray());
     }
 
-    /** The expression to use for this filter should initialization fail. */
-    private final String expression;
-    /** The failover filter to use if this filter fails to initialize. */
-    private WhereFilter failoverFilter;
-    /** The parser configuration to use for the failover filter. */
-    private final FormulaParserConfiguration parserConfiguration;
+    /** A fail-over where filter supplier should the match filter initialization fail. */
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:55]:
```suggestion
    /** A fail-over WhereFilter supplier should the match filter initialization fail. */
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 15]
```diff
@@ -103,60 +101,33 @@ public MatchFilter(
     public MatchFilter(
             @NotNull final String columnName,
             @NotNull final Object... values) {
-        this(null, null, null, CaseSensitivity.IgnoreCase, MatchType.Regular, columnName, null, values);
+        this(null, CaseSensitivity.IgnoreCase, MatchType.Regular, columnName, null, values);
     }
 
     public MatchFilter(
             @NotNull final CaseSensitivity sensitivity,
             @NotNull final MatchType matchType,
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:109]: This addition seems suspicious. You pointed out that we seem to have removed one constructor and added another.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 16]
```diff
@@ -167,12 +138,11 @@ private MatchFilter(
 
     public MatchFilter renameFilter(String newName) {
         if (strValues == null) {
-            return new MatchFilter(expression, parserConfiguration, failoverFilter, getMatchType(), newName, values);
+            return new MatchFilter(getMatchType(), newName, values);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:141]: This is effectively asserting that there can be no failover if we have values. I think it's accurate. Might need a comment.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 17]
```diff
@@ -681,12 +717,16 @@ public boolean canMemoize() {
...
+
             copy = new MatchFilter(
-                    expression, parserConfiguration, failoverFilter,
-                    caseInsensitive ? CaseSensitivity.IgnoreCase : CaseSensitivity.MatchCase,
-                    getMatchType(), columnName, strValues);
+                    failoverFilter, caseInsensitive ? CaseSensitivity.IgnoreCase : CaseSensitivity.MatchCase,
+                    getMatchType(), columnName, strValues, null);
         } else {
-            copy = new MatchFilter(expression, parserConfiguration, failoverFilter, getMatchType(), columnName, values);
+            copy = new MatchFilter(getMatchType(), columnName, values);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:729]: Same as `rename`, might want a comment.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 18]
```diff
@@ -681,12 +717,16 @@ public boolean canMemoize() {
     public WhereFilter copy() {
         final MatchFilter copy;
         if (strValues != null) {
+            final WhereFilter failover = failoverFilter != null ? failoverFilter.getIfCached() : null;
+            if (failover != null) {
+                return failover.copy();
+            }
+
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:724]: This is suspicious. We might resolve different query scope params on a new init.
```suggestion
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 19]
```diff
@@ -46,21 +47,16 @@ static MatchFilter ofLiterals(
...
-    /** The failover filter to use if this filter fails to initialize. */
-    private WhereFilter failoverFilter;
-    /** The parser configuration to use for the failover filter. */
-    private final FormulaParserConfiguration parserConfiguration;
+    /** A fail-over where filter supplier should the match filter initialization fail. */
+    private final CachingSupplier<WhereFilter> failoverFilter;
 
     @NotNull
-    private final String columnName;
+    private String columnName;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:59]: There's an accessor for this. Is it still safe? Might be sufficient to JavaDoc accessors as only safe after init, and then verify usages.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/RangeFilter.java [hunk 20]
```diff
@@ -296,6 +323,10 @@ public void setRecomputeListener(RecomputeListener listener) {}
 
     @Override
     public WhereFilter copy() {
+        if (filter != null) {
+            return filter.copy();
+        }
+
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/RangeFilter.java:329]: Same concern as in MatchFilter.
```suggestion
```

File: engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereSingleTest.java [hunk 21]
```diff
@@ -24,4 +24,10 @@ public void tearDown() throws Exception {
         QueryTable.FORCE_PARALLEL_WHERE = oldParallel;
         QueryTable.DISABLE_PARALLEL_WHERE = oldDisable;
     }
+
+    @Override
+    public void testRangeFilterFallback() {
+        super.testRangeFilterFallback();
+    }
```
Comment (rcaudy) [inline engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereSingleTest.java:31]:
```suggestion
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/RangeFilter.java [hunk 22]
```diff
@@ -323,10 +334,6 @@ public void setRecomputeListener(RecomputeListener listener) {}
 
     @Override
     public WhereFilter copy() {
-        if (filter != null) {
-            return filter.copy();
-        }
-
         return new RangeFilter(columnName, condition, value, expression, filter, parserConfiguration);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/RangeFilter.java:337]: Should we be copying the `filter`?

**Review by rcaudy — DISMISSED** [review]

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 23]
```diff
@@ -337,9 +337,17 @@ Object convertParamValue(Object paramValue) {
...
         final boolean convertValue(
                 @NotNull final ColumnDefinition<?> column,
+                @NotNull final TableDefinition tableDefinition,
                 @NotNull final String strValue,
                 @NotNull final Map<String, Object> queryScopeVariables,
                 @NotNull final Consumer<Object> valueConsumer) {
+            if (tableDefinition.getColumn(strValue) != null) {
+                // this is also a column name which needs to take precedence, and we can't convert it
+                throw new IllegalArgumentException(String.format(
+                        "Failed to convert literal value <%s> for column \"%s\" of type %s; it is a column name",
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:347]:
```suggestion
                        "Failed to convert value <%s> for column \"%s\" of type %s; it is a column name",
```

**Review by rcaudy — APPROVED** [review]

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java [hunk 24]
```diff
@@ -390,6 +399,18 @@ Object convertStringLiteral(String str) {
                         }
                         return Byte.parseByte(str);
                     }
+
+                    @Override
+                    Object convertParamValue(Object paramValue) {
+                        paramValue = super.convertParamValue(paramValue);
+                        if (paramValue instanceof Byte) {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java:406]: `paramValue.getClass()` is going to NPE...
```suggestion
                        if (paramValue instanceof Byte || paramValue == null) {
```

**Review by rcaudy — DISMISSED** [review]

**Review by rcaudy — APPROVED** [review]
