### PR TITLE
DH to work with byte arrays

### LINKED ISSUE #4355: Support in Java client for publishing columns of type byte[]
As a user of the Java client, I want to be able to publish variable-length byte arrays into a Deephaven table column. Currently attempting to publish
```
ColumnHeader<byte[]> binary = ColumnHeader.of("B", byte[].class)
```
throws an exception from [here](https://github.com/deephaven/deephaven-core/blob/50bdba43c0290d75aad3dcfd70f4f7761ca8ba17/java-client/flight/src/main/java/io/deephaven/client/impl/FieldVectorAdapter.java#L159)

However, since Arrow supports `VarBinaryVector`, it might be possible to implement this in the same way that publishing a String-valued column is currently published.

### PR DESCRIPTION
**Pull request by ilyaberdnikov**
Fixes #4355.

This is currently a very rough hack, but it does work locally. Not sure what it breaks.

### CODE REVIEW

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java [hunk 1]
```diff
@@ -204,8 +205,18 @@ static WritableChunk<Values> extractChunkFromInputStream(
                         Double.BYTES, options,fieldNodeIter, bufferInfoIter, is, outChunk, outOffset, totalRows);
             case Object:
                 if (type.isArray()) {
-                   return VarListChunkInputStreamGenerator.extractChunkFromInputStream(
-                           options, type, fieldNodeIter, bufferInfoIter, is, outChunk, outOffset, totalRows);
+                    if(componentType == byte.class) {
```
Comment (nbauernfeind) [inline extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:208]: The style here is slightly off. If you run `./gradlew spotlessApply` at the top level, then everything non-comforming will be formatted automatically. (Otherwise, once CI runs, it will fail here and in a few other locations.)

File: java-client/flight-examples/src/main/java/io/deephaven/client/examples/AddToInputTable.java [hunk 2]
```diff
@@ -44,9 +54,10 @@ protected void execute(FlightSession flight) throws Exception {
 
             while (true) {
                 // Add a new row, at least once every second
-                final NewTable newRow = header.row(Instant.now()).newTable();
+                final NewTable newRow = header.row(true, (byte) 42, 'a', (short) 32_000, 1234567, 1234567890123L, 3.14f, 3.14d, "Hello, World",
+                      Instant.now(), "abc".getBytes()).newTable();
                 flight.addToInputTable(timestampHandle, newRow, bufferAllocator).get(5, TimeUnit.SECONDS);
-                Thread.sleep(ThreadLocalRandom.current().nextLong(1000));
+                Thread.sleep(ThreadLocalRandom.current().nextLong(100000));
```
Comment (nbauernfeind) [inline java-client/flight-examples/src/main/java/io/deephaven/client/examples/AddToInputTable.java:60]: Let's set this value back to 1s. Alternatively, you could make this a flag.

Here is an example flag that is a similar type:
```java
    @Option(names = {"--input-table-size"}, description = "The input table size, default ${DEFAULT-VALUE}",
            defaultValue = "1000")
    int inputTableSize;
```
(Source for this flag is here: https://github.com/deephaven/deephaven-core/blob/main/java-client/flight-examples/src/main/java/io/deephaven/client/examples/AggInputBase.java#L30)

If you make as a flag; change the comment on line 56 to reference the flag rather than 'once every second'.

**Review by nbauernfeind — COMMENTED** [review]
Please sign the CLA (see the automated message above). 

Once you do and address my comments, I'll kick of a "nightly" build which runs a suite of tests (many of which go through the ChunkInputStreamGenerator code path).

Thank you for the PR; once merged I'll probably tack on support for the remaining primitive arrays. (No reason the java client shouldn't be supporting these.)

**Comment by ilyaberdnikov** [comment]
I have read the CLA Document and I hereby sign the CLA

File: java-client/flight-examples/src/main/java/io/deephaven/client/examples/AddToInputTable.java (hunk 2 above)
Comment (ilyaberdnikov) [reply java-client/flight-examples/src/main/java/io/deephaven/client/examples/AddToInputTable.java]: reverted to 1s

File: extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java (hunk 1 above)
Comment (ilyaberdnikov) [reply extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java:208]: should now be spotless

**Comment by ilyaberdnikov** [comment]
recheck

**Comment by nbauernfeind** [comment]
Your PR looks good to me so far. I've just kicked off that suite of tests. When they pass (plus or minus a known random failure) then I'll get this merged. 

Thank you so much for your contribution!

**Review by nbauernfeind — APPROVED** [review]

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

How-to: https://github.com/deephaven/deephaven.io/issues/3202
Reference: https://github.com/deephaven/deephaven.io/issues/3201
