### PR TITLE
fix: JS subscriptions should return correct size while updating

### LINKED ISSUE #6423: Unable to scroll s3 parquet file
Attempting to view a parquet file from s3, I am unable to scroll the resulting table.

cant_scroll

Steps to reproduce:

1. Run this code
```py
from deephaven import parquet
from deephaven.experimental import s3

poi = parquet.read(
    path="s3://fsq-os-places-us-east-1/release/dt=2024-11-19/places/parquet/places-00000.snappy.parquet",
    special_instructions=s3.S3Instructions(
        # @devinrsmith had a theory that it was timeout, but that doesn't seem to make a difference
        connection_timeout="PT20s",
        read_timeout="PT20s"
    ),
)
```

2. Attempt to scroll the resulting table in the UI

Note: reversing the table and scrolling DOES work. No idea why.

Versions:
Issue was observed on both these commit
acdb6bfb47baa103c929797b610270f09e551214
7b47794a0739671d1de933836bd69f191a3ce66f

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #6423

### CODE REVIEW

File: web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java [hunk 1]
```diff
@@ -1715,7 +1714,7 @@ public void setSize(double s) {
         this.size = s;
 
         TableViewportSubscription subscription = subscriptions.get(getHandle());
-        if (changed && (subscription == null || subscription.getStatus() == TableViewportSubscription.Status.DONE)) {
+        if (changed && (subscription == null || !subscription.hasValidSize())) {
```
Comment (mofojed) [inline web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java:1717]: Guessing we don't need to worry about the `STARTING` state here? Or shouldn't this just be checking `subscription.isClose()` (as it was just checking against == `DONE` before).

**Review by mofojed — COMMENTED** [review]
I tested it in the case against the ticket. Just one comment about one of these if checks that I'm not sure about, as it does change the logic. Will approve after you confirm.

File: web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java (hunk 1 above)
Comment (niloc132) [reply web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java:1717]: If the subscription is in the STARTING state, we havent yet received a definitive size for the subscription, and so we should continue to use the "other" way that we get sizes. That is, the server sends ExportedTableUpdateMessage values that show the new size of the table whenever it changes, but those are sometimes faster than the update interval for the subscription, so technically using the subscription means we might skip some size changes (the purpose of this `if`).

However, that's a good thing. We don't want tell the UI that the table size is changing in a way that is actually incompatible with the subscription's own contents.

The old behavior here was to say "if you have started a subscription, but the first message hasnt arrived from the server, don't worry about the size changes, you'll get an accurate picture when the snapshot gets here". The bug report that led to the PR pointed out that sometimes it can be seconds (or minutes) before the first snapshot gets here, and we need to have accurate information before, during, and after.

The actual fix for the patch is to say "if the subscription is actively changing, assume the old value is still good, and the next subscription message is the best way to get updates". Formerly, we would actually create a new subscription to the server when the viewport was adjusted, so "before" that subscription was ready also encompassed "during, but temporarily invalid". Now, that "temporarily invalid" state doesn't require a new subscription, so we can treat the "before" state as "not actually ready to hand the reins to the subscription".

**Review by mofojed — APPROVED** [review]
