### PR TITLE
QueryCompiler Batch Formula Compilation

### LINKED ISSUE #4814: Investigate Whether `QueryCompiler` Can Reuse `JavaFileManager` for Server Duration
While working on #4808, I discovered that there is potential to cut formula compile time by ~50% if the `JavaFileManager` is reused across all calls to `QueryCompiler#maybeCreateClassHelper`. See the test, the test results, and accompanying image below.

The concerns / things that need follow up validation:
- Does this prevent us from overriding classes / jars mid-day through the filesystem?
- Does this prevent us from redefining classes in groovy?
- The zulu-17 implementation of `JavaFileManager` is certainly not thread safe. Is it sufficient to implement a delegating implementation that synchronizes all public methods?
- We should have a unit test of some sort that attempts to stress parallel compilation (only the go client caught this via check-ci).

The Test:
- first query shown in the table is the REPL command to construct the tree table and should be ignored.
- then three batches of 10 batch queries of 100 operations that run serially and guarantee the need to compile a single formula.
-- the first batch is run sharing a single, initial, `JavaFileManager` (`JFM`) that was also used in the first query.
-- the second batch disables sharing the `JFM` and instead creates a new one that it closes at the end of the compilation (engine behavior as of #4808).
-- the third batch goes back to sharing a single `JFM` but creates a new instance first.

The first batch of group 1 has an average operation time of 48ms. (shared JFM)
The first batch of group 2 has an average operation time of 113ms. (new JFM per compilation)
The first batch of group 3 has an average operation time of 58ms. (shared JFM, but validating that the JFM is not responsible for the time creep)

Note that over time the simple formula compilation time creeps from 48ms to 69ms over ~3k formulas. This is possibly due to the temp dir that we write formula results into - I couldn't put my finger on the time creep except to eliminate blame on the `JFM`.

Screenshot 2023-11-10 at 2 36 51 PM

### LINKED ISSUE #4918: Errors from query strings should contain the original query strings
When query strings yield errors, DH is currently returning a variant of the string after some query translation.  It would be much more greppable if the user's original query string was returned.

Consider this example:

```python
from deephaven import empty_table

def gain(start:float, end:float) -> float:
    raise Exception("Broke")
    # return (end - start) / start * 100.0

t = empty_table(10).update(["avg_rate = 1.3", "op_rate = 2.6", "Change = gain(avg_rate, op_rate) / 100"])
```

I would expect the error string to contain `Change = gain(avg_rate, op_rate) / 100`.  In reality, the following error is returned, which contains only `Change = divide(doubleCast(gain.call(avg_rate, op_rate)), 100)`.  Not very greppable by users.

```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : java.lang.RuntimeException: Error in Python interpreter:
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 913, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: Change = divide(doubleCast(gain.call(avg_rate, op_rate)), 100)
```

### LINKED ISSUE #5185: PartitionAwareSourceTable's `selectDistinct` Does not Handle Formulas Well
```groovy
import io.deephaven.engine.util.TableTools
import io.deephaven.parquet.table.ParquetTools

def partition = emptyTable(10).update("I = `` + (ii % 100)", "K = ii")
ParquetTools.writeTable(partition, new java.io.File("/tmp/test/A=a/data.parquet"))
ParquetTools.writeTable(partition, new java.io.File("/tmp/test/A=b/data.parquet"))

def imTable = TableTools.merge(partition.updateView("A = 'a'"), partition.updateView("A = 'b'"))
res1 = imTable.selectDistinct("E = (short)A", "L = (long)E")

def rdTable = ParquetTools.readTable("/tmp/test")
res2 = rdTable.selectDistinct("E = (short)A", "L = (long)E")
```

Note that `res1` works fine, but `res2` gives the following error:
```
Error running script: io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: (long)E
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:214)
	at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:56)
	at io.deephaven.engine.table.impl.PartitionAwareSourceTable.selectDistinct(PartitionAwareSourceTable.java:327)
	at io.deephaven.engine.table.impl.PartitionAwareSourceTable.selectDistinct(PartitionAwareSourceTable.java:35)
	at io.deephaven.api.TableOperationsDefaults.selectDistinct(TableOperationsDefaults.java:392)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:186)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:51)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at io.deephaven.dynamic.Script_12.run(Script_12.groovy:11)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
	at io.deephaven.engine.util.GroovyDeephavenSession.evaluateCommand(GroovyDeephavenSession.java:291)
	at io.deephaven.engine.util.GroovyDeephavenSession.lambda$evaluate$0(GroovyDeephavenSession.java:314)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:314)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:148)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:148)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1519)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:992)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.deephaven.engine.table.impl.lang.QueryLanguageParser$QueryLanguageParseException: 

Having trouble with the following expression:
Full expression           : (long)E
Expression having trouble : 
Exception type            : io.deephaven.engine.table.impl.lang.QueryLanguageParser$ParserResolutionFailure
Exception message         : Cannot find variable or class E

	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.resolveName(QueryLanguageParser.java:1445)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:1399)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:131)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:1735)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:131)
	at com.github.javaparser.ast.expr.CastExpr.accept(CastExpr.java:75)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.<init>(QueryLanguageParser.java:317)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.<init>(QueryLanguageParser.java:262)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.<init>(QueryLanguageParser.java:230)
	at io.deephaven.engine.table.impl.select.codegen.FormulaAnalyzer.getCompiledFormula(FormulaAnalyzer.java:140)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:194)
	... 38 more
```

While, technically, this dependent formula only applies to partition columns - it would be fair to kick it out to the super impl. It is probably bad form to fail given that this query works on the non-partitioned version of this table.

### PR DESCRIPTION
**Pull request by nbauernfeind**
The following example, which compiles 1k simple formulas, drops from 96s down to 9s on an M2 MBP:
```groovy
def size = 1000
ia = new int[size]
upd = new String[size]
for (int ii = 0; ii < size; ++ii) {
    ia[ii] = 1024 * ii
    upd[ii] = "C" + ii + " = ia[" + ii + "]"
}
s = emptyTable(1).update(upd)
```

Fixes #4814.
Fixes #4918.
Fixes #5185.

This also addresses ambiguity when column array names clash with column names; columns trump column arrays. This query is now well defined (resulting in `R = 1`):
```groovy
import io.deephaven.engine.util.TableTools
t_0 = TableTools.emptyTable(1).update("C = 0", "C_ = new long[] {1, 2, 3}", "R = C_[0]")
t_1 = TableTools.emptyTable(1).update("C_ = new long[] {1, 2, 3}", "C = 0", "R = C_[0]")
```

Nightlies: https://github.com/nbauernfeind/deephaven-core/actions/runs/8194327638

### CODE REVIEW

File: engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java [hunk 1]
```diff
@@ -663,125 +818,167 @@ private void maybeCreateClass(String className, String code, String packageName,
...
                     // noinspection ThrowFromFinallyBlock
                     throw new UncheckedIOException("Could not close JavaFileManager", ioe);
                 }
             }
         }
-        if (!result) {
-            throw new UncheckedDeephavenException("Error compiling class " + fqClassName + ":\n" + compilerOutput);
+    }
+
+    private void maybeCreateClassHelper(
```
[the remark this answers is not in the document]
Comment (nbauernfeind) [reply engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java:897]: There is continual resolution whenever there are collisions. This particular piece of code intentionally is doing two passes. The first pass might fail a few requests. If any request is failed, then none of the non-failing requests have their class files written. To properly complete these non-failures, we need to compile a second time to write the class files.

Thanks for the snippets; I've integrated your ideas into the solution.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/by/FormulaChunkedOperator.java [hunk 2]
```diff
@@ -69,10 +71,13 @@ class FormulaChunkedOperator implements IterativeChunkedAggregationOperator {
...
      * @param resultColumnPairs The names for formula input and result columns
      */
-    FormulaChunkedOperator(@NotNull final GroupByChunkedOperator groupBy,
+    FormulaChunkedOperator(
+            @NotNull final GroupByChunkedOperator groupBy,
             final boolean delegateToBy,
             @NotNull final String formula,
             @NotNull final String columnParamName,
+            @NotNull final Supplier<Map<String, Object>> queryScopeVariables,
+            @NotNull final QueryCompilerRequestProcessor compilationProcessor,
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/by/FormulaChunkedOperator.java:80]: Would it be cool to combine these into one object, so you don't always have to pass both?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/BaseNodeOperationsRecorder.java [hunk 3]
```diff
@@ -284,16 +281,24 @@ private Stream<? extends SelectColumn> absoluteSelectColumns() {
...
+            final SelectColumn[] columns = sortColumns.stream()
                     .map(sc -> sc.column().name())
                     .filter(AbsoluteSortColumnConventions::isAbsoluteColumnName)
                     .map(cn -> {
                         final String baseColumnName = AbsoluteSortColumnConventions.absoluteColumnNameToBaseName(cn);
                         final Selectable selectable = AbsoluteSortColumnConventions.makeSelectable(cn, baseColumnName);
                         final SelectColumn selectColumn = SelectColumn.of(selectable);
-                        selectColumn.initDef(Map.of(baseColumnName, getDefinition().getColumn(baseColumnName)));
+                        selectColumn.initDef(Map.of(baseColumnName, getDefinition().getColumn(baseColumnName)),
+                                SelectAndViewAnalyzer.newQueryScopeVariableSupplier(), compilationProcessor);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/BaseNodeOperationsRecorder.java:296]: Making a new var supplier each time.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java [hunk 4]
```diff
@@ -44,7 +46,10 @@ public List<String> initInputs(
     }
 
     @Override
-    public List<String> initDef(@NotNull final Map<String, ColumnDefinition<?>> columnDefinitionMap) {
+    public List<String> initDef(
+            @NotNull final Map<String, ColumnDefinition<?>> columnDefinitionMap,
+            @NotNull final Supplier<Map<String, Object>> queryScopeVariables,
+            @NotNull final QueryCompilerRequestProcessor compilationRequestProcessor) {
         return getColumns();
     }
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java:54]: I'm inclined to think that you would have less code to write if you defaulted the long-form initDef to the short-form.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java [hunk 5]
```diff
@@ -44,7 +49,7 @@
 public class ConditionFilter extends AbstractConditionFilter {
 
     public static final int CHUNK_SIZE = 4096;
-    private Class<?> filterKernelClass = null;
+    private Future<Class<?>> filterKernelClass = null;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java:52]: Maybe rename?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java [hunk 6]
```diff
@@ -34,11 +41,12 @@ public abstract class AbstractFormulaColumn implements FormulaColumn {
 
 
     protected String formulaString;
+    protected final String originalFormulaString;
     protected List<String> usedColumns;
 
     @NotNull
     protected final String columnName;
-    protected FormulaFactory formulaFactory;
+    protected Future<FormulaFactory> formulaFactory;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java:49]: Maybe rename?

**Comment by rcaudy** [comment]
Here is a code review focused just on `QueryCompiler` in PR form, since I reviewed offline:
https://github.com/nbauernfeind/deephaven-core/pull/4
Comments are prefixed `RWC-CODE-REVIEW`

**Review by rcaudy — COMMENTED** [review]
Old pending review I forgot to submit

File: engine/table/src/main/java/io/deephaven/engine/table/impl/select/ReinterpretedColumn.java [hunk 7]
```diff
@@ -169,6 +169,12 @@ public Class<?> getReturnedType() {
         return destDataType;
     }
 
+    @Override
+    public Class<?> getReturnedComponentType() {
+        // we don't support reinterpretting column types with components
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/select/ReinterpretedColumn.java:174]:
```suggestion
        // we don't support reinterpreting column types with components
```

**Review by rcaudy — COMMENTED** [review]
.

File: extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java [hunk 8]
```diff
@@ -10,6 +10,7 @@
 import io.deephaven.parquet.compress.DeephavenCompressorAdapterFactory;
 import io.deephaven.util.channel.SeekableChannelContext.ContextHolder;
 import io.deephaven.util.datastructures.SoftCachingFunction;
+import org.apache.commons.io.FilenameUtils;
```
[the remark this answers is not in the document]
Comment (nbauernfeind) [reply extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java:13]: It's used; this is an artifact of merging in main.

File: engine/table/src/main/java/io/deephaven/engine/context/QueryCompilerImpl.java [hunk 9]
```diff
@@ -0,0 +1,1037 @@
...
+
+    private static final JavaCompiler compiler;
+    private static final JavaFileManager fileManager;
+    static {
+        compiler = ToolProvider.getSystemJavaCompiler();
+        if (compiler == null) {
+            throw new UncheckedDeephavenException("No Java compiler provided - are you using a JRE instead of a JDK?");
+        }
+        fileManager = new SynchronizedJavaFileManager(compiler.getStandardFileManager(null, null, null));
+    }
```
[the remark this answers is not in the document]
Comment (nbauernfeind) [reply engine/table/src/main/java/io/deephaven/engine/context/QueryCompilerImpl.java:770]: After initializing in the constructor the thrown error looks good:
```
Initiating shutdown due to: Uncaught exception in thread main
io.deephaven.UncheckedDeephavenException: No Java compiler provided - are you using a JRE instead of a JDK?
	at io.deephaven.engine.context.QueryCompilerImpl.ensureJavaCompiler(QueryCompilerImpl.java:83)
	at io.deephaven.engine.context.QueryCompilerImpl.<init>(QueryCompilerImpl.java:131)
	at io.deephaven.engine.context.QueryCompilerImpl.create(QueryCompilerImpl.java:110)
	at io.deephaven.engine.util.AbstractScriptSession.<init>(AbstractScriptSession.java:98)
	at io.deephaven.engine.util.AbstractScriptSession.<init>(AbstractScriptSession.java:81)
	at io.deephaven.integrations.python.PythonDeephavenSession.<init>(PythonDeephavenSession.java:86)
	at io.deephaven.server.console.python.PythonConsoleSessionModule.bindPythonSession(PythonConsoleSessionModule.java:41)
	at io.deephaven.server.console.python.PythonConsoleSessionModule_BindPythonSessionFactory.bindPythonSession(PythonConsoleSessionModule_BindPythonSessionFactory.java:77)
	at io.deephaven.server.console.python.PythonConsoleSessionModule_BindPythonSessionFactory.get(PythonConsoleSessionModule_BindPythonSessionFactory.java:61)
	at io.deephaven.server.console.python.PythonConsoleSessionModule_BindPythonSessionFactory.get(PythonConsoleSessionModule_BindPythonSessionFactory.java:18)
	at io.deephaven.server.console.python.PythonConsoleSessionModule_BindScriptSessionFactory.get(PythonConsoleSessionModule_BindScriptSessionFactory.java:37)
	at io.deephaven.server.console.python.PythonConsoleSessionModule_BindScriptSessionFactory.get(PythonConsoleSessionModule_BindScriptSessionFactory.java:13)
	at io.deephaven.server.session.ScriptSessionModule.provideScriptSession(ScriptSessionModule.java:31)
	at io.deephaven.server.session.ScriptSessionModule_ProvideScriptSessionFactory.provideScriptSession(ScriptSessionModule_ProvideScriptSessionFactory.java:44)
	at io.deephaven.server.session.ScriptSessionModule_ProvideScriptSessionFactory.get(ScriptSessionModule_ProvideScriptSessionFactory.java:34)
	at io.deephaven.server.session.ScriptSessionModule_ProvideScriptSessionFactory.get(ScriptSessionModule_ProvideScriptSessionFactory.java:13)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at io.deephaven.server.runner.DeephavenApiServer.run(DeephavenApiServer.java:151)
	at io.deephaven.server.jetty.JettyMain.main(JettyMain.java:24)
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java [hunk 10]
```diff
@@ -226,9 +227,10 @@ public QueryLanguageParser(
             Map<String, Class<?>> variables,
             Map<String, Class<?>[]> variableTypeArguments,
             @Nullable Map<String, Object> queryScopeVariables,
-            @Nullable Set<String> columnVariables) throws QueryLanguageParseException {
+            @Nullable Set<String> columnVariables,
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java:230]: Constructor on L222 is unused.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java [hunk 11]
```diff
@@ -270,7 +272,8 @@ public QueryLanguageParser(
                 columnVariables,
                 unboxArguments,
                 false,
-                PyCallableWrapperJpyImpl.class.getName());
+                PyCallableWrapperJpyImpl.class.getName(),
+                timeConversionResult);
     }
 
     QueryLanguageParser(
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java:279]: @VisibleForTesting

**Review by rcaudy — DISMISSED** [review]

**Review by rcaudy — APPROVED** [review]
