### PR TITLE
Properly ignore non-refreshing dynamic nodes; fix jsapi getObject to wait for Ticket

### LINKED ISSUE #1128: Web UI CSV import is broken
When attempting to DoPut the contents of a CSV, the table seems to be released before it can be exported, resulting in this server error:

```
r-Scheduler-Serial-1 | i.d.g.s.SessionState      | Internal Error '1ef42b1c-1dc6-4fee-b6fd-b9097866feba' io.deephaven.db.util.liveness.LivenessStateException: PythonDeephavenSession-303716477[2] failed to add BarrageTable-1413421479, which is no longer live
        at io.deephaven.db.util.liveness.LivenessManager.manage(LivenessManager.java:17)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$10(ConsoleServiceGrpcImpl.java:214)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1240)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:798)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:141)
        at java.lang.Thread.run(Thread.java:748)
```

Reverting https://github.com/deephaven/deephaven-core/commit/87aa98e8f9c0572cf8b4419589f637f40a5c3837 apparently fixes it, but reintroduces the bug in that issue.

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #1128

### CODE REVIEW

File: web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java [hunk 1]
```diff
@@ -146,6 +161,46 @@ public JsRunnable subscribeToFieldUpdates(JsConsumer<JsVariableChanges> callback
...
+                    subscription.run();
+                    promise.succeed(foundField);
+                }
+            }
+        }
+
+        Listener listener = new Listener();
+
+        return promise
+                .timeout(10000)
```
Comment (niloc132) [inline web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java:194]: style nit, stick a _ in there so we can read it? `10_000`

**Review by niloc132 — APPROVED** [review]
One small nit, feel free to ignore.

**Review by niloc132 — APPROVED** [review]
