### PR TITLE
Fix bugs in moveColumns and renameColumns

### LINKED ISSUE #4824: `QueryTable#moveColumns(int, String...)` May Drop Columns By Accident
Move columns may lose columns from the original table. I would expect to insert these columns at the specified location without loss of existing columns.

```groovy
def source = newTable(
    stringCol("A", "apple", "apple", "orange", "orange", "plum", "plum"),
    intCol("B", 1, 1, 2, 2, 3, 3),
    stringCol("C", "Macoun", "Opal", "Navel", "Cara Cara ", "Greengage", "Mirabelle"),
    intCol("D", 1, 2, 12, 3, 2, 3),
)

result_1 = source.moveColumns(1, "C", "C2 = C")
```

Note that `Table#moveColumns(int index, boolean moveToEnd, String... columnsToMove)` probably doesn't belong in the public facing API, and the implementation itself is a little suspect.

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #4824.

There were a few odd behaviors of the existing replace columns implementation. This hopefully makes behavior well defined and consistent. I've also added tests; which apparently were quite useful in extracting bugs.

I've explicitly disallowed having multiple entries for the same source or the same destination. You can lose columns by renaming some column to an existing column name; it was easy to support and there may be legitimate uses.

Nightlies: https://github.com/nbauernfeind/deephaven-core/actions/runs/8085227568

### CODE REVIEW

**Review by jmao-denver — APPROVED** [review]
The Python changes LGTM

**Review by chipkent — APPROVED** [review]
Python LGTM

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 1]
```diff
@@ -342,8 +381,14 @@ public interface Table extends
     Table formatColumnWhere(String columnName, String condition, String formula);
 
     /**
-     * Produce a new table with the specified columns moved to the leftmost position. Columns can be renamed with the
+     * Produce a new table with the specified columns moved to the rightmost position. Columns can be renamed with the
```
Comment (malhotrashivam) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:384]: Should this say leftmost?
```suggestion
     * Produce a new table with the specified columns moved to the leftmost position. Columns can be renamed with the
```

**Review by malhotrashivam — COMMENTED** [review]
I really like the new Javadoc and the new tests, helped me understand the code much better. I wonder if we can add similar move+rename examples in the [official docs](https://deephaven.io/core/docs/reference/table-operations/select/move-columns/) as well since I couldn't find such an example there.

Suggested a small correction in javadoc at one place. Would defer the discussion about semantics to the experts.

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java (hunk 1 above)
Comment (chipkent) [reply engine/api/src/main/java/io/deephaven/engine/table/Table.java:384]: Check the pydocs as well.

**Review by malhotrashivam — APPROVED** [review]

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 2]
```diff
@@ -327,7 +327,8 @@ public interface Table extends
     Table dropColumnFormats();
 
     /**
-     * Produce a new table with the specified columns renamed using the syntax {@code "NewColumnName=OldColumnName"}.
+     * Produce a new table with the specified columns renamed using the specified {@link Pair pairs}. The renames are
+     * simultaneous, and unordered, enabling direct swaps between column names.
```
Comment (chipkent) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:331]:
```suggestion
     * Produce a new table with the specified columns renamed using the specified {@link Pair pairs}. The renames are
     * simultaneous and unordered, enabling direct swaps between column names.
```

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 3]
```diff
@@ -343,6 +344,7 @@ public interface Table extends
 
     /**
      * Produce a new table with the specified columns renamed using the syntax {@code "NewColumnName=OldColumnName"}.
+     * The renames are simultaneous, and unordered, enabling direct swaps between column names.
```
Comment (chipkent) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:347]:
```suggestion
     * The renames are simultaneous and unordered, enabling direct swaps between column names.
```

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 4]
```diff
@@ -357,13 +359,8 @@ public interface Table extends
...
     /**
-     * Produce a new table with the specified columns renamed using the provided function.
-     * <p>
-     * {@link IllegalArgumentException} will be thrown:
-     * <ul>
-     * <li>if a source column is used more than once</li>
-     * <li>if a destination column is used more than once</li>
-     * </ul>
+     * Produce a new table with the specified columns renamed using the provided function. The renames are simultaneous,
+     * and unordered, enabling direct swaps between column names.
```
Comment (chipkent) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:363]:
```suggestion
     * Produce a new table with the specified columns renamed using the provided function. The renames are simultaneous
     * and unordered, enabling direct swaps between column names.
```

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 5]
```diff
@@ -381,8 +378,9 @@ public interface Table extends
     Table formatColumnWhere(String columnName, String condition, String formula);
 
     /**
-     * Produce a new table with the specified columns moved to the rightmost position. Columns can be renamed with the
-     * usual syntax, i.e. {@code "NewColumnName=OldColumnName")}.
+     * Produce a new table with the specified columns moved to the leftmost position. Columns can be renamed with the
+     * usual syntax, i.e. {@code "NewColumnName=OldColumnName")}. The renames are simultaneous, and unordered, enabling
+     * direct swaps between column names.
```
Comment (chipkent) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:383]:
```suggestion
     * usual syntax, i.e. {@code "NewColumnName=OldColumnName")}. The renames are simultaneous and unordered, enabling
     * direct swaps between column names.
```

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 6]
```diff
@@ -398,7 +396,8 @@ public interface Table extends
 
     /**
      * Produce a new table with the specified columns moved to the rightmost position. Columns can be renamed with the
-     * usual syntax, i.e. {@code "NewColumnName=OldColumnName")}.
+     * usual syntax, i.e. {@code "NewColumnName=OldColumnName")}. The renames are simultaneous, and unordered, enabling
```
Comment (chipkent) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:399]:
```suggestion
     * usual syntax, i.e. {@code "NewColumnName=OldColumnName")}. The renames are simultaneous and unordered, enabling
```

File: engine/api/src/main/java/io/deephaven/engine/table/Table.java [hunk 7]
```diff
@@ -413,8 +412,9 @@ public interface Table extends
     Table moveColumnsDown(String... columnsToMove);
 
     /**
-     * Produce a new table with the specified columns moved to the rightmost position. Columns can be renamed with the
-     * usual syntax, i.e. {@code "NewColumnName=OldColumnName")}.
+     * Produce a new table with the specified columns moved to the specified {@code index}. Column indices begin at 0.
+     * Columns can be renamed with the usual syntax, i.e. {@code "NewColumnName=OldColumnName")}. The renames are
+     * simultaneous, and unordered, enabling direct swaps between column names.
```
Comment (chipkent) [inline engine/api/src/main/java/io/deephaven/engine/table/Table.java:417]:
```suggestion
     * simultaneous and unordered, enabling direct swaps between column names.
```

File: py/server/deephaven/table.py [hunk 8]
```diff
@@ -721,7 +727,9 @@ def move_columns_up(self, cols: Union[str, Sequence[str]]) -> Table:
             raise DHError(e, "table move_columns_up operation failed.") from e
 
     def rename_columns(self, cols: Union[str, Sequence[str]]) -> Table:
-        """The rename_columns method creates a new table with the specified columns renamed.
+        """The rename_columns method creates a new table with the specified columns renamed. The renames are
+        simultaneous, and unordered, enabling direct swaps between column names. Specifying a source or
```
Comment (chipkent) [inline py/server/deephaven/table.py:731]:
```suggestion
        simultaneous and unordered, enabling direct swaps between column names. Specifying a source or
```

File: py/server/deephaven/table.py [hunk 9]
```diff
@@ -703,10 +707,12 @@ def move_columns_down(self, cols: Union[str, Sequence[str]]) -> Table:
 
     def move_columns_up(self, cols: Union[str, Sequence[str]]) -> Table:
         """The move_columns_up method creates a new table with specified columns appearing first in order, to the far
-        left.
+        left. Columns may be renamed with the same semantics as rename_columns. The renames are simultaneous, and
```
Comment (chipkent) [inline py/server/deephaven/table.py:710]:
```suggestion
        left. Columns may be renamed with the same semantics as rename_columns. The renames are simultaneous and
```

File: py/server/deephaven/table.py [hunk 10]
```diff
@@ -684,10 +686,12 @@ def move_columns(self, idx: int, cols: Union[str, Sequence[str]]) -> Table:
 
     def move_columns_down(self, cols: Union[str, Sequence[str]]) -> Table:
         """The move_columns_down method creates a new table with specified columns appearing last in order, to the far
-        right.
+        right. Columns may be renamed with the same semantics as rename_columns. The renames are simultaneous, and
```
Comment (chipkent) [inline py/server/deephaven/table.py:689]:
```suggestion
        right. Columns may be renamed with the same semantics as rename_columns. The renames are simultaneous and
```

File: py/server/deephaven/table.py [hunk 11]
```diff
@@ -665,10 +665,12 @@ def drop_columns(self, cols: Union[str, Sequence[str]]) -> Table:
 
     def move_columns(self, idx: int, cols: Union[str, Sequence[str]]) -> Table:
         """The move_columns method creates a new table with specified columns moved to a specific column index value.
+        Columns may be renamed with the same semantics as rename_columns. The renames are simultaneous, and unordered,
```
Comment (chipkent) [inline py/server/deephaven/table.py:668]:
```suggestion
        Columns may be renamed with the same semantics as rename_columns. The renames are simultaneous and unordered,
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java [hunk 12]
```diff
@@ -1820,73 +1776,121 @@ public void onUpdate(final TableUpdate upstream) {
...
+
+                    final OperationSnapshotControl snapshotControl =
+                            createSnapshotControlIfRefreshing(OperationSnapshotControl::new);
+                    initializeWithSnapshot("renameColumns", snapshotControl, (usePrev, beforeClockValue) -> {
+                        final QueryTable resultTable = new QueryTable(rowSet, newColumns);
+                        propagateFlatness(resultTable);
+
+                        copyAttributes(resultTable, CopyAttributeOperation.RenameColumns);
+                        copySortableColumns(resultTable, pairs);
+                        maybeCopyColumnDescriptions(resultTable, pairs);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java:1864]: Please read through these to make sure they are correct.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java [hunk 13]
```diff
@@ -1820,73 +1776,121 @@ public void onUpdate(final TableUpdate upstream) {
...
+                                    methodNuggetPrefix + Arrays.deepToString(pairs) + ')', this, resultTable) {
+                                @Override
+                                public void onUpdate(final TableUpdate upstream) {
+                                    final TableUpdateImpl downstream = TableUpdateImpl.copy(upstream);
+                                    downstream.modifiedColumnSet = resultTable.getModifiedColumnSetForUpdates();
+                                    if (upstream.modified().isNonempty()) {
+                                        mcsTransformer.clearAndTransform(upstream.modifiedColumnSet(),
+                                                downstream.modifiedColumnSet);
+                                    } else {
+                                        downstream.modifiedColumnSet.clear();
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java:1879]: Could just assign downstream to empty instead of mutating the re-usable result MCS.

**Review by rcaudy — COMMENTED** [review]
.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java [hunk 14]
```diff
@@ -1776,60 +1799,109 @@ public void onUpdate(final TableUpdate upstream) {
...
+                            append.accept("Duplicate source column(s): " + String.join(", ", duplicateSource));
                         }
-                        if (!newNames.add(pair.leftColumn)) {
-                            throw new IllegalArgumentException(
-                                    "Duplicate destination column \"" + pair.leftColumn + "\"");
+                        if (duplicateDestination != null) {
+                            append.accept("Duplicate destination column(s): " +
+                                    String.join(", ", duplicateDestination));
                         }
+                        throw new IllegalArgumentException(msg.toString());
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java:1881]: Want something terser?
```
                        throw new IllegalArgumentException(Stream.of(
                                notFound == null ? null :
                                        "Column(s) not found: " + String.join(", ", notFound),
                                duplicateSource == null ? null :
                                        "Duplicate source column(s): " + String.join(", ", duplicateSource),
                                duplicateDestination == null ? null :
                                        "Duplicate destination column(s): " + String.join(", ", duplicateDestination)
                        ).filter(Objects::nonNull).collect(Collectors.joining("\n")));
```

**Review by rcaudy — COMMENTED** [review]
Don't hate me

**Review by rcaudy — APPROVED** [review]

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

Community: https://github.com/deephaven/deephaven.io/issues/3750
