### PR TITLE
BaseTable: Remove Swap Listener and Add Atomic addUpdateListener

### LINKED ISSUE #4556: DynamicTableWriter fails with `PeriodicUpdateGraph notification` in pip-installed Deephaven
**Description**

Writing data to a DynamicTableWriter from a Python script or Jupyter notebook via pip-installed Deephaven results in an assertion failure after some amount of time. That amount of time seems to change per run, but it always seems to happen. It also kills the Jupyter kernel, if testing from Jupyter.

**Steps to reproduce**

Run the following script from Python or a Jupyter notebook.

```python
import time
class DHErrorCheck:
    @staticmethod
    def run():
        with main_exec_context:
            global liveFeed
            import deephaven.dtypes as dht
            from deephaven import DynamicTableWriter
            table_writer = DynamicTableWriter({"X": dht.double})
            liveFeed = table_writer.table
            while True:
                t=time.time()
                table_writer.write_row(t)
                livFeed=liveFeed.where(filters=["X>t-60"])
                time.sleep(0.0001)
                
if __name__ == "__main__":
    from deephaven_server import Server
    s=Server(jvm_args=["-Dauthentication.psk=deephaven"])
    s.start()
    from deephaven.execution_context import get_exec_ctx
    main_exec_context = get_exec_ctx()
    DHErrorCheck.run()
```

**Expected results**

The table writer to keep writing data.

**Actual results**

The following exception:

```
Initiating shutdown due to: Exception while processing PeriodicUpdateGraph notification
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 61, updateGraph.clock().currentStep() == 61.
	at io.deephaven.base.verify.Assert.fail(Assert.java:100)
	at io.deephaven.base.verify.Assert.lt(Assert.java:674)
	at io.deephaven.engine.table.impl.BaseTable.notifyListenersOnError(BaseTable.java:806)
	at io.deephaven.engine.table.impl.MergedListener.propagateErrorDownstream(MergedListener.java:175)
	at io.deephaven.engine.table.impl.MergedListener.propagateError(MergedListener.java:151)
	at io.deephaven.engine.table.impl.MergedListener.handleUncaughtException(MergedListener.java:292)
	at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:360)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Additional details and attachments**

**Versions**
 - Deephaven: 0.28.0/1
 - OS: Mac
 - Browser: Chrome
 - Docker: 20.10.13

### PR DESCRIPTION
**Pull request by nbauernfeind**
Fixes #4556.

Nightlies: https://github.com/nbauernfeind/deephaven-core/actions/runs/6542750841

### CODE REVIEW

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+    private static final Logger log = LoggerFactory.getLogger(SimpleSnapshotControl.class);
+
+    private TableUpdateListener eventualListener;
+    private NotificationStepReceiver eventualResult;
+    boolean success = false;
+
+    /**
+     * The last clock cycle which the source table produced a notification.
+     */
+    protected long lastNotificationStep = NotificationStepReceiver.NULL_NOTIFICATION_STEP;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java:35]:
```suggestion
    long lastNotificationStep = NotificationStepReceiver.NULL_NOTIFICATION_STEP;
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+    }
+
+    @Override
+    public boolean snapshotConsistent(long currentClockValue, boolean usingPreviousValues) {
+        return isInInitialNotificationWindow();
+    }
+
+    @Override
+    public final boolean snapshotCompletedConsistently(long afterClockValue, boolean usedPreviousValues) {
+        return end(afterClockValue);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java:95]: Maybe just in-line end here? Or keep the `start/usePreviousValues` split.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+     *
+     * @param clockCycle The {@link LogicalClock logical clock} cycle we are ending a snapshot on
+     * @return true if the snapshot was successful, false if we should try again.
+     * @throws IllegalStateException If the snapshot was successful (consistent), but the snapshot function failed to
+     *         set the eventual listener or eventual result
+     */
+    @OverridingMethodsMustInvokeSuper
+    protected synchronized boolean end(@SuppressWarnings("unused") final long clockCycle) {
+        if (isInInitialNotificationWindow()) {
+            if (eventualResult == null) {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java:110]:
```suggestion
            if (eventualListener == null) {
                throw new IllegalStateException("Listener has not been set on end!");
            }
            if (eventualResult == null) {
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+public class SimpleSnapshotControl implements ConstructSnapshot.SnapshotControl {
+
+    static final boolean DEBUG =
+            Configuration.getInstance().getBooleanWithDefault("SwapListener.debug", false);
+
+    private static final Logger log = LoggerFactory.getLogger(SimpleSnapshotControl.class);
+
+    private TableUpdateListener eventualListener;
+    private NotificationStepReceiver eventualResult;
+    boolean success = false;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java:30]: This can be a local variable in `end`.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 5]
```diff
@@ -0,0 +1,171 @@
...
+                    .append(" control=").append(System.identityHashCode(this))
+                    .append("} End: success=").append(success)
+                    .append(", last=").append(lastNotificationStep)
+                    .endl();
+        }
+
+        if (success) {
+            eventualResult.setLastNotificationStep(lastNotificationStep);
+            success = subscribeForUpdates(eventualListener);
+        }
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java:129]:
```suggestion
        if (!success) {
            return false;
        }
        // Be sure to record initial last notification step before subscribing
        eventualResult.setLastNotificationStep(lastNotificationStep);
        return subscribeForUpdates(eventualListener);
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 6]
```diff
@@ -0,0 +1,171 @@
...
+        return lastNotificationStep == newNotificationStep;
+    }
+
+    /**
+     * Subscribe for updates from the source table.
+     *
+     * @param listener The listener to subscribe
+     * @return Whether the subscription was successful
+     */
+    protected boolean subscribeForUpdates(@NotNull final TableUpdateListener listener) {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java:148]:
```suggestion
    boolean subscribeForUpdates(@NotNull final TableUpdateListener listener) {
```

File: engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java [hunk 7]
```diff
@@ -101,8 +101,9 @@ protected final void setCoalesced(final Table coalesced) {
 
     // region uncoalesced listeners
 
-    protected final void addUpdateListenerUncoalesced(@NotNull final TableUpdateListener listener) {
-        super.addUpdateListener(listener);
+    protected final boolean addUpdateListenerUncoalesced(
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java:104]: I would prefer to keep "shadowed" versions of both overloads.

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java [hunk 8]
```diff
@@ -264,32 +265,25 @@ protected Collection<ImmutableTableLocationKey> filterLocationKeys(
...
-        initializeWithSnapshot("SourceTable.coalesce", swapListener, (usePrev, beforeClockValue) -> {
+        initializeWithSnapshot("SourceTable.coalesce", snapshotControl, (usePrev, beforeClockValue) -> {
             final QueryTable resultTable = new QueryTable(definition, rowSet, columnSourceManager.getColumnSources());
             copyAttributes(resultTable, CopyAttributeOperation.Coalesce);
             if (rowSet.isEmpty()) {
                 resultTable.setAttribute(INITIALLY_EMPTY_COALESCED_SOURCE_TABLE_ATTRIBUTE, true);
             }
 
-            if (swapListener != null) {
+            result.setValue(resultTable);
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java:285]: Seems kind of weird. Why the change?

**Review by rcaudy — COMMENTED** [review]
Placeholder, reviewed up to here

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 9]
```diff
@@ -90,22 +88,20 @@ public boolean snapshotConsistent(long currentClockValue, boolean usingPreviousV
...
+     * @param afterClockValue The {@link LogicalClock logical clock} cycle we are ending a snapshot on
+     * @param usedPreviousValues Whether we used previous values during the snapshot
      * @return true if the snapshot was successful, false if we should try again.
      * @throws IllegalStateException If the snapshot was successful (consistent), but the snapshot function failed to
      *         set the eventual listener or eventual result
      */
+    @Override
     @OverridingMethodsMustInvokeSuper
-    protected synchronized boolean end(@SuppressWarnings("unused") final long clockCycle) {
+    public synchronized final boolean snapshotCompletedConsistently(long afterClockValue, boolean usedPreviousValues) {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java]: final inputs?

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java [hunk 10]
```diff
@@ -90,22 +88,20 @@ public boolean snapshotConsistent(long currentClockValue, boolean usingPreviousV
...
+        boolean success;
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSnapshotControl.java]: final
Maybe rename `snapshotConsistent`

File: engine/table/src/main/java/io/deephaven/engine/table/impl/SortOperation.java [hunk 11]
```diff
@@ -85,8 +85,8 @@ public MemoizedOperationKey getMemoizedOperationKey() {
     public SimpleSnapshotControl newSnapshotControl(QueryTable queryTable) {
         return new SimpleSnapshotControl(queryTable) {
             @Override
-            public synchronized boolean end(long clockCycle) {
-                final boolean success = super.end(clockCycle);
+            public synchronized boolean snapshotCompletedConsistently(long afterClockValue, boolean usedPreviousValues) {
```
Comment (rcaudy) [inline engine/table/src/main/java/io/deephaven/engine/table/impl/SortOperation.java:88]: Same comment. Better to be final.

File: server/src/main/java/io/deephaven/server/session/SessionState.java [hunk 12]
```diff
@@ -286,15 +286,18 @@ public <T> ExportObject<T> getExport(final int exportId) {
         final ExportObject<T> result;
 
         // If this a non-export or server side export, then it must already exist or else is a user error.
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/session/SessionState.java:288]: This doesn't seem to match the code anymore.

File: server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java [hunk 13]
```diff
@@ -133,6 +134,11 @@ private synchronized void onNewTableExport(final Ticket ticket, final int export
             sendUpdateMessage(ticket, table.size(), null);
             return;
         }
+        if (table.isFailed()) {
```
Comment (rcaudy) [inline server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java:141]: This is nice, but doesn't really completely do the job. We want to also handle races in the snapshot. Talked about adding more specific exception types to two layers of the stack.

**Review by rcaudy — COMMENTED** [review]
.

**Review by rcaudy — DISMISSED** [review]

**Review by rcaudy — APPROVED** [review]
